### PR TITLE
Fix Pettern Matching typo

### PR DESCRIPTION
**Pull request by iantabolt**

### CODE REVIEW

**Comment by felixmulder** [comment]
Hey Ian! Thanks for the PR - could you sign the CLA real quick? https://www.lightbend.com/contribute/cla/scala

Otherwise we can't accept your code changes for legal reasons :-1:

Thanks again! :tada:

**Comment by felixmulder** [comment]
(Also, yeah - the bot is being weird in saying that you have, because your username is not on here: https://www.lightbend.com/contribute/cla/scala/check/iantabolt)

**Comment by felixmulder** [comment]
Also - please ping me after :)

**Comment by iantabolt** [comment]
@felixmulder done!

**Pull request merged**
