### PR TITLE
Add time travelling copies

### PR DESCRIPTION
**Pull request by odersky**
Make Apply and TypeApply copy only if function or argument types have changed.

### CODE REVIEW

**Comment by odersky** [comment]
I still don't understand exactly what goes wrong here. I tried to do a minimized time travelling copier to see if I could reproduce. This seems to work fine (at least on my end it did).

**Comment by DarkDimius** [comment]
@odersky, I think this may simply hide the bug. `A.scala` from #2520 needs to be copied once to fix wrong signature created by Typer before we pickle it, while `B.scala` needs to be copied 2 times. It seems that there may be more complex that need to be copied more times to be fixed.

Were you able to see a wrong signature printed in https://github.com/lampepfl/dotty/pull/2520/files#diff-7c63b7bfffa9340fb48ac9b61fa56beeR363 ? For A.scala(which is simpler) it should return `TermName` but it returns `Name` instead.

**Comment by odersky** [comment]
But _where_ was the bad signature created? That is the question. Instrumenting the copier does not help - it only diagnosed what happened before. Hint: instrument withType on Select nodes instead.

**Comment by DarkDimius** [comment]
@odersky, it was created in `TypeAssigner.selectionType` during typing of the node in typedSelect.
```
 at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:1981)
	  at dotty.tools.dotc.core.Types$Type.select(Types.scala:1106)
	  at dotty.tools.dotc.typer.TypeAssigner$class.selectionType(TypeAssigner.scala:215)
	  at dotty.tools.dotc.typer.Typer.selectionType(Typer.scala:65)
	  at dotty.tools.dotc.typer.TypeAssigner$class.accessibleSelectionType(TypeAssigner.scala:236)
	  at dotty.tools.dotc.typer.Typer.accessibleSelectionType(Typer.scala:65)
	  at dotty.tools.dotc.typer.TypeAssigner$class.assignType(TypeAssigner.scala:267)
	  at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:65)
	  at dotty.tools.dotc.typer.Typer.dotty$tools$dotc$typer$Typer$$typedSelect(Typer.scala:360)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedSelect$1.dotty$tools$dotc$typer$Typer$$anonfun$$typeSelectOnTerm$1(Typer.scala:390)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedSelect$1.apply(Typer.scala:422)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedSelect$1.apply(Typer.scala:386)
	  at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	  at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:386)
	  at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1512)
	  at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1576)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1592)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	  at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
	  at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	  at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1590)
	  at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1646)
	  at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:643)
	  at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:641)
	  at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	  at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:641)
	  at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:741)
	  at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:65)
	  at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1531)
	  at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1577)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1592)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	  at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
	  at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	  at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1590)
	  at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1646)
	  at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:643)
	  at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:641)
	  at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	  at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:641)
	  at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:741)
	  at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:65)
	  at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1531)
	  at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1577)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1592)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	  at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
	  at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	  at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1590)
	  at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1625)
	  at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1634)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1324)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1272)
	  at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	  at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1272)
	  at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1522)
	  at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1576)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1592)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	  at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
	  at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	  at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1590)
	  at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1614)
	  at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1634)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1437)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1424)
	  at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	  at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1424)
	  at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1561)
	  at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1577)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1592)
	  at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	  at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
	  at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	  at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1590)
	  at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1646)
	  at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:64)
	  at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:32)
	  at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:62)
	  at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:93)
	  at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:93)
	  at scala.collection.immutable.List.foreach(List.scala:392)
	  at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:93)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:82)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:79)
	  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:79)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
	  at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	  at dotty.tools.dotc.Run.compileUnits(Run.scala:67)
	  at dotty.tools.dotc.Run.compileSources(Run.scala:64)
	  at dotty.tools.dotc.Run.compile(Run.scala:48)
	  at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	  at dotty.tools.dotc.Driver.process(Driver.scala:124)
	  at dotty.tools.dotc.Driver.process(Driver.scala:93)
	  at dotty.tools.dotc.Driver.process(Driver.scala:105)
	  at dotty.tools.dotc.Driver.main(Driver.scala:132)
	  at dotty.tools.dotc.Main.main(Main.scala:-1)
```

**Comment by odersky** [comment]
I just checked the signatures everytime a type was assigned to a Select node. They all look good. 
And the tests also pass. So I don't know what causes this in your PR. Can you see whether this PR here fixes the problem with the termination check? If yes I would suggest continue with this one.

**Comment by DarkDimius** [comment]
> Can you see whether this PR here fixes the problem with the 
> termination check? If yes I would suggest continue with this one

Ok, will do now.

**Comment by DarkDimius** [comment]
This tree-copier didn't fix the termination issue.
With it two tests are copied forever. 
Here's the branch with this copier: https://github.com/dotty-staging/dotty/tree/local-opt-time

I'm trying to find what trees in what tests were copied. @felixmulder  is there a good way in vulpix to see what are the two remaining tests?

```
[info] Test dotty.tools.dotc.CompilationTests.runAll started
[======================================>] completed (793/795, 438s)
```

**Comment by nicolasstucki** [comment]
@DarkDimius, look in `out` in the run test outputs for the tests folders that do not have classes yet.

**Comment by odersky** [comment]
@DarkDimius I noted that Closures also need to be handled more conservatively in normal copiers. Maybe that fixes the non-termination issue? If not we really need to find out where the copies come from.

**Pull request closed without merging**
