### PR TITLE
Scala3doc: ensure testcases are compiled before documenting them

### PR DESCRIPTION
**Pull request by abgruszecki**
What it says in the title.

### CODE REVIEW

**Comment by abgruszecki** [comment]
@romanowski can you pat this one on the back? Compare also with https://github.com/lampepfl/dotty/pull/10141 which switched from using `classDirectory` to `product`.

**Review by romanowski — APPROVED** [review]

**Comment by romanowski** [comment]
LGTM! however I think I am not officialy a contributor so I am not sure if you do not need another approve to merge the PR.

**Comment by abgruszecki** [comment]
@romanowski that's fine, I don't think anyone will have any strong feelings about me merging this PR.

**Comment by smarter** [comment]
> however I think I am not officialy a contributor

Just gave you access, you should be now :).

**Comment by romanowski** [comment]
@smarter Thank you!

**Pull request merged**
