### PR TITLE
Add sourcepath to IDE setup

### PR DESCRIPTION
**Pull request by odersky**
This allows the compiler to succeed even if the project is not fully built.
It also gives navigation capability into directly dependent files.

### CODE REVIEW

**Comment by odersky** [comment]
@allanrenucci Can you figure out what's wrong with test?

**Comment by allanrenucci** [comment]
@odersky The issue is when compiling with `-from-tasty`. You can reproduce locally:
```sh
# Make sure output dir is empty
$ rm -rf out/*
$ sbt
> dotc -d out tests/run/hello.scala
> dotc -from-tasty -classpath out Test -Xprint:all
```
The second sbt command does not compile anything. This line returns `None`: https://github.com/dotty-staging/dotty/blob/d1db0dc9bd82bab724361f756d5d487fed926ba0/compiler/src/dotty/tools/dotc/fromtasty/ReadTastyTreesFromClasses.scala#L69

**Comment by odersky** [comment]
FromTasty seems to be flakey (compilation order dependent?). I can't repeat test failures on the CI locally, and vice versa I get failures locally that are not issue on the CI. @nicolasstucki can you look into this at some point?

**Comment by odersky** [comment]
@allanrenucci I don't think the test failure is explained by the FromTasty tests. I mean you r diagnosis was correct, but this did not cause a test failure. Even after the problem is fixed, we still fail in the same way. It's not in FromTasty. It seems towards the end of the run. Here is what we got:

./project/scripts/sbt ';dotc tests/pos/sbtDotrTest.scala -d out/scriptedtest1/; dotc -from-tasty -classpath out/scriptedtest1/ -d out/scriptedtest2/ dotrtest.Test; dotr -classpath out/scriptedtest2/ dotrtest.Test'
1159s
11196
Error: Could not find or load main class dotrtest.Test
1177s
11197
+ cat sbtdotr2.out
1177s
11198
[info] Loading project definition from /tmp/1/project/project
1177s
11199
[info] Loading project definition from /tmp/1/project
1177s
11200
[info] Resolving key references (16135 settings) ...
1177s
11201
[info] Set current project to dotty (in build file:/tmp/1/)
1177s
11202
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11203
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11204
[info] Running dotty.tools.dotc.Main -classpath /tmp/1/library/target/scala-2.12/dotty-library_2.12-0.7.0-bin-SNAPSHOT-nonbootstrapped.jar tests/pos/sbtDotrTest.scala -d out/scriptedtest1/
1177s
11205
[success] Total time: 4 s, completed Feb 1, 2018 2:18:55 PM
1177s
11206
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11207
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11208
[info] Running dotty.tools.dotc.Main -classpath out/scriptedtest1/:/tmp/1/library/target/scala-2.12/dotty-library_2.12-0.7.0-bin-SNAPSHOT-nonbootstrapped.jar -from-tasty -d out/scriptedtest2/ dotrtest.Test
1177s
11209
[success] Total time: 2 s, completed Feb 1, 2018 2:18:57 PM
1177s
11210
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11211
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
1177s
11212
[success] Total time: 0 s, completed Feb 1, 2018 2:18:58 PM
1177s
11213
+ grep -e 'dotr test ok' sbtdotr2.out
1177s
11214
failed output check
1177s
11215
+ echo 'failed output check'
1177s
11216
+ exit -1

**Comment by odersky** [comment]
I see now, it was a from tasty test after all. But I am at the end of my patience with them now. Somebody else will have to take this over and re-instantiate the failing tests. I never wanted to get involved with them in the first place, but they were so entangled with source trees that I had no choice.

**Comment by odersky** [comment]
Current status: We can now construct trees from source, it's no longer required that the project is built so that we can read the Tasty trees. 

Also, we have now a cool find-references, which works very fast even for large code bases. For example it finds all 3360 references to "Context" in the Dotty project in under 3 seconds. Smaller sets take much less than a second.

**Comment by odersky** [comment]
Current status: We can now also navigate to overridden symbols.

**Comment by nicolasstucki** [comment]
I will fix the from tasty tests later. We could have issues that come from compilation order. The error that @allanrenucci pointed out means that the class is not found or cannot be loaded from the classpath.

**Pull request merged**
