### PR TITLE
Use Wconf to silence Unsafe usage under jdk18

### PR DESCRIPTION
**Pull request by som-snytt**
Allow build to proceed under JDK 18.

### CODE REVIEW

**Comment by som-snytt** [comment]
If I don't use `-Wconf` periodically, I forget how to use it. Eventually, I forget to use it.

However, I'll reconsider.

**Comment by som-snytt** [comment]
Scaladoc in the community build balks on
```
Error:  bad option: '-Werror'
```
FSR, scaladoc in every version is the source of things that don't work.

**Comment by dwijnand** [comment]
> @dwijnand I remember now, it's because I hate typing `import scala.annotation.*`, there's just no reason for it.

I feel you.  I can't decide if I hate more the adding of import, out yonder at the start of whatever file I'm in, the eye-sore verbosity of `@scala.annotation.nowarn...`, or the less verbose but still very eye-sore of the stumpy `@annotation.nowarn..`.

**Review by dwijnand — APPROVED** [review]

**Comment by som-snytt** [comment]
I hope the auto-import of `scala.annotation` makes it in.

**Comment by som-snytt** [comment]
The title should be, "Use every means at one's disposal...".

**Pull request merged**
