### PR TITLE
fix for #11536 and other terminal and shell environment issues

### PR DESCRIPTION
**Pull request by philwalk**
fix for #11536

Also verified working REPL for various combinations of Terminal and Windows shell.
See [https://github.com/lampepfl/dotty/issues/11536#issuecomment-786156696](11536#issuecomment-786156696)

### CODE REVIEW

**Comment by philwalk** [comment]
Currently, calling scripts results in common being sourced twice, first by `bin/scala`, then by `bin/scalac`.
We can cut some significant time from script startups, by the following changes:
1. export variables at the bottom of [dist/bin/common](https://github.com/lampepfl/dotty/blob/master/dist/bin/common)
2. conditionally source `bin/common`, only if variables are not already initialized
```scala
# only need to source common if variables not inherited from scala
[[ -z "$PSEP" && -z "$DOTTY_COMP" ]] && source "$PROG_HOME/bin/common"
```
In my environment, it eliminates between 250 and 350 milliseconds from script startups, when a compile is required.

**Comment by michelou** [comment]
@philwalk Usage of `eval` and `onExit` is not consistent accros the three bash scripts : 

```diff
$ git diff dist\bin\scalac dist\bin\scaladoc
diff --git a/dist/bin/scalac b/dist/bin/scalac
index f81c20853b..74bfc4a603 100755
--- a/dist/bin/scalac
+++ b/dist/bin/scalac
@@ -120,7 +120,7 @@ if [ "$PROG_NAME" == "$ScriptingMain" ]; then
   scripting_string="-script $target_script ${scripting_args[@]}"
 fi

-eval exec "\"$JAVACMD\"" \
+eval "\"$JAVACMD\"" \
      ${JAVA_OPTS:-$default_java_opts} \
      "${DEBUG-}" \
      "${java_args[@]}" \
@@ -130,4 +130,5 @@ eval exec "\"$JAVACMD\"" \
      "${scala_args[@]}" \
      "${residual_args[@]}" \
      "${scripting_string-}"
-exit $?
+scala_exit_status=$?
+onExit
diff --git a/dist/bin/scaladoc b/dist/bin/scaladoc
index b536dbf99e..304da8f504 100755
--- a/dist/bin/scaladoc
+++ b/dist/bin/scaladoc
@@ -125,7 +125,7 @@ done

 classpathArgs

-eval exec "\"$JAVACMD\"" \
+eval "\"$JAVACMD\"" \
      ${JAVA_OPTS:-$default_java_opts} \
      "$DEBUG" \
      "${java_args[@]}" \
@@ -134,4 +134,5 @@ eval exec "\"$JAVACMD\"" \
      "${scala_args[@]}" \
      "${residual_args[@]}" \
      "$scripting_string"
-exit $?
+scala_exit_status=$?
+onExit
```

Do we agree with the following general rules  ?! 
- do not write `eval exec <something>`.
- a call to `eval` is *always* followed by the assignment `scala_exit_status=$?`.
- `onExit` is *always* the last executed instructon in the script.

**Comment by philwalk** [comment]
@michelou 
The rules sound correct to me, I will push an updated `dist\bin\scaladoc` after some manual testing.

**Comment by philwalk** [comment]
@michelou - I'm not able to exhaustively test the change to `dist/bin/scaladoc`, although it's is pretty simple.  Should I push the updated version?

**Comment by michelou** [comment]
> 
> 
> @michelou - I'm not able to exhaustively test the change to `dist/bin/scaladoc`, although it's is pretty simple. Should I push the updated version?

I'd like to keep `scalac` and `scaladoc` in sync. So yes.

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
