### PR TITLE
Drop experimental inheritance checking

### PR DESCRIPTION
**Pull request by odersky**
IMO it's a foot gun that prevents useful idioms. Concretely I have an @experimental marker trait `@caps.Pure` that classes can inherit. So far, there was no way to do that except if the inheriting class is also @experimental. This requirement was unconditional. It did not help to be in an experimental scope or to use a snapshot compiler version.

This basically means that @experimental base traits are useless, unless one is prepared to pollute the codebase with sprinkling experimental over all inheriting classes.

On the other hand, I see no useful property that is established by this restriction. The (now deleted) documentation is also silent about the motivation of all this.

### CODE REVIEW

**Comment by dwijnand** [comment]
Perhaps dropping it makes sense.  But to be devil's advocate, perhaps the useful property is that it makes it blatantly obvious that a class is experimental, without having to get the compiler or the scaladoc tool to look through the inheritance chain, you can just see it plainly in the source?

I can see how retroactively applying it to an establish codebase may look ridiculous, but perhaps it's a good thing?  Might make you stop and think if you really want to make all those classes experimental?  And I agree being in an experimental scope or using a snapshot compiler should be exemptions.  And to that note, perhaps we should figure out how to annotate a package as experimental?

I don't hold a strong opinion on this.

**Comment by odersky** [comment]
@dwijnand How do you propose to handle `caps.Pure` then? I see no way to do it without making capture checking ridiculously cumbersome. And that's not specific to capture checking. It's just that this is the first time anyone has used an @experimental marker trait.

I wish we would spend at least equal measure of thought on how to make things practical than how to prevent things. Right now, my tendency is again to just get rid of the whole experimental thing. It's been so painful to get over all its inadequacies and I have lost an inordinate amount of time on it that would have been better spent elsewhere.

**Comment by dwijnand** [comment]
I don't know the specifics of the caps.Pure use case to answer that directly.  But I think there should be a way to indicate that, for instance, the whole project is experimental.

**Comment by odersky** [comment]
> I don't know the specifics of the caps.Pure use case to answer that directly. But I think there should be a way to indicate that, for instance, the whole project is experimental.

Right now there isn't. Here is a scenario: In one file:
```scala
@experimental class A
```
In the other:
```scala
object project B extends A
```
This fails _already_ because it refers to `A`, which is experimental. No separate experimental check is needed. 

We should be able to fix it like this:
```scala
@experimental object project B extends A
```
With the changes in this PR this works. Before, it failed because of the experimental inheritance check. 

So the experimental inheritance check achieves nothing useful that is not already covered by the external reference check

**Comment by dwijnand** [comment]
Oh, so this is just a cleanup PR removing a redundant check, not actually changing any behaviour?  If so, should we look to keeping the various different examples in the test cases?  Maybe there's an external reference check test where they can be folded into.

**Comment by odersky** [comment]
No, it does change behavior. Previously a class A could not inherit from an experimental class without  having an @experimental annotation itself. We both agree this is unreasonable. So that behavior was removed.

**Comment by dwijnand** [comment]
Ah, right.  That example makes sense now.  Yes, indeed, this makes sense.

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
