### PR TITLE
Add stdlib blacklist and whitelist more sources.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by felixmulder** [comment]
Hey @SethTisue! The `validate-main` thing is still showing up and seems stuck :(

**Comment by SethTisue** [comment]
@felixmulder I can't seem to locate anything else to switch off at our end. perhaps you need to switch something off at https://github.com/lampepfl/dotty/settings/hooks...?

**Comment by SethTisue** [comment]
and/or get rid of your `scripts/jobs/validate` directory, or the whole `scripts` directory?

**Comment by SethTisue** [comment]
and/or find out what or where "dotty-bot" even is?

**Comment by felixmulder** [comment]
@SethTisue, I see - the CLA checking is on our bot not yours. Disabled the webhook!

**Comment by odersky** [comment]
It seems the two CI's disagree. Does anybody know what's the root cause?

**Comment by nicolasstucki** [comment]
It looks like the new CI did not update the `scala-scala/dotty-library` dependency.

**Comment by nicolasstucki** [comment]
@felixmulder any insight about this? Was is cached?

**Comment by odersky** [comment]
@nicolasstucki Can you add Function0..Function22, Tuple1..Tuple22, and also control.{Try, Exception} to the whitelist? These should all be fixed now.

**Comment by odersky** [comment]
@nicolasstucki Please, just LGTM/merge my fixes when you need them. No need to cherrypick in your PR.  I am really hoping for faster reviews anyway. This constant piling up is causing me a lot of work. Thanks!

**Comment by odersky** [comment]
LGTM! 👍 Let's get this in now. I'll try to move some items from black to white in a follow-on PR.

**Pull request merged**
