### PR TITLE
Optimize MegaPhase

### PR DESCRIPTION
**Pull request by odersky**
#3366 did lose some performance relative to the previous tree transform scheme.

http://dotty-bench.epfl.ch/3366/

shows a loss of about 4% for scalapb and dotty. This PR is trying to get it back by reverting to a scheme close to the previous TreeTransform. We keep the new names, and shorten everything by about 20%, but otherwise rely on a similar dispatch algorithm as before.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
How can I find out what failed?

**Comment by liufengyun** [comment]
@odersky This is a regression of the bench infrastructure. I've reverted the changes on the server to the old code.

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
The website is already pushed to github as usual, but seems gh-pages have some problem in publishing it:

https://github.com/liufengyun/bench/tree/gh-pages/3393 

I plan to host the site on our own server instead.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Tests are still a bit too noisy to be able to isolate effects of changes in details but we are at all-time lows for compile times for Vector, scalpb and dotty, so I'd say it's a success overall.

**Comment by smarter** [comment]
Note that the removal of TreeTransform is likely to have a signficant impact on the benchmark here since you're compiling a thousand lines of code less. Is it possible that the original MegaPhase stuff is slower for dotty just because you were compiling more code?

**Comment by odersky** [comment]
@smarter Yes, removal of TreeTransform is surely a large part of the improvement of dotty. But we see smaller improvements for scalapb and Vector as well.

**Pull request merged**
