### PR TITLE
fix type err, improve readability of patmat doc

### PR DESCRIPTION
**Pull request by bjornregnell**
based on discussion here: https://github.com/lampepfl/dotty/issues/16131

### CODE REVIEW

**Comment by julienrf** [comment]
Does that overlap with #15993?

**Comment by som-snytt** [comment]
Indeed. The description here is not accurate about `A`, but the other PR also does not explain about the type param.

**Comment by Sporarum** [comment]
I will update the other PR with more information about the types

Can this PR therefore be closed ?
(But not merged or deleted, I'll use it as inspiration)

**Comment by bjornregnell** [comment]
ok I'll close this. @som-snytt for curiosity: what would be a more accurate statement about A?

**Pull request closed without merging**
