### PR TITLE
Macro annotations class modifications (part 2) 

### PR DESCRIPTION
**Pull request by nicolasstucki**
Enable modification of classes with `MacroAnnotation`:
 * Can annotate `class` to transform it
 * Can annotate `object` to transform the companion class

Supported class modifications:
 * Modify the implementations of `def`, `val`, `var`, `lazy val`, `class`, `object` in the class
 * Add new `def`, `val`, `var`, `lazy val`, `class`, `object` members to the class
 * Add a new override for a `def`, `val`, `var`, `lazy val` members in the class

Restrictions:
 * An annotation on a top-level class cannot return a top-level `def`, `val`, `var`, `lazy val`.

Related PRs:
 * Includes #16513
 * Follows #16392
 * Followed by #16534

### CODE REVIEW

**Review by smarter — APPROVED** [review]
LGTM. I think a good test case would be a mini-cask where you can get rid of the `initialize()` call: https://github.com/com-lihaoyi/cask#readme

**Comment by jilen** [comment]
Is it possible to transform companion object while annotate on class ?

**Comment by alexarchambault** [comment]
> Is it possible to transform companion object while annotate on class ?

Would love to know this too. In Scala 2 macro annotations, the `transform` method accepts a list of `Tree`s, like `def transform(annottees: Tree*): Tree`, that is passed both a `ClassDef` and a `ModuleDef`. But it only accepts a single `quotes.reflect.Definition` in Scala 3.

**Comment by nicolasstucki** [comment]
> Is it possible to transform companion object while annotate on class ?

It is not possible with this version. What is the use case?

**Comment by alexarchambault** [comment]
A use case for me would be a macro annotation acting as a more refined `derives`, or more generally, adding given instances in the companion depending on what's in the class body, like
```scala
@IsMapEntry
class Foo {
  @Key
  def id: String = "a"
  @Value
  def value: Int = 2
}
```
where `@IsMapEntry` would look at the body of `Foo`, find the `@Key` and `@Value` annotated methods, read their types, and put something like this in the companion of `Foo`:
```scala
given AsMapEntry[Foo, String, Int] = AsMapEntry.derive // String and Int are the @Key and @Value annotated method types
```

**Comment by alexarchambault** [comment]
> Why not use `class Foo(val id: String = "a", val value: Int = 2) derives IsMapEntry `?

Because `IsMapEntry` has more than one type parameter. Getting an error like `Foo cannot be unified with the type argument of IsMapEntry` when using `derives` (and things like `derives IsMapEntry[?, String, String]` don't seem to work).

**Comment by alexarchambault** [comment]
In more complex cases, I wish I would have been able to use parameters of the annotation in the additional definitions (`derives` wouldn't cover that case either).

**Comment by jilen** [comment]
Another case is the  [zio accessor generation](https://zio.dev/reference/service-pattern/generating-accessor-methods-using-macros/)

**Comment by kitlangton** [comment]
Similar to the accessor macro above, generating lenses on the companion object would also be an example use case. 

```scala
@lenses
case class Person(name: String, age: Int)

// Would expand into

case class Person(name: String, age: Int)

object Person:
  val name: Lens[Person, String]
  val age: List[Person, Int]
```

It seems like a trivial thing, but it'd be nice to avoid the boilerplate 😄. I wonder if there's a solution to this that doesn't require full power Scala 2-style pre-type-checked annotations.

**Comment by smarter** [comment]
>  I wonder if there's a solution to this that doesn't require full power Scala 2-style pre-type-checked annotations.

My best attempt: https://contributors.scala-lang.org/t/scala-3-macro-annotations-and-code-generation/6035

**Comment by smarter** [comment]
Cool! In case you haven't seen it, I have a prototype up at https://github.com/lampepfl/dotty/pull/16545

**Comment by kitlangton** [comment]
I was actually just looking at that! It would appear that it's not yet using the `-rewrite` mechanism, is that correct? If not, is there anything preventing that at the moment, if I were to try to hook into that ability?

**Comment by smarter** [comment]
>  If not, is there anything preventing that at the moment

No, it's just a matter of doing the work, so you're more than welcome to take a stab at it :). This ties in with work started by  @ckipp01 on structured diagnostic since we want to expose that information to IDEs, but that part should be orthogonal to the API we use in macros hopefully.

**Pull request merged**
