### PR TITLE
Fix: -no-link-warnings does not work

### LINKED ISSUE #16694: scaladoc -no-link-warnings does not work
Scaladoc version 3.2.1 -- Copyright 2002-2022, LAMP/EPFL

If the `--no-link-warnings` flag is used, it does not suppress link warnings,

    [warn] -- Warning: static_site/_docs/index.md -----------------------------------------
    [warn] /home/foo/static_site/_docs/index.md: Unable to resolve link '../foo/bar/SomeClass.html

### PR DESCRIPTION
**Pull request by Dedelweiss**
## Goal
There are two purposes to this PR, the first is to add warning suppression when the path to the file is inneficient and a warning suppression flag is set.

The second one is to deprecate the current flag and introduce a new to avoid the ambiguity. One for dead links with the current meaning, and one with dead links in assets. The goal is to avoid the confusion with overloading of the naming.
I wonder if I also change the name of the previous flag to be more precise in its use.

## Flags
noLinkWarnings - Boolean
    "-no-link-warnings",
    "Avoid warnings for ambiguous and incorrect links in members look up. Doesn't affect warnings for incorrect links of assets etc."

noLinkAssetWarnings - Boolean
    "-no-link-asset-warnings",
    "Avoid warnings for incorrect links of assets like images, static pages, etc.",
    false

## Before :
Screenshot 2023-03-13 at 16 25 03

## After :
Screenshot 2023-03-13 at 16 28 02

Fixes #16694

### CODE REVIEW

**Review by ckipp01 — COMMENTED** [review]
Thanks for the pr @Dedelweiss!

So I'm not convinced that changing the value is worth it here since this would in theory be a breaking change for scaladoc or for people using this value already.

**Review by ckipp01 — COMMENTED** [review]
Hey @Dedelweiss are you able to squash these commits and update the PR description as it's out of date now.

**Comment by ckipp01** [comment]
I took a bit of time and dug a bit deeper into what was going on here @Dedelweiss and I think there is a small misunderstanding. I explained further in https://github.com/lampepfl/dotty/issues/16694#issuecomment-1490389821. We'll need to discuss how we proceed there first.

**Review by Florian3k — APPROVED** [review]

**Review by ckipp01 — APPROVED** [review]
This looks good to me. @Dedelweiss we'll probably want to document this somewhere. Maybe a draft pr in the scala lang site that we can merge once this is released?

**Pull request merged**
