### PR TITLE
update scalatest compiler to 0.18.1-RC1

### PR DESCRIPTION
**Pull request by liufengyun**
update scalatest compiler to 0.18.1-RC1

### CODE REVIEW

**Comment by smarter** [comment]
When we run the community build, the version of dotty in the project is overridden by the version of the current snapshot, so I don't think this needs to be updated.

**Comment by liufengyun** [comment]
@smarter Thanks for the point. It's better to make the change, so that we may sync with upstream scalatest.

**Comment by smarter** [comment]
Why not make the change upstream directly, then update our submodule ?

**Comment by liufengyun** [comment]
We don't control the upstream, we'll do it after some refactoring of the recent changes due to 2.13 switch. It will take some time. Meanwhile, it's better to sync our submodule with the community build branch of `dotty-staging/scalatest`.

**Pull request merged**
