### PR TITLE
Cleanup some of the macro code in protoquill

### PR DESCRIPTION
**Pull request by nicolasstucki**
Remove Quotes from fields

Instances of `Quotes` should be contextual, placing them in fields inevitably causes the wrong instance of `Quotes` to be used. This causes extra overhead in the code, fragility of the abstractions and potential slowdowns (as owners will need to be fixed everywhere).

* Remove the name `qctx` as it is outdated and we can uses `quotes` now.
* Make `Extractors` an object and avoid all the workaround with extensions and `ExtractorsBundle`. Now we simply need to import the extractors.
* Transform some implicit classes into extension methods

### CODE REVIEW

**Comment by nicolasstucki** [comment]
This is only a first step. More will come later.

@deusaquilus is the branch on which I'm working up to date?

**Comment by deusaquilus** [comment]
Are you using the RC2_Nightly branch? The latest is master.

**Comment by deusaquilus** [comment]
This is very impressive! I love the changes you made to Extractors!

**Comment by nicolasstucki** [comment]
Then I will try to rebase on protoquill/master

**Comment by deusaquilus** [comment]
Thank you. I really appreciate what you’ve done here but is there any chance you could have a look at #12179 first? That’s another significant blocker for me :(

**Comment by nicolasstucki** [comment]
We should add these changes to getguill/protoquill first. I opened an issue in that repo to not forget about it.

**Comment by deusaquilus** [comment]
@nicolasstucki I just checked in a version of `master` with scalatest shimmed-out and the dependency removed. You should be able to build master now.

**Comment by deusaquilus** [comment]
Also, it looks like `dottyLatestNightlyBuild.get` still doesn't work. Is there something I should be doing instead?

**Pull request closed without merging**
