### PR TITLE
Implement/i499

### PR DESCRIPTION
**Pull request by odersky**
Implements #499.

And its the first time we tried to make language enhancements issues -- let's see how that will play out. Review by @DarkDimius @xeno-by

### CODE REVIEW

**Comment by DarkDimius** [comment]
LGTM. But it would be good to also include a run-test.
If you agree, I'll add one.

**Comment by odersky** [comment]
Yes, let's add a run test.

**Comment by odersky** [comment]
Jason's examples in #499 would be good to have in that test.

**Comment by DarkDimius** [comment]
@odersky please review tests.

**Pull request merged**
