### PR TITLE
I18628

### PR DESCRIPTION
**Pull request by EnzeXing**
This PR fixes the minimized test of #18628 that previously runs infinitely on the global initialization checker.

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM, thanks a lot.

Please add the long test as a positive test (no warnings).

**Comment by EnzeXing** [comment]
> Please add the long test as a positive test (no warnings).

@liufengyun With this fix I'm afraid the long test cannot pass the checker since the environment of `repMany` will eventually widen the by-name parameters to `Cold`

**Comment by liufengyun** [comment]
> > Please add the long test as a positive test (no warnings).
> 
> @liufengyun With this fix I'm afraid the long test cannot pass the checker since the environment of `repMany` will eventually widen the by-name parameters to `Cold`

It should work --- I checked on my machine, it works as expected. The case is OK, because the recursive call is `by-name`.

**Review by olhotak — APPROVED** [review]
I confirm that the long test also works for me. (It gives a warning but does not run out of memory). Please add it, but otherwise LGTM.

**Comment by EnzeXing** [comment]
> I confirm that the long test also works for me. (It gives a warning but does not run out of memory). Please add it, but otherwise LGTM.

It is the same for me, but @liufengyun do you expect the test to pass without warning?

**Comment by liufengyun** [comment]
> > I confirm that the long test also works for me. (It gives a warning but does not run out of memory). Please add it, but otherwise LGTM.
> 
> It is the same for me, but @liufengyun do you expect the test to pass without warning?

Sorry, I made a mistake in my test. Yes, it produce warnings. But it shouldn't --- It seems we have a problem handling the local lazy vals.

Just change the following method in the test from 

```Scala
    def ~ [U](q: => Parser[U]): Parser[~[T, U]] = { lazy val p = q // lazy argument
      (for(a <- this; b <- p) yield new ~(a,b))
    }
```

to

```Scala
    def ~ [U](q: => Parser[U]): Parser[~[T, U]] = {
      (for(a <- this; b <- q) yield new ~(a,b))
    }
```

will suppress the warning.

**Pull request merged**
