### PR TITLE
test: add in regression test for #7445

### PR DESCRIPTION
**Pull request by ckipp01**
So this adds in a test that shows that the minimized version of the original issue is fixed, but the original report now fails the pickling tests. I've gone ahead and added a test for that as well, but added it to the excludes. I'll reopen the issue and mention this update.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
We should also include the original example as a regression test.
```scala
type O1[A] = {
  type OutInner[Ts] <: Tuple = Ts match {
    case Unit   => Unit
    case h *: t => h *: OutInner[t]
  }
  
  type Out = OutInner[A]
}

def f1: O1[(Int, Int)]#Out = ???
```

**Comment by ckipp01** [comment]
Huh, actually trying out the originally report produces a different error than the original report is about.

```
Compiling project (Scala 3.3.1-RC1-bin-20230511-5c4e597-NIGHTLY, JVM)
[error] ./example.scala:5:20
[error] Found:    Unit
[error] Required: Tuple
[error]     case Unit   => Unit
[error]                    ^^^^
[warn] ./example.scala:6:25
[warn] forward reference in refinement is deprecated
[warn]     case h *: t => h *: OutInner[t]
[warn]                         ^^^^^^^^
Error compiling project (Scala 3.3.1-RC1-bin-20230511-5c4e597-NIGHTLY, JVM)
Compilation failed
```

To be honest, i'm not 100% sure on the intended behavior here. Is this indeed illustrating the original issue, another issue, or should this compile?

**Comment by nicolasstucki** [comment]
That makes sense. The code should be updated to 
```scala
type O1[A] = {
  type OutInner[Ts] <: Tuple = Ts match {
    case EmptyTuple => EmptyTuple
    case h *: t => h *: OutInner[t]
  }
  
  type Out = OutInner[A]
}

def f1: O1[(Int, Int)]#Out = ???
```

**Comment by ckipp01** [comment]
> That makes sense. The code should be updated to
> 
> ```scala
> type O1[A] = {
>   type OutInner[Ts] <: Tuple = Ts match {
>     case EmptyTuple => EmptyTuple
>     case h *: t => h *: OutInner[t]
>   }
>   
>   type Out = OutInner[A]
> }
> 
> def f1: O1[(Int, Int)]#Out = ???
> ```

Alright, thanks. So this doesn't show the original issue, but it does still fail a test with pickling. I've updated the original description to reflect this and I'll update the original issue as well.

**Comment by ckipp01** [comment]
Weird so running `testCompilation i7445b` locally correctly skips this, but when I run the full `testOnly dotty.tools.dotc.CompilationTests` it does run this one and fails:

```
26 suites passed, 1 failed, 27 total
tests/pos/i7445b.scala failed
```

Am I misunderstanding how this `.exludes` file is working? Shouldn't it skip this?

**Review by nicolasstucki — APPROVED** [review]

**Pull request merged**
