### PR TITLE
[Backport] Fix #10747: Raise type error on unreducible match type

### LINKED ISSUE #10747: irreducible match types should be type errors
## Minimized code

```Scala
type Foo[A] = A match {
  case Int => String
}

type B = Foo[Boolean]
```

## Output

```scala
// code compiles fine
```

## Expectation

It seems to me that the concrete instantiation `Foo[Boolean]` should be an immediate type error (as happens when an invalid type argument is provided for a bounded type parameter), ideally with an explanation of the reduction failure.

More generally it should be a type error if a term somehow (by inference) ends up with a concretely-instantiated but irreducible match type. The alternative (as now) is that nonsensical types propagate and users have few tools at their disposal to figure out what happened.

I discussed this briefly with @smarter and I understand that it's complicated, but at least in the concrete case I think the compiler could be more helpful.

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Scaladoc test failed:

```
2021-09-14T06:29:56.1461820Z [error] Test dotty.tools.scaladoc.sourcelinks.RemoteLinksTest.runTest failed: Page https://github.com/lampepfl/dotty/blob/f3305d43544c7b2507661a9c0b3748ed2962ea05/library/src/scala/CanThrow.scala does not exists, took 0.2 sec
2021-09-14T06:29:56.2665019Z [error] Failed: Total 4, Failed 1, Errors 0, Passed 3
2021-09-14T06:29:56.2674455Z [error] Failed tests:
2021-09-14T06:29:56.2678095Z [error] 	dotty.tools.scaladoc.sourcelinks.RemoteLinksTest
2021-09-14T06:29:56.3567112Z [error] (scaladoc / SourceLinksIntegrationTest / test) sbt.TestsFailedException: Tests unsuccessful
2021-09-14T06:29:56.3774220Z [error] Total time: 412 s (06:52), completed Sep 14, 2021 6:29:56 AM
```

@pikinier20 @BarkingBad @KacperFKorban does anyone know why?

**Comment by pikinier20** [comment]
This error happens because `CanThrow` is in `src-bootstrapped`. Some time ago I did a workaround for one of PRs but apparently it didn't get merged to release branch.

You can take a look at it here: https://github.com/dotty-staging/dotty/pull/19

**Comment by anatoliykmetyuk** [comment]
Is it merged in `master`? Anywhere I can cherry-pick it from?

**Comment by pikinier20** [comment]
I see that my commit wasn't merged to any branch but the problem is resolved by temporary disabling source links test (it's disabled on master). https://github.com/lampepfl/dotty/pull/13448

**Review by Kordyjan — APPROVED** [review]

**Pull request merged**
