### PR TITLE
fix exception 'UnmappableCharacterException' in dottydoc on Windows

### PR DESCRIPTION
**Pull request by michelou**
Environment: 
&nbsp;&nbsp;&nbsp;&nbsp;MS Windows 10 Home, JDK 1.8.0_191, SBT 1.2.6
Console output **before** fix:
```
[doc info] Generating doc page for: dotty.tools.dotc.plugins
Exception in thread "main" java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        at scala.io.BufferedSource.$anonfun$iter$2(BufferedSource.scala:38)
        [...]
        at dotty.tools.dottydoc.staticsite.Site.toSourceFile(Site.scala:411)
        at dotty.tools.dottydoc.staticsite.Site.$anonfun$blogInfo$1(Site.scala:101)
        [...]
        at dotty.tools.dottydoc.staticsite.Site.blogInfo(Site.scala:99)
        at dotty.tools.dottydoc.staticsite.Site.genDoc$1(Site.scala:202)
        at dotty.tools.dottydoc.staticsite.Site.$anonfun$generateApiDocs$4(Site.scala:215)
        at dotty.tools.dottydoc.staticsite.Site.$anonfun$generateApiDocs$4$adapted(Site.scala:214)
        [...]
        at dotty.tools.dottydoc.staticsite.Site.$anonfun$generateApiDocs$1(Site.scala:214)
        at dotty.tools.dottydoc.staticsite.Site.createOutput(Site.scala:186)
        at dotty.tools.dottydoc.staticsite.Site.generateApiDocs(Site.scala:192)
        at dotty.tools.dottydoc.DocDriver.process(DocDriver.scala:52)
        at dotty.tools.dotc.Driver.process(Driver.scala:105)
        at dotty.tools.dotc.Driver.process(Driver.scala:117)
        at dotty.tools.dotc.Driver.main(Driver.scala:144)
        at dotty.tools.dottydoc.Main.main(Main.scala)
```

### CODE REVIEW

**Comment by smarter** [comment]
Note that you'll need to sign the CLA on https://www.lightbend.com/contribute/cla/scala before we can merge your PR.

**Comment by smarter** [comment]
Can you open a separate PR for the batch scripts? That's going to be harder to review

**Comment by michelou** [comment]
Scala CLA signed.

**Comment by allanrenucci** [comment]
Thanks @michelou!

**Pull request merged**
