### PR TITLE
dep: update mill to a stable version in community build

### PR DESCRIPTION
**Pull request by ckipp01**
This updates mill to the latest stable release 0.10.5.

### CODE REVIEW

**Comment by ckipp01** [comment]
Pretty much all of these need to be updated in staging:

```
 - dotty.communitybuild.CommunityBuildTestC.sourcecode
 - dotty.communitybuild.CommunityBuildTestC.pprint
 - dotty.communitybuild.CommunityBuildTestC.requests
 - dotty.communitybuild.CommunityBuildTestC.upickle
 - dotty.communitybuild.CommunityBuildTestC.cask
 - dotty.communitybuild.CommunityBuildTestC.geny
 - dotty.communitybuild.CommunityBuildTestC.fansi
 - dotty.communitybuild.CommunityBuildTestC.oslib
 - dotty.communitybuild.CommunityBuildTestC.ujson
 - dotty.communitybuild.CommunityBuildTestC.utest
 - dotty.communitybuild.CommunityBuildTestC.parboiled2
 ```

**Comment by anatoliykmetyuk** [comment]
I believe your change is enough to change the Mill version everywhere in the CB. Note how mill bootstrap scripts read the environmental variable to obtain the version: https://github.com/dotty-staging/geny/blob/master/mill#L10

**Review by anatoliykmetyuk — APPROVED** [review]

**Comment by ckipp01** [comment]
> I believe your change is enough to change the Mill version everywhere in the CB. Note how mill bootstrap scripts read the environmental variable to obtain the version: https://github.com/dotty-staging/geny/blob/master/mill#L10

Thanks for the approval, but I was actually looking for some insight on the questions I asked up above, mainly about the best way to proceed with these type of prs. Right now it seems the only way to update things in the community build is to ping someone on Discord hoping they see your message and sync the community repo. Moving forward, how can we make this more sustainable. It's unrealistic to expect people to do this.

Also I know this is approved, but don't merge this yet. I still have one more PR that needs to be merged in cask, and then all the repos I mentioned have been updated, and then they all need to be synced. That syncing part is the part I'd like insight on.

**Comment by ckipp01** [comment]
@anatoliykmetyuk I got everything in staging updated as well since you gave your original ✅ . This should be good to merge, but just to make sure can you or someone else give a ✅ to verify.

**Review by anatoliykmetyuk — APPROVED** [review]
LGTM, thank you!

**Comment by anatoliykmetyuk** [comment]
Regarding your original question: the most optimal way so far is to submit your work to the staging repo as a branch, and then update the submodule. Not the most ergonomic solution, but with the current setup, it does the job.

Sorry for the late reply – vacation period...

**Pull request merged**
