### PR TITLE
Change scheme to implement creator applications

### PR DESCRIPTION
**Pull request by odersky**
Use synthetic apply methods instead of a fallback in Typer to implement
creator applications.

Todo:

 - [x] Check for shadowing of creator proxies
 - [x] Investigate problem in zio: made a separate issue https://github.com/lampepfl/dotty/issues/10808
 - [x] Change reference doc page

### CODE REVIEW

**Comment by sjrd** [comment]
Will that affect the bytecode in any way? (new `object`s, new `def`s, call sites?)

**Comment by sjrd** [comment]
More importantly: can this change the meaning of existing programs?
* Through accidental overrides of an existing `apply` method in a superclass/trait of the companion?
* Through a change in overload resolution if there are other `apply` methods in the companion?
* Through shadowing an `apply` method available via an implicit conversion/extension method?

All the previous discussions of this feature were based on the fact that it couldn't change the meaning of existing programs. Changing this premise invalidates all those discussions, including at the SIP meetings, where I recall that this was an important concern.

**Comment by odersky** [comment]
Here are the breakages observed in the community  build:

 - Shadowing problems of the kind described above. Fixed by 6 additional imports or qualifiers in cats-effects-2 (1), cats-mtl (3), scala-parallel collections (2).
 - One issue in `zio` where some type parameters were not detected due to a cyclic reference that is probably caused by the completion of a constructor proxy (this one needs follow up).
 - A weird issue where scalacheck used a case class named `apply` and relied on two `apply`s in a row being inserted, which is no longer the case for some reason (I count that as a bug fix).
 - An issue in `scas` that I believe comes from a build that mixes several compiler versions in an illegal way. 

I believe we should address the shadowing problems. We could demand that when resolving a constructor proxy identifier the same identifier does not already exist as a regular identifier in some outer scope. That would have caught each of the shadowing issues. We should also see what we can do to avoid the problem in zio. 

Overall I am quite positive now. The new scheme is much safer than the previous one, and it looks compatible enough with Scala 2 to be workable.

**Comment by odersky** [comment]
The code so far can already be reviewed.

**Comment by odersky** [comment]
I verified that the shadowing check catches and diagnoses the observed errors in the community build.

**Comment by odersky** [comment]
From my point of view, this is ready to merge. We can figure out the problem observed in zio later. If someone still has the time to review this until tomorrow, this would be great. Otherwise we'll merge as is and deal with any possible improvements later.

**Comment by odersky** [comment]
The shapeless error was interesting. It looks like we wanted the creator proxy since there was an explicit
import for its companions class. But we resolved to the outer apply before, so the fallback never kicked in.
Which shows that the fallback scheme can also be misleading.. Now we see that there's a conflict since
we get the shadowing error.

**Comment by odersky** [comment]
Overall I am now quite convinced that the new scheme is better than the previous one, and that the previous one had hidden problems that would have only got worse with widespread adoption. So I am glad we can get it changed in time for 3.0.

**Comment by odersky** [comment]
test performance please

**Comment by SethTisue** [comment]
before, I could `val lock = AnyRef()`, now I can't?

I guess it's because `AnyRef` a is type alias? I see also that `class C; type D = C; D()` worked before but now doesn't.

is this supposed to be acceptable collateral damage, or what?

**Comment by rjolly** [comment]
I concur. This is the cause of the failure in ScAS. I have opened an issue: https://github.com/lampepfl/dotty/issues/10862

**Comment by odersky** [comment]
Yes, that's intended. You don't get an apply for a type alias. I think this is what we want. To compare, if I write
```scala
type S = scala.collection.immutable.Seq
```
I still can't do `S(1, 2, 3)`. I'd have to add
```scala
val S = scala.collection.immutable.Seq
```
For the new kind of apply methods, it's the same.

**Comment by SethTisue** [comment]
(I guess let's discuss further on https://github.com/lampepfl/dotty/issues/10862)

**Pull request merged**
