### PR TITLE
Optimize constant folding

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by sjrd** [comment]
There are also a number of `widenDealias.typeSymbol` in the Scala.js backend (in `JSCodeGen.scala`), which should probably be changed as well.

**Comment by odersky** [comment]
@sjrd widenDealias is also removed in JSCodeGen.

**Comment by odersky** [comment]
test performance please

**Comment by sjrd** [comment]
> @sjrd widenDealias is also removed in JSCodeGen.

Oh right, it is. Somehow I had not realized that. Sorry.

**Comment by odersky** [comment]
Seems to give consistent small wins between 1 and 2%

**Review by liufengyun — APPROVED** [review]
LGTM

**Pull request merged**
