### PR TITLE
Added scopt.

### PR DESCRIPTION
**Pull request by dotbg**

### CODE REVIEW

**Comment by dotbg** [comment]
Seems to be blocked by #10544 and #7128

```
scala.MatchError: 
  TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class scopttest)),module class SpecUtil$)),class RichString)
 (of class dotty.tools.dotc.core.Types$CachedTypeRef) while compiling

 /__w/dotty/dotty/community-build/community-projects/scopt/jvm/src/test/scala/scopt/ImmutableParserSpecJVM.scala, 
 /__w/dotty/dotty/community-build/community-projects/scopt/jvm/src/test/scala/scopt/MonadicParserSpecJVM.scala, 
 /__w/dotty/dotty/community-build/community-projects/scopt/jvm/src/test/scala/scopt/SpecUtilPlatform.scala,
 /__w/dotty /dotty/community-build/community-projects/scopt/jvm_js/src/test/scala/scopttest/UriSpec.scala,
 /__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/DiffUtil.scala,
 /__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/ImmutableParserSpec.scala, 
/__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/Issue239.scala,
 /__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/MonadicParserSpec.scala, 
/__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/MutableParserSpec.scala, 
/__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/NotToStringInverse.scala, 
/__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/SpecUtil.scala
```

**Comment by dotbg** [comment]
It does look different now. I have attached the complete log as well 
```
[  error ]    -- Error: /__w/dotty/dotty/community-build/community-projects/scopt/shared/src/test/scala/scopttest/MutableParserSpec.scala:185:10   
[  error ]    185 |     assert(foo ==  1 ) 
[  error ]       |     ^^^^^^^^^^^^^^^^  
[  error ]       |Exception occurred while executing macro expansion. 
[  error ]       |java.lang.RuntimeException: Expecty: Error rewriting expression. 
[  error ]       |Text:            foo == 1 
[  error ]       |AST : Apply(Select(Ident("foo"), "=="), List(Literal(IntConstant(1)))) 
[  error ]       |	at verify.asserts.RecorderMacro.recordExpressions(RecorderMacro.scala:65) 
[  error ]       |	at verify.asserts.RecorderMacro.apply$$anonfun$4(RecorderMacro.scala:35) 
[  error ]       |	at verify.asserts.RecorderMacro.apply$$anonfun$adapted$2(RecorderMacro.scala:35) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:82) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1367) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1437) 
[  error ]       |	at scala.collection.immutable.List.mapConserve(List.scala:472) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1437) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1435) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:122) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61) 
[  error ]       |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2886) 
[  error ]       |	at verify.asserts.RecorderMacro.apply(RecorderMacro.scala:35) 
[  error ]       |	at verify.asserts.RecorderMacro$.apply(RecorderMacro.scala:172) 
[  error ]       |Caused by: java.lang.ArrayIndexOutOfBoundsException: 1900 
[  error ]       |	at dotty.tools.dotc.util.SourceFile.column(SourceFile.scala:199) 
[  error ]       |	at dotty.tools.dotc.util.SourcePosition.startColumn(SourcePosition.scala:52) 
[  error ]       |	at scala.quoted.runtime.impl.SpliceScope.toString(SpliceScope.scala:44) 
[  error ]       |	at java.lang.String.valueOf(String.java:2994) 
[  error ]       |	at java.lang.StringBuilder.append(StringBuilder.java:131) 
[  error ]       |	at scala.quoted.runtime.impl.ScopeException$.checkInCorrectScope(ScopeException.scala:27) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$.quotedExprToTree(PickledQuotes.scala:44) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:83) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1367) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:97) 
[  error ]       |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:122) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61) 
[  error ]       |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2886) 
[  error ]       |	at verify.asserts.RecorderMacro.recordExpressions(RecorderMacro.scala:60) 
[  error ]       |	at verify.asserts.RecorderMacro.apply$$anonfun$4(RecorderMacro.scala:35) 
[  error ]       |	at verify.asserts.RecorderMacro.apply$$anonfun$adapted$2(RecorderMacro.scala:35) 
[  error ]       |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:82) 
```
[dotty-scopt-errors.txt](https://github.com/lampepfl/dotty/files/6135613/dotty-scopt-errors.txt)

**Comment by dotbg** [comment]
It does look like the length of the `content()` is different from the one we expect.  
``` scala
    if (idx < length && content()(idx) == '\t') (tabInc - col) % tabInc else 1
```

**Comment by griggt** [comment]
The new error seems to go away if I revert https://github.com/dotty-staging/nanotest-strawman/commit/3af47d0e929786436cc26bee576870a330f0d0cb

Not sure if it is a problem with the original commit (from https://github.com/lampepfl/dotty/pull/11576), a semantic merge conflict in https://github.com/lampepfl/dotty/pull/11642, or something else.

/cc @nicolasstucki

**Comment by dotbg** [comment]
Updated the branch, the [error differs a bit](https://github.com/lampepfl/dotty/pull/11625/checks?check_run_id=2310515223#step:8:42978) 

 [error] -- Error: /__w/dotty/dotty/community-build/community-projects/scopt/jvm/src/test/scala/scopt/MonadicParserSpecJVM.scala:33:10 
[error] 33 |    assert(OParser.usage(parser1) == expectedUsage)
[error]    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.RuntimeException: Expecty: Error rewriting expression.
[error]    |Text:            OParser.usage(parser1) == expectedUsage
[error]    |AST : Apply(Select(Apply(TypeApply(Select(Ident("OParser"), "usage"), List(Inferred())), List(Ident("parser1"))), "=="), List(Ident("expectedUsage")))
[error]    |	at verify.asserts.RecorderMacro.recordExpressions(RecorderMacro.scala:65)

**Comment by anatoliykmetyuk** [comment]
Since there hasn't been any activity on this PR for a while, we'll close it. If you would like to continue working on it, feel free to reopen it or submit a new one.

**Comment by dotbg** [comment]
thanks. I think it is obsolete now

**Pull request closed without merging**
