### PR TITLE
Fix check bounds

### PR DESCRIPTION
**Pull request by odersky**
I noticed that we do not check all bounds of type parameters. Fixing this revealed another
problem when compiling stdlib which this commit also fixes. However, bounds checking
in PostTyper now causes deep subtypes, so stdlib has to be compiled without -Yno-dee-subtypes.
Review by @smarter.

### CODE REVIEW

**Comment by smarter** [comment]
I haven't looked into it much yet, but I think the deep subtype error is worth investigating, it happens just by running:
```scala
./bin/dotc -Yno-deep-subtypes ./scala-scala/src/library/scala/collection/generic/ParMapFactory.scala
```
however, if I enable the `subtyping` `Printer` in `Printers.scala` and run:
```scala
./bin/dotc -Ylog:all -Yno-deep-subtypes ./scala-scala/src/library/scala/collection/generic/ParMapFactory.scala
```
Then the error disappears! So clearly it's possible to typecheck this without deep subtyping

**Comment by odersky** [comment]
An explanation could be that LazyRefs forcing creates additional subtypes.
Printing forces ahead of time, so there are fewer subtype tests.


On Wed, Dec 30, 2015 at 5:51 PM, Guillaume Martres <notifications@github.com
> wrote:

> I haven't looked into it much yet, but I think the deep subtype error is
> worth investigating, it happens just by running:
>
> ./bin/dotc -Yno-deep-subtypes ./scala-scala/src/library/scala/collection/generic/ParMapFactory.scala
>
> however, if I enable the subtyping Printer in Printers.scala and run:
>
> ./bin/dotc -Ylog:all -Yno-deep-subtypes ./scala-scala/src/library/scala/collection/generic/ParMapFactory.scala
>
> Then the error disappears! So clearly it's possible to typecheck this
> without deep subtyping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/1012#issuecomment-168032835>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
I think I got it, see #1014.

**Comment by odersky** [comment]
Superseded by #1014

**Pull request closed without merging**
