### PR TITLE
Fix jvm8 lamba related issues.

### PR DESCRIPTION
**Pull request by DarkDimius**

### CODE REVIEW

**Comment by DarkDimius** [comment]
@smarter please review.

**Comment by DarkDimius** [comment]
ahh. needs to be merged after #479, as it relies on behavior introduced there.

**Comment by DarkDimius** [comment]
@odersky, please update your dependencies: https://repo1.maven.org/maven2/me/d-d/scala-compiler/2.11.5-20150416-144435-09c4a520e1/scala-compiler-2.11.5-20150416-144435-09c4a520e1.jar
This update allows to have non-static implementations of SAMs.

**Comment by smarter** [comment]
Lgtm

**Pull request merged**
