### PR TITLE
Fix #3246: Refine handling of postfix _ for non-functions

### LINKED ISSUE #3246: Converting from `T` to `() => T`
With scalac you can do
```scala
val foo = 1
val bar: () => Int = foo _
```
dotc reject this code snippet. Should we support it under `-language:Scala2` and emit a migration warning?

### PR DESCRIPTION
**Pull request by allanrenucci**
Reopening #3300 from `dotty-staging`

### CODE REVIEW

**Comment by allanrenucci** [comment]
This used to compile but doesn't compile anymore:
```scala
class Test {
  class A
  def foo(x: A)(y: x.type) = ()
  val bar = foo(new A()) _
 }
```
```scala
-- Error: tests/allan/Test.scala:4:25 ------------------------------------------
4 |  val bar = foo(new A()) _
  |            ^^^^^^^^^^^^^^
  |            not a function: foo(new A()); cannot be followed by `_'

one error found
```

**Comment by allanrenucci** [comment]
Same for:
```scala
class Test {
  class A {
    type T
    def f(x: T): T = ???
  }
  def a: A = new A
  val f = a.f _
 }
```
```scala
-- Error: tests/allan/Test.scala:7:14 ------------------------------------------
7 |  val f = a.f _
  |          ^^^^^
  |          not a function: a.f; cannot be followed by `_'

one error found
```

**Comment by liufengyun** [comment]
@allanrenucci The two examples don't compile by `2.12.3`, do we need to support in Dotty?

**Comment by allanrenucci** [comment]
They compile on Dotty master and are extracted from our test suite.

I believe the second example should probably compile or at least this should compile (it compiles with scalac):
```scala
class Test {
  class A {
    type T = Int
    def f(x: T): T = ???
  }
  def a: A = new A
  val f = a.f _
}
```
Regarding the first example, I am not sure

**Comment by liufengyun** [comment]
It works now, review @allanrenucci , thanks.

**Comment by allanrenucci** [comment]
LGTM. Thanks!

**Pull request merged**
