### PR TITLE
Add macro error reporting

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by biboudis** [comment]
@liufengyun related to the change in `Splicer` here https://github.com/lampepfl/dotty/pull/5822/files#diff-43be0f2f8a9625bb70763569c65a6fdcR49

**Comment by nicolasstucki** [comment]
What @liufengyun is describing is exactly what @biboudis is doing. The difference between reflect and quote errors is that reflect will take a position and quote will take an expression (i.e. one of the arguments) for which the position is taken.

**Comment by smarter** [comment]
@nicolasstucki this broke master: http://dotty-ci.epfl.ch/lampepfl/dotty/11117

**Comment by nicolasstucki** [comment]
It conflicted with the white box macros which will stop expanding macros after the first failed expansion. I will fix it first thing in the morning.

**Pull request merged**
