### PR TITLE
Replace quoted `toExpr` with `Expr.apply`

### PR DESCRIPTION
**Pull request by nicolasstucki**
* Improves error messages
* Makes it simpler to find in the API
* Avoid the need for a `given` import (with this we would not need #7257)

### CODE REVIEW

**Comment by milessabin** [comment]
@nicolasstucki this is great ... but would you mind tagging me whenever you push changes to dotty-staging/shapeless (or PR-ing the change against milessabin/shapeless if you're feeling enthusiastic).

**Comment by milessabin** [comment]
Merged into shapeless-3-staging here: https://github.com/dotty-staging/shapeless/pull/1.

**Comment by nicolasstucki** [comment]
Will tag you next time.

**Comment by nicolasstucki** [comment]
I was planning to do it myself but I see that you did it faster

**Pull request merged**
