### PR TITLE
Disable old context function syntax

### LINKED ISSUE #10697: decide on final context function syntax
## Minimized code

The following are both valid, I believe we should be removing the form with `using` clause based on #10487

```Scala
val f = (using x: Int) => x
val g = (x: Int) ?=> x
```

## Expectation

Only `val g = (x: Int) ?=> x` should work

### PR DESCRIPTION
**Pull request by odersky**
Fixes #10697

### CODE REVIEW

**Review by bishabosha — CHANGES_REQUESTED** [review]
these changes will allow to use the context arrow to define a no-arg lambda
`val f = () ?=> 0` which is typed as a plain function0 `() => Int`

**Comment by odersky** [comment]
@bishabosha Can you take the PR over please and fix the problem? I am swamped, so won't have the time. Thanks!

**Comment by bishabosha** [comment]
this should be ready to go

**Comment by nicolasstucki** [comment]
@bishabosha there is still a failure
```scala
-- Error: tests/pos/i7778.scala:11:34 ----------------------------------------------------------------------------------
  final case class Foo[A, B](run: () ?=> Int)
                                  ^^
                                  context function types require at least one parameter
```

**Comment by bishabosha** [comment]
> @bishabosha there is still a failure

oh right, i did not expect to see that explicitly as a pos test, seems confusing to want to allow 0 arg ctx fn. Ill move it to neg

**Comment by nicolasstucki** [comment]
It looks like we also need to fix the community build https://github.com/lampepfl/dotty/runs/1550414420

**Comment by bishabosha** [comment]
> It looks like we also need to fix the community build https://github.com/lampepfl/dotty/runs/1550414420

I think it will be ok, both tasks passed after the compiler sources were fixed in https://github.com/lampepfl/dotty/pull/10786/commits/59bca1c49d5a5214c0632017bba2e070efdcfa70

**Comment by bishabosha** [comment]
only community build to go - hopefully it passes

**Review by nicolasstucki — APPROVED** [review]

**Review by bishabosha — APPROVED** [review]

**Pull request merged**
