### PR TITLE
Benchmark with inline disabled

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by smarter** [comment]
@liufengyun No idea what happened here, do you know how I could reproduce this failure locally?

**Comment by liufengyun** [comment]
@smarter I'm investigating and see what's wrong on the server. It seems difficult to reproduce locally.

**Comment by liufengyun** [comment]
@smarter I've been able to reproduce locally:

```
sbt dotty-bootstrapped/clean dist-bootstrapped/pack
dist-bootstrapped/target/pack/bin/dotc -d out/ (find compiler/src/dotty -name "*.scala" -o -name "*.java")
```

**Comment by smarter** [comment]
test performance please

**Pull request closed without merging**
