### PR TITLE
Fix #7595: Redesign dottydoc theme

### LINKED ISSUE #7595: Please Revert Dotty Doc Style
Can we please revert the CSS for the Dotty Docs to what it was before? I find the new style visually galling compared to what we had before. It's a clear regression. Everything is worse, from insensitive contrasts to bad fonts.

### PR DESCRIPTION
**Pull request by TheElectronWill**
This PR:
- [x] makes the sidebar more narrow, and applies some other tweaks (e.g. color the current page and don't make the sidebar fullscreen on mobile)
- [x] (re)sets the colors to a light palette
- [x] replaces Source Code Pro by Fira Code
- [x] replaces Source Sans Pro by Lato
- [x] removes Lobster (the curvy script font used in the navbar)

**Ligatures:** Fira Code provides font ligatures, which I've disabled to avoid confusing people. I can enable them if you don't believe they will be a problem.

**Text font:** Nobody seems to dislike the current text font, but maybe you'd prefer another one?
EDIT: Lato is widely appreciated in the Scala community, and for me it increases readability over the current font. It also works very well with Fira Code.

### Theme Comparison
<details>
Current theme:

Screenshot_2019-11-24 Enumerations

New theme:
Screenshot_2019-11-24 Enumerations(1)
</details>

### Font Choice
Please click on the image to open it in full size. Do you have a preference?

<details>

**Current theme: Roboto Slab**
**Proposal (EDIT: applied in this PR): Lato**
Alternative: Roboto or something else

Roboto Slab (current):

Screenshot_2019-11-24 Import Given

**Lato** (proposal - used by scala-lang.org and many Scala projects):
Screenshot_2019-11-24 Import Given(2)

Roboto (used by the Rust Book):
Screenshot_2019-11-24 Import Given(1)
</details>

---
I think this addresses most of the issues raised in #7595. Please tell me what you think! All comments are welcome.

### CODE REVIEW

**Comment by TheElectronWill** [comment]
PS: **this PR does not change the front page**.However it seems clear that it needs to be changed, we'll have to talk about this.

**Comment by TheElectronWill** [comment]
@odersky There are some screenshots in the "details" of the *Theme Comparison* and *Font Choice* sections.

If you want to have the full website you can pull and run `sbt genDocs`, but the screenshots should be enough.

**Comment by odersky** [comment]
I think it's a huge improvement! There's one thing we could still fiddle with: I have the impression the code font is a bit thin. If I compare with, say, the Rust Book, their code fonts seem to have a bit more weight. Can we achieve the same?

**Comment by julienrf** [comment]
The result looks great, thanks @TheElectronWill!

The [blog article lists](https://dotty.epfl.ch/blog/index.html) still looks ugly in my opinion, though:

Screenshot from 2019-11-25 16-45-49

What do you think of decreasing the font weight?

**Comment by TheElectronWill** [comment]
> I think it's a huge improvement! There's one thing we could still fiddle with: I have the impression the code font is a bit thin. If I compare with, say, the Rust Book, their code fonts seem to have a bit more weight. Can we achieve the same?

I see what you mean. Hopefully I can just increase the font weight property and it will look nice, I'll try that.

> The [blog articles list](https://dotty.epfl.ch/blog/index.html) still looks ugly in my opinion, though.
> What do you think of decreasing the font weight?

I think the font size needs some tweaking too. The headings are way bigger than the posts' summaries. On mobile the first title takes almost 1/2 of the page!

**Pull request merged**
