### PR TITLE
Make -Xprompt work as desired under -Werror

### LINKED ISSUE #19713: Bring back behavior of -Xfatal-warnings
## Compiler version

Since #19245, -Xfatal-warning became completely useless to me. I critically rely on -Xfatal-warnings in connection with -Xprompt to stop the compilation at the point where a warning was given. I need this every other day. But with the new behavior, -Xfatal-warnings has become useless for this task, since it waits until the very end of the compilation run before anything is reported.

I don't see what the point of these disruptive things to the toolchain is. This change causes me to lose lots of time, and probably will cause problems for others relying on the old behavior as well. 

We can institute new behavior for -Werror. But please, let's leave -Xfatal-warnings alone!

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #19713

### CODE REVIEW

**Comment by dwijnand** [comment]
Tested manually with `bin/scalac -Werror -Xprompt tests/warn/i15661.scala`.

**Review by odersky — CHANGES_REQUESTED** [review]
I think I tried the same fix but it did not work. The problem is that the warning is emitted (sent to ConsoleReporter) only at the end of the compilation run.

Did you do an -Xprompt with abort and then check whether the stacktrace makes sense?

**Review by odersky — CHANGES_REQUESTED** [review]
I think I tried the same fix but it did not work. The problem is that the warning is emitted (sent to ConsoleReporter) only at the end of the compilation run.

Did you do an -Xprompt with abort and then check whether the stacktrace makes sense?

**Comment by dwijnand** [comment]
I don't think I looked closely.  I'll check again, sorry.

**Comment by dwijnand** [comment]
Yes, using the example, it makes sense:

```
-- [E092] Pattern Match Unchecked Warning: tests/warn/i15661.scala:5:19 --------
5 |    case Composite(l: List[Int], v: Int) => println(v) // warn: type test for List[Int] cannot be checked at runtime
  |                   ^
  |the type test for List[Int] cannot be checked at runtime because its type arguments can't be determined from List[T$1]
  |
  | longer explanation available when compiling with `-explain`

a)bort, s)tack, r)esume: s
S
java.lang.Throwable
	at dotty.tools.dotc.reporting.Reporter$.loop$1(Reporter.scala:53)
	at dotty.tools.dotc.reporting.Reporter$.displayPrompt(Reporter.scala:62)
	at dotty.tools.dotc.reporting.ConsoleReporter.doReport(ConsoleReporter.scala:24)
	at dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:177)
	at dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:187)
	at dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:201)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:213)
	at dotty.tools.dotc.report$.issueWarning(report.scala:24)
	at dotty.tools.dotc.report$.uncheckedWarning(report.scala:33)
	at dotty.tools.dotc.transform.TypeTestsCasts$.checkTypePattern(TypeTestsCasts.scala:397)
	at dotty.tools.dotc.transform.TypeTestsCasts$.interceptWith$1(TypeTestsCasts.scala:367)
	at dotty.tools.dotc.transform.TypeTestsCasts$.interceptTypeApply(TypeTestsCasts.scala:383)
	at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:810)
```

**Review by odersky — APPROVED** [review]
OK, not sure why I thought this did not work before. Let's try this!

**Pull request merged**
