### PR TITLE
Fix MT separate compilation bug

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
@odersky There's a few things that go wrong to cause this:

1. Unpickler doesn't call simplified/overrideType like Typer does, so trees have different types if they're jointly compiled or separately compiled
2. Type simplification replaces type parameters with a type var for that type parameter in the constraint
3. Match type reduction uses type simplify on the reduction

I went for the narrow fix, but I'm open to addressing bigger issues.  What do you think we should do?

**Review by odersky — COMMENTED** [review]
It looks OK to me as far as I can tell, but I am really out of my depth here. I propose to add @sjrd as a reviewer of match type issues; he has far more up-to-date knowledge of the issues than I do.

**Review by sjrd — APPROVED** [review]
LGTM. Also I checked that it has the same effect if rebased on the new match types branch (i.e., the new test fails without the fix and succeeds with it).

**Comment by soronpo** [comment]
Unfortunately, continuing the "short blanket" phenomenon, this PR apparently causes a new regression #18448 (although I'm not sure this was supposed to compile to begin with).

**Pull request merged**
