### PR TITLE
Replace `private var` by `private[this] var` where possible

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by odersky** [comment]
Why do it? It does not make the code more beautiful, for sure.

**Comment by smarter** [comment]
Makes the intended usage more explicit, and it generates less bytecode (direct field access instead of accessor method calls). I agree that the syntax is not the nicest, I think @Ichoran suggested `my` as an alias for `private[this]` to encourage its use, that would help ;).

**Comment by smarter** [comment]
test performance please

**Comment by odersky** [comment]
How much less bytecode is generated? Performance data don't indicate a change in speed.

**Pull request merged**
