### PR TITLE
Make tasty inspector receive tasty files directly

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@abgruszecki this change will affect the doc tool.

**Review by liufengyun — COMMENTED** [review]
On the surface level, it seems the API is more complex to use.

I have never used this API. Maybe @abgruszecki and @bishabosha can share more ideas?

**Comment by bishabosha** [comment]
@gzoller what do you think

**Comment by bishabosha** [comment]
I guess this now makes it more clear how to use the API in some ways, as users must identify the top level class corresponding to the target being inspected

**Comment by bishabosha** [comment]
can this work with relative paths?

**Review by abgruszecki — COMMENTED** [review]
The code LGTM, but I'm not sure why exactly we're making this change. Is it to avoid problems with loading .tasty files from unknown/unexpected jars on the classpath?

**Comment by nicolasstucki** [comment]
Yes, it is to not accidentally load the wrong version of the class if another one is in the classpath. Or load from a class that has no TASTy.

**Comment by nicolasstucki** [comment]
> can this work with relative paths?

Yes it does. The stdlib tests use relative paths.

**Comment by nicolasstucki** [comment]
> if they are using inspector from a class obtained from `.getClass`, they will then need to do some manipulation if they want to inspect an object

The TASTy inspector is designed to take as input TASTy or jar files and inspect their TASTy. What you are describing is some kind of runtime reflection mixed with the tasty inspector, not really what this is designed for.

**Comment by bishabosha** [comment]
looks good to me - probably best to make it clear this is about files and not classes

**Review by liufengyun — APPROVED** [review]
LGTM

**Pull request merged**
