### PR TITLE
Fix typo in FromExpr#BooleanFromExpr

### PR DESCRIPTION
**Pull request by Iltotore**
This is a simple typo fix in the method comment.

### CODE REVIEW

**Comment by Iltotore** [comment]
I just signed to Scala CLA. You can re-launch checks.

**Comment by OlivierBlanvillain** [comment]
Thanks! Can you rebase your PR to have a single commit commit?

**Review by nicolasstucki — DISMISSED** [review]

**Comment by nicolasstucki** [comment]
@Iltotore We just need to rebase and squash the commits before merging

**Comment by Iltotore** [comment]
> @Iltotore We just need to rebase and squash the commits before merging

Hello @nicolasstucki , I didn't replied to this PR because I thought it was for you but now I'm not really sure. Should I rebase+squash ?

**Comment by Iltotore** [comment]
mhh... I don't really understand why tests stopped passing for fixing only a typo

**Comment by nicolasstucki** [comment]
@Iltotore maybe it is simpler to just create a new branch/PR from dotty/master and fix the typo again.

**Comment by Iltotore** [comment]
@nicolasstucki I re-created a new PR from a fresh new branch. 

PS: If you don't want to be pinged anymore, let me know.

**Pull request closed without merging**
