### PR TITLE
Invalidate companions of classes lifted by FlatMap

### PR DESCRIPTION
**Pull request by odersky**
RestoreScopes enters classes lifted by FlatMap into the
enclosing package scope. It should also invalidate any companions
because otherwise we risk linking up a new class with a previously
generated companion which exists only as a Java classfile.

### CODE REVIEW

**Comment by odersky** [comment]
Review by @darkdimius

**Comment by odersky** [comment]
On my local setup this still fails with CyclicReference errors caused by isDerivedValueClass. Will investigate separately.

**Comment by smarter** [comment]
@odersky : Try this commit: https://github.com/smarter/dotty/commit/789dc0c070bde6ce8634aa89e73e31ec1233a6f8 from #411.

**Comment by DarkDimius** [comment]
LGTM

**Pull request merged**
