### PR TITLE
Protected case class constructor -> non-public apply

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Coming back to protected apply: doesn't a protected apply method make the method available for subclasses of the case class?  I guess I could write a test for that, either way.

**Comment by arturopala** [comment]
Practically, the current situation means that you cannot enforce control over your case class consistency by making the constructor private because you are still left with the companion object's `apply` and `copy` breaking the encapsulation. I would argue the whatever modifier is put before the constructor should be then replicated on the autogenerated `apply` and `copy` methods.

**Comment by dwijnand** [comment]
> Practically, the current situation means that you cannot enforce control over your case class consistency by making the constructor private because you are still left with the companion object's `apply` and `copy` breaking the encapsulation.

No, that works, check out the two caseclass-access tests.  This is about what happens when you make the constructor protected.

**Review by odersky — APPROVED** [review]
It's a nice simplification for sure.

Is it true that the only effective change here is that if the constructor is protected, so is the `apply` method? Protected for the method does not really make sense here, since objects cannot be inherited. On the other hand `protected` also implies "package-private", and that's something we want. For clarity one might change this to a package private apply method instead. On the other hand `protected` is not wrong here, and it makes the code in desugar simpler.

**Pull request merged**
