### PR TITLE
Update reference compiler to 3.0.0-M3

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
```scala
[error] -- Error: community-build/community-projects/shapeless/modules/deriving/src/main/scala/shapeless3/deriving/erased.scala:86:25 
[error] 86 |      mirror.fromProduct(ArrayProduct(arr))
[error]    |                         ^^^^^^^^^^^^
[error]    |Reference to creator proxy for class ArrayProduct in object ErasedProductInstances
[error]    |shadows outer reference to object ArrayProduct in package scala.deriving
[error] one error found
```

**Comment by nicolasstucki** [comment]
Tests for `dotty.communitybuild.CommunityBuildTestA.scissLucre` failed on CI (not on my machine) with the following error.

```scala
2020-12-17T08:28:55.0143146Z com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=5,015,453,696 diskFreeSpace=353,255,424 availableLogSize=-5,015,453,696 totalLogSize=1,266 activeLogSize=1,266 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={}
2020-12-17T08:28:55.0150197Z 	at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5337)
2020-12-17T08:28:55.0153715Z 	at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5314)
2020-12-17T08:28:55.0156819Z 	at com.sleepycat.je.Cursor.putInternal(Cursor.java:2410)
2020-12-17T08:28:55.0159555Z 	at com.sleepycat.je.Cursor.putInternal(Cursor.java:830)
2020-12-17T08:28:55.0162063Z 	at com.sleepycat.je.Database.put(Database.java:1603)
2020-12-17T08:28:55.0164430Z 	at com.sleepycat.je.Database.put(Database.java:1656)
2020-12-17T08:28:55.0167089Z 	at de.sciss.lucre.store.BerkeleyDB$Impl.put$$anonfun$1(BerkeleyDB.scala:194)
2020-12-17T08:28:55.0170073Z 	at de.sciss.lucre.store.BerkeleyDB$TxEnv.withIO(BerkeleyDB.scala:323)
2020-12-17T08:28:55.0173115Z 	at de.sciss.lucre.store.BerkeleyDB$Impl.put(BerkeleyDB.scala:195)
2020-12-17T08:28:55.0176011Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.write(DurableImpl.scala:115)
2020-12-17T08:28:55.0179072Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.write$(DurableImpl.scala:34)
2020-12-17T08:28:55.0182073Z 	at de.sciss.lucre.impl.DurableImpl$System.write(DurableImpl.scala:488)
2020-12-17T08:28:55.0185232Z 	at de.sciss.lucre.impl.DurableImpl$CachedIntVar.update(DurableImpl.scala:410)
2020-12-17T08:28:55.0188504Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.newIdValue(DurableImpl.scala:104)
2020-12-17T08:28:55.0191674Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.newIdValue$(DurableImpl.scala:34)
2020-12-17T08:28:55.0194883Z 	at de.sciss.lucre.impl.DurableImpl$System.newIdValue(DurableImpl.scala:488)
2020-12-17T08:28:55.0198001Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.rootBody(DurableImpl.scala:62)
2020-12-17T08:28:55.0201030Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.rootJoin(DurableImpl.scala:54)
2020-12-17T08:28:55.0204048Z 	at de.sciss.lucre.impl.DurableImpl$Mixin.rootJoin$(DurableImpl.scala:34)
2020-12-17T08:28:55.0207750Z 	at de.sciss.lucre.impl.DurableImpl$System.rootJoin(DurableImpl.scala:488)
...
```
@anatoliykmetyuk could you investigate that?

**Comment by nicolasstucki** [comment]
`community_build_a` was skipped for some reason.

**Comment by anatoliykmetyuk** [comment]
Let's not disable it just yet. Our lampsrv26 is leaking space, we ran out of all space on that machine. The reason is Docker: see moby/moby#32420 and docker/distribution#2212. I tried running `docker system prune -a` and then nuking `/var/lib/docker/volumes/<big_hash>/_data/docker/registry/v2/blobs` which gave us 100GB of space on that machine.

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
