### PR TITLE
Add -Vprofile option

### PR DESCRIPTION
**Pull request by odersky**
Add `-Vprofile` and `-Vprofile-sorted-by` options.

This prints for each source file

 - the number of code lines
 - the number of tokens
 - the size of serialized tasty trees (just the trees, not the name table, nor the positions)
 - the complexity per line, computed by the formula (tasty-size/lines/50). That is, we
   assume 50 tasty-bytes/line as standard. 

Using `-Vprofile-sorted-by` one can sort by a column name.

### CODE REVIEW

**Comment by odersky** [comment]
Two questions:

 - This currently is awkwardly close in naming to the `-Yprofile-enabled` and related options. I believe `-Yprofile-enabled` is only for internal use; not sure when it was used last at all. Should we rename `-Yprofile-enabled`?
 - What is the best way to document the option and its uses (which would be: to pinpoint hidden complexity leading to long compile times).

**Comment by odersky** [comment]
Additionally, option `-Vprofile-details N` prints the details of the `N` most complex methods (measured by size of the generated Tasty).

**Comment by odersky** [comment]
The new format shows the Tasty size in terms of number of "chunks" where one chunk = 50 bytes. The threshold between low and moderate complexity is when chunk count and line count are the same.

**Comment by odersky** [comment]
The `-Vprofile` option gives some insights in code complexity and where compilation time is likely spent. If given the compiler prints a summary for every compiled source. It looks like this:
```
Sourcefile                   Lines   Tokens   Tasty  Complexity/Line    Directory
ConstantOps.scala               22      210      21   0.95  low         semanticDB
LinkMode.scala                   3       20      24   8.00  high        semanticDB
Serializer.scala                28      385      32   1.14  moderate    coverage
Location.scala                  34      215      65   1.91  moderate    coverage
Coverage.scala                  19      119      93   4.89  moderate    coverage
SyntheticsExtractor.scala      118      998     112   0.95  low         semanticDB
Tools.scala                    105     1081     113   1.08  moderate    semanticDB
SemanticSymbolBuilder.scala    128     1201     141   1.10  moderate    semanticDB
Descriptor.scala               112      780     243   2.17  moderate    semanticDB
PPrint.scala                   362     3526     446   1.23  moderate    semanticDB
TypeOps.scala                  391     3740     482   1.23  moderate    semanticDB
ExtractSemanticDB.scala        410     4259     529   1.29  moderate    semanticDB
Scala3.scala                   435     4391     680   1.56  moderate    semanticDB
---------------------------------------------------------------------
Total                         2167    20925    2977   1.37  moderate    
1 warning found
```
The columns are:

 - the source file name,
 - the number of code lines in the source, excluding comments and whitespace,
 - the number of tokens (separately parsed words) in the source, 
 - the number of Tasty chunks produced the source. A chunk consists of 50 bytes of Tasty output that serializes the type-checked tree coming from the source, using some compression techniques. The size of generated Tasty is a good estimator of compile times and code complexity. 
 - the average complexity per line, which is computed by dividing the number of lines by the number of Tasty chunks. 
 - an explanation of the average complexity number, computed as follows:
     - _low complexity_: fewer Tasty chunks than source lines,
     - _moderate complexity_: up to 5 times as many Tasty chunks than source lines,
     - _high complexity_: up to 25 times as many Tasty chunks than than source lines,
     - _extreme complexity_": At least 25 times as many Tasty chunks than than source lines,
 - the directory where the source is located.

**Comment by odersky** [comment]
The previous comment is a first stab at docs for `-Vprofile`. The question remains where should we put these docs and when should they be shown? It basically looks like a man page, but I don't think we have man pages for options.

**Comment by dwijnand** [comment]
Well there's https://docs.scala-lang.org/overviews/compiler-options/index.html and then the various pages next to https://docs.scala-lang.org/scala3/guides/migration/options-new.html.  Also, for options that take arguments, like -Wconf and -Xlint, there's a practice of adding some guidance under `-Xlint:help`.

**Comment by odersky** [comment]
> Well there's https://docs.scala-lang.org/overviews/compiler-options/index.html and then the various pages next to https://docs.scala-lang.org/scala3/guides/migration/options-new.html. Also, for options that take arguments, like -Wconf and -Xlint, there's a practice of adding some guidance under -Xlint:help.

The closest would be to include `-Vprofile` in `options-new.html`, but then the doc would be only a line or two. 
We'd need a general mechanism to find out more about an option. Ideally `scalac -help -<option-name>` should do something useful.

**Comment by odersky** [comment]
> then the various pages next to https://docs.scala-lang.org/scala3/guides/migration/options-new.html.

I tried to add something about VProfile, but can't find that the markdown source of that file. Where is it?

**Comment by dwijnand** [comment]
https://github.com/scala/docs.scala-lang/blob/main/_overviews/scala3-migration/options-new.md

**Comment by odersky** [comment]
@dwijnand Thanks! I made a PR: https://github.com/scala/docs.scala-lang/pull/2428

**Comment by odersky** [comment]
@som-snytt The problem here is that `-Vprofile` is not a `ChoiceSetting`.

**Comment by som-snytt** [comment]
The boolean check is `.isSetByUser` on scala 2, maybe I can find an example of choices used that way, with a default so `-Vprofile` works.

**Review by dwijnand — APPROVED** [review]

**Comment by bishabosha** [comment]
This option is not very useful for profiling code that depend on `inline` methods heavily - and `inlining` phase can be very significant

**Pull request merged**
