### PR TITLE
fix:better error msg for cyclic error for constructors

### PR DESCRIPTION
**Pull request by doofin**
This provides better error msg for https://github.com/lampepfl/dotty/issues/17076 , doesn't solve the cyclic error yet
image

### CODE REVIEW

**Comment by doofin** [comment]
I signed Scala CLA although CI shows as failed

**Comment by SethTisue** [comment]
the `CoursierScalaTests` failure would probably go away if you rebase on top of the recently merged #17127

**Comment by doofin** [comment]
Sorry I just messed up with my branch , new PR goes to https://github.com/lampepfl/dotty/pull/17131 rebased with recent updates

**Comment by anatoliykmetyuk** [comment]
> the CoursierScalaTests failure will probably go away if you rebase on top of the recently merged https://github.com/lampepfl/dotty/pull/17127

That PR only adds better debugging info for the error. #17141 should fix it.

**Pull request closed without merging**
