### PR TITLE
Fix #16693 scaladoc inserts -project-logo twice

### LINKED ISSUE #16693: scaladoc inserts -project-logo twice
Scaladoc version 3.2.1 -- Copyright 2002-2022, LAMP/EPFL

Using the `-project-logo` command line flag results in the logo being included twice in the generated HTML, and it being displayed twice.

Screenshot_2023-01-13_22-45-11

### PR DESCRIPTION
**Pull request by little-inferno**

### CODE REVIEW

**Comment by little-inferno** [comment]
Maybe i should add additional flag -dark-project-logo instead of this implicit magic with "$logo-file-name_dark" ?

**Review by szymon-rd — APPROVED** [review]

**Comment by szymon-rd** [comment]
@little-inferno Please rebase this commit onto `language-reference-stable` and change the PR base.

**Comment by little-inferno** [comment]
@szymon-rd Done

**Comment by szymon-rd** [comment]
@little-inferno Thanks!

**Comment by little-inferno** [comment]
@szymon-rd when will this be merged?

**Comment by ckipp01** [comment]
Thanks for this @little-inferno, although it looks like this was also added in cabfa689274, so I'm going to go ahead and close here.

**Pull request closed without merging**
