### PR TITLE
docs: add example how to unlift opaque type

### PR DESCRIPTION
**Pull request by vitaliis**
documentation page shows how to lift into opaque type,
but doesn't show [an example] of how to unlift it

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Thank you for the contribution @vitaliis! Can you please sign the CLA [here](https://www.lightbend.com/contribute/cla) so that we can merge this?

**Comment by vitaliis** [comment]
I thought it is already done. Ok. Signed the one for Scala.

**Comment by vitaliis** [comment]
Seemed to be not enough. Submitted it for lightbend as well. Got "Thank you! Your submission was processed.". It is fine now?

**Comment by vitaliis** [comment]
Apparently something has changed because previously it showed me (as you can see above):
> All contributors have signed the CLA, thank you! :heart:

**Comment by vitaliis** [comment]
Sorry. Another attempt (copy-paste from email):
> If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

I did sign the CLA.

**Comment by anatoliykmetyuk** [comment]
@vitaliis, it looks like we're having troubles with our CLA system. Currently, we check the CLA status manually via the following link: `https://www.lightbend.com/contribute/cla/scala/check/<username>`. For you, `https://www.lightbend.com/contribute/cla/scala/check/vitaliis`, it still says `"signed": false`. This is not the first time we are having problems related to CLA – so could you help us figure out what went wrong? Precisely, can you please let us know what exact steps are you taking while signing the CLA?

**Comment by vitaliis** [comment]
Now there is `given logarithmOps: {` `toDouble` method. So this example became deprecated.

**Pull request closed without merging**
