### PR TITLE
Doc on how to build on Eclipse

### PR DESCRIPTION
**Pull request by odersky**
This is what works for me. I have written it down so that I remember
the next time I have to update the project. If others have different
schemes, please comment and edit.

### CODE REVIEW

**Comment by sjrd** [comment]
1 + 2 is basically what I do.

Also, I have to explicitly change the Compliance levels of `dotty-interfaces` to use Java 8 compliant settings. Otherwise it complains on `default` methods.

**Comment by smarter** [comment]
I can't comment on the content but I suggest putting that kind of information on the wiki, the [Getting Started](https://github.com/lampepfl/dotty/wiki/Getting-Started) page already contains information on the Scala IDE, maybe update that?

**Comment by odersky** [comment]
@smarter The linked wiki page is for users of `dotc`. This one if for contributors. So I don't think they should be the same page. But I am OK with putting it on the wiki as a separate page if people prefer that.

**Comment by odersky** [comment]
I opened a wiki page with the contensts

**Pull request closed without merging**
