### PR TITLE
Add quoted.Type.valueOfTuple

### PR DESCRIPTION
**Pull request by nicolasstucki**
```scala
  /** Extracts the value of a tuple of singleton constant types.
   *  Returns Some of the tuple type if it is a tuple singleton constant types.
   *  Returns None if the type is not a tuple singleton constant types.
   *
   *  Example usage:
   *  ```scala
   *  ... match
   *    case '{ $mirrorExpr : Mirror.Sum { type MirroredElemLabels = label } } =>
   *      Type.valueOfTuple[label] // Option[Tuple]
   *  }
   *  ```
   *  @syntax markdown
   */
  @experimental
  def valueOfTuple[T <: Tuple](using Type[T])(using Quotes): Option[T] = ...
```

### CODE REVIEW

**Comment by nicolasstucki** [comment]
See https://github.com/lampepfl/dotty/issues/12417#issuecomment-838572813

**Comment by nicolasstucki** [comment]
Will need rebase on #12371

**Review by liufengyun — APPROVED** [review]
LGTM

**Review by liufengyun — APPROVED** [review]
CI failed, otherwise LGTM

**Pull request merged**
