### PR TITLE
Add a test that showcases #462

### PR DESCRIPTION
**Pull request by DarkDimius**

### CODE REVIEW

**Comment by DarkDimius** [comment]
Cannot get travis to reproduce the issue, though It always triggers on my machine.

**Comment by odersky** [comment]
I can't reproduce the error. But happy to include the test anyway.

**Comment by odersky** [comment]
But it needs to be rebased.

**Comment by DarkDimius** [comment]
The error seems to be fixed, I cant reproduce it anymore either.

**Comment by odersky** [comment]
I guess we can close this one then.

**Pull request closed without merging**
