### PR TITLE
Fix bootstrap 2

### PR DESCRIPTION
**Pull request by odersky**
This differs from #1270 only in the last commit, where finger printing was removed. The plan is to merge this PR with master one day after #1270 to verify what the effect on compiler performance is.

### CODE REVIEW

**Comment by smarter** [comment]
> Trying the dotc bootstrap revealed that Frozen logic can lead
to assertion errors. So we want to remove it, but then taking
fingerprints would no longer be cost-effective.

Is it not possible to fix `Frozen`?

**Comment by odersky** [comment]
@smarter I don't see a way to fix `Frozen`.

**Comment by DarkDimius** [comment]
> Trying the dotc bootstrap revealed that Frozen logic can lead to assertion errors.

would you elaborate about under which circumstances the Frozen logic is not working? Is it specific to Dotty bootstrap?

**Comment by odersky** [comment]
It turned out that errors connected with Frozen were just early warnings of an unrelated problem with Tasty unpickling. So we do not need to drop it, after all.

**Pull request closed without merging**
