### PR TITLE
Cleanup current/prev inversion in Constraint methods

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Review by odersky — APPROVED** [review]
LGTM. It would be good if @smarter could also take a look.

**Comment by smarter** [comment]
Any reason to close this? It was on my todo list to review now that I'm back working.

**Comment by dwijnand** [comment]
@smarter shall I rebase this one again?

**Comment by smarter** [comment]
Sorry I was planning to rebase it myself but  forgot, I'm on holiday this week but next week I'll be able to review and rebase if needed this pr

**Comment by dwijnand** [comment]
Spent too long trying to figure out my mistake in rebasing and it's not worth it at this point.

**Pull request closed without merging**
