### PR TITLE
Homogenize mutable symbol maps

### PR DESCRIPTION
**Pull request by nicolasstucki**
Use IdentityHashMap instead of mutable.HashMap to make fast equality check

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance please

**Comment by OlivierBlanvillain** [comment]
LGTM!

**Comment by nicolasstucki** [comment]
test performance please

**Pull request merged**
