### PR TITLE
fix: need to capture all scripting args when script arg is detected

### PR DESCRIPTION
**Pull request by philwalk**
This fixes 2 issues:

1. rename mispelled array `scripting_args` to `script_args`
2. capture potentially lost scripting args

An example of the 2nd issue would be if a script expects arguments `-script`, '-repl`, '-run`, etc.
Here's a script that prints all arguments, and what it should print.

```sc
scala showargs.sc a b c -repl -run -script -debug
arg  0:[a]
arg  1:[b]
arg  2:[c]
arg  3:[-repl]
arg  4:[-run]
arg  5:[-script]
arg  6:[-debug]
```

Here's the same script called via `scalac -script`:
```sc
$ scalac -script ssrc/showargs.sc a b c -run -repl -script
arg  0:[a]
arg  1:[b]
arg  2:[c]
arg  3:[-repl]
arg  4:[-run]
arg  5:[-script]
arg  6:[-debug]
```

### CODE REVIEW

**Review by liufengyun — COMMENTED** [review]
Thanks @philwalk. Can we add regression tests for the spotted problems?

**Comment by philwalk** [comment]
> Thanks @philwalk. Can we add regression tests for the spotted problems?
I can add some tests.

**Comment by philwalk** [comment]
Two tests are now added to verify that script arguments are preserved, even when they collide with `dist/bin` bash script options.

**Review by liufengyun — APPROVED** [review]
LGTM, thanks @philwalk 🎉 

Could you please rebase against master (instead of merge master into the PR)?

**Comment by philwalk** [comment]
> 
> 
> LGTM, thanks @philwalk 🎉
> 
> Could you please rebase against master (instead of merge master into the PR)?

Ok.  I'm not a `git` expert, but perhaps my default `git` settings are causing problems.   I'll figure it out.

**Comment by liufengyun** [comment]
> The only thing I did differently on this PR was to fetch upstream periodically so I could avoid merge issues.
> I assume the requirement is that in the future, I do a git rebase master after commits, and before pushing changes.

Yes, using rebase will avoid the `merge commits` thus makes history cleaner. And then you can (have to) force push to the PR.

> I just changed the pulldown to Enable auto-merge (rebase) on this page, hopefully that's correct.
> I notice the [Merge Pull Request] button below. I'm guessing that should be changed to [Rebase and Merge]

Thanks, I don't know that `rebase and merge` exists, I'll use that.

**Comment by liufengyun** [comment]
> > I notice the [Merge Pull Request] button below. I'm guessing that should be changed to [Rebase and Merge]

> Thanks, I don't know that rebase and merge exists, I'll use that.

I notice `rebase and merge` will not create a merge commit. It's still preferable to have a merge commit. Could you instead rebase and force push to the PR branch? Hopefully that will get rid of the `merge commits` and we can merge it as usual.

**Comment by philwalk** [comment]
> I notice `rebase and merge` will not create a merge commit. It's still preferable to have a merge commit. Could you instead rebase and force push to the PR branch? Hopefully that will get rid of the `merge commits` and we can merge it as usual.

I tried to rebase but there are merge requirements that I'm not qualified to resolve, so I think I should close this PR and create another with the changes from this PR.

**Comment by philwalk** [comment]
I will create a new pull request with identical changes in the same 4 files:
```sc
compiler/test-resources/scripting/showArgs.sc
compiler/test/dotty/tools/scripting/BashScriptsTests.scala
dist/bin/scala
dist/bin/scalac
```

**Comment by philwalk** [comment]
this is superceded by #12467

**Pull request closed without merging**
