### PR TITLE
Hide fewer-braces page.

### PR DESCRIPTION
**Pull request by julienrf**
See b1a68679cd666db9f4752daca988d71429b8d242.

### CODE REVIEW

**Comment by pikinier20** [comment]
It only hides the page on reference documentation but the PR is targeted to main, so this change won't affect neither the dotty.epfl.ch nor docs.scala-lang.com until release

**Comment by odersky** [comment]
How do we hide a page that's no longer relevant?

**Comment by pikinier20** [comment]
It's just matter of the sidebar.yml in which the change is introduced. This one is dedicated for reference documentation. Applying this change to `docs/sidebar.yml` will hide the page

**Comment by julienrf** [comment]
> It only hides the page on reference documentation but the PR is targeted to main, so this change won't affect neither the dotty.epfl.ch nor docs.scala-lang.com until release

Yes, the PR targets main because it reflects the current state (not yet released) of the compiler. I chose to hide the page from the sidebar to not break possible links from the outside.

**Comment by pikinier20** [comment]
> > It only hides the page on reference documentation but the PR is targeted to main, so this change won't affect neither the dotty.epfl.ch nor docs.scala-lang.com until release
> 
> Yes, the PR targets main because it reflects the current state (not yet released) of the compiler. I chose to hide the page from the sidebar to not break possible links from the outside.

But shouldn't we hide the page on both sidebars?

**Comment by julienrf** [comment]
> But shouldn't we hide the page on both sidebars?

I’d like to ask Martin about this change then, since that would be impact dotty.epfl.ch. On my side, I’m fine with removing the page from dotty.epfl.ch because I think this website is more like a “live” documentation of the nightly state of the compiler.

**Comment by odersky** [comment]
The page can be hidden from both sidebars.

**Comment by julienrf** [comment]
OK, I pushed another commit to align both websites. They now both render the page, but hide them from the sidebar.

**Review by pikinier20 — APPROVED** [review]

**Pull request merged**
