### PR TITLE
Remove "(both forms are equivalent)" after only one form

### PR DESCRIPTION
**Pull request by Kazark**
Only one form is listed. Alternatively, perhaps this is the wrong change and the other form needs to be implemented---I am too ignorant to know (which is why I was reading this page).

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Scala CLA is not [signed](https://www.lightbend.com/contribute/cla/scala/check/Kazark). @Kazark could you sign it [here](https://www.lightbend.com/contribute/cla/scala).

**Comment by Kazark** [comment]
@nicolasstucki Thank you. When I first submitted, there was a message about the CLA service being down, and I was not sure how to sign.

**Comment by Kazark** [comment]
@nicolasstucki Hm, how do I ask the CLA bot to recheck?

**Comment by nicolasstucki** [comment]
CLA is ok https://www.lightbend.com/contribute/cla/scala/check/Kazark

**Comment by nicolasstucki** [comment]
Thank you @Kazark

**Pull request merged**
