### PR TITLE
Disallow synthesized lambdas in statement position

### LINKED ISSUE #11761: Eta expansion undesirable when result will be immediately discarded
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
def go(x: Int): Unit =
  go
```

## Output

```
[warn] -- [E129] Potential Issue Warning: /home/golly/projects/public/univeq/univeq/shared/src/main/scala-3/japgolly/univeq/internal/bug.scala:2:2 
[warn] 2 |  go
[warn]   |  ^^
[warn]   |A pure expression does nothing in statement position; you may be omitting necessary parentheses
```

## Expectation

The code shouldn't compile. The `go` function requires an explicit `x` argument. It's probably converting `go` to a function literal which is normally fine, but doesn't make sense if its the entirely of the statement and not a return value.

(Also keep in mind that this is the minimised case, the real case I encountered was much more confusing and dangerous.)

### PR DESCRIPTION
**Pull request by odersky**
Disallow lambdas in statement position or if the expected type is Unit. This was a loophole that opened up due to the changes to eta expansion in Scala 3. We did get a warning in these cases, but an error might be better.

Fixes #11761

### CODE REVIEW

**Comment by som-snytt** [comment]
Scala 3 is quite opinionated! I wondered if this will clash in a REPL, where people try expressions typically. If the templating adds a valdef, it is OK. I don't know about worksheets. BTW, punning on "try expression", `try f` no longer warns about missing `catch/finally`. `List(42).map(try f)`

Recently I thought that warnings should be REPL-sensitive. I opened a Scala 2 ticket that REPL was swallowing `Pattern definition introduces Unit-valued member`, but it turned out that when I added that warning, I suppressed it if detecting that it occurs in a REPL template, because the warning is irrelevant in that context -- unless you are interested in seeing exact scalac behavior, which is also the use case for REPL.

It may be the job of the reporter to filter warnings in REPL, rather than the issuer to detect a REPL context.

**Comment by odersky** [comment]
This looks like a simple fix that makes sense, but it has been nightmarish since it seems all testing frameworks hate me now.

There are two utest tests that fail where I am stuck. Unfortunately the assertions fail without
any info and I don't know enough about utest to figure out what went wrong. So I had to disable
the test. Who knows enough about utest to follow up on this?

**Comment by odersky** [comment]
The latest iteration of this does allow user-defined lambdas in statement position even though they don't make sense since
all testing suites rely on this heavily. So what we do is to try to flag as errors just synthetic lambdas that arise from eta expansion or other operations. The problem is how to to detect these lambdas. That has been super tricky.

**Review by abgruszecki — APPROVED** [review]
LGTM!

**Comment by griggt** [comment]
> There are two utest tests that fail where I am stuck. Unfortunately the assertions fail without any info and I don't know enough about utest to figure out what went wrong. So I had to disable the test. Who knows enough about utest to follow up on this?

I took a look and proposed a fix in #11887.

**Pull request merged**
