### PR TITLE
Fix #7512: Add regression test

### LINKED ISSUE #7512: Infinite loop for given ev with match types on dependently typed method args
## Minimized code

This code implements type-level addition and multiplication on top of `scala.compiletime.S`. The `testProd` looks for given evidence that the multiplication commutes for two particular values.

```Scala
import scala.compiletime.ops.int.S

object InfiniteLoopMatchType {
    def main(args: Array[String]): Unit = {
        testProd(2, 3) // Infinite loop on Dotty 0.20.0-RC1
    }

    def testProd(a: Int, b: Int)(using ev: (a.type * b.type) =:= (b.type * a.type)) = true

    type *[A <: Int, B <: Int] <: Int = A match {
        case 0 => 0
        case _ => MultiplyLoop[A, B, 0]
    }

    type MultiplyLoop[A <: Int, B <: Int, Acc <: Int] <: Int = A match {
        case 0 => Acc
        case S[aMinusOne] => MultiplyLoop[aMinusOne, B, B + Acc]
    }

    type +[A <: Int, B <: Int] <: Int = A match {
        case 0 => B
        case S[aMinusOne] => aMinusOne + S[B]
    }
}
```

## Behavior
The compiler loops infinitely (or at least for a very long time, 20+ minutes).

## Expectation
The compiler should be able to reduce `2 * 3` and `3 * 2` to `6`, and trivially find an implicit for `6 =:= 6`. 

## Narrowing down the issue
The following compiles instantly, which leads me to believe that the issue is with dependently typed methods:

```scala
val a: 2 = 2
val b: 3 = 3
implicitly[(a.type * b.type) =:= (b.type * a.type)]
```

Alternatively, the following definition of type addition compiles faster (~10s) but still quite slowly compared to the `implicitly`:

```scala
type +[A <: Int, B <: Int] <: Int = A match {
    case 0 => B
    case S[aMinusOne] => S[aMinusOne + B]
}
```

## Related issues
I did not find any related issues.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Now it takes around 1 minute to compile instead of 20+ minutes.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@liufengyun this might be a good candidate for a benchmark. Could you add it?

**Comment by liufengyun** [comment]
> @liufengyun this might be a good candidate for a benchmark. Could you add it?

I'll add that.

**Comment by nicolasstucki** [comment]
The underlying issue is still there if we increase any number in `testProd(2, 3)`. The benchmark will me a better way to track progress or regression on this issue.

**Comment by liufengyun** [comment]
> The underlying issue is still there if we increase any number in `testProd(2, 3)`. The benchmark will me a better way to track progress or regression on this issue.

Maybe put it under `tests/bench/`?

**Comment by nicolasstucki** [comment]
Will do

**Pull request closed without merging**
