### PR TITLE
Fix #6622: Add `code` interpolation

### LINKED ISSUE #6622: Make compiletime.error more useful
Right now `error` is defined like this:
```
inline def error(inline msg: String, objs: Any*): Nothing
```
We should make it take a full interpolated string. That does not work now, since interpolated
strings are not inline constants.

### PR DESCRIPTION
**Pull request by rtfpessoa**
Allows to get string representations for code passed in the interpolated
values

```scala
inline def logged(p1: => Any) = {
  val c = code"code: $p1"
  val res = p1
  (c, p1)
}
logged(indentity("foo"))
```

is equivalent to:
```scala
("code: indentity("foo")", indentity("foo"))
```

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Thanks a lot to @nicolasstucki and @biboudis for the help, coaching and patience.

**Comment by biboudis** [comment]
Nice work!

**Comment by allanrenucci** [comment]
What is the rational to implement this in the compiler instead of as a macro?

**Comment by nicolasstucki** [comment]
As we plan to use this feature inside the standard library we cannot use a macro due to potential bootstrapping issues.

**Comment by nicolasstucki** [comment]
Thanks @rtfpessoa

**Pull request merged**
