### PR TITLE
Fix #8531: Annnotations on class value parameters go to the constructor

### LINKED ISSUE #8531: java annotation with @Retention(RUNTIME) is not retained for parameters
## minimized code

Named.java
```java
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Named {}
```

Test.scala
```scala
class Foo(@Named s: String)

object Test {
  def main(args: Array[String]): Unit = {
    val ctor = classOf[Foo].getDeclaredConstructors()(0)
    val annots = ctor.getParameterAnnotations()(0)
    println(annots.length) // == 0 in dotty, == 1 in scala 2
    assert(annots.length == 1)
  }
}
```

## expectation
`annots.length == 1` as in scala 2

### PR DESCRIPTION
**Pull request by smarter**
Mimic the behavior of Scala 2: an annotation on a class value
parameters (but not on a type parameter) is moved to the constructor
parameter and not to any of the derived parameters.

### CODE REVIEW

**Comment by smarter** [comment]
@odersky @nicolasstucki The signature of paramSymss is:
```scala
def paramSymss(using ctx: Context): (List[TypeSymbol], List[List[TermSymbol]])
```
This assumes that we only have one type parameter list which might not be correct in the future, this is especially problematic since we're exposing this API via tasty-reflect, so we need something future-proof. I suggest:
```scala
def paramSymss(using ctx: Context): List[List[Symbol]]
``

**Comment by smarter** [comment]
> def paramSymss(using ctx: Context): List[List[Symbol]]

We agreed to this in a meeting, I'll do the change.

**Comment by milessabin** [comment]
@smarter 
> Once this is merged and a new nightly is published, I could make a PR against your shapeless-3 branch to get this upstream, would that be convenient for you ?

:100:

**Comment by milessabin** [comment]
@smarter I've updated shapeless here: https://github.com/lampepfl/dotty/pull/8705.

**Pull request merged**
