### PR TITLE
Upgrade reference compiler to 3.0.1-RC2

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by smarter** [comment]
```scala
 Error:  -- Error: /__w/dotty/dotty/library/src/scala/annotation/experimental.scala:14:6 
Error:  14 |class experimental extends StaticAnnotation
Error:     |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:     |use of @experimental is experimental and therefore may only be used with a nightly or snapshot version of the compiler
```
@nicolasstucki Did something change in how `@experimental` is checked between 3.0.0 and 3.0.1-RC2?

**Comment by bishabosha** [comment]
> @nicolasstucki Did something change in how @experimental is checked between 3.0.0 and 3.0.1-RC2?

forward port https://github.com/lampepfl/dotty/pull/12672 ?

**Comment by smarter** [comment]
@anatoliykmetyuk Should https://github.com/lampepfl/dotty/pull/12672 be backported to release-3.0.1? As is, the compiler from that branch cannot be used as a reference compiler, so we can't release 3.0.1 without fixing that.

**Comment by anatoliykmetyuk** [comment]
Seen that 3.0.1 is around the corner, I think we can just wait for it to be released and then use it as a reference compiler.

**Comment by smarter** [comment]
Looks like the issue with `@experimental` doesn't happen when using a nightly as a reference compiler, so hopefully we'll be able to use 3.0.2-RC1 as our reference compiler (and just skip 3.0.1 since using the latest RC is more valuable anyway). However stdlib-sourcelinks-test fails currently:
> Error:  Test dotty.tools.scaladoc.sourcelinks.RemoteLinksTest.runTest failed: Page 3.0.2-RC1-bin-20210628-10145ff-NIGHTLY/tasty/src/dotty/tools/tasty/TastyBuffer.scala does not exists, took 4.883 sec

@BarkingBad could you have a look at why this test is failing when using a nightly compiler as our reference compiler?

**Comment by BarkingBad** [comment]
The `RemoteLinksTest` is supposed to test whether the source links are pointing to the correct repository and to the correct line. The source links of the new dotty classes are based on the `referenceVersion` property to build the link. It's not only the problem with the test, all the docs published after merging this PR will have `source link url` pointing to, for example: `https://github.com/lampepfl/dotty/blob/3.0.2-RC1-bin-20210628-10145ff-NIGHTLY/library/src/scala/quoted/runtime/Expr.scala#L7`,  that will yield 404 (since the link is broken). We can either:
- provide git tag for the reference version (the links will work)
- remove `referenceVersion` property dependency from the calculated source-link and set it to be `3.0.0` for now (but we would have to update it after `3.0.1` release etc.
- all other solutions with conditional logic/dictionaries

What solution do you like the most?

**Comment by anatoliykmetyuk** [comment]
> @anatoliykmetyuk Should #12672 be backported to release-3.0.1? As is, the compiler from that branch cannot be used as a reference compiler, so we can't release 3.0.1 without fixing that.

The functionality appears to already be present in `3.0.1` branch: https://github.com/lampepfl/dotty/blob/release-3.0.1/compiler/src/dotty/tools/dotc/config/Properties.scala#L91

**Comment by smarter** [comment]
@BarkingBad I'll let you choose what you think is best for maintaining this test, keeping in mind that we should really avoid having tests that can randomly start failing when something unrelated changes, so

> remove referenceVersion property dependency from the calculated source-link and set it to be 3.0.0 for now (but we would have to update it after 3.0.1 release etc.

Seems fine to me.

**Comment by BarkingBad** [comment]
I checked it once again and missed Krzysztof has made some enhancement for links to point them to hash commit rather than to git tag, but didn't apply it for tasty sources (which defaulted to 3.0.0). I made PR to this branch that should fix that https://github.com/dotty-staging/dotty/pull/18

**Comment by smarter** [comment]
Can you open a separate pr for that? We might not end up merging this one.

**Comment by BarkingBad** [comment]
Sure, here it is #12990

**Comment by odersky** [comment]
Fixed by changes to @experimental.

**Pull request closed without merging**
