### PR TITLE
Intrinsify scala.compiletime.testing.typeChecks

### PR DESCRIPTION
**Pull request by nicolasstucki**
As know from the start, this funtionallity should not have been added to the reflection API.
Nevertheless it is still possible to use its result in a macro.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@liufengyun could you help me to update the scalatest macros to use this new version. Have a look at how I handled it in tests/run-macros/reflect-typeChecks/assert_1.scala

**Comment by milessabin** [comment]
Is this going to break shapeless as well?

I'm happy to update as soon as there's a nightly build published with the change.

**Comment by bishabosha** [comment]
minitest also is affected
https://github.com/dotty-staging/minitest/blob/9d5fbb80dcb095baac88deb4960d616870745cf9/shared/src/main/scala/minitest/api/Asserts.scala#L129

**Comment by nicolasstucki** [comment]
Shapeless should not be affected. CI tests passed for it.

**Comment by nicolasstucki** [comment]
I will update minitest. With this change we will not need the macro anymore as it fixed #7040 and we can use that as implementation.

**Comment by liufengyun** [comment]
@nicolasstucki I'll have a look at ScalaTest.

**Comment by liufengyun** [comment]
@nicolasstucki This change makes it awkward to implement macros like `assertDoesNotDompile` in ScalaTest, as now it's impossible to call `typeChecks` from macro implementation --- the method has to be called inside the inline method.

On reflection, it seems `compiletime` + `inline` is not a good combination for the API, as one program's compile-time could be another program's run-time. The change makes it impossible to use the API from staging and macro implementation.

BTW, what makes it not fit in reflection API?

> As know from the start, this funtionallity should not have been added to the reflection API.

**Comment by nicolasstucki** [comment]
It does not fit the TASTy reflection API because it has nothing to do with typed trees. We just added it there because it was a simple but dirty way to support it and unblock the scalatest/minitest macros.

**Pull request merged**
