### PR TITLE
Fix/#652 erase constructors

### PR DESCRIPTION
**Pull request by odersky**
Several problems detected and fixed when trying to compile constructors.scala. These are all pretty fundamental, and therefore a version of the PR should be merged before we try to continue with the bootstrap. Review by @DarkDimius.

### CODE REVIEW

**Comment by odersky** [comment]
Fixes #652

**Comment by odersky** [comment]
Now fixes also #644

**Comment by odersky** [comment]
Hmm, how do I get the original PR back?

**Comment by odersky** [comment]
I'll do a second branch.

**Comment by DarkDimius** [comment]
Otherwise LGTM. No need to revert.

**Pull request merged**
