### PR TITLE
Upgrade to Scala.js 1.3.0.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Review by nicolasstucki — APPROVED** [review]

**Comment by sjrd** [comment]
@liufengyun There's one test failing on the Windows CI although it works locally for me. Apparently an *expected* multiline string literal contains an extra new line that shouldn't be there. Could it be that the Windows CI's git is configured to "checkout Windows-style"? If yes, that should be changed to "checkout as is".

**Comment by liufengyun** [comment]
> @liufengyun There's one test failing on the Windows CI although it works locally for me. Apparently an _expected_ multiline string literal contains an extra new line that shouldn't be there. Could it be that the Windows CI's git is configured to "checkout Windows-style"? If yes, that should be changed to "checkout as is".

@sjrd  To fix the problem once for all Windows, we can try  `.gitattributes`:

https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings

**Comment by sjrd** [comment]
That's not really going to help, because it's for sources of Scala.js that are cloned through a `JGit` command. So adding `.gitattributes` won't help.

I've pushed an attempt at working around the issue by forcing `autocrlf=false` at the `JGit` level. We'll see whether that works.

**Comment by sjrd** [comment]
@anatoliykmetyuk In the community build, for cats-effects-2, I errors like:
```
2020-10-15T17:04:21.4501775Z [error] org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.3 (supported up to: 1.2): /__w/dotty/dotty/community-build/community-projects/cats-effect-2/laws/js/target/scala-0.28/test-classes/cats/effect/ResourceTests.sjsir
2020-10-15T17:04:21.4504067Z [error] You may need to upgrade the Scala.js sbt plugin to version 1.3 or later.
```
So we're running the JS tests of cats-effects-2 in the community build? If yes we should force it to use sbt-scalajs 1.3.0 instead of the 1.2.0 that it declares in its `project/plugins.sbt`. How can I do that?

**Comment by liufengyun** [comment]
> That's not really going to help, because it's for sources of Scala.js that are cloned through a `JGit` command. So adding `.gitattributes` in this repo won't help.
> 
> I've pushed an attempt at working around the issue by forcing `autocrlf=false` at the `JGit` level. We'll see whether that works.

Can you put it in the Scala.js repo?

**Comment by sjrd** [comment]
I could, but it would only work when the next version comes out, so no upgrading for 2 months.

Having anything but `autocrlf=false` globally on Windows is asking for trouble. Nobody does that on their own Windows machine.

**Comment by liufengyun** [comment]
> I could, but it would only work when the next version comes out, so no upgrading for 2 months.
> 
> Having anything but `autocrlf=false` globally on Windows is asking for trouble. Nobody does that on their own Windows machine.

I agree. I already changed the setting on the machine:

```
PS C:\actions-runner2> git config --global core.autocrlf false
PS C:\actions-runner2> git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
core.autocrlf=false
```

To ease maintainability,  I think it is better to minimize external configurations that are not managed by git.

**Comment by anatoliykmetyuk** [comment]
> So we're running the JS tests of cats-effects-2 in the community build? If yes we should force it to use sbt-scalajs 1.3.0 instead of the 1.2.0 that it declares in its project/plugins.sbt. How can I do that?

To override a plugin, you can modify the command with which SBT is started for that test. The following line, e.g., tells each test to use the locally-published SBT Dotty plugin, you can do the same with the Scala.js plugin.

https://github.com/lampepfl/dotty/blob/master/community-build/src/scala/dotty/communitybuild/projects.scala#L83

**Comment by sjrd** [comment]
@anatoliykmetyuk Thanks, that worked! Would you mind reviewing the third commit, where I introduce that (Force-upgrade ...)?

**Review by anatoliykmetyuk — APPROVED** [review]
3rd commit which forces the Scala.js plugin LGTM

**Pull request merged**
