### PR TITLE
Change inference

### PR DESCRIPTION
**Pull request by odersky**
Change inference scheme to look at how type variables are constrained
instead of just taking into account the variance in which they occur in some
type. Review by @smarter.

### CODE REVIEW

**Comment by odersky** [comment]
Can we get this reviewed please? it's been lingering for a long time.

**Comment by smarter** [comment]
Yes, I'm on it

**Comment by smarter** [comment]
Overall I think this PR is a good improvement on the current situation but there are still things which don't work correctly, for example:
```scala
object Test {
  def one[T](x: T)(implicit ev: T): Nothing = ???

  def test = {
    implicit val ii: Int = 42

    one(10)
    // error: ambiguous implicits: both getter StringCanBuildFrom in object Predef$
    // and getter NothingClassTag in object DottyPredef$ match type Any of
    // parameter ev of method one in object Test$
  }
}
```
I'm working on fixing this(it should only require us to be less eager to instantiate in `interpolateUndetVars`) and other issues. I'm not sure if the new design of "interpolate in the direction that was constrained" is the correct thing to do, but we can always revert that in the future if it ends up being a problem.

**Comment by odersky** [comment]
OK, should we get this in then and do further improvements in a separate PR?

**Comment by smarter** [comment]
Yes, sounds good to me.

**Pull request merged**
