### PR TITLE
Implement auto tupling of function arguments

### PR DESCRIPTION
**Pull request by odersky**
Based on #887. Implements SIP #897. Review by @retronym?

### CODE REVIEW

**Comment by retronym** [comment]
@odersky Can you find them in your email archives ("search for "[dotty] Implement auto uncurry"). I don't get email notifications of my own comments, and I can't find them on commits in your previous branch, either: https://github.com/lampepfl/dotty/compare/master...0b8737

**Comment by retronym** [comment]
Oh, it looks like I made my comments on https://github.com/lampepfl/dotty/issues/897.

**Comment by odersky** [comment]
Thanks for digging them out Jason! I'll remember the e-mail trick for next
time.

 - Martin

On Wed, Nov 18, 2015 at 5:06 AM, Jason Zaugg <notifications@github.com>
wrote:

> Oh, it looks like I made my comments on #897
> <https://github.com/lampepfl/dotty/issues/897>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/898#issuecomment-157599492>.
>



-- 
Martin Odersky
EPFL

**Comment by odersky** [comment]
I don't think we see further reviewer comments. Merging.

**Pull request merged**
