### PR TITLE
Improvements to search UX

### PR DESCRIPTION
**Pull request by dylemma**
Aims to address some of the topics from #12526

- Pressing "S" while not focused on an input/textarea will now open the search.
- Pressing "F" while not focused on an input/textarea will focus the member filter input.
- Pressing Escape while focused on the search/filter will clear the input and close/unfocus it
- Search result links are now treated as block elements so you can click anywhere inside the rectangle rather than specifically on the result text.

### CODE REVIEW

**Review by pikinier20 — APPROVED** [review]
Good job! The only detail that we might think about is a key which opens searchbar. I've asked some people and e.g. GitHub open searchbar on '/' button. We might discuss it.

**Comment by dylemma** [comment]
Thanks @pikinier20! 

Interesting about the searchbar key. I chose `S` for the same reason (GitHub opens the search bar with it). Now that you mention it, it seems both `s` and `/` work, so I think I'll update the PR to support both keys.

I'm open to suggestions/alternatives for the filter, e.g. maybe `f` *and* some other key could work?

The other thing I wasn't very sure of was how to signal to users that these key shortcuts exist. For the filter, I could probably copy what GitHub did, and put a little key icon in the side of the input. But for the search, since it's just an icon right now, I don't see an easy modification. Maybe just put the key icon inside the search input once it's open, so users can learn about it after the fact?

**Review by pikinier20 — APPROVED** [review]
LGTM!

**Comment by dylemma** [comment]
Paging @romanowski since you already merged #12595 (the description of that PR said it was intended to be merged after this one)

**Comment by romanowski** [comment]
@pikinier20 merged the PR. @dylemma thank you for your contribution and we are always open to talk about UX and related things in scaladoc :)

**Pull request merged**
