### PR TITLE
Use 0.19.0 as base version

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by smarter** [comment]
Blog post should also be updated:

> Dotty is now using the standard library 2.13 instead of the previous 2.12.8. This fact is reflected in the patch version 1 in 0.18.1-RC1 which Dotty will be using from now on.

**Comment by nicolasstucki** [comment]
The blog post does not mention `0.19.1`, only `0.18.1` which is correct.

**Comment by anatoliykmetyuk** [comment]
> This fact is reflected in the patch version 1

This can be a problem

**Comment by nicolasstucki** [comment]
But it is a patch of `0.18` not `0.19`

**Comment by anatoliykmetyuk** [comment]
This sentence is selling the wrong story. As if, in general, patch version 1 has a relationship with the standard library in use, and the users can expect this relationship to hold also for further versions.

**Comment by bishabosha** [comment]
> which Dotty will be using from now on.

This is the part that should change

**Comment by nicolasstucki** [comment]
> This sentence is selling the wrong story. As if, in general, patch version 1 has a relationship with the standard library in use, and the users can expect this relationship to hold also for further versions.

@anatoliykmetyuk could you fix the misleading blogpost of `0.18.1` in another PR.

**Comment by nicolasstucki** [comment]
We should probably merge this one before #7190 is fixed to avoid publishing misleading nightlies.

**Pull request merged**
