### PR TITLE
Fix rendering of the CONTRIBUTING page on Github

### PR DESCRIPTION
**Pull request by maseev**
This PR is related to the following issue - #2466. 

It appears that the link about contributing (which is located at the bottom) from the [getting-started.md](https://github.com/lampepfl/dotty/blob/master/docs/docs/contributing/getting-started.md) page points to the following [file](https://github.com/lampepfl/dotty/blob/master/CONTRIBUTING) which apparently doesn't have a necessary `.md` file extension in order to be rendered correctly on Github. 

This PR adds the necessary file extension as well as fixes the link in the appropriate file so that users will be able to see the correctly rendered document written in the Markdown language.

### CODE REVIEW

**Comment by maseev** [comment]
Can you tell me where's this generated doc is located? Is it accessible via the Dotty website?

**Comment by allanrenucci** [comment]
>Can you tell me where's this generated doc is located? Is it accessible via the Dotty website?

It should be fixed in the code that generates the doc not in the generated doc. The code that generates the doc is under `doc-tool/src/dotty/tools/dottydoc`

**Comment by allanrenucci** [comment]
I am closing this for now. Feel free to reopen when you have a fix

**Comment by maseev** [comment]
Unfortunately, I don't have the necessary rights to reopen this PR. I guess I'll create a new one.

**Pull request closed without merging**
