### PR TITLE
Alternative fix for #6909: Use @cached annotation

### PR DESCRIPTION
**Pull request by odersky**
Instead of memo, have a @cached annotation. Usage example:
```
@scala.annotation.meta.cached def foo = rhs
```
A `@cached def ` is like a `lazy val`, except that

 - it's not synchronized
 - it uses `null` as uninitialized value
 - it can have given parameters

Use the same logic for caching given aliases

### CODE REVIEW

**Comment by jducoeur** [comment]
Out of curiosity, would this be available to userland code?  I can definitely see it being useful, at least for folks who know what they're doing...

**Comment by odersky** [comment]
@jducoeur That's to be discussed. Im this PR @cached is available as an annotation in package `scala.annotation.meta`.

**Comment by smarter** [comment]
It seems that this is very close to `@threadUnsafe lazy val`, can we remove one of those in favor of the other ?

**Comment by propensive** [comment]
Maybe I'm not understanding the discriminating factors, but I think this feature deserves a first-class keyword rather than an annotation.

**Comment by odersky** [comment]
In light of the progress made with the lazy vals design in #6979, it seems safer and more systematic to just use a lazy val for caching given instances. 

That leaves the question whether @cached in its present form should be made available as a macro. I am not sure about that anymore. It does not seem to belong in the language spec. The compiler will have some usage for @cached but it's not clear it's enough to warrant the expense of having to implement it.

**Pull request closed without merging**
