### PR TITLE
Do not fail on warnings in sbt-dotty scripted tests

### PR DESCRIPTION
**Pull request by nicolasstucki**
To avoid errors seen in http://dotty-ci.epfl.ch/lampepfl/dotty/1700/7

### CODE REVIEW

**Comment by nicolasstucki** [comment]
This could potentially be the source of the unexpected cancellation of http://dotty-ci.epfl.ch/lampepfl/dotty/1700/8

**Comment by nicolasstucki** [comment]
The strange thing is that with fatal warnings we have errors reporter in the console but they are not failures. I would prefer to keep them as warnings to make sure those tests are run to the end an not interrupted. 
There is also the question why those errors do not make the tests fail. Could actual failures also be swallowed by these tests?

**Comment by allanrenucci** [comment]
>The strange thing is that with fatal warnings we have errors reporter in the console but they are not failures.

What errors are you talking about?

**Comment by allanrenucci** [comment]
[Here](http://dotty-ci.epfl.ch/lampepfl/dotty/1707) the build for the latest push on master passed.

**Pull request closed without merging**
