### PR TITLE
Fix lift try and captured vars interaction

### PR DESCRIPTION
**Pull request by odersky**
Replaces #753. Review by @DarkDimius.

### CODE REVIEW

**Comment by odersky** [comment]
Note: This PR uncovered (and fixes) a deeper problem about miniphase assembly which caused a
CapturedVars treetransform to come with an idx of 0, so the system would think tarnsformFollowing needs to run LazyVals on it, so we got NotDefinedHere errors.

**Comment by odersky** [comment]
@darkdimius Can you take a look at what fails here? The PR tests OK locally, but it seems we run out of memory on jenkins.

**Comment by odersky** [comment]
It was a spurious failure, after all.

**Comment by DarkDimius** [comment]
Otherwise LGTM

**Comment by odersky** [comment]
@darkdimius Last two commits ready for review.

**Comment by DarkDimius** [comment]
LGTM

**Pull request merged**
