### PR TITLE
Move Quotes and IArray to src-bootstrapped

### PR DESCRIPTION
**Pull request by nicolasstucki**
This extracts a change done in #10950. Merging this one first will make it easier to track the actual changes in Quotes in done in #10950.

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM

**Comment by nicolasstucki** [comment]
@liufengyun I also added `IArray`. This one is more important to avoid losing the history of `IArray.scala`

**Comment by liufengyun** [comment]
> @liufengyun I also added `IArray`. This one is more important to avoid losing the history of `IArray.scala`

What's the motivation for the move? It seems to just duplicate the file.

**Comment by nicolasstucki** [comment]
Yes, it just moves the file and creates a duplicate. This ensures the `library/src/scala/IArray.scala` is moved with it's history to ` library/src-bootstrapped/scala/IArray.scala`. If we do the move when we do the changes to that file, git moves the file to `src-non-bootstrapped` and assumes that the one in `src-bootstrapped` is a new file (hence loss of history). Here I removed the comments from the `src-non-bootstrapped` version to make sure that git understands this is the new file.

**Review by liufengyun — APPROVED** [review]
LGTM

**Pull request merged**
