### PR TITLE
Fix #5699: retry branches if simpleAndType failed

### LINKED ISSUE #5699: Spurious type error with value of weird intersection
The following:

```scala
type M = { type T[+A] } & { type T[-A] }
val M: M = ().asInstanceOf[M]
M: M
```

raises:

```
-- [E007] Type Mismatch Error: /tmp/scastie3590197869340764976/src/main/scala/main.scala:10:2 
10 |  M: M
   |  ^
   |found:    Test.M(Test.M')
   |required: Test.M
   |
   |where:    M  is a type in object Test which is an alias of Object{T <: ([+A] => Any)} & Object{T <: ([-A] => Any)}
   |          M' is a value in object Test
```

It also happens in the REPL without even ascribing `M`:

```
scala> M
1 |M
  |^
  |Found:    M(M')
  |Required: M
  |
  |where:    M  is a type which is an alias of Object{T <: ([+A] => Any)} & Object{T <: ([-A] => Any)}
  |          M' is a value
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #5699: retry branches if simpleAndType failed

The test case in #5699 shows that `simplifyAndTypeWithFallback(A, B)`
may return a type which is not a subtype of `A & B`. Thus, if the
comparison fails, we should retry `A <: X` or `B <: X`.

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
Thanks @odersky , I agree it's better to reject the ill-formed program.

BTW, by slow-down, do you mean the change of `isNewSubType` with `recur`? That change seems to be justified by the test case `tests/pos/gadt-no-approx.scala`, which does not check previously.

**Comment by odersky** [comment]
Yes, `isNewSubtype` is there for the only reason to avoid an unnecessary second test. We should not remove it.

**Comment by liufengyun** [comment]
Will propose a new fix to reject the ill-formed code.

**Pull request closed without merging**
