### PR TITLE
Avoid shadowing of name 'name'

### LINKED ISSUE #13440: `StringFormatter.showArg` throws `NullPointerException`
## Compiler version

`3.1.0-RC1` and `3.1.0-RC1-bin-20210831-adefa48-NIGHTLY`

## Minimized code

```scala
scalacOptions ++= Seq("-source", "3.0-migration")

scalaVersion := "3.1.0-RC1"
```

```Scala
case class A(enum: List[Int] = Nil)
```

## Output (click arrow to expand)
<details>

```
[error] ## Exception when compiling 1 sources to /Users/kenji/enum-null/target/scala-3.1.0-RC1/classes
[error] java.lang.NullPointerException
[error] dotty.tools.dotc.printing.Formatting$StringFormatter.showArg(Formatting.scala:39)
[error] dotty.tools.dotc.printing.Formatting$StringFormatter.treatArg(Formatting.scala:49)
[error] dotty.tools.dotc.printing.Formatting$StringFormatter.$anonfun$2(Formatting.scala:62)
[error] scala.collection.LazyZip2$$anon$1$$anon$2.next(LazyZipOps.scala:42)
[error] scala.collection.mutable.Growable.addAll(Growable.scala:62)
[error] scala.collection.mutable.Growable.addAll$(Growable.scala:57)
[error] scala.collection.mutable.ArrayBuilder.addAll(ArrayBuilder.scala:66)
[error] scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1282)
[error] scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1276)
[error] scala.collection.AbstractIterable.toArray(Iterable.scala:919)
[error] scala.Array$.from(Array.scala:73)
[error] scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:274)
[error] scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:265)
[error] scala.collection.ClassTagIterableFactory$AnyIterableDelegate.from(Factory.scala:671)
[error] scala.collection.BuildFromLowPriority2$$anon$11.fromSpecific(BuildFrom.scala:112)
[error] scala.collection.BuildFromLowPriority2$$anon$11.fromSpecific(BuildFrom.scala:109)
[error] scala.collection.LazyZip2.map(LazyZipOps.scala:37)
[error] dotty.tools.dotc.printing.Formatting$StringFormatter.assemble(Formatting.scala:62)
[error] dotty.tools.dotc.core.Decorators$.i(Decorators.scala:276)
[error] dotty.tools.dotc.parsing.Scanners$Scanner.treatAsIdent$$anonfun$1(Scanners.scala:251)
[error] dotty.tools.dotc.reporting.NoExplanation.msg(Message.scala:132)
[error] dotty.tools.dotc.reporting.Message.message(Message.scala:87)
[error] dotty.tools.dotc.reporting.Message.isNonSensical(Message.scala:99)
[error] dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden(HideNonSensicalMessages.scala:16)
[error] dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden$(HideNonSensicalMessages.scala:10)
[error] dotty.tools.dotc.reporting.AbstractReporter.isHidden(AbstractReporter.scala:8)
[error] dotty.tools.dotc.reporting.Reporter.go$3$$anonfun$2(Reporter.scala:161)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.Option.foreach(Option.scala:437)
[error] dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:174)
[error] dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:184)
[error] dotty.tools.dotc.Run.reportSuspendedMessages$$anonfun$3$$anonfun$1(Run.scala:140)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:127)
[error] dotty.tools.dotc.Run.dotty$tools$dotc$Run$suppressions$$$_$reportSuspendedMessages$$anonfun$1(Run.scala:140)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.Option.foreach(Option.scala:437)
[error] dotty.tools.dotc.Run$suppressions$.reportSuspendedMessages(Run.scala:140)
[error] dotty.tools.dotc.typer.TyperPhase.liftedTree1$1(TyperPhase.scala:60)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:62)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:411)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:63)
[error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$1(TyperPhase.scala:105)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:105)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] dotty.tools.dotc.Run.compile(Run.scala:206)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
```
</details>

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #13440

### CODE REVIEW

**Comment by som-snytt** [comment]
Reopen for rebase.

**Comment by som-snytt** [comment]
As a refresher, HEAD says
```
-- [E040] Syntax Error: /tmp/i13440.scala:6:11 --------------------------------------------------------------------------------------------------
6 |  val s = s"$enum" // error
  |           ^
  |           '}' expected, but string literal found
-- Error: /tmp/i13440.scala:6:17 ----------------------------------------------------------------------------------------------------------------
6 |  val s = s"$enum" // error
  |                 ^
  |                 unclosed string literal
exception occurred while parser /tmp/i13440.scala
exception occurred while compiling /tmp/i13440.scala
java.lang.NullPointerException: Cannot invoke "dotty.tools.dotc.core.Names$SimpleName.length()" because the return value of "dotty.tools.dotc.parsing.Scanners$Scanner.name()" is null while compiling /tmp/i13440.scala
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "dotty.tools.dotc.core.Names$SimpleName.length()" because the return value of "dotty.tools.dotc.parsing.Scanners$Scanner.name()" is null
        at dotty.tools.dotc.parsing.Scanners$Scanner.treatAsIdent(Scanners.scala:255)
        at dotty.tools.dotc.parsing.Scanners$Scanner.handleMigration(Scanners.scala:246)
        at dotty.tools.dotc.parsing.Scanners$Scanner.toToken(Scanners.scala:260)
        at dotty.tools.dotc.parsing.Scanners$ScannerCommon.finishNamed(Scanners.scala:146)
        at dotty.tools.dotc.parsing.Scanners$Scanner.getStringPart(Scanners.scala:1171)
        at dotty.tools.dotc.parsing.Scanners$Scanner.stringPart$1(Scanners.scala:786)
        at dotty.tools.dotc.parsing.Scanners$Scanner.fetchDoubleQuote$1(Scanners.scala:807)
        at dotty.tools.dotc.parsing.Scanners$Scanner.fetchToken(Scanners.scala:826)
        at dotty.tools.dotc.parsing.Scanners$Scanner.nextToken(Scanners.scala:343)
        at dotty.tools.dotc.parsing.Parsers$Parser.interpolatedString(Parsers.scala:1192)
```

**Comment by odersky** [comment]
Hi Tim, could you take a look at this? Thanks?

**Review by griggt — APPROVED** [review]

**Comment by som-snytt** [comment]
@griggt Thanks, Tom?

**Pull request merged**
