### PR TITLE
Invalidate member caches after completing classes in Namer

### LINKED ISSUE #10634: Order of the source files changes the compilation result
While compiling `scala3doc` I found surprising that the order of the source files change the compilation result.

## Minimized code

I minimized it to 3 files.

```Scala
// Context.scala
trait Context:
  type Symbol

trait SymOps[C <: Context](val c: C):
  extension (sym: c.Symbol):
    def getVisibility(): Int = 0
```

```scala
// Parser.scala
case class Parser(ctx: Context) extends BasicSupport
```

```scala
// BasicSupport.scala
trait BasicSupport:
  self: Parser =>

  object SymOps extends SymOps[ctx.type](ctx)
  export SymOps._

  def parse(sym: ctx.Symbol): Int =
    sym.getVisibility()
```

## Output

`BasicSupport.scala Context.scala Parser.scala` compiles successfully.

But `Parser.scala Context.scala BasicSupport.scala` compiles in error:
```shell
[info] cannot take signature of (sym: Parser.this.SymOps.c.Symbol)(): Int
[error] -- [E008] Not Found Error: /home/piquerez/lampepfl/dotty-issue/src/main/scala/tasty/BasicSupport.scala:8:8 
[error] 8 |    sym.getVisibility()
[error]   |    ^^^^^^^^^^^^^^^^^
[error]   |    value getVisibility is not a member of BasicSupport.this.ctx.Symbol.
[error]   |    An extension method was tried, but could not be fully constructed:
[error]   |
[error]   |        sym
[error] one error found
```

## Expectation

The order of the source files should not change the compilation result.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #10634

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Review by adpi2 — APPROVED** [review]
Thanks @odersky, it indeed fixes the issue in #10634.

I let you judge the impact of `invalidateMemberCaches` in terms of performance.

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
We have a little problem with the bench server. I'm on it.

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
We still have a problem with the bench server (after the file system fix yesterday), I'm investigating.

**Pull request merged**
