### PR TITLE
Don't generate case class method if it clashes with inherited concret…

### LINKED ISSUE #10866: Case class creates an unapply method even if one is inherited in the companion object
## Minimized code

```Scala
abstract class B{
  def unapply(arg:A)={println ("Unapply from B"); true}
}

case class A()

object A extends B

A() match {case A() => println("done")}
```

## Output

```scala
done
```

## Expectation
In Scala 2.13.4, the same code would have used the unapply from B instead, and would have displayed 
```scala
Unapply from B
done
```

### PR DESCRIPTION
**Pull request by odersky**
…e member

Fixes #10866

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Review by bishabosha — APPROVED** [review]
performance hit doesn't look so bad

**Comment by odersky** [comment]
Test performance please

(just to be sure)

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by bishabosha** [comment]
the spike looks consistent but it is not so big looking at the trend over time

**Pull request merged**
