### PR TITLE
lint trivially self-recursive extension methods

### LINKED ISSUE #9880: Confusing interaction between opaque types and extension methods
## Minimized code

```Scala
opaque type Bytes = Array[Byte]
object Bytes:
  def fromArray(arr: Array[Byte]): Bytes = arr
  extension (self: Bytes):
    def toArray: Array[Byte] = self
    def length: Int = (self: Array[Byte]).length
    def size: Int = (self: Array[Byte]).size

val b = Bytes.fromArray(Array(1, 2, 3))

object Main extends App {
  println("Length: " + b.length)
  println("Size: " + b.size)
}
```

## Output

Length is printed and then an infinite loop is encountered on `b.size`

## Expectation

`Array[Byte]` doesn't have a `size` member so `(self: Array[Byte])` is lifted to `Bytes` instead of picking up `ArrayOps` implicit conversion. This seems like a pretty big gotcha but not sure how to improve.

### PR DESCRIPTION
**Pull request by SethTisue**
broadens Martin's fix for #13542, as suggested by Guillaume in a comment on that PR

fixes #9880

### CODE REVIEW

**Comment by SethTisue** [comment]
sorry to take an issue labeled "spree", but Dale and I actually worked through this explicitly as if we were spree-ing, with me using VS Code + Metals (instead of my usual Emacs or IntelliJ) as practice for doing the same thing with a newcomer at the next spree

**Comment by SethTisue** [comment]
@griggt heh. did you already handle the `||` and `&&` thing?

**Comment by griggt** [comment]
We were focused on the lazy vals stuff, and I hadn't tried running a bootstrapped test since broadening to cover 9880, so had not seen the `&&` and `||` thing pop up.  

It would have come up tonight when opening a PR though, so thanks for catching it first!  :-)

**Comment by SethTisue** [comment]
@griggt happy to let your more ambitious effort go forward instead of this one, but let us know if you get stuck or need reviewers/collaborators

Dale noticed when he looked at #13011 that `isInfiniteRecCall` in `TailRec` already exists; have you looked at that and considered where it could be DRYed with `CheckLoopingImplicits`?

**Comment by SethTisue** [comment]
@griggt any update? (Dale and I were thinking of finishing this more modest PR up anyway.)

**Comment by griggt** [comment]
Ah, sorry, I've been swamped lately.  But please continue your work and don't let me hold up progress, I likely wouldn't have time to look at this until the weekend at the earliest.

**Review by odersky — APPROVED** [review]
I think the danger of false positives is very low in this case, and the possibility of accidental recursion is higher. So LGTM.

**Pull request merged**
