### PR TITLE
Use 3.0.0-M1 nightly as a reference compiler

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by smarter** [comment]
> Error:  Bad symbolic reference. A signature
> Error:  refers to Enum/T in package scala.reflect which is not available.

https://github.com/lampepfl/dotty/blob/master/library/src-bootstrapped/scala/reflect/Enum.scala and https://github.com/lampepfl/dotty/blob/master/library/src-bootstrapped/scala/Enum.scala need to be moved to library/src, https://github.com/lampepfl/dotty/blob/master/library/src-non-bootstrapped/scala/Enum.scala needs to be deleted (the same might be true for the other files in src-bootstrapped and src-non-bootstrapped, I don't know if there's some reasons they'd need to stay as is /cc @nicolasstucki)

**Comment by smarter** [comment]
Also we should bring back https://github.com/lampepfl/dotty/pull/9949/commits/099074c6a7e191ac04c7189cc7b23dddcc431789 which was blocked on having a new reference compiler.

**Comment by nicolasstucki** [comment]
I don't see a reason why we should keep `Enum.scala` split with this update. Moving it to `library/src` is the right thin to do in this case.

**Comment by bishabosha** [comment]
I moved the files and rebased

**Comment by anatoliykmetyuk** [comment]
Thanks a lot @bishabosha!

**Comment by smarter** [comment]
@nicolasstucki My question was about the other files in src-non-bootstrapped and src-bootstrapped which are all macro-related stuff, should they be moved too?

**Comment by nicolasstucki** [comment]
No, the macro related stuff should stay

**Comment by bishabosha** [comment]
so can this be merged?

**Review by nicolasstucki — APPROVED** [review]

**Pull request merged**
