### PR TITLE
Fix #838. Fixes to non-local modules& static forwarders.

### LINKED ISSUE #838: pos/Iter2 fails to compile after bootstrap
after applying #836, #833 and #837

```scala

dark@reco ~/workspace/dotty/tests/pos (reb) $ dotc -bootstrapped Iter2.scala
Exception in thread "main" java.lang.NoSuchMethodError: dotty.tools.dotc.transform.PatternMatcher$Translator$TreeMakers$TypeTestTreeMaker$treeCondStrategy$: method <init>()V not found
	at dotty.tools.dotc.transform.PatternMatcher$Translator$TreeMakers$TypeTestTreeMaker$treeCondStrategy$.<clinit>(PatternMatcher.scala)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$TreeMakers$TypeTestTreeMaker$.treeCondStrategy(PatternMatcher.scala:632)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$TreeMakers$TypeTestTreeMaker.<init>(PatternMatcher.scala:799)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$TreeMakers$TypeTestTreeMaker$.apply(PatternMatcher.scala:713)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.typeTest$lzyINIT1$1(PatternMatcher.scala:1061)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.typeTest$1(PatternMatcher.scala:1061)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.extractorStep(PatternMatcher.scala:1072)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.nextStep(PatternMatcher.scala:1092)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.translate(PatternMatcher.scala:1101)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator.translatePattern(PatternMatcher.scala:1276)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translatePattern(PatternMatcher.scala:75)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator.translateCase(PatternMatcher.scala:1273)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translateCase(PatternMatcher.scala:75)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator.$anonfun$556(PatternMatcher.scala:1197)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$$Lambda$1067/2035381640.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator.translateMatch(PatternMatcher.scala:1197)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translateMatch(PatternMatcher.scala:75)
	at dotty.tools.dotc.transform.PatternMatcher.transformMatch(PatternMatcher.scala:51)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goMatch(TreeTransform.scala:724)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1114)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1004)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1238)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$637(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$945/532885071.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1011)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1238)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$637(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$945/532885071.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1011)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1238)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$637(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$945/532885071.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1240)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$637(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$945/532885071.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$11(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$944/1192672907.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:563)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:480)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$2(Phases.scala:271)
	at dotty.tools.dotc.core.Phases$Phase$$Lambda$816/2041605291.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:273)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.runOn(TreeTransform.scala:474)
	at dotty.tools.dotc.Run.$anonfun$$anonfun$3(Run.scala:59)
	at dotty.tools.dotc.Run$$Lambda$194/611437735.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:57)
	at dotty.tools.dotc.Run$$Lambda$185/1761291320.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:58)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:65)
	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	at dotty.tools.dotc.Run.compile(Run.scala:33)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by DarkDimius**
fixes #838

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky please review.

**Comment by odersky** [comment]
LGTM

**Pull request merged**
