### PR TITLE
Fix #2957 single quote highlighting and refactor

### LINKED ISSUE #2957: Dotty Repl highlighting does not work for Symbol literals
image

### PR DESCRIPTION
**Pull request by maxov**
Hi all, this is my first PR so please let me know if I'm doing anything wrong. 

This fixes #2957, here's a picture of how things are highlighted now:

screen shot 2017-08-18 at 9 16 31 am

And it does actually highlight as little as possible for characters:
screen shot 2017-08-18 at 9 37 16 am

I also did a tiny refactor because `Chars.isLineBreakChar` did the same thing as some logic in the syntax highlighter.

### CODE REVIEW

**Comment by felixmulder** [comment]
Hey @maxov - LGTM for the most part. Restarted the CI for your last commit.

Regarding your example with:

```scala
scala> 'a'toString
```

Are you writing: `'a'.toString` but the highlighter is eating up the dot?

**Comment by maxov** [comment]
@felixmulder No, that is valid Scala syntax.  It is postfix operator notation that works in previous versions of scala.

**Comment by felixmulder** [comment]
Unary postfix is valid, yes, we know this :)

If there are inconsistencies in the highlighting, then the most common symptom is: things get eaten up. Since we don't have tests for this - I needed to ask you.

**Comment by maxov** [comment]
I see, thanks for clarifying!

**Pull request merged**
