### PR TITLE
[backport] Fix separate compilation issues with opaque types

### PR DESCRIPTION
**Pull request by odersky**
This backports https://github.com/lampepfl/dotty/pull/13206

### CODE REVIEW

**Comment by odersky** [comment]
Not sure how to proceed here. Can someone else take over? If not this will have to wait for next release.

**Comment by odersky** [comment]
Linked to #13196 maybe? Do we have to backport that first?

**Comment by bishabosha** [comment]
> Linked to #13196 maybe? Do we have to backport that first?

I think both #13201 #13200 need to be backported

**Comment by odersky** [comment]
Maybe somebody else can take this over (assuming we really want to backport)?

**Comment by smarter** [comment]
@BarkingBad it looks like the  stdlib-sourcelinks-test test is broken in the release-3.0.2 branch, could you investigate?

**Comment by BarkingBad** [comment]
Hopefully, #13274 will fix the problem.

**Pull request merged**
