### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by odersky**
Lots of new tests and some fixes. Review by @smarter

### CODE REVIEW

**Comment by odersky** [comment]
This one is based on #1001, which should go in first.

**Comment by smarter** [comment]
Something weird is going on with constraints, in:
```scala
class A {
  def f[CC[X] <: Traversable[X]](x: CC[Int]): CC[Int] = x

  f(1 to 5)
}
```
we get:
```scala
[info] added constraint CC <: [+X0] -> scala.collection.immutable.IndexedSeq[X0] to
[info] Constraint(
[info]  uninstVars = CC;
[info]  constrained types = 
[info]   [CC <: [X0] ->  <: scala.collection.Traversable[X0]](x: CC[Int])CC[Int]
[info]  bounds = 
[info]      CC = [+X0] -> scala.collection.immutable.IndexedSeq[X0]
[info]  ordering = 
[info] ) = true
[error] [log frontend]           ==> adapting intWrapper(1).to of type ((end: Int)scala.collection.immutable.Range.Inclusive)(scala.runtime.RichInt#to) to FunProto(5):??
[error] [log frontend]           <== adapting intWrapper(1).to of type ((end: Int)scala.collection.immutable.Range.Inclusive)(scala.runtime.RichInt#to) to FunProto(5):? = intWrapper(1).to
[error] [log frontend]         <== adapting intWrapper(1).to of type <overloaded scala.runtime.RichInt#to> to FunProto(5):? = intWrapper(1).to
[error] [log frontend]       <== typing 1.to = intWrapper(1).to
[error] [log frontend]       ==> adapting 5 of type Int(5) to Int?
[error] [log frontend]       <== adapting 5 of type Int(5) to Int = 5
[error] [log frontend]       ==> adapting intWrapper(1).to(5) of type scala.collection.immutable.Range.Inclusive to CC[Int]?
[error] [log frontend]       <== adapting intWrapper(1).to(5) of type scala.collection.immutable.Range.Inclusive to CC[Int] = intWrapper(1).to(5)
[error] [log frontend]       ==> adapting this.f[CC](intWrapper(1).to(5)) of type CC[Int] to ??
[info] interpolate undet vars in CC[Int], pos = [71..72..80], mode = Mode(ImplicitsEnabled), undets = ArrayBuffer(CC@[71..72])
[info] qualifying undet vars: ArrayBuffer(TypeVar(PolyParam(CC)) / CC), constraint: Constraint(
[info]  uninstVars = CC;
[info]  constrained types = 
[info]   [CC <: [X0] ->  <: scala.collection.Traversable[X0]](x: CC[Int])CC[Int]
[info]  bounds = 
[info]      CC <: [X0] ->  <: scala.collection.Traversable[X0]
[info]  ordering = 
[info] )
[info] interpolate covariant CC in CC[Int]
[info] approx CC, from below = true, bound = Nothing, inst = Nothing
[info] instantiating CC with Nothing
```
Notice that we correctly have `CC = [+X0] -> scala.collection.immutable.IndexedSeq[X0]` in the constraint set, but then somehow we go back to `CC <: [X0] ->  <: scala.collection.Traversable[X0]` and we infer `CC` to `Nothing`.

**Comment by odersky** [comment]
@smarter 
> Something weird is going on with constraints, in: ...

Where did that test come from. The example compiles OK for me (?)

@smarter @DarkDimius I cannot make sense of the test failures of this commit. It says something about compilation of pos/printing_v1fails, but I have no idea what that is.

**Comment by smarter** [comment]
> Where did that test come from? The example compiles OK for me (?)

I took `hkrange.scala` and changed it slightly. It does compile OK, the issue is that it infers `Nothing` instead of inferring `[X] => IndexedSeq[X]` for the call `f(1 to 5)`.

> @smarter @DarkDimius I cannot make sense of the test failures of this commit. It says something about compilation of pos/printing_v1fails, but I have no idea what that is. Can you help?

Not sure what the problem is either, I suspect it might be another kind of random bugs that disappear when we rebuild.

**Comment by smarter** [comment]
LGTM since the issues I encountered are not specific to this PR, I'll investigate them separately

**Pull request merged**
