### PR TITLE
Fix #9482: implement reflect.Manifest summoning

### LINKED ISSUE #9482: OptManifest not resolved
I'm currently adding Dotty support to [ScalaSTM](https://github.com/scala-stm/scala-stm). Everything went smooth except that `OptManifest` implicit compiler resolution seems broken (works through Scala 2.11–13).

## Minimized code

We use the following API

```scala
object Ref {
  def make[A: OptManifest]: Ref[A] = ???
}
trait Ref[A]
```

which is needed to distinguish between primitive types and reference types, and create arrays.

This works in the cases where the type is concrete, such as `Ref.make[String]` or `Ref.make[Int]`, but also when it is abstract such as

```scala
trait Foo[A] {
  val bar = Ref.make[Int]
  val baz: Ref[A] = Ref.make
}
```

## Output

This no longer works in Dotty 

```
[error] -- Error: /data/temp/dotty-optmanifest/src/main/scala/Foo.scala:2:25 -----------
[error] 2 |  val bar = Ref.make[Int]
[error]   |                         ^
[error]   |no implicit argument of type OptManifest[Int] was found for an implicit parameter of method make in object Ref
[error] -- Error: /data/temp/dotty-optmanifest/src/main/scala/Foo.scala:3:28 -----------
[error] 3 |  val baz: Ref[A] = Ref.make
[error]   |                            ^
[error]   |no implicit argument of type OptManifest[A] was found for an implicit parameter of method make in object Ref
[error] two errors found
```

## Expectation

It should work, like it did in Scala 2.13, i.e. resolve to either `ClassManifest` or `NoManifest`. E.g.:

https://travis-ci.org/github/scala-stm/scala-stm/jobs/714280130

### PR DESCRIPTION
**Pull request by bishabosha**
This PR implements summoning for `reflect.Manifest`, `reflect.OptManifest` and `reflect.ClassManifest` following the algorithm present in Scala 2:
https://github.com/scala/scala/blob/0c011547b1ccf961ca427c3d3459955e618e93d5/src/compiler/scala/tools/nsc/typechecker/Implicits.scala#L1519

A special case is added in Definitions for `reflect.ClassManifest` so that is not de-aliased at the time of Implicit search, added in c84f057, so careful review is required here.

fixes #9482

### CODE REVIEW

**Comment by bishabosha** [comment]
So far there is no restriction on summoning - I can think of several options:
- enable it only in `source:3.0-migration` I think this could be a problem as Manifests themselves are not deprecated
- forbid it in `source:future` - by this time the library may have deprecated/dropped them
- enable it under one of the `legacy` language features?

**Comment by smarter** [comment]
I won't be available to review this in the near future but my first reaction here is that this is way too much code and complexity for a legacy and known-broken feature, I also don't understand why some of the logic and error messages reference `TypeTag` since this isn't something we support at all. IMO, it's fine to add support for the simplest usecases where Manifest is used instead of ClassTag, but we shouldn't aim to perfectly emulate what Scala 2 does (because we'll never match it exactly anyway).

**Comment by bishabosha** [comment]
The special casing for `ClassManifest` is causing too much trouble - I will try to simplify seeing as there is no point to trying to match the behaviour for `<:<` as that is deprecated.

I will also remove the special casing for `TypeTag` also

**Comment by smarter** [comment]
> So far there is no restriction on summoning - I can think of several options:

I suggest emitting a deprecation warning encouraging the use of ClassTag and http://dotty.epfl.ch/docs/reference/metaprogramming/toc.html whenever we materialize a Manifest.

**Comment by bishabosha** [comment]
see #13142

**Pull request closed without merging**
