### PR TITLE
Optimize megaphase

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Review by liufengyun — APPROVED** [review]
LGTM, let's see which recursive number is better.

BTW, we can run benchmarking for multiple commits like `test performance please: dd9dbf4 0315e27`, which results in one point for each commit.

**Comment by odersky** [comment]
It seems the lower number is dramatically better! So, deep stacks seem to be a performance bottleneck. I am going to test without the optimization altogether, to get another comparison.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
So recursiing 1000 levels before going into the fall-back is clearly worse than doing nothing, but recursing 10 levels is clearly better.

**Pull request merged**
