### PR TITLE
[CI only] Add sourcepos 4

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@liufengyun Still no performance data. Can you check again, please?

**Comment by liufengyun** [comment]
@odersky The logs show the compilation failed. Another file system error makes the CI unable to report the failure. 

http://128.178.154.49:8000/pull-5678-01-08-13.02.out

**Comment by liufengyun** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Pull request closed without merging**
