### PR TITLE
Script startup latency improvement

### PR DESCRIPTION
**Pull request by philwalk**
When launching a scala3 script, there are two calls to [dist/bin/common](dist/bin/common), the first from within [dist/bin/scala](dist/bin/scala) and the 2nd when `dist/bin/scala` calls `dist/bin/scalac`. 

It turns out that the avoidable 2nd call is quite expensive in terms of what it adds to script startup latency.   Here are the reductions in startup time when running in `cygwin` and in `WSL Linux`:

```sh
cygwin:    837 mSec
WSL Linux:  66 mSec
```

The numbers are the difference in startup latency for calling a `hello-world.sc` script with and without the changes in this PR, averaged over 100 runs.

The categories of change in the PR are:

- exporting values initialized by `dist/bin/common` and required by scalac
- modification of `dist/bin/scalac` to conditionally source `dist/bin/common`
- changes to avoid spurious unset variable errors when testing with: `set -o nounset` 
- fail early if a script file doesn't exist

The third change is exemplified by line 114 in `dist/bin/common`:
```diff
-if [ -n "$CYGPATHCMD" ]; then
+if [ -n "${CYGPATHCMD-}" ]; then
```

### CODE REVIEW

**Comment by philwalk** [comment]
Unintentionally included the changes from #11633, I'll have to re-create this PR later.

**Comment by philwalk** [comment]
not yet ready

**Comment by griggt** [comment]
Just an FYI, I've noticed that the act of re-opening a PR launches a fresh CI run.  There are 3 jobs now running in CI for this PR:

https://github.com/lampepfl/dotty/actions/runs/633879155
https://github.com/lampepfl/dotty/actions/runs/633879159
https://github.com/lampepfl/dotty/actions/runs/633891730

**Comment by philwalk** [comment]
This PR needs to be re-created from scratch, to avoid possible problems with #11633

**Comment by philwalk** [comment]
This PR is superceded by #11698

**Pull request closed without merging**
