### PR TITLE
Type match with a match type when a match type is expected

### PR DESCRIPTION
**Pull request by mbovel**

### CODE REVIEW

**Comment by mbovel** [comment]
Alternative implementation: could also add a case here instead of modifying `MatchTypeInDisguise`:

```diff
diff --git a/compiler/src/dotty/tools/dotc/typer/Typer.scala b/compiler/src/dotty/tools/dotc/typer/Typer.scala
index e4aa1e634e..bd99da7b0e 100644
--- a/compiler/src/dotty/tools/dotc/typer/Typer.scala
+++ b/compiler/src/dotty/tools/dotc/typer/Typer.scala
@@ -1601,6 +1601,8 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
         val result = pt match {
           case MatchTypeInDisguise(mt) if isMatchTypeShaped(mt) =>
             typedDependentMatchFinish(tree, sel1, selType, tree.cases, mt)
+          case mt: MatchType if isMatchTypeShaped(mt) =>
+            typedDependentMatchFinish(tree, sel1, selType, tree.cases, mt)
           case _ =>
             typedMatchFinish(tree, sel1, selType, tree.cases, pt)
         }
```

**Review by OlivierBlanvillain — APPROVED** [review]
LGTM!

**Comment by bishabosha** [comment]
> Alternative implementation: could also add a case here instead of modifying `MatchTypeInDisguise`:

I think I would prefer that one because now all all types will be tested by `MatchTypeInDisguise`, which I guess can alter the pattern match plan of all the existing call-sites, but only a benchmark can know the impact.

**Comment by mbovel** [comment]
> > Alternative implementation: could also add a case here instead of modifying `MatchTypeInDisguise`:
>
> I think I would prefer that one because now all all types will be tested by `MatchTypeInDisguise`, which I guess can alter the pattern match plan of all the existing call-sites, but only a benchmark can know the impact.

Ok, I changed from adding a `case mt: MatchType => Some(mt)` inside `MatchType.InDisguise` to adding a  `case mt: MatchType if isMatchTypeShaped(mt)` in `Typer.typedMatch`.

**Review by bishabosha — APPROVED** [review]

**Pull request merged**
