### PR TITLE
Fix #10466: Update `rootPosition` to `Position.ofMacroExpansion`

### LINKED ISSUE #10466: Nightly build failed (in macro-expansion-dependencies-2 sbt scripted test)
The nightly build failed on the `macro-expansion-dependencies-2` scripted test in `test_sbt`:

```diff
-Error: [error] -- [E006] Not Found Error: /tmp/sbt_41e7727c/macro-expansion-dependencies-2/MacroRuntime.scala:7:6 
-Error: [error] 7 |      error("some error", rootPosition)
-Error: [error]   |      ^^^^^
-Error: [error]   |      Not found: error
-Error: [error] -- [E006] Not Found Error: /tmp/sbt_41e7727c/macro-expansion-dependencies-2/MacroRuntime.scala:7:26 
-Error: [error] 7 |      error("some error", rootPosition)
-Error: [error]   |                          ^^^^^^^^^^^^
-Error: [error]   |                          Not found: rootPosition
-Error: [error] two errors found
-Error: [error] (Compile / compileIncremental) Compilation failed
-Error: [error] Total time: 1 s, completed Nov 24, 2020 4:29:10 AM
 [info] [success] Total time: 0 s, completed Nov 24, 2020 4:29:11 AM
 [info] [info] Compiling 3 Scala sources to /tmp/sbt_41e7727c/macro-expansion-dependencies-2/target/scala-3.0.0-M2/classes ...
 [info] [info] Done compiling.
 [info] [success] Total time: 1 s, completed Nov 24, 2020 4:29:11 AM
 [info] [info] Compiling 1 Scala source to /tmp/sbt_41e7727c/macro-expansion-dependencies-2/target/scala-3.0.0-M2/classes ...
 [info] [info] Done compiling.
 [info] [info] running Main 
 [info] Implementation in Macro
 [info] [success] Total time: 0 s, completed Nov 24, 2020 4:29:12 AM
-Error:  x source-dependencies / macro-expansion-dependencies-2 
-Error:   Cause of test exception: {line 13}  Command succeeded but failure was expected
```

It looks like `macro-expansion-dependencies-1` could use an update as well:

https://github.com/lampepfl/dotty/blob/64c8e77aa9bb0e9e928ecd0609b85eb3b47f8c69/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-1/changes/MacroCompileError.scala#L9

__Note:__ the actual cause of the job failure is that the runtime test of `MacroRuntimeRuntimeError.scala` on line 13 succeeded when it was expected to fail. The "not found" errors don't cause the job to fail because they are inside tests that are expected to fail at compile time.

EDIT: It seems the failure is for some reason caused by the recent change making the context parameter anonymous:

https://github.com/lampepfl/dotty/blob/64c8e77aa9bb0e9e928ecd0609b85eb3b47f8c69/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-2/changes/MacroRuntimeRuntimeError.scala#L5

### PR DESCRIPTION
**Pull request by nicolasstucki**
[test_sbt]

### CODE REVIEW

**Comment by nicolasstucki** [comment]
We need to fix this one to be able to publish 3.0.0-M2

**Review by liufengyun — APPROVED** [review]
LGTM

**Comment by griggt** [comment]
In order to get the test to pass locally, I had to give a name to the context parameter:

```diff
diff --git a/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-2/changes/MacroRuntimeRuntimeError.scala b/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-2/changes/MacroRuntimeRuntimeError.scala
index caa79c3d24..e917a255af 100644
--- a/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-2/changes/MacroRuntimeRuntimeError.scala
+++ b/sbt-dotty/sbt-test/source-dependencies/macro-expansion-dependencies-2/changes/MacroRuntimeRuntimeError.scala
@@ -2,7 +2,7 @@ import scala.quoted._

 object MacroRuntime {

-   def impl()(using Quotes): Expr[Unit] = {
+   def impl()(using q: Quotes): Expr[Unit] = {
       '{ ??? }
    }

```

I have no idea why that makes a difference here.

**Comment by nicolasstucki** [comment]
That changes the signature in one of the steps, which may trigger the incremental compilation recompile more.

**Comment by griggt** [comment]
Ah, that must be it.  Adding a `> clean` before the final `-> run` in the test script seems to work also.

**Comment by nicolasstucki** [comment]
This means that there was a regression in the incremental compilation of macros. I added the `clean` to unblock the release. I'm bisecting the commit to find the source of the problem and will open an issue when I find it.

@liufengyun could you have a last look at the changes I added?

**Comment by liufengyun** [comment]
> This means that there was a regression in the incremental compilation of macros. I added the `clean` to unblock the release. I'm bisecting the commit to find the source of the problem and will open an issue when I find it.
> 
> @liufengyun could you have a last look at the changes I added?

It looks good to me.

**Comment by nicolasstucki** [comment]
It looks like c5480489140789be5bc52beecb9d22e4a373ebf4 is the first commit to fail

**Pull request merged**
