### PR TITLE
Change 'private, protected, or this expected' to Message

### PR DESCRIPTION
**Pull request by ennru**
@felixmulder 
Another error message with explanation. It captures the class name Symbol, but does not use it for now. 
I tried to get the error position indicator to move to the position where the keyword is missing, but did not manage to do so. Ideas?

### CODE REVIEW

**Comment by felixmulder** [comment]
Does `pos.focus` help with that?

**Comment by ennru** [comment]
No. My problem is that the parser has passed the constructor parameters:
`-- [E043] Syntax Error: tests/pos/HelloWorld.scala -----------------------------`
`5 |class Annotated @deprecated (s: List[String])`
`..|.........,.........,.........,.........,....^`
`..|    private, protected, or this expected for annotated primary constructor`

I did not find a good spot to keep `in.offset`. If captured before parsing the annotations it ends up like this:
`-- [E043] Syntax Error: tests/pos/HelloWorld.scala -----------------------------`
`5 |class Annotated @deprecated (s: List[String])`
`..|.........,......^^^^^^^^^^`
`..|....private, protected, or this expected for annotated primary constructor`

**Comment by felixmulder** [comment]
So a couple of alternatives without digging too deep:

1. Take `in.lastOffset` from `Parsers.scala:2058`
2. Take positions from some other part of the constructor in `Parsers.scala:2058-2068`
3. Take positions from `Modifiers` they are positioned, so you could look at that and then add the size of the name - might be a bit dirty...

**Comment by ennru** [comment]
I think it is best to settle on the last annotation's position, which includes the parameter list:
`4 |class Annotaded @inline @deprecated (s: String, i: Int)`
`..|........................^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by felixmulder** [comment]
LGTM, thanks @ennru!

**Pull request merged**
