### PR TITLE
Fix typo in extension method example

### PR DESCRIPTION
**Pull request by eloots**
- Remove an extraneous ‘.’ in example code

### CODE REVIEW

**Comment by eloots** [comment]
Apparently, I hadn't signed the Scala CLA (as I wrongly assumed it was covered by another CLA I signed before).
Fixed now.

**Comment by biboudis** [comment]
@dotty-bot recheck cla

**Comment by biboudis** [comment]
Just noticed that the same exists in 

https://dotty.epfl.ch/docs/reference/contextual/extension-methods-new.html

According to this:

https://github.com/lampepfl/dotty/pull/7914
which was superseded by 
https://github.com/lampepfl/dotty/pull/7917

the dot syntax is valid. It is also documented in 

```scala
DefSig            ::=  id [DefTypeParamClause] DefParamClauses
                    |  ExtParamClause [nl] [‘.’] id DefParamClauses
```

https://dotty.epfl.ch/docs/internals/syntax.html

**Comment by eloots** [comment]
@biboudis Indeed.

`docs/docs/reference/contextual/extension-methods-new.md` contains the same typo in the first example, so I've added the correction to this file to this PR.

I presume the plan is to swap `docs/docs/reference/contextual/extension-methods.md` for `docs/docs/reference/contextual/extension-methods-new.md` when 0.22.0-RC1 is released.

**Comment by biboudis** [comment]
I meant that the dot-syntax is valid so we shouldn't remove it

**Comment by Blaisorblade** [comment]
@biboudis No, one of those dots is a syntax error, because https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html is meant to be about 0.21.0-RC1.

```
$ dotr -version
Starting dotty REPL...
Dotty compiler version 0.21.0-RC1 -- Copyright 2002-2019, LAMP/EPFL
scala> case class Circle(x: Double, y: Double, radius: Double)
// defined case class Circle

scala> def (c: Circle).circumference: Double = c.radius * math.Pi * 2
1 |def (c: Circle).circumference: Double = c.radius * math.Pi * 2
  |               ^
  |               an identifier expected, but '.' found
1 |def (c: Circle).circumference: Double = c.radius * math.Pi * 2
  |                                                              ^
  |                                               '=' expected, but eof found

scala> def (c: Circle) circumference: Double = c.radius * math.Pi * 2
def circumference(c: Circle): Double

scala>
```

**Comment by Blaisorblade** [comment]
@eloots I took the liberty of editing the PR to show what it should be, IIUC.

**Comment by Blaisorblade** [comment]
FWIW, the current docs workflow seems very challenging to deal with: Docs in master must document both the latest release and the current master. In many other projects, each version contains its own docs, and the website has a different folder for each release.

**Comment by eloots** [comment]
@Blaisorblade 
> FWIW, the current docs workflow seems very challenging to deal with: Docs in master must document both the latest release and the current master. In many other projects, each version contains its own docs, and the website has a different folder for each release.

Couldn't agree more. It's quite confusing. I now look at the ref docs on the latest RC1 **and** the latest version on master (by pulling the most recent state on master & running `genDocs`)

**Pull request merged**
