### PR TITLE
Implement new main annotation

### PR DESCRIPTION
**Pull request by nicolasstucki**
Followup to #14558 adding the missing new main annotation form #13727.

This is a finished version of the new main annotation design of #13727. This is not necessarily intended to be the final version. We want to add it as experimental to allow users to try it out and promote further design discussions in #14977.

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Hmm, so this annotation does exactly what `@main` does with the purpose to test out the new implementation and possibly replace `@main` in the future? I believe having two annotations doing the same thing will generate confusion. We should instead replace `@main` with this annotaiton right away and fix any regressions as they are reported IMO.

**Comment by julienrf** [comment]
IMHO, the problem is not the risk of introducing regression, but the risk of introducing new features that will have to be maintained.

I think adding new features to the current `@main` annotation should be motivated by explaining why and how the current behavior is problematic.

**Comment by bishabosha** [comment]
> We should instead replace `@main` with this annotaiton right away and fix any regressions as they are reported IMO.

this would mean making `@main` experimental because it extends the experimental `MainAnnotation`

**Comment by nicolasstucki** [comment]
rebased

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
