### PR TITLE
Rename Not to NotGiven

### PR DESCRIPTION
**Pull request by amsayk**
I think this is a much cooler name for this concept. 

This is my first PR and Trial to open up a discussion whether this makes sense or not.

### CODE REVIEW

**Comment by som-snytt** [comment]
That is cooler. I might have said, `Ungiven` for its resonance with `Unforgiven`.

**Comment by odersky** [comment]
I also think that NotGiven is a promising choice. Before we can merge this I believe it should be discussed on contributors. Can you open a thread there?

**Comment by amsayk** [comment]
Will do.

**Comment by amsayk** [comment]
@odersky I need some help fixing tests. `tests/run/i3396.scala` won't compile for some reason. 

I am getting the following error:

```
-- Error: tests/run/i3396.scala:19:31 ------------------------------------------
19 |    assert(implicitly[Foo[Int]].value) // fooDefault
   |                               ^
   |ambiguous implicit arguments of type Test.Foo[Int] found for parameter e of method implicitly in object Predef.
   |I found:
   |
   |    Test.Foo.fooNotTagged[A](
   |      /* ambiguous: both method amb1 in object NotGiven and method amb2 in object NotGiven match type util.NotGiven[Test.Tagged[Int]] */
   |        summon[util.NotGiven[Test.Tagged[A]]]
   |    )
   |
   |But both method amb1 in object NotGiven and method amb2 in object NotGiven match type util.NotGiven[Test.Tagged[A]].
1 error found
```

**Comment by bishabosha** [comment]
@amsayk you will also need to change in the compiler references to `scala.util.Not`, such as here https://github.com/lampepfl/dotty/blob/928e01ad0a49d556e75b71144df8ff4bfca6cf5e/compiler/src/dotty/tools/dotc/core/Definitions.scala#L854

**Comment by amsayk** [comment]
Thanks @bishabosha

**Comment by amsayk** [comment]
I think this is ready to go. Can someone take a look ?  @bishabosha  👀

**Comment by bishabosha** [comment]
Im not sure why but it seems the CI is not running your tests, can you make a trivial change to the last commit to change its hash and repush?

**Comment by amsayk** [comment]
@bishabosha  done 😊

**Comment by smarter** [comment]
Thanks for the PR! Unfortunately it stopped merging cleanly as the syntax for given was changed recently, I've updated it and opened a new PR based on this (I couldn't update this one): https://github.com/lampepfl/dotty/pull/10720

**Pull request closed without merging**
