### PR TITLE
[WIP] Check if opts succeed in CI

### PR DESCRIPTION
**Pull request by DarkDimius**
If they do, I'll force push to PR by @OlivierBlanvillain

### CODE REVIEW

**Comment by OlivierBlanvillain** [comment]
@DarkDimius Looks green to me, the failure comes from the bytecode tests I've added (and never tried to run bootstrapped), it's looks like a test infrastructure thing:

```scala
[error] Test dotty.tools.dotc.SimplifyPosTests.initializationError failed: java.lang.Exception: No runnable methods, took 0.002 sec
[error] Test dotty.tools.dotc.SimplifyNegTests.initializationError failed: java.lang.Exception: No runnable methods, took 0.0 sec
[error] Test dotty.tools.dotc.SimplifyEquivalences.initializationError failed: java.lang.Exception: Test class should have exactly one public constructor, took 0.0 sec
```

**Comment by DarkDimius** [comment]
@OlivierBlanvillain could you please modify the bytecode tests to make sure they pass?

**Comment by smarter** [comment]
`SimplifyNegTests` extends a trait with `@Test` methods, I wonder if this is related to https://github.com/scala-js/scala-2.12-junit-mixin-plugin

**Comment by smarter** [comment]
@DarkDimius Does dotty emit mixin forwarders?

**Comment by DarkDimius** [comment]
@smarter, it’s likely that your suggestion is the right one.
We don’t emit forwarders if default method dispatch will yield the 
same result.

**Comment by smarter** [comment]
Doesn't Scala 2.12 always emit forwarders for performance reasons now?

**Comment by DarkDimius** [comment]
I'm working on fixing Junit4 in Dotty

**Comment by OlivierBlanvillain** [comment]
@DarkDimius I have a fix for the SimplifyTests, it it ok for to test it by force pushing this branch?

**Comment by DarkDimius** [comment]
@OlivierBlanvillain, yes please force push. I'll still fix JUnit 4 in separate branch.

**Comment by OlivierBlanvillain** [comment]
@DarkDimius it passed the CI! http://dotty-ci.epfl.ch/lampepfl/dotty/2614 I've pushed it to #2513.

**Pull request closed without merging**
