### PR TITLE
Fix #11076: Use bootstrapped scalaInstance for community build

### LINKED ISSUE #11076: `community-docs` CI is using the non-bootstrapped library
`community-docs` CI is using the non-bootstrapped library. It must use the bootstrapped version of the library.

This was seen in https://github.com/lampepfl/dotty/pull/11074/checks?check_run_id=1689298098 where one of the methods was implemented `???` only on the `non-bootstrapped`.

### PR DESCRIPTION
**Pull request by griggt**
This PR seems to fix the issue, however it is not at all clear to me whether there are better/alternative solutions.

Fixes #11076

### CODE REVIEW

**Comment by nicolasstucki** [comment]
I double-checked that the fix works for the case I encountered. It looks good. Not sure if there is a better alternative. @smarter WDYT?

**Review by smarter — CHANGES_REQUESTED** [review]
The problem is that the community-build project uses a macro: https://github.com/lampepfl/dotty/blob/master/community-build/src/scala/dotty/communitybuild/FieldsImpl.scala, macros require classloading which means the version of the standard library in the scalaInstance must match the one used in the project (so bootstrapped in both case), which in turns means that all bootstrapped projects have to be compiled. This is fine for the community-build since we need the bootstrapped projects compiled anyway to run it, so we can make the change proposed in this PR but it would need to be documented better (and ideally it should avoid duplicating code and comment with the other `scalaInstance`). Alternatively, we could get rid of the macro in the community-build project: IMO it's really overkill to use a macro here, the list of project could be built by adding entries into a mutable set for example.

**Comment by nicolasstucki** [comment]
We should get rid of the macro and just list them. We already list those in other parts of the code.

**Comment by nicolasstucki** [comment]
I added a commit to remove the macro in #11074

**Pull request closed without merging**
