### PR TITLE
Add tests related to variance checking.

### PR DESCRIPTION
**Pull request by sstucki**

### CODE REVIEW

**Comment by DarkDimius** [comment]
Huh??? Strange error. I guess there's some bug hidden behind non-determinism.
```
[error] Test dotc.tests.compileStdLib failed: dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$BadSignature: error reading Scala signature of class Tuple2 from /home/jenkins/workspace/dotty-master-validate-junit/ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar(scala/Tuple2.class):
[error] error occurred at position 1932: a runtime exception occurred: java.util.NoSuchElementException, took 0.928 sec
[error]     at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler.errorBadSignature(Scala2Unpickler.scala:180)
[error]     at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler.handleRuntimeException(Scala2Unpickler.scala:189)
[error]     at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.complete(Scala2Unpickler.scala:579)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:210)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:188)
[error]     at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1571)
[error]     at dotty.tools.dotc.core.Types$Type.isRef(Types.scala:111)
[error]     at dotty.tools.dotc.core.Types$Type.isRef(Types.scala:116)
[error]     at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$apply(TypeErasure.scala:336)
[error]     at dotty.tools.dotc.core.TypeErasure$.valueErasure(TypeErasure.scala:126)
[error]     at dotty.tools.dotc.core.TypeErasure.eraseDerivedValueClassRef(TypeErasure.scala:415)
[error]     at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:466)
[error]     at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:479)
[error]     at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:479)
[error]     at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:136)
[error]     at dotty.tools.dotc.core.Signature$.apply(Signature.scala:76)
[error]     at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2185)
[error]     at dotty.tools.dotc.core.Types$MethodType.resultSignature(Types.scala:2204)
[error]     at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2276)
[error]     at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2195)
[error]     at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2204)
[error]     at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2184)
[error]     at dotty.tools.dotc.core.Types$PolyType.resultSignature(Types.scala:2395)
[error]     at dotty.tools.dotc.core.Types$PolyType.computeSignature(Types.scala:2405)
[error]     at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2195)
[error]     at dotty.tools.dotc.core.Types$PolyType.signature(Types.scala:2395)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:465)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.matches(Denotations.scala:810)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.filterDisjoint(Denotations.scala:817)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:821)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:457)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeNPMembersNamed$1.collect$1(SymDenotations.scala:1578)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeNPMembersNamed$1.collect$1(SymDenotations.scala:1573)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeNPMembersNamed$1.apply(SymDenotations.scala:1586)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeNPMembersNamed$1.apply(SymDenotations.scala:1563)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeNPMembersNamed(SymDenotations.scala:1562)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.nonPrivateMembersNamed(SymDenotations.scala:1552)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1539)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1591)
[error]     at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:432)
[error]     at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:528)
[error]     at dotty.tools.dotc.core.Types$Type.memberExcluding(Types.scala:418)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:409)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:409)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.member(Types.scala:408)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$implicitMembers$1$$anonfun$apply$6.apply(Types.scala:597)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$implicitMembers$1$$anonfun$apply$6.apply(Types.scala:597)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$memberDenots$1.apply(Types.scala:566)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$memberDenots$1.apply(Types.scala:566)
[error]     at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
[error]     at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
[error]     at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
[error]     at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:566)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$implicitMembers$1.apply(Types.scala:596)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$implicitMembers$1.apply(Types.scala:598)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.implicitMembers(Types.scala:595)
[error]     at dotty.tools.dotc.typer.ImportInfo.importedImplicits(ImportInfo.scala:84)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:203)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.core.Contexts$Context.implicits(Contexts.scala:210)
[error]     at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:595)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1$$anonfun$apply$17.apply(Implicits.scala:435)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1$$anonfun$apply$17.apply(Implicits.scala:430)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1.apply(Implicits.scala:430)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1.apply(Implicits.scala:425)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Implicits$class.inferImplicit(Implicits.scala:425)
[error]     at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferView$1.apply(Implicits.scala:408)
[error]     at dotty.tools.dotc.typer.Implicits$$anonfun$inferView$1.apply(Implicits.scala:401)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Implicits$class.inferView(Implicits.scala:400)
[error]     at dotty.tools.dotc.typer.Typer.inferView(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Implicits$class.viewExists(Implicits.scala:392)
[error]     at dotty.tools.dotc.typer.Typer.viewExists(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.ProtoTypes$Compatibility$class.isCompatible(ProtoTypes.scala:38)
[error]     at dotty.tools.dotc.typer.Typer.isCompatible(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Applications$TestApplication.addArg(Applications.scala:387)
[error]     at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:319)
[error]     at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:358)
[error]     at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:190)
[error]     at dotty.tools.dotc.typer.Applications$TestApplication.<init>(Applications.scala:395)
[error]     at dotty.tools.dotc.typer.Applications$ApplicableToTrees.<init>(Applications.scala:402)
[error]     at dotty.tools.dotc.typer.Applications$class.isApplicable(Applications.scala:810)
[error]     at dotty.tools.dotc.typer.Typer.isApplicable(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$resolveOverloaded$1$$anonfun$narrowByTrees$1$1.apply(Applications.scala:1084)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$resolveOverloaded$1$$anonfun$narrowByTrees$1$1.apply(Applications.scala:1083)
[error]     at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
[error]     at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
[error]     at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$resolveOverloaded$1.narrowByTrees$1(Applications.scala:1083)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$resolveOverloaded$1.apply(Applications.scala:1097)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$resolveOverloaded$1.apply(Applications.scala:978)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Applications$class.resolveOverloaded(Applications.scala:978)
[error]     at dotty.tools.dotc.typer.Typer.resolveOverloaded(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Typer.adaptOverloaded$1(Typer.scala:1442)
[error]     at dotty.tools.dotc.typer.Typer.adaptInterpolated(Typer.scala:1675)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1$$anonfun$apply$22.apply(Typer.scala:1384)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1$$anonfun$apply$22.apply(Typer.scala:1380)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1.apply(Typer.scala:1380)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1.apply(Typer.scala:1380)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:1379)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1325)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:540)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:536)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:536)
[error]     at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:602)
[error]     at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1238)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1272)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:202)
[error]     at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:519)
[error]     at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:517)
[error]     at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:319)
[error]     at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:358)
[error]     at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:190)
[error]     at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:437)
[error]     at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:518)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1$$anonfun$apply$1.apply(Applications.scala:557)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1$$anonfun$apply$1.apply(Applications.scala:554)
[error]     at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1333)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:560)
[error]     at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:536)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:536)
[error]     at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:602)
[error]     at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:61)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1238)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1272)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:706)
[error]     at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:716)
[error]     at dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:822)
[error]     at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:823)
[error]     at dotty.tools.dotc.typer.Namer.lhsType$lzycompute$1(Namer.scala:824)
[error]     at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:824)
[error]     at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:836)
[error]     at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:844)
[error]     at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:910)
[error]     at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:513)
[error]     at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:555)
[error]     at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:538)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:210)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:188)
[error]     at dotty.tools.dotc.core.Types$Type.memberInfo(Types.scala:620)
[error]     at dotty.tools.dotc.core.Denotations$Denotation.matchingDenotation(Denotations.scala:234)
[error]     at dotty.tools.dotc.typer.Namer$$anonfun$13.apply(Namer.scala:765)
[error]     at dotty.tools.dotc.typer.Namer$$anonfun$13.apply(Namer.scala:763)
[error]     at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
[error]     at scala.collection.immutable.List.foldLeft(List.scala:84)
[error]     at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:136)
[error]     at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]     at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:763)
[error]     at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:844)
[error]     at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:910)
[error]     at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:513)
[error]     at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:555)
[error]     at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:538)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:210)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:188)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:312)
[error]     at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1190)
[error]     at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1215)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1276)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1310)
[error]     at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1321)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1064)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1047)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1047)
[error]     at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1229)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1276)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1310)
[error]     at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1321)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1154)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1145)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1145)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1266)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1316)
[error]     at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1321)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1154)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1145)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1145)
[error]     at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1266)
[error]     at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1278)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1288)
[error]     at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1286)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:131)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:54)
[error]     at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1286)
[error]     at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1325)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:47)
[error]     at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:23)
[error]     at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:45)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:69)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:69)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:69)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:61)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:58)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:58)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:53)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:53)
[error]     at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
[error]     at dotty.tools.dotc.Run.compileUnits(Run.scala:53)
[error]     at dotty.tools.dotc.Run.compileSources(Run.scala:50)
[error]     at dotty.tools.dotc.Run.compile(Run.scala:34)
[error]     at dotty.tools.dotc.Driver.doCompile(Driver.scala:28)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:126)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:95)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:107)
[error]     at test.CompilerTest.compileArgs(CompilerTest.scala:222)
[error]     at test.CompilerTest.compileList(CompilerTest.scala:196)
[error]     at dotc.tests.compileStdLib(tests.scala:139)
[error]     ...
```

**Comment by odersky** [comment]
Can it be reproduced locally? Or force push to see whether it persists on Jnkins?

**Comment by DarkDimius** [comment]
@odersky I wasn't able to reproduce it locally, but it was reproduced at least once on jenkins.

**Comment by sstucki** [comment]
BTW this is related to [SI 9725](https://issues.scala-lang.org/browse/SI-9725): dotty passes the tests while scalac fails.

**Pull request merged**
