### PR TITLE
Restrict Eta-reduction to Java-defined classes

### PR DESCRIPTION
**Pull request by odersky**
Collapse `[X] =>> C[X]` only if `C` is a Java-defined class. Since
Java does not have hk-types it must be a raw type in this case.

### CODE REVIEW

**Comment by smarter** [comment]
We try to always cook raw types so in what case is this actually needed ?

**Comment by odersky** [comment]
@smarter Failing tests if the `case EtaExpansion` clauses are completely removed:
```
    tests/pos/i4908.scala failed
    tests/pos/t3349 failed
    tests/pos/t3429 failed
    tests/pos/i4908.scala failed
    tests/pos/t3349 failed
    tests/pos/t3429 failed
    tests/pos-java-interop/t1196 failed
```

**Comment by smarter** [comment]
OK, so it seems the issues all come from joint-compilation with .java sources where we don't actually cook types.

**Comment by odersky** [comment]
OK, we cook types coming from Java sources now as well, which means we can simplify TypeComparer to no longer test for eta expansions.

**Comment by odersky** [comment]
Backing out. It seems we cannot cook things everywhere without running into cyclic references.

**Pull request merged**
