### PR TITLE
Improve our ability to override default parameters

### PR DESCRIPTION
**Pull request by smarter**
Don't just use the type of the rhs of the default getter as its inferred
type, this can be more precise than the type of the corresponding
parameter and prevent seemingly valid overrides.

### CODE REVIEW

**Comment by smarter** [comment]
(this is a blocker for https://github.com/lampepfl/dotty/pull/11671)

**Comment by odersky** [comment]
I think we want to go the other way: make default arguments inline (and hence final). Without that step we won't be able to get any of the other desired improvements of default arguments. So, is this change really necessary?

**Comment by smarter** [comment]
> So, is this change really necessary?

It's necessary to get the scala.js tests to pass with https://github.com/lampepfl/dotty/pull/11671. This change improves compatibility with Scala 2 in general but does not change anything fundamentally, we already allow overrides for default parameters, this change just avoid seemingly arbitrary situations where this fails with a puzzling error message. So getting this change in won't have any impact on our future plans with default parameters.

**Comment by smarter** [comment]
Also, independent of overrides, this change is good because it avoids breaking unnecessary breaks to binary compatibility, right now:
```scala
class A {
  def foo(param: X = new Y): X = param
}
```
will generate a default getter whose return type is `Y`, meaning that if I later want to change this to `= new X`, binary compatibility will be broken.

**Comment by smarter** [comment]
Another point in favor of this PR, this currently fails on master:
```scala
case class SourcePosition(outer: SourcePosition = NoSourcePosition) {
  assert(outer != null)  // crash
}

object NoSourcePosition extends SourcePosition()
```
with the weird error:
```scala
-- Error: tests/neg/i4659b.scala:5:32 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5 |object NoSourcePosition extends SourcePosition() // error
  |                                ^^^^^^^^^^^^^^
  |                                super constructor cannot be passed a self reference
1 error found
```
By widening the type of the default getter we don't run into this anymore.

**Comment by smarter** [comment]
This is now green after fixing some community build issues.

**Review by odersky — APPROVED** [review]
LGTM

**Pull request merged**
