### PR TITLE
Feature - Responsive Dottydoc (Part 1) - Main layout

### PR DESCRIPTION
**Pull request by hhandoko**
Related ticket: #1945 

Added better responsive support to sidebar by implementing off-canvas behaviour (i.e. content body slides to the right instead of becoming narrower).

Tested on:
- Chrome 56.0.2924.87
- Firefox 47.0.1
- Safari 10.0.3

### CODE REVIEW

**Comment by felixmulder** [comment]
As a side note - we're using the imperative mood for our commit messages. This means "Add X" instead of "Added X". Here's a quick primer:

> 1. Separate subject from body with a blank line
> 1. Limit the subject line to 50 characters
> 1. Capitalize the subject line
> 1. Do not end the subject line with a period
> 1. Use the imperative mood in the subject line
> 1. Wrap the body at 72 characters
> 1. Use the body to explain what and why vs. how
>
> taken from [Chris Beams](https://chris.beams.io/posts/git-commit/)

**Comment by hhandoko** [comment]
Hi @felixmulder,

> The position of the hamburger icon has changed, we'd like to keep it where it was. Also in moving it, it looks like it lost its CSS styling.

By CSS styling do you mean `:hover` styles? I missed it but I can add it back again. I changed the positions since a fixed hamburger icon positioning overlaps with the content body text (it looks less intrusive in the sidebar area). Also, I am taking these cues from Elixir's ExDocs convention [1].

> The width of the sidebar now feels a bit too wide, what was your reasoning here?

I felt 250px was a bit too narrow as some package names got cut-off and most class names barely fit, so I added an extra 50px... But you have a good point, probably on narrower viewport width I can reduce it back to 250px.

> The animation from ☰ to ˿ while nice-looking, doesn't really add anything in its context, I assume it's for mobile devices / something thinner than 767px - maybe it'd look ok with the old styling restored? Let's leave it in for the next iteration of the PR.

I was looking to give more context with the left-pointing arrow, I've seen it implemented on the old Google Play Store mobile sidebar. Yes, the animation has no functional purpose, I just thought it looks nice 😁 

> In the <767px view the size of the sidebar exposed is huge, I'm not sure if that was intentional or if it looks better on mobile. But we should probably differentiate between rules for mobile devices and smaller viewports on desktops, just a thought

Yes, it is intentional. As per earlier comments I'll reduce it back to 250px before minimising the sidebar at 576px.

Let me know if you have any further thoughts.

Notes:
[1] - Example of Elixir's ExDocs output: https://hhandoko.github.io/diskusi/readme.html

**Comment by felixmulder** [comment]
> By CSS styling do you mean `:hover` styles? 

I mean:

screen shot 2017-03-06 at 15 45 01
vs before:
screen shot 2017-03-06 at 15 45 08

> a fixed hamburger icon positioning overlaps with the content body text

Not sure what you mean by "overlaps" in this sentence here is what it looks like on rMBP all  up to date browsers:

screen shot 2017-03-06 at 15 53 34

> Also, I am taking these cues from Elixir's ExDocs

I see, let's try to do our own thing 🙂 

> I felt 250px was a bit too narrow as some package names got cut-off and most class names barely fit

You're right, but then again, 300px is not enough for some projects, so this will be arbitrary - if we keep it at 250px - people can override the CSS on their own docs if need be.

**Comment by hhandoko** [comment]
> Not sure what you mean by "overlaps" in this sentence here is what it looks like on rMBP all up to date browsers:

WRT the screenshot, it looks OK when the content body fits entirely in one page, but it becomes an issue on lengthy pages.

- Without fixed hamburger menu positioning, the menu gets hidden when the user scrolls towards the bottom of the page. It is especially problematic on mobile devices with lengthy content body, as the user won't be able to minimise the sidebar again without scrolling to the top of the page.

- With fixed hamburger menu positioning (i.e. fixed position on top-left of content body), some left-padding must be added to the content body otherwise the menu will appear on top of the content body text / whitespace when the user scrolls towards the bottom of the page.

hamb-menu-overlap

> I see, let's try to do our own thing 🙂

Yes, I'm not saying Dottydoc should copy ExDocs, just that I found that their UI pattern is useful and solves an existing problem given that the primary layout is very similar (as mentioned above).

> You're right, but then again, 300px is not enough for some projects, so this will be arbitrary - if we keep it at 250px - people can override the CSS on their own docs if need be.

Good point 👌 

Actions:
[ ] - Add `:hover` styles to hamburger menu
[ ] - Reduce sidebar width back to 250px
[ ] - Switch to minimise sidebar at x < 576px from x < 768px

**Comment by hhandoko** [comment]
@felixmulder, any thoughts? ☝️

**Comment by hhandoko** [comment]
The last batch of commits completes the following:

[X] - Add `:hover` styles to hamburger menu
[X] - Reduce sidebar width back to 250px
[ ] - Switch to minimise sidebar at x < 576px from x < 768px

I've left sidebar minimisation / collapse at 768px as the layout looks really awkward between Mobile and Tablet resolution (sidebar and content body is split almost equally down the middle).

**Comment by felixmulder** [comment]
Thanks for the hard work @hhandoko! :tada:

**Pull request merged**
