### PR TITLE
Fix #10709: Add missing level check before inlining

### LINKED ISSUE #10709: summonInline[B <:< A] compiles when quoted despite B not being a subtype of A
## Minimized code

```Scala
// using 3.0.0-M2

import scala.quoted._
import scala.compiletime.summonInline

object Invalid {
  inline def apply[A, B]: Any = ${ invalidImpl[A, B] }

  def invalidImpl[A, B](using qctx: Quotes, tpeA: Type[A], tpeB: Type[B]): Expr[Any] = {
    '{summonInline[B <:< A]}
  }
}

/************ other file ************/

class A
class B extends A
println(Invalid[A, B]) // compiles as expected
println(Invalid[B, A]) // does also compile!
```

## Expectation

`'{summonInline[B <:< A]}` should not compile when subtyping rules are violated

### PR DESCRIPTION
**Pull request by nicolasstucki**
If an a call to an inline method is within a quote, this call must not be inlined.

* Delay inlining within quotes.
* Disallow `inline def` within quotes. Same as `inline def` in `inline def`.
* Disable `tests/run-staging/i3876-{d,e}.scala`. This test requires inlining after Pickler to be able to inline the missing expression. This will be fixed by #9984 and it only affects `scala.quoted.staging.run`.

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM

**Comment by nicolasstucki** [comment]
Just to double-check. @liufengyun did you see the second commit while reviewing?

**Comment by liufengyun** [comment]
> Just to double-check. @liufengyun did you see the second commit while reviewing?

Thanks. For `tests/run-staging/i3876-e.scala`, it is not obvious to me why `inlineLambda` is inlined after Pickler:

```Scala
import scala.quoted._
import scala.quoted.staging._
object Test {
  def main(args: Array[String]): Unit = {
    given Toolbox = Toolbox.make(getClass.getClassLoader)

    def x(using Quotes): Expr[Int] = '{ println(); 3 }

    def f4(using Quotes): Expr[Int => Int] = '{
      inlineLambda
    }
    println(run(Expr.betaReduce('{$f4($x)})))
    println(withQuotes(Expr.betaReduce('{$f4($x)}).show))
  }

  transparent inline def inlineLambda: Int => Int = x => x + x
}
```

**Comment by nicolasstucki** [comment]
Indeed, it is not obvious. 

Previously we would evaluate `'{$f4($x)}` to  `'{ (x => x + x).apply({println(); 3}) }`.

Now we evaluate `'{$f4($x)}` to `'{ inlineLambda({println(); 3}) }`. In this particular case the `betaReduce` operation would be a no-opp, but `BetaReduce` phase would reduce it later. If we were to use this value in a macro then the code `inlineLambda({println(); 3})` would be inserted somewhere and then inline calls from it would be inlined by `Typer`. In `i3876-e` we do not pass again in typer after generating `'{ inlineLambda({println(); 3}) }` and therefore we do not get a chance to inline this call. #9984 will make it possible to inline after pickler. This phase can also be used in the special instance of the compiler used for `scala.quoted.staging.run`.

**Comment by liufengyun** [comment]
Thanks for the detailed explanation, it makes sense 👍

**Comment by nicolasstucki** [comment]
The downside of this PR is that it will temporarily break `scala.quoted.staging.run` that runs code with calls to inline methods.

**Comment by liufengyun** [comment]
> The downside of this PR is that it will temporarily break `scala.quoted.staging.run` that runs code with calls to inline methods.

I don't think it matters much, as it's not as commonly used as macros and the fix is coming in RC1.

**Comment by nicolasstucki** [comment]
#10803 will fix `scala.quoted.staging.run`

**Pull request merged**
