### PR TITLE
Remove mixin traits of Context

### PR DESCRIPTION
**Pull request by odersky**
In particular:

  - `newSymbol`, `requiredSymbol` etc, now are available
     from Symbols, no `ctx.` prefix needed
  - All reporing methods are available from `report` object.

It's clearer to make them regular objects. Also:

 - Change functions from Context to context functions. 
 - Add atPhase, atPhaseNoLater, addPhaseNoEarlier and have them replace
   most uss of `withPhase`...
 - Add inMode, withMode, withoutMode utility wrappers
 - Move error messages directly into reporting: this avoids
   an annoying import
 - Convert old style implicit parameters to `(using Context)`
 - Reorganize TyperState.test: Instead of overwriting fields of TyperState, keep test
   contexts in an explicit stack, so that they can be re-used. This is simpler and
   since there is more decoupling between tests. Usage is now
   `Contexts.explore(...)` instead of `ctx.test(...)`.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
From the logs:

```
[error] -- [E008] Not Found Error: /data/workspace/bench/dotty/bench/src/main/scala/Benchmarks.scala:105:14 
[error] 105 |          ctx.error(ex.getMessage) // signals that we should fail compilation.
[error]     |          ^^^^^^^^^
[error]     |value error is not a member of dotty.tools.dotc.core.Contexts.Context - did you mean ctx.period?
[error] one error found
```

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
We seem to have a small but significant improvement of performance in stdlib compilation. The rest is more or less the same. The compiler itself is a little bit slower, which is to be expected since there are now many more implicit searches than before.

**Comment by odersky** [comment]
Squashed to one commit to allow for easier rebasing

**Comment by odersky** [comment]
test performance please

**Pull request merged**
