### PR TITLE
Harmonize PolyType and TypeLambda

### PR DESCRIPTION
**Pull request by odersky**
Push as much as we can into common superclass GenericType. Review by @smarter.

Update: I managed to completely eliminate any distinction between PolyType and TypeLambda. They are the same type now, and GenericType as a supertype could also be eliminated.

### CODE REVIEW

**Comment by smarter** [comment]
Needs to be rebased after the inline merge

**Comment by odersky** [comment]
Rebased to master

**Comment by odersky** [comment]
In theory this commit paves the way to allow polymorphic types as value types. A test of some
of the basic functionality is in pending/pos/polyTypes. This does not work yet,  because `adapt` forces every polytype it sees to be fully applied. Enabling this functionality should be a SIP and separate PR.

**Comment by smarter** [comment]
Rebased after the union-type PR merge

**Comment by smarter** [comment]
LGTM, I wonder if we can merge `LambdaParam` and `PolyParam` ?

**Comment by odersky** [comment]
> LGTM, I wonder if we can merge LambdaParam and PolyParam ?

Yes, interesting question. PolyParam is a reference to a parameter, whereas LambdaParam is a surrogate for a symbol, i.e. a definition. So it's not obvious, but still worth thinking about it.

**Pull request merged**
