### PR TITLE
Add scodec to the community build

### PR DESCRIPTION
**Pull request by mpilquist**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Thanks for adding this @mpilquist!

All the community projects exist in Dotty as forks of the original repos under dotty-staging organization. I've created such forks for your projects and added you to the repos:

https://github.com/dotty-staging/scodec-bits
https://github.com/dotty-staging/scodec

Could you make the submodules point to these repos?

Also, the build is failing because `sbt.librarymanagement.ResolveException: Error downloading org.scalatest:scalatest_0.24:3.1.1`. This is because in the community build, we do not have Scalatest 3.1.1, only `3.1.0-SNAP13`. This means that for your projects to compile, you need to depend exactly on that version. I would recommend to try to update the dependency on the forks in the dotty-staging organization so that the original repo is not affected.

**Comment by mpilquist** [comment]
@anatoliykmetyuk Thanks! 

Is there a way to run the community build locally? I knew this PR wasn't yet in a good state but wanted to see the output of CI in order to make progress.

Also, can you give me write permissions to the two scodec dotty-staging repositories?

**Comment by anatoliykmetyuk** [comment]
> Is there a way to run the community build locally?

You can do so by cloning the Dotty repo, launching SBT console from it and running the following command from there:

```
community-build/testOnly dotty.communitybuild.CommunityBuildTest -- *scodec
community-build/testOnly dotty.communitybuild.CommunityBuildTest -- *scodecBits
```

**Comment by mpilquist** [comment]
OK I think this is ready. Do you want me to close this and reopen a PR with a single commit? Alternatively, squash merging is fine.

**Comment by smarter** [comment]
> Do you want me to close this and reopen a PR with a single commit? 

You can squash your commits and push-force without closing/reopening.

**Comment by mpilquist** [comment]
Okay squashed. Thanks for all the help!

**Comment by anatoliykmetyuk** [comment]
Thanks for contributing these tests @mpilquist!

**Pull request merged**
