### PR TITLE
Scaladoc: UI/UX Changes

### PR DESCRIPTION
**Pull request by pikinier20**
Changed elements:

- colors in dark theme
- sidebar navigation
- signature highlighting
- anchors in member lists
- version dropdown component
- font size, line height
- width of content

@Katrix I tag you because you always were involved in UI/UX part of Scaladoc. 

I'm going to post there link to example documentation as soon as it's generated.

### CODE REVIEW

**Comment by BarkingBad** [comment]
https://scala3docstorage.blob.core.windows.net/pr-change-dark-theme/scala3/docs/index.html

**Comment by BarkingBad** [comment]
obraz
obraz

**Comment by pikinier20** [comment]
@BarkingBad No, it's not. It's probably broken due to the `align-items: center;` rule.

**Comment by BarkingBad** [comment]
Missing class icons? 
obraz

**Comment by BarkingBad** [comment]
Maybe golden color for annotations?
obraz

**Review by BarkingBad — APPROVED** [review]
Changes seem OK, just please fix breaking `Deprecated` `<dt>` and `Inherited from:` (colon)

**Comment by Katrix** [comment]
Looks for the most part good. Notice that the scroll bar disappeared at some point in the past, and while I understand it causes problems, I also think it's important for it to be present. That's not related to these changes though.

**Review by BarkingBad — APPROVED** [review]
Looks good

**Pull request merged**
