### PR TITLE
Use new docker image with updated cache after the switch to 2.12

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
log: https://gist.github.com/OlivierBlanvillain/de56bb13951ca87d9d86aabbbf41c450

### CODE REVIEW

**Comment by felixmulder** [comment]
Gotta sign the file mate `drone sign lampepfl/dotty` 👍

**Comment by allanrenucci** [comment]
I guess you should update all the images in the file

**Comment by allanrenucci** [comment]
From my understanding we set `pull: true` in the `done.yml` file to always pull the latest image. However, to have the latest image we should write `image:lampepfl/dotty:latest` and a specific version.
Am I missing something?

**Comment by OlivierBlanvillain** [comment]
Tags of docker images are mutable, with `pull: true` drone will always ask docker-hub, "hey is <local-hash> the latest version of `lampepfl/dotty:2017-08-30`". I guess it could be removed since the plan is to keep all images for better reproducibility :)

**Pull request merged**
