### PR TITLE
Fix #7781: Loosen check for classes in wrong directory

### LINKED ISSUE #7781: Check bootstrapping issue with `quoted.Expr`
Check bootstrapping issue with `quoted.Expr`.

### LINKED ISSUE #7783: Pattern matching with an `AnyVal` scrutinee fails with unreachable case error
Compiling this,

```scala
object Test {
  def foo(t: AnyVal): Unit = t match {
    case _: Int =>
  }
}
```

gives me the following unreachable case error rather than the non-exhaustivity warning I was hoping for,
```
-- Error: local/nulls.scala:3:9 ------------------------------------------------
3 |    case _: Int =>
  |         ^
  |this case is unreachable since class AnyVal and class Integer are unrelated
1 error found
```

Assuming this _is_ a bug and that this _should_ instead give us a warning about a non-exhaustive match, then does this make the introduction of `Null` as a subtype of `AnyVal` with `-Yexplict-nulls` in https://github.com/lampepfl/dotty/pull/7546 problematic? Presumably the extra case would make previously exhaustive matches over existing `AnyVals` non-exhaustive?

### PR DESCRIPTION
**Pull request by odersky**
The previous check demanded that the package prefix of a file corresponds
one-to-one with the directory name. This makes it illegal to have classes
in nested package clauses inside a file, which seems unreasonable. We now
only require that the file path is a prefix of the package path.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@smarter do you know how to create a test that triggers this warning?

**Comment by smarter** [comment]
Use  tests/pos-special/sourcepath and tests/neg-custom-args/sourcepath

**Comment by odersky** [comment]
> Isn't this going to enter classes with the wrong owner?

No.

> This also lacks a test.

Well, in a sense the quoted.Expr example is the test. That's what failed before, anyway.

I won't be able to work on this anymore, but it needs to be part of the release. @smarter or @nicolasstucki maybe you want to add a test? If there's no time for that let's merge anyway.

**Comment by smarter** [comment]
>> Isn't this going to enter classes with the wrong owner?
> I don't think so. Why would it?

Because `owner` comes from the path and will be the same for everything entered by `enterScanned`. Demonstration with this PR:

```scala
// A.scala
package foo
package bar

class A
```
```scala
// B.scala
type Bla = foo.bar.A
```
```shell
% mkdir sp/foo
% mv A.scala sp/foo
% dotc -sourcepath sp B.scala
-- [E008] Member Not Found Error: B.scala:1:15 ------------------------------
1 |type Bla = foo.bar.A
  |           ^^^^^^^
  |           value bar is not a member of foo - did you mean foo.A?
```

No symbol was created for `foo.bar`, let alone `foo.bar.A`, and `A` was mistakenly added in `foo`.

> I won't be able to work on this anymore, but it needs to be part of the release

I think merging https://github.com/lampepfl/dotty/pull/7784 would be more conservative.

**Comment by odersky** [comment]
@smarter I see what you mean. That aspect did not change. So, basically, outline parsing with nested packages was broken and is still broken now.  #7784  "fixes" this by not using the feature in our own codebase. But others will run into the same problem. 

So I think we should either fix it or disable it (by issuing a "not implemented error") before the release.

**Comment by smarter** [comment]
> So, basically, outline parsing with nested packages was broken and is still broken now.

But before this PR the same code would have lead to a warning "class A is in the wrong directory." and wouldn't have added A to foo. Is there some other scenario where current master would add the symbol anyway ?

**Comment by odersky** [comment]
> But before this PR the same code would have lead to a warning "class A is in the wrong directory." and wouldn't have added A to foo. 

That's not quite as bad, but still counts as broken. The problem is,  #7784 changes the public API of the core Type and Expr types in a non-desirable way to curcumvent our lack of support for nested packages. So I much prefer we fix it instead.

**Comment by odersky** [comment]
I see it's not so easy to fix, since there is quite involved logic in Namer for creating packages. It's not clear we want to push all that into the outline parser. So, let's close this and revive #7784.

**Pull request closed without merging**
