### PR TITLE
make refutable patterns an error in 3.4

### PR DESCRIPTION
**Pull request by bishabosha**
was originally targeting 3.3 - opening this to see which community build projects fail

### CODE REVIEW

**Comment by bishabosha** [comment]
@sjrd so far this requires patching the `sjsJUnitTests` sources, what do you recommend to do here?

**Comment by sjrd** [comment]
The Scala.js tests have to pass with older 2.12 and 2.13 versions, all the way back to 2.12.2 and 2.13.0.

What's the magnitude of this problem? Is it a couple places, or is it everywhere? Can you give examples?

**Comment by bishabosha** [comment]
The failure in the CI points to these files:
- test-suite/js/src/test/scala/org/scalajs/testsuite/niocharset/UTF16Test.scala
- test-suite/js/src/test/scala/org/scalajs/testsuite/scalalib/ArrayTest.scala
- test-suite/js/src/test/scala/org/scalajs/testsuite/library/ObjectTest.scala
- test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/TupleTest.scala

in total there are 7 lines affected - all refutable patterns in for comprehension or pattern val bindings

**Comment by sjrd** [comment]
The ones in `UTF16Test` and `ArrayTest` can be changed to use an explicit `match` with a `fail("message")` in the default case.

In `ObjectTest` and `TupleTest`, I think there's a deeper issue. It seems they are all related to extracting `js.TupleN(...)` from something that is known to be a `js.TupleN` (with the same `N`), so they should be irrefutable. Perhaps we messed up the definition of those extractors? There are here:
https://github.com/scala-js/scala-js/blob/v1.12.0/library/src/main/scala/scala/scalajs/js/Tuple.scala
https://github.com/scala-js/scala-js/blob/v1.12.0/library/src/main/scala/scala/scalajs/js/Tuple.nodoc.scala

**Comment by bishabosha** [comment]
these community-build projects still need patching to pass Community Build C:
- [ ] utest
- [ ] scala-collection-compat
- [ ] scala-xml (suite C)
- [ ] scalaz
- [ ] protoquill

**Comment by bishabosha** [comment]
updated for 3.4 - unsure if the patches are still needed for various community projects

**Comment by bishabosha** [comment]
list of community build projects still failing:
 - [ ] dotty.communitybuild.CommunityBuildTestC.protoquill
 - [ ] dotty.communitybuild.CommunityBuildTestC.pprint
 - [ ] dotty.communitybuild.CommunityBuildTestC.scalaz
 - [ ] dotty.communitybuild.CommunityBuildTestC.scalaXml
 - [ ] dotty.communitybuild.CommunityBuildTestC.requests
 - [ ] dotty.communitybuild.CommunityBuildTestC.scalaCollectionCompat
 - [ ] dotty.communitybuild.CommunityBuildTestC.upickle
 - [ ] dotty.communitybuild.CommunityBuildTestC.cask
 - [ ] dotty.communitybuild.CommunityBuildTestC.geny
 - [ ] dotty.communitybuild.CommunityBuildTestC.fansi
 - [ ] dotty.communitybuild.CommunityBuildTestC.oslib
 - [ ] dotty.communitybuild.CommunityBuildTestC.ujson
 - [ ] dotty.communitybuild.CommunityBuildTestC.utest
 - [ ] dotty.communitybuild.CommunityBuildTestC.parboiled2

**Comment by bishabosha** [comment]
The problematic Scala.js tests will have to remain ignored until base Scala.js version is updated to 1.13.0+

**Comment by bishabosha** [comment]
> I'm not completely sure, but I don't this ever went through the SIP process. Since it turns previously valid (and not unsound) code into an error by design, it seems to me that it affects the language spec and therefore needs a SIP.
> 
> Perhaps alternatively, it could remain a _configurable_ error. Scala 2 has enough configuration options with `-W` flags and `@nowarn` annotations that some things can be errors by default but can be downgraded to warnings at will. This would be a good candidate for such a treatment.

The thing is this isn't just a lint - the code generation with this change no longer calls withFilter. Previously in 3.3 the code calls withFilter even for irrefutable patterns

**Comment by sjrd** [comment]
So this was part of https://docs.scala-lang.org/scala3/reference/changed-features/pattern-bindings.html, which was in the set of proposals that were accepted by the SIP committee while leading up to Scala 3. So seems fine to me.

**Comment by bishabosha** [comment]
I think it'd be good to address #18621 and https://github.com/lampepfl/dotty/issues/18622 in the same release

**Comment by bishabosha** [comment]
I rebased to fix the conflict, I'll work on only making only the for-comprehension change, in anticipation of the `checkedCast` SIP if that will occur

**Comment by bishabosha** [comment]
close in favor of #18842

**Pull request closed without merging**
