### PR TITLE
Fix/restore scopes

### PR DESCRIPTION
**Pull request by odersky**
Tentative fix to the "wrong owner" problems we are seeing in ClassfileParser. Review by @darkdimius.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky, I guess you have eclipse that uses an old version of ` scala-compiler` fork, that causes `KeyNotFound`. I believe that's the bug that I have already fixed https://github.com/DarkDimius/scala/commit/f58d45491b3b8b71eeafe7738889e2756113947d 

Can you please check? The version that should be currently used is
`"me.d-d" % "scala-compiler" % "2.11.5-20150216-154453-f58d45491b"`

**Comment by odersky** [comment]
That's probably it. How do I update to the new fork?

**Comment by DarkDimius** [comment]
I'm not sure, as I use sbt to build the project.
If your project is imported from sbt, I guess you can reimport.
If you have it set up by hand: replace the scala-compiler that it depends on currently by https://oss.sonatype.org/content/repositories/releases/me/d-d/scala-compiler/2.11.5-20150216-154453-f58d45491b/scala-compiler-2.11.5-20150216-154453-f58d45491b.jar

**Comment by odersky** [comment]
Suoerseded by #420

**Pull request closed without merging**
