### PR TITLE
Fix #8569: Better error message for erroneous creator applications

### LINKED ISSUE #8569: Creator application with unstable prefix should either work or produce a better error message
```Scala
class Outer(x: Int) {
  class Inner(y: Int) {
  }
}
object Test {
  def outer = Outer(1)
  
  outer.Inner(2) // error: value Inner is not a member of Outer
  new outer.Inner(2) // error: (Test.outer : => Outer) is not stable
}
```
The error message when using the creator application syntax is unhelpful, one has to know about `new` to find the real problem. It'd be better if the error also mentioned the unstable prefix, it'd be even nicer if the message explained how to solve the problem (Scala beginners don't know what "stable" means). But we could just avoid the error in the first place by having the compiler stabilize the prefix itself. Forcing the user to do it manually doesn't seem particularly useful, and it makes for weird-looking code ("why did you create a val that is used only once here ?").

### PR DESCRIPTION
**Pull request by odersky**
Don't just fall-back to say "not a member".

### CODE REVIEW

**Comment by odersky** [comment]
Based on #8583

**Comment by odersky** [comment]
I considered auto-stabilization, but in the end did not follow through. The problem is that you might generate a temporary variable that then gives a mysterious error message when you need to apply avoidance later. Also, it works only in some cases. I.e. works for new, but not for other types or class parents. 

I believe the issue is best discussed separately. If we talk about auto-stabilization, we should also consider paths in patterns and in imports.

**Comment by liufengyun** [comment]
This PR creates significant performance regression.

http://dotty-bench.epfl.ch/

**Comment by odersky** [comment]
Wow, that's amazing. I guess it's because it's forcing error message contents to see what's in it.

**Pull request merged**
