### PR TITLE
[DRAFT] Allow customisation of metaprogramming via scalac flags

### LINKED ISSUE #12038: Allow customisation of metaprogramming via scalac flags
This issue is to allow `inline` code to customise its output based on user-defined settings provided as scalac flags.

# Background

Full detail here: https://contributors.scala-lang.org/t/metaprogramming-configurability/4961

This issue is the first part of the solution I proposed above.

# Proposal

*Disclaimer: the names used below are just drafts and still need some good bikeshedding.*

* Add a new scalac flag that takes a `-E:key=value` (similar to how java accepts `-Dkey=value` args)
* Add `transparent inline def envGet(inline key: String): Option[String]` to `scala.compiletime`
  that provides access to the settings specified with above scalac flags

# Usage Example

The very first example in [the inlining doc](https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html) is a logger that can be configured at compile-time, and is "zero-cost" (as they say) at runtime.
* when `logging = true` then calls to `log()` generate `println` statements
* when `logging = false` then calls to `log()` generate nothing
* there is never a logging-config check at runtime

Currently, the problems with this are
1) `Logger` and its `Config` are static, and changing the setting is a code change
2) `Config` must be pre-configured and defined alongside `Logger` (else `Logger` wouldn't compile)
3) If `Logger` were a library, downstream users would have no way of configuring it

If this issue were implemented, our zero-cost-ish `Logger` could be written like this below, to accept a `"myLogger.level"` setting that downstream users can populate:

```scala
import scala.compiletime.*

object Logging {
  private inline val Trace = 0
  private inline val Debug = 1
  private inline val Info  = 2
  private inline val Warn  = 3

  private transparent inline def chosenThreshold: Int =
    inline envGet("myLogger.level") match
      case Some("TRACE") => Trace
      case Some("DEBUG") => Debug
      case Some("INFO")  => Info
      case Some("WARN")  => Warn
      case None          => Warn // let's provide a default out-of-the-box
      case Some(x)       => error("Unsupported logging level: " + x)

  private inline def log(inline lvl: Int, inline msg: String): Unit =
    inline if lvl >= chosenThreshold then println(msg) else ()

  // This is the public API
  inline def trace(inline msg: String) = log(Trace, msg)
  inline def debug(inline msg: String) = log(Debug, msg)
  inline def info (inline msg: String) = log(Info , msg)
  inline def warn (inline msg: String) = log(Warn , msg)
}
```

And then a downstream user could specify `-E:myLogger.level=INFO` in their scalac flags so that our toy logging library effectively becomes this for them:

```scala
object Logging {
  inline def trace(inline msg: String) = ()
  inline def debug(inline msg: String) = ()
  inline def info (inline msg: String) = println(msg)
  inline def warn (inline msg: String) = println(msg)
}
```

Reconsidering the three problems above, with this new solution:
1) `Logger` can now be configured dynamically, and via config (no code changes required)
2) `Config` is no longer necessary. Whether the library author wants to provide it and/or defaults is now something under their control.
3) Downstream users can now configure the behaviour of `Logger`

# PR?

I'm not asking that the busy Scala 3 team take some time out to implement this. This seemed simple enough for me to try implementing it myself and so I have, and it seems to work well! The above logging example is one of the tests and is confirmed to work as excepted.

### PR DESCRIPTION
**Pull request by japgolly**
Fixes #12038

*Disclaimer: the names used are just drafts and still need some good bikeshedding, and some parts of this need some tidying up. This PR is currently for feedback.*

### CODE REVIEW

**Comment by bishabosha** [comment]
Hi @japgolly, do you plan to work any more on this?, we are trying to clean up open PR

**Comment by japgolly** [comment]
@bishabosha @nicolasstucki Conditionally, yes!

Let me give some context: After raising this I thought I might be able to implement this as a compiler plugin instead. I made some progress in https://github.com/japgolly/ctenv but ended up stopping because it just seemed way too hard because a plugin can't intercept the calls at the ideal time/phase. Instead it became a huge hackfest where I retrospectively tried to patch generated ASTs and ultimately it's just not feasible. You can partially get it working a simple cases but it's super brittle and impossible to have it work reliably.

OTOH, this implementation here was super easy. It would be great to pick this up again, and I'm conditionally willing to update and maintain the PR to get it merged. The reason I say conditionally is that I don't wont to get more invested and spend lots of effort only for this to end up in the bin so I think the first step would be to discover whether or not this would really be accepted. I love to get the concept approved in some form before working further on the implementation.

I think @nicolasstucki (or was it @bishabosha?) had some concerns about the impact on tasty. So if code is compiled with scalac flags specifying `a=1` and then is used downstream with a scalac flags specifying `a=2`, what should happen? Should `a=2` take effect and result in different code when using the tasty generated with `a=1`? I think this isn't a problem for tasty itself because we're talking about inlined bodies which aren't expanded until concrete use anyway. In cases where one wouldn't want `a=2` to override `a=1` I could extend the syntax to make it specifiable. Are there any other concerns that would need to be addressed before approving the spirit of this feature? Or maybe put another way, what would it take to get this or a similar feature approved?

**Comment by japgolly** [comment]
Oh, other potential concerns:
* should the env/flags themselves be stored in tasty?
* if `a` isn't overridden downstream, should the `a=1` still be available via tasty? What about diamond problems?

It seems to me that the compile-time env should only persist for the current compilation phase, and not be transitive. I don't foresee any problems with that and it would be a much simpler design, but would love to hear any counter points of view.

**Comment by neko-kai** [comment]
Lack of `-Xmacro-settings` (I'm probably biased towards keeping the existing name and API from Scala 2, rather than renaming to `-E`) is currently one of the blockers for porting [Izumi](https://github.com/7mind/izumi) libraries, since we heavy rely on them to provide build information for self-reporting in libraries and applications.

Regarding reproducibilty: Reading from environment is a side effect; side-effecting macros cannot be and aren't meant to be reproducible - instead they are used for their side effects, which by design may differ in each build. I hope that's not a deal breaker for Tasty recompilation – before I assumed that applied macros would be expanded to their resulting tasty trees and wouldn't have to be re-executed for recompilation – requiring re-execution would impose a lack of side effects on macros which would be a heavy restriction to work with.

**Comment by rssh** [comment]
I moved the @japgolly  test case from here into #14234 (merged in),  so this issue can be closed as implemented.

**Pull request closed without merging**
