### PR TITLE
Remove separate compilation tests for pickling blacklist

### PR DESCRIPTION
**Pull request by nicolasstucki**
Adding new separate compilation is quite annoying because we have to add them all to the pickling blacklist. Moving separate compilation tests to their own folder fixes this issue.

### CODE REVIEW

**Comment by smarter** [comment]
Why do all separate compilation tests need to be in the pickling blacklist?

**Comment by allanrenucci** [comment]
> Why do all separate compilation tests need to be in the pickling blacklist?

IIRC pickling tests stop after pickling, so separate compilation cannot work since the first compilation does not produce anything

**Comment by smarter** [comment]
If we get them to output .tasty files that should be enough to get separate compilation working (possibly with some extra stuff from my parallel Dotty PR where I rely on that, cant remember)

**Comment by OlivierBlanvillain** [comment]
:+1:

**Comment by nicolasstucki** [comment]
When we get the extra stuff from the parallel PR in we can just move back this files to `run` and `pos`

**Comment by nicolasstucki** [comment]
Rebased

**Pull request merged**
