### PR TITLE
 Refactor gadt state, without using composition for ConstraintHandling

### PR DESCRIPTION
**Pull request by abgruszecki**

### CODE REVIEW

**Comment by AleksanderBG** [comment]
@odersky can you review? This PR splits `GadtConstraint` into `GadtState` and `GadtConstraintHandling` (like you asked), mimicking the split between `TyperState` and `ConstraintHandling`. It also gets rid of `AbstractContext` of `ConstraintHandling` that was necessary for the pre-refactor code.

**Comment by AleksanderBG** [comment]
@odersky alright, now it should be ready.

**Comment by odersky** [comment]
@abgruszecki I see this got left behind. (I mostly look at PRs only if they are assigned to me). Do you want to revive this?

**Comment by abgruszecki** [comment]
Yeah, it'd be good to get it merged before RC1. I'll find the time for it.

**Pull request closed without merging**
