### PR TITLE
Fix #5224: Make implicit shadowing conform to the rules in the spec

### LINKED ISSUE #5224: Scala 2/Dotty difference in implicit shadowing behaviour
Scala 2 and Dotty compile the following example differently,

```scala
object Test {
  class Foo
  class Bar[T]
  class Baz[T] extends Bar[T]

  implicit def foo(implicit bar: Bar[Int]): Foo = ???
  implicit def barInt: Bar[Int] = ???
  implicit def bar[T]: Bar[T] = ???

  implicitly[Foo] // outer

  {
    def barInt: Unit = ???

    implicitly[Foo] // inner
  }
}
```
Dotty selects the `barInt` instance in both the outer and the inner cases. Scala 2 selects the `barInt` instance in the outer case, and the `bar[T]` instance in the inner case due to shadowing by the inner non-implicit definition of `barInt`.

It's not clear to me whether or not this is intentional; or a bug due to the inner context reusing the outer implicit cache without recognizing that the inner non-implicit definition requires the eligible set to be recomputed for the inner scope.

### PR DESCRIPTION
**Pull request by odersky**
The previous version of implicit shadowing considered a nested reference
as a shadow _only_ if it matched the prototype of the implicit search.
This is not backed up by the spec, and is different to what scalac does.
Arguably, the spec is right here: We should consider an implicit ineligible
if it is not visible as a simple name because a nested reference has the
same name, no matter what the type of the nested reference is.

### CODE REVIEW

**Comment by odersky** [comment]
```
object Test {
  class Foo
  implicit def foo: Foo = ???
  {
    def foo = ???
    implicitly[Foo]  // outer foo is shadowed
  }
```
This should not compile, since the rules say "implicits are eligible if they can be referred to by a simple identifier". That's not the case in this example.

**Comment by milessabin** [comment]
FWIW, it compiles both with Dotty prior to this PR _and_ Scala 2.13.x.

**Comment by milessabin** [comment]
I'd like to play around with this a bit ... I was digging around here because I had a hunch that shadowing might interact badly with your implicit caching strategy. I wasn't able to come up with a problematic case for caching because, prior to this PR, eligible implicits more or less only increased monotonically with more nested scopes. Now that shadowing can knock out arbitrary implicit definitions in outer scopes I think it might be possible to trick the caching mechanism into miscompiling.

**Comment by milessabin** [comment]
@odersky that example still compiles after this PR.

The issue is in `computeEligible` ... shadowers are only the inner contexts `ownEligible` which must both be implicit and match the expected type.

**Comment by milessabin** [comment]
Correction, the problem seems to be here: https://github.com/lampepfl/dotty/blob/876fb32f830602e3175eb19bbc043b6079d3c449/compiler/src/dotty/tools/dotc/typer/Implicits.scala#L963-L970

Second time though, `contextual` is false and the candidate which should have been shadowed is allowed through.

**Comment by milessabin** [comment]
Is the issue that contextual implicits are retained in the cache and then found via a cache hit when only the implicit scope should be considered?

**Comment by odersky** [comment]
> Second time though, contextual is false and the candidate which should have been shadowed is allowed through.

That's also as required. Implicits in the implicit scope cannot be shadowed. The rules are:

Contextual implicit: Any implicit value that can be referred to with a simple name qualifies
Type scope implicit: All implicit values in the implicit scope of the required type qualify.

**Comment by milessabin** [comment]
> That's also as required. Implicits in the implicit scope cannot be shadowed.

Understood. But there's no implicit scope in play here.

**Comment by odersky** [comment]
> Understood. But there's no implicit scope in play here.

I think there is: The full type is `Test.Foo`. Since `foo` is in `Test`, it's in the implicit scope.

(Aside: We should try whether we can reduce this aspect of type prefixes contributing to the implicit scope. In the past there have been some abuses where implicits were placed in package prefixes which made their implicit scope surprisingly large. So it might be good if we could at least avoid packages as parts of implicit scopes.)

**Pull request merged**
