### PR TITLE
Scala 2.13.10 (was 2.13.8)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
CI is failure is because API docs haven't published yet. marking as draft until I resolve that.

**Comment by SethTisue** [comment]
community build: JsonMemoryFootprintSpec, in play-json, needs an update

**Comment by SethTisue** [comment]
I've submitted https://github.com/playframework/play-json/pull/813 and hopefully the play-json folks will confirm that there's not some regression

**Comment by SethTisue** [comment]
The play-json folks say it's good/expected. I've pushed the fix to dotty-staging.

**Comment by SethTisue** [comment]
One reason to fast-track this, that I should have mentioned earlier, is the `LazyList` deserialization CVE on 2.13.8 (and all earlier 2.13.0 versions). In practice, I doubt many users are truly affected by it. But in practice, many shops don't really analyze the contents of CVEs — any CVE is considered a big red flag.

**Review by Kordyjan — APPROVED** [review]

**Pull request merged**
