### PR TITLE
Compile from Tasty

### PR DESCRIPTION
**Pull request by odersky**
New compiler main module: FromTasty.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky is it ready to be tested? 
If yes, can you please add several tests?

**Comment by odersky** [comment]
That depends whether macros are expanded before or after pickling. Either is possible IMO.

**Comment by odersky** [comment]
Currently, we can only test classes, not objects. The problem is that the backend puts the TASTY information in the wrong file. For a top-level object like Labels, it should be put in Labels.class, but it is put in Labels$.class. @DarkDimius can you add a commit for this?

**Comment by xeno-by** [comment]
@DarkDimius What would you prefer? Before or after pickling? Expanding before would allow to report errors early.

**Comment by DarkDimius** [comment]
> @DarkDimius can you add a commit for this?

Ok, I will.

**Comment by odersky** [comment]
Usage information is in FromTasty. I have not got around to write test infrastructure for this. Essentially you need to compile first a Scala file, then call FromTasty with the output directory on the classpath. 

Currently tested that this works: In directory pickling (where classes needs to be on the classpath):

   dotc -d classes Coder
   java dotty.tools.dotc.FromTasty Coder

succeeds with 6 warnings.

   dotc extmethods.scala 
   java dotty.tools.dotc.FromTasty extMethods.T

succeeds.

@vladimirnik Can you try some other files and add tests to tests.scala?

**Comment by odersky** [comment]
@xeno-by Early or late is actuallu not so much of a concern. The normal compiler will anyway immediately proceed after pickling, so expansion will happen anyway then. It's more a question
of not having to redo expansions in (non-inline) library modules. 

And I think that settles it: We do not want to be forced to touch trees of dependencies except for their top-level symbols. the linker will read them, but that should be optional. So We will need to cope with multi-source units.

**Comment by DarkDimius** [comment]
> Before or after pickling? Expanding before would allow to report errors early.

That's a hard question. As `inline` redoes overload resolution, than `inline` has new particularities with separate compilation. In order to have more `inline` methods discovered, we would want to perform `inline` expansion as late as possible. 
But from linker perspective, if macros or inline are not expanded - it cannot save any information about the trees, and will need to read whole world.

**Comment by xeno-by** [comment]
Actually, that's something that I wanted to discuss. Can we revisit the point of inline redoing overload resolution? I'm afraid that it might cause problems later on and this is one of the examples. @odersky, are we open to alternatives?

**Comment by VladimirNik** [comment]
@odersky Yes, I'll try other tests.

**Comment by VladimirNik** [comment]
I tried to run FromTasty with ```Coder``` and ```extmethods```, and in my environment it fails for both of the test files.

I tried to use FromTasty with simplified example (based on Coder) and it works:

```scala
class mytest {
  private val mnemonics = Map('2' -> "ABC")
  val str = "abc"
}
```

If modify example:

```scala
class mytest {
  private val mnemonics = Map('2' -> "ABC")
  val str = "abc"
  for ((digit, str) <- mnemonics; ltr <- str ) {}
}
```

it fails with:

```shell
error lambda lifting Simple(mytest.scala): value x22 is not visible from <none>
error lambda lifting Simple(mytest.scala): value x22 is not visible from class mytest
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2()
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2().asInstanceOf
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2().asInstanceOf[String]
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing val str: String = x22._2().asInstanceOf[String]
dotty.tools.dotc.transform.LambdaLift$NoPath while traversing {
  val str: String = x22._2().asInstanceOf[String]
  {
    augmentString(str).foreach({
      def $anonfun(ltr: Char): Unit = {
        ()
      }
      closure($anonfun)
    })
  }
}
...
...
Exception in thread "main" dotty.tools.dotc.transform.LambdaLift$NoPath
	at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.dotty$tools$dotc$transform$LambdaLift$LambdaLifter$$markFree(LambdaLift.scala:148)
	at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.dotty$tools$dotc$transform$LambdaLift$LambdaLifter$$markFree(LambdaLift.scala:155)
	at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:204)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:827)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:820)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1198)
	at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:221)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:827)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:820)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1204)
	at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:221)
```

In this case it seems that the problem is with the usage of ```str``` inside fo.

Also it seems that ```FromTasty``` modifies .class files (remove TASTY attribute). If try to run FromTasty second time on the same class (that was successfully pickled/unpickled), there is an error:

```shell
error: class mytest cannot be unpickled because its class file ./mytest.class does not have a TASTY attribute.
```

**Comment by odersky** [comment]
Did you run with -Ycheck:frontend? That would likely tell you of errors
before they reach pickling.

On Thu, Apr 30, 2015 at 4:03 AM, Vladimir Nikolaev <notifications@github.com
> wrote:

> I tried to run FromTasty with Coder and extmethods, and in my environment
> it fails for both of the test files.
>
> I tried to use FromTasty with simplified example (based on Coder) and it
> works:
>
> class mytest {
>   private val mnemonics = Map('2' -> "ABC")
>   val str = "abc"
> }
>
> If modify example:
>
> class mytest {
>   private val mnemonics = Map('2' -> "ABC")
>   val str = "abc"
>   for ((digit, str) <- mnemonics; ltr <- str ) {}
> }
>
> it fails with:
>
> error lambda lifting Simple(mytest.scala): value x22 is not visible from <none>
> error lambda lifting Simple(mytest.scala): value x22 is not visible from class mytest
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2()
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2().asInstanceOf
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing x22._2().asInstanceOf[String]
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing val str: String = x22._2().asInstanceOf[String]
> dotty.tools.dotc.transform.LambdaLift$NoPath while traversing {
>   val str: String = x22._2().asInstanceOf[String]
>   {
>     augmentString(str).foreach({
>       def $anonfun(ltr: Char): Unit = {
>         ()
>       }
>       closure($anonfun)
>     })
>   }
> }
> ...
> ...
> Exception in thread "main" dotty.tools.dotc.transform.LambdaLift$NoPath
>     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.dotty$tools$dotc$transform$LambdaLift$LambdaLifter$$markFree(LambdaLift.scala:148)
>     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.dotty$tools$dotc$transform$LambdaLift$LambdaLifter$$markFree(LambdaLift.scala:155)
>     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:204)
>     at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:827)
>     at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:820)
>     at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1198)
>     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:221)
>     at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:827)
>     at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:820)
>     at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1204)
>     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter$CollectDependencies.traverse(LambdaLift.scala:221)
>
> In this case it seems that the problem is with the usage of str inside fo.
>
> Also it seems that FromTasty modifies .class files (remove TASTY
> attribute). If try to run FromTasty second time on the same class (that was
> successfully pickled/unpickled), there is an error:
>
> error: class mytest cannot be unpickled because its class file ./mytest.class does not have a TASTY attribute.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/507#issuecomment-97633726>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
I'd recommend to run with `-Ycheck:all`.

**Comment by VladimirNik** [comment]
@odersky , @DarkDimius With these options there are no errors.

Other issue is that after the first run of FromTasty, the same, previously correct ```.class file``` can't be unpickled during the second run of FromTasty:

```shell
error: class mytest cannot be unpickled because its class file ./mytest.class does not have a TASTY attribute.
```

**Comment by odersky** [comment]
> @odersky , @DarkDimius With these options there are no errors.

Wow. Need to investigate.

> Other issue is that after the first run of FromTasty, the same, previously correct .class file can't be
> unpickled during the second run of FromTasty:

That will be hard to fix. I recommend to run FromTasty with an output directory that does not override the classpath. Let's also add a comment to FromTasty's docs that clarifies this point.

**Comment by odersky** [comment]
@VladimirNik The problem should be fixed now.

**Comment by odersky** [comment]
Should we merge this? It will help @VladimirNik progress.

**Pull request merged**
