### PR TITLE
Fix issue #17465

### PR DESCRIPTION
**Pull request by hamzaremmal**
Fix issue #17465

### CODE REVIEW

**Comment by Linyxus** [comment]
test performance please

**Comment by nicolasstucki** [comment]
What is the status of this PR? Did this fix work? Were there concerns about performance?

@mbovel what is the status of the benchmarking bot/machine?

The PR is missing a test for https://github.com/lampepfl/dotty/issues/17465.

**Comment by mbovel** [comment]
test performance please

**Comment by Linyxus** [comment]
Duplicate of #18213.

**Comment by mbovel** [comment]
test performance please

**Comment by mbovel** [comment]
(I know this PR won't be merged, but I am testing the benchmarks bot again. Not sure why it did not work last time.)

**Comment by mbovel** [comment]
Oh, well, seems to work now.

**Pull request closed without merging**
