### PR TITLE
Add 0.17.0-RC1 blog post

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@nicolasstucki does the macro section look good?

@nicolasstucki @alemannosara do you think we can mention the f-interpolator? Do we have the docs for it somewhere?

**Comment by nicolasstucki** [comment]
Macro section looks good

**Comment by nicolasstucki** [comment]
We can mention `f` interpolators. We do not have docs, the change is that now all the compile-time checks that scala2 did are implemented as a macro in dotty.

**Comment by anatoliykmetyuk** [comment]
Can you please elaborate on what I should write about it?

**Comment by nicolasstucki** [comment]
I think it is enough to state the we fully implemented the `f` interpolator as a macro. We can also add this link https://docs.scala-lang.org/overviews/core/string-interpolation.html#the-f-interpolator

**Comment by anatoliykmetyuk** [comment]
If everyone's fine with the article, I'll merge it tomorrow

**Pull request merged**
