### PR TITLE
fix #10997: check accessible from sealed parent not companion

### LINKED ISSUE #10997: Mirror.Sum not synthesised for base class without companion
## Minimized code

```Scala
class Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  
  println(summon[Mirror.Of[Role]])
}
```

## Output

```scala
// no implicit argument of type deriving.Mirror.Of[Test.this.Role] was found for parameter x of method summon in object Predef
```

## Expectation

It should be able to derive the mirror as if it was inside the companion object.

```scala
object Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  
  println(summon[Mirror.Of[Role]])
}
```

I found this while I was port play-json to dotty (https://github.com/playframework/play-json/pull/555/files).

### PR DESCRIPTION
**Pull request by bishabosha**
fixes #10997 

given the commit https://github.com/lampepfl/dotty/commit/275a0a96bdb1f28300ca8e0f045226e1e99b3df1 I am unclear why the accessibilty test in `whyNotGenericSum` needs to check for the companion.

I believe that it was a lucky coincidence that `whyNotGenericSum` passes for traits without a companion, i.e. if you trace the owners of any definition up to the root package then eventually you get the owner `NoSymbol`, which then succeeds in the case there is no companion, which breaks the criterion "all of its children are addressable through a path from its companion object".

The motivation for the change in this PR is that we use `whyNotGenericSum` to implement `isGenericSum`. Then `isGenericSum` is used by `Synthesizer.sumMirror` to decide if something gets a synthesized `Mirror.Sum`. 

Since `Synthesizer.sumMirror` still generates a mirror even if there is no companion, I can not see a reason to fail `whyNotGenericSum` if there is no companion.

### CODE REVIEW

**Review by odersky — CHANGES_REQUESTED** [review]
What about the `fromProduct` method? That is not generated if there is no companion, right? How does that manifest itself?

We probably should have a test involving fromProduct

**Comment by bishabosha** [comment]
> What about the `fromProduct` method? That is not generated if there is no companion, right? How does that manifest itself?
> 
> We probably should have a test involving fromProduct

I have added a test using `ordinal`, and `fromProduct` but there should be no change in behaviour for `fromProduct` as it is only generated on `Mirror.Product`, which is not affected by this change.

**Comment by bishabosha** [comment]
I have found a case which causes a crash, which is requesting the synthetic anonymous mirror outside the scope of the wrapper class:
```scala
class ClassWrapper {
  sealed trait Parent
  case class Foo(x: Int, y: Int, s: String) extends Parent
}

@main def Test =
  val cw = new ClassWrapper()
  val mirrorParent = summon[deriving.Mirror.Of[cw.Parent]]
```

**Comment by bishabosha** [comment]
I have added a test to check that the mirror can also access the children if it is an anonymous class

**Review by odersky — CHANGES_REQUESTED** [review]
So, the downside of not having a companion is that everytime you demand a mirror a new object is created, right? Which means a new class is generated per call site, and an object per dynamic call.

I think that's a serious degradation that is not at all obvious. So at least we should have a warning that this happens and an encouragement to create a companion object. 

Typeclass derivation libraries often need to be high-performance, so we should make users aware of the trap.

**Comment by bishabosha** [comment]
> I think that's a serious degradation that is not at all obvious. So at least we should have a warning that this happens and an encouragement to create a companion object.

Should this warning be for all anonymous mirrors (i.e. including mirrors for Scala 2 types) or just the ones for types in Scala 3.

I would assume probably avoid noise for Scala 2 types

**Comment by bishabosha** [comment]
adding the warning is breaking shapeless though with an unrelated error

**Comment by odersky** [comment]
I think I misunderstood two cases. If a trait has a derived clause 
```scala
sealed trait T derives C
```
it gets a companion automatically. That's the case I was after. If we summon a mirror outside, we should be prepared that an anonymous class is created. So I think we can just revert the last commit and drop the warning. Sorry for the confusion!

**Comment by bishabosha** [comment]
I have reverted the changes to add the warning

**Comment by bishabosha** [comment]
the problem in shapeless was that it had fatal warnings turned on which suppressed the error for summoning an anonymous Mirror in favour of Implicit not found error

**Pull request merged**
