### PR TITLE
Scala 2.13.12 (was 2.13.10)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
I would add the missing MiMa filter for `MapNodeRemoveAllSetNodeIterator.next` [MiMaFilters.scala](https://github.com/lampepfl/dotty/blob/main/project/MiMaFilters.scala) `StdlibBootstrappedBackwards` or `StdlibBootstrappedForward`. It it seems to be another case where the inferred type is not the same. To solution will be to set this type explicitly in Scala `2.13`.

```
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.MapNodeRemoveAllSetNodeIterator.next")
```

**Comment by nicolasstucki** [comment]
Maybe we can also remove https://github.com/lampepfl/dotty/blob/main/project/TastyMiMaFilters.scala#L45-L47

**Comment by SethTisue** [comment]
@nicolasstucki will do

and while I've got your attention, I just noticed that 3.3.1 ships with 2.13.10 stdlib. this is unfortunate — 2.13.11 came out months ago. will this PR fix it for 3.3.2, if I add the "backport requested" label? @Kordyjan maybe you could add this to the Scala 3 release steps, to check that you aren't shipping an out of date Scala 2 stdlib?

**Comment by SethTisue** [comment]
We have binary compatibility checks in the scala/scala repo, so I believe that should be considered sufficient assurance. All of the 2.13.x stdlibs are known to be both forward and backward compatible with each other.

**Comment by SethTisue** [comment]
> solution will be to set this type explicitly in Scala 2.13

agree. PR: https://github.com/scala/scala/pull/10549

**Comment by SethTisue** [comment]
> Maybe we can also remove [main/project/TastyMiMaFilters.scala#L45-L47](https://github.com/lampepfl/dotty/blob/main/project/TastyMiMaFilters.scala?rgh-link-date=2023-09-07T15%3A48%3A42Z#L45-L47)

Not yet, I don't think, since we're jumping straight from 2.13.10 to 2.13.12 here. (I've changed the PR title to make that more obvious.)

**Comment by SethTisue** [comment]
@nicolasstucki this is ready for you to take a second look at

**Review by nicolasstucki — APPROVED** [review]

**Pull request merged**
