### PR TITLE
Fix #10085: check if enum case confirms to scrutinee type

### LINKED ISSUE #9190: Exhaustivity checking on union types within product types is too restrictive
Exhaustivity checking in pattern matching on union types within product types seems to be too restrictive. This might be caused or reinforced by indirection through type aliases as it does not happen for `testee3` (see below).

## Minimized code

dotty version `0.25.0-RC1`

```Scala
  case object X; type X = X.type
  case object Y; type Y = Y.type

  type XorY = X | Y

  val testee1: XorY = X
  testee1 match {
    case value: XorY => println(value)
  }

  val testee2: Tuple1[XorY] = Tuple1(X)
  testee2 match {
    case Tuple1(value: XorY) => println(value)
  }

  type IntOrString = Int | String

  val testee3: Tuple1[IntOrString] = Tuple1(42)
  testee3 match {
    case Tuple1(value: IntOrString) => println(value)
  }
```

## Output

```
[warn]    |  testee2 match {
[warn]    |  ^^^^^^^
[warn]    |  match may not be exhaustive.
[warn]    |
[warn]    |  It would fail on pattern case: (_)
[warn] one warning found
```

## Expectation

The compiler should understand that the match must be exhaustive and not give a warning.

### LINKED ISSUE #10085: Simple GADT giving "match may not be exhaustive"
## Minimized code

```Scala
enum Bool:
  case True
  case False

import Bool._

enum SBool[B <: Bool]:
  case STrue extends SBool[True.type]
  case SFalse extends SBool[False.type]

import SBool._

def f(b: SBool[True.type]): Unit = b match
  case STrue => ()
```
https://scastie.scala-lang.org/sFyhkz0wRg2Uvtl9GE37dQ

## Output

```scala
match may not be exhaustive.

It would fail on pattern case: SFalse
```

## Expectation
I would expect `f` to be exhaustive because from the type parameter we can know that `SFalse` cannot occur. Is this a limitation of Dotty or a bug?

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10085: check if enum case confirms to scrutinee type
Fix #9190: infer union types

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Comment by smarter** [comment]
The latest commit in this PR is:

>  Fix CI: add facility to infer union and singleton types
- infer singleton types: tests/patmat/i4227.scala
- infer union types: tests/patmat/i9190.scala

- I checked out the previous commit and tried `scala3-compiler/testOnly *PatmatExhaustivityTest` and no test failed, how can I reproduce the problem?
-  tests/patmat/i9190.scala doesn't exist

**Comment by liufengyun** [comment]
> The latest commit in this PR is:
> 
> > Fix CI: add facility to infer union and singleton types
> > 
> > * infer singleton types: tests/patmat/i4227.scala
> > * infer union types: tests/patmat/i9190.scala
> 
> * I checked out the previous commit and tried `scala3-compiler/testOnly *PatmatExhaustivityTest` and no test failed, how can I reproduce the problem?

You can try `testOnly -- *.patmatExhaustivity`.

> * tests/patmat/i9190.scala doesn't exist

Good catch, it's now added.

**Comment by smarter** [comment]
> You can try testOnly -- *.patmatExhaustivity.

I think that runs the same set of tests, anyway I tried it and I still don't get any error on commit https://github.com/lampepfl/dotty/pull/10094/commits/149d4de244af4aafd4502e13a8ec8770fcacf4b0, (I do get an error for i9190 if I add it manually, but nothing for i4227)

**Comment by liufengyun** [comment]
> > You can try testOnly -- *.patmatExhaustivity.
> 
> I think that runs the same set of tests, anyway I tried it and I still don't get any error on commit [149d4de](https://github.com/lampepfl/dotty/commit/149d4de244af4aafd4502e13a8ec8770fcacf4b0), (I do get an error for i9190 if I add it manually, but nothing for i4227)

For `i4227`, we only get an error if we remove the following lines (removed in the 2nd commit):

``` scala
          // force type inference to infer a narrower type: could be singleton
          // see tests/patmat/i4227.scala
          mt.paramInfos(0) <:< scrutineeTp
```

The code was there just to make type inference infer a singleton type.

**Comment by smarter** [comment]
I see, thanks. I was surprised that `mt.paramInfos(0) <:< scrutineeTp` didn't work for the union case, so I investigated and found that this was caused by a bug for which I made a PR: https://github.com/lampepfl/dotty/pull/10106. Once this is merged we shouldn't need https://github.com/lampepfl/dotty/pull/10094/commits/c245d33679d6206e6303be2fbb76e90b014e2894 (we can separately discuss if this is still useful, but it wouldn't be needed for this PR).

**Comment by liufengyun** [comment]
> I see, thanks. I was surprised that `mt.paramInfos(0) <:< scrutineeTp` didn't work for the union case, so I investigated and found that this was caused by a bug for which I made a PR: #10106. Once this is merged we shouldn't need [c245d33](https://github.com/lampepfl/dotty/commit/c245d33679d6206e6303be2fbb76e90b014e2894) (we can separately discuss if this is still useful, but it wouldn't be needed for this PR).

Thanks for going deep into the issue. Once that's merged, I'll rebase and drop the 2nd commit for now.

**Comment by smarter** [comment]
> rebase and drop the 2nd commit for now.

Done.

**Review by smarter — APPROVED** [review]

**Comment by liufengyun** [comment]
> > rebase and drop the 2nd commit for now.
> 
> Done.

Thanks, I also pushed some simplifications from the 2nd commit in 6a9c4ea.

**Pull request merged**
