### PR TITLE
Refcatorings in TASTy reflection interface

### PR DESCRIPTION
**Pull request by nicolasstucki**
This PR focuse on refactorings that have been on hold to avoid rebasing other PRs. Now is a good moment to do it as other PRs won't be too hard to rebase on this.
- Rename the reflection API from `tasty.Tasty` to `tasty.Reflection`
- Rename `toTasty/toExpr` (quoted to tasty trees / tasty trees to quoted) to relfect/reify in the `tasty.Reflection` interface
- Rename `Show` to `Printer`
- Add `showCode` to tasty trees 
- Refactor `util.{TreeAcumulator, TreeTraverser}` to not need and explicit singleton type parameter (`[T <: Tasty with Singleton](tasty: T)`). Move them inside `tasty.Reflection`.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
`Reflection` feels like a good name for the reflection API.

**Comment by nicolasstucki** [comment]
What would be simpler than `ReflectionCore`?

**Comment by liufengyun** [comment]
@nicolasstucki I was thinking something like `Types` or  just `Core`. But as this is just an internal name, it does not matter much.

**Comment by nicolasstucki** [comment]
`Types` would get confused with the part that has the extractors for `Type`s. Core is good, I will shorten it.

**Comment by nicolasstucki** [comment]
Rebased

**Comment by nicolasstucki** [comment]
Fix conflicts after rebase

**Comment by nicolasstucki** [comment]
To simplify rebasing, we should merge this one before #5416, #5388 and any new PR using TASTy reflect.

**Comment by nicolasstucki** [comment]
I should merge this before the meeting to get unblocked. WDYT @liufengyun. If needed we can rename methods later.

**Comment by nicolasstucki** [comment]
FYI people seem to be familiar with the `reflect`/`reify` names because of all the keynotes @odersky presented with this notation.

**Pull request merged**
