### PR TITLE
Experiment: cache symHelpers

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance please

**Comment by smarter** [comment]
A better approach I think would be to make SymHelper a value class.

**Comment by smarter** [comment]
Ah, but I guess that won't help in the backend where we use the abstract `SymbolHelper`.

**Comment by nicolasstucki** [comment]
This change reduces the allocations of `symHelper` from 14373196 to 320878 when doing `sbt ;dotty-bootstrapped/clean;dotty-bootstrapped/compile`.

**Comment by nicolasstucki** [comment]
All those objects were probably GCd in the young generation.

**Comment by nicolasstucki** [comment]
It did not show any improvement on performance

**Pull request closed without merging**
