### PR TITLE
Remove excluded filters from mima

### PR DESCRIPTION
**Pull request by Kordyjan**

### CODE REVIEW

**Comment by smarter** [comment]
mima is complaining because of new public methods defined inside, but isn't that binary-compatible? (/cc @dwijnand @sjrd). In any case, these traits are all defined inside Quotes which users are not supposed to inherit (I don't know if this is enforced?), so I think we can ignore those errors.

**Comment by sjrd** [comment]
Ah but they're new *abstract* methods in traits. That's definitely not backward binary compatible. It's only compatible if third-parties cannot extend the trait. For example because they're `sealed`. Or if they have a self type that cannot be fulfilled from the outside. It *looks like* we may be in the latter case, here, but I'm not sure.

**Comment by smarter** [comment]
> Or if they have a self type that cannot be fulfilled from the outside. 

It looks like this isn't enforced, the following compiles:
```scala
import scala.quoted.*

class A extends Quotes with runtime.QuoteUnpickler with runtime.QuoteMatching:
    val ExprMatch: ExprMatchModule = ???
    val TypeMatch: TypeMatchModule = ???
    def unpickleExpr[T](pickled: String | List[String], typeHole: (Int, Seq[Any]) => Type[? <: AnyKind], termHole: (Int, Seq[Any], Quotes) => Expr[?]): Expr[T] = ???
    def unpickleType[T <: AnyKind](pickled: String | List[String], typeHole: (Int, Seq[Any]) => Type[? <: AnyKind], termHole: (Int, Seq[Any], Quotes) => Expr[?]): Type[T] = ???
    extension(self: Expr[Any])
      def asExprOf[X](using Type[X]): Expr[X] = ???
      def isExprOf[X](using Type[X]): Boolean = ???
    val reflect: reflectModule = ???
    extension [T](self: Expr[T])
      def show: String = ???
      def matches(that: Expr[Any]): Boolean = ???
      def valueOrAbort(using FromExpr[T]): T = ???
```

@nicolasstucki Can we make `runtime.QuoteUnpickler` private to prevent people from making instances of Quotes?

**Comment by smarter** [comment]
Though I think we don't give any API/ABI guarantees for scala.runtime so I guess this is fine anyway?

**Comment by sjrd** [comment]
> Though I think we don't give any API/ABI guarantees for scala.runtime so I guess this is fine anyway?

If user-level access to `scala.runtime` is required to extend them, then it's fine indeed. `scala.runtime` is off-limit for user-level code.

**Review by smarter — CHANGES_REQUESTED** [review]
OK, then I think this is fine as-is. @Kordyjan can you re-add the MimaFilters for abstract methods with a note that this is safe because user code is not allowed to inherit Quotes?

**Comment by Kordyjan** [comment]
Done!

**Review by smarter — APPROVED** [review]

**Comment by dwijnand** [comment]
> can you re-add the MimaFilters for abstract methods with a note that this is safe because user code is not allowed to inherit Quotes?

If that's the case we can keep a rule as
`ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.quoted.Quotes#*")`.  I normally comment those with `// KEEP` to make sure they don't get cleared.

**Pull request merged**
