### PR TITLE
Move Reflection to scala.quoted

### PR DESCRIPTION
**Pull request by nicolasstucki**
In theory it should be inside of the QuoteContext but this is blocked by #10253.
We take this first step to cleanup the `scala.tasty` package.

### CODE REVIEW

**Review by romanowski — APPROVED** [review]
scala3doc changes looks ok

**Review by abgruszecki — APPROVED** [review]
These changes look fine, but I suppose we should have a separate discussion about how `qctx` is supposed to be used in paths. That trick looks very fishy.

**Comment by nicolasstucki** [comment]
I'm exploring an alternative to the `qctx` in #10289

**Comment by liufengyun** [comment]
It is a bit weird that this makes many micro-benchmarks slower.

**Comment by nicolasstucki** [comment]
I noticed. Maybe there are more situations where we need to load this class file.

**Pull request merged**
