### PR TITLE
Fix #2663: More refined handling of enum case apply results

### LINKED ISSUE #2663: Type parameter inference broken for parent of an enum case
This works:
```scala
class Foo[T](x: T)
class Bar[T](y: T) extends Foo(y)
```
But this doesn't:
```scala
enum Foo[T](x: T) {
  case Bar[T](y: T) extends Foo(y)
}
```
```scala
-- [E055] Syntax Error: try/parents.scala:2:28 ---------------------------------
2 |  case Bar[T](y: T) extends Foo(y)
  |                            ^^^
  |                            missing type parameter for [Foo$$T] => Foo[T]
```
Manually adding the missing type parameter works:
```scala
enum Foo[T](x: T) {
  case Bar[T](y: T) extends Foo[T](y)
}
```

### PR DESCRIPTION
**Pull request by odersky**
i2663 demonstrates that we do not always have a complete result type
for the `apply` method of an enum case. In that case our only recourse
is to add a generic widening method that upcasts the enum case class to the
enum base class.

### CODE REVIEW

**Comment by liufengyun** [comment]
It doesn't work for the following case:

```Scala
enum Foo[T](x: T) {
  case Bar[S, T](y: T) extends Foo(y)
}
```

While the following compiles without no problem:

```Scala
class Foo[T](x: T)
case class Bar[S, T](y: T) extends Foo(y)
```

**Comment by odersky** [comment]
@liufengyun Excellent catch! This turned out to be an even bigger can of worms than I thought.

**Comment by liufengyun** [comment]
The fix looks good, but I found another related issue about the return type of `apply`:

```Scala
enum Foo[T](x: T) {
  case Bar[S, T](y: T) extends Foo[y.type](y)
}
```

**Comment by odersky** [comment]
That's devious (or clever, depending how you look at it)! It seems to fix this properly we need #3920 to be solved, and it is uncertain whether we will ever get there.

The only quick fix I see is to disallow parameter references in extension clauses of enum cases.

**Comment by odersky** [comment]
Or we leave it as is, and just accept the fact that the enum expansion is not type correct in some cases.

**Comment by odersky** [comment]
I filed a separate issue #3935 to keep track of this.

**Pull request merged**
