### PR TITLE
Port Constant Types for Literal Final Static Java Fields and Implicit Conversions from Scalac 

### PR DESCRIPTION
**Pull request by noti0na1**
Currently, the `ClassParser` will give `ConstantType`s to constant fields, but the `JavaParser` will not, because the `JavaParser` in Dotty doesn’t parse the expressions of fields. This PR ports the parsing literals part from Scalac, so that `ConstantType`s will be assigned to constant Java fields with simple literals.  

SI-3236 constant types for literal final static java fields 
https://github.com/scala/scala/commit/81d2c6185e6c10defcf1f6a25f69e8b2ed025d86 

Support implicit converstions from java literals 
https://github.com/scala/scala/commit/74c613bd45df26c96833d5eecde6de5bb59d1a4f 

This is also useful for the explicit nulls #6344. With this feature, we don’t need to nullify constant fields. 

I am not able to port the test of SI-3236 directly, since the annotation arguments in Dotty can only refers to enum values (in `DottyBackendInterface.emitArgument`)? If I’m wrong, please correct me. 

Edit: The SI-3236 test is now ported.

### CODE REVIEW

**Comment by smarter** [comment]
> I am not able to port the test of SI-3236 directly, since the annotation arguments in Dotty can only refers to enum values (in DottyBackendInterface.emitArgument)?

Not sure I understand, what error are you seeing with that test exactly ?

**Comment by noti0na1** [comment]
@smarter Here is the code which triggers the same error:

`J.java`
```java
import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
public @interface J {
    String value();
}
```

`S.scala`
```scala
object C {
  val cs: String = "cs"
}

object S {
  @J(C.cs)
  def f(): Int = 1
}
```

`dotc J.java S.scala`:
```
Error while emitting S.scala
exception occurred while compiling mytest/annot/S.scala
java.lang.AssertionError: assertion failed: not an enum: C.cs / getter cs / object C / false / final module <touched> while compiling mytest/annot/J.java, mytest/annot/S.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: not an enum: C.cs / getter cs / object C / false / final module <touched>
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitArgument(DottyBackendInterface.scala:261)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAssocs$$anonfun$2(DottyBackendInterface.scala:325)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:891)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAssocs(DottyBackendInterface.scala:325)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAnnotations$$anonfun$4(DottyBackendInterface.scala:335)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:891)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAnnotations(DottyBackendInterface.scala:336)
	at dotty.tools.backend.jvm.BCodeHelpers$BCAnnotGen.emitAnnotations(BCodeHelpers.scala:274)
	at dotty.tools.backend.jvm.BCodeHelpers$JCommonBuilder.emitAnnotations(BCodeHelpers.scala:440)
	at dotty.tools.backend.jvm.BCodeHelpers$BCForwardersGen.addForwarder(BCodeHelpers.scala:342)
	at dotty.tools.backend.jvm.BCodeHelpers$BCForwardersGen.addForwarders$$anonfun$2(BCodeHelpers.scala:393)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.backend.jvm.BCodeHelpers$BCForwardersGen.addForwarders(BCodeHelpers.scala:395)
	at dotty.tools.backend.jvm.BCodeHelpers$JCommonBuilder.addForwarders(BCodeHelpers.scala:440)
	at dotty.tools.backend.jvm.BCodeHelpers$JMirrorBuilder.genMirrorClass(BCodeHelpers.scala:488)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:208)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:184)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:514)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:480)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:51)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:55)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:162)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:172)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:180)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:187)
	at dotty.tools.dotc.Run.compileSources(Run.scala:124)
	at dotty.tools.dotc.Run.compile(Run.scala:107)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by smarter** [comment]
That code emits a "annotation argument is not a constant" in scalac, I've just created a PR to do the same for dotty: https://github.com/lampepfl/dotty/pull/7495

**Comment by noti0na1** [comment]
@smarter Thanks for the crash fix!

However, with this fix, the annotation arguments still cannot be constants.
If we modify the code above: `val cs: String = "cs"` -> `val cs: "cs" = "cs"`, then it can be compiled by scalac but not by dotty. 

That's why I am not able to port the test of SI-3236.

**Comment by smarter** [comment]
OK, I've pushed an extra commit to https://github.com/lampepfl/dotty/pull/7495 which handles this.

**Comment by smarter** [comment]
If you rebase on master you should be able to add these tests now.

**Comment by noti0na1** [comment]
@smarter Thanks, the SI-3236 test is now added.

**Pull request merged**
