### PR TITLE
Change GADT constrainer to consider all parents when upcasting

### PR DESCRIPTION
**Pull request by Linyxus**
test performance please

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Comment by Linyxus** [comment]
Previous commits change the GADT constrainer's behavior by treating the scrutinee type as an and type constituted by all shared base classes in the hierarchy with the pattern type to derive GADT constraints from all possible parents. This avoids considering unrelated candidates, but requires going deep into the inheritance hierarchy. The modification do not seem to greatly deteriorate the performance as seen in the test.

Now an alternative implementation that simply use the direct parents of the scrutinee type to construct the and type is applied. This, in essence, delays the subtype checking afterwards when constraining this and type and the pattern type. Let's see how the performance is influenced.

**Comment by Linyxus** [comment]
test performance please

**Comment by Linyxus** [comment]
test performance please

**Comment by smarter** [comment]
You'll need to make a PR adding your name to the list in https://github.com/lampepfl/bench/blob/55576c7eb30517b09ad71f677f0cc73374f4f979/bin/process#L22 to be able to run the benchmarks /cc @liufengyun

**Comment by smarter** [comment]
test performance please

**Comment by Linyxus** [comment]
> https://github.com/lampepfl/bench/blob/55576c7eb30517b09ad71f677f0cc73374f4f979/bin/process#L22

Thank you!

**Comment by Linyxus** [comment]
The test results in http://dotty-bench.epfl.ch/11447/ seems problematic. The running time for stdlib is zero.

**Comment by Linyxus** [comment]
test performance please

**Comment by Linyxus** [comment]
test performance please

**Pull request closed without merging**
