### PR TITLE
where -> were

### PR DESCRIPTION
**Pull request by danmur**
small typo

### CODE REVIEW

**Comment by danmur** [comment]
I can't find a CLA to sign, but it's such a small thing maybe someone could just make the change and close this :)

**Comment by smarter** [comment]
Here's the link to the CLA: https://www.lightbend.com/contribute/cla/scala

**Comment by biboudis** [comment]
@dotty-bot recheck cla

**Comment by biboudis** [comment]
@danmur every contribution counts ;-). If you sign it, I will merge we can merge.

**Comment by danmur** [comment]
Done!

**Comment by biboudis** [comment]
I confirm CLA is signed. Thx!

**Pull request merged**
