### PR TITLE
Update `scalatest` in community build

### PR DESCRIPTION
**Pull request by nicolasstucki**
[skip test] 
[skip test_windows_fast] 
[skip test_sbt] 
[skip mima] 
[skip docs] 
[skip community_build_b] 
[skip community_build_c]

Some tests were disabled due to failures involving `intercept` of exception. These could be regression in the compiler or a bug in a scalatest macro. 
* https://github.com/dotty-staging/scalatest/commit/6be253c707c33e4ba52dfc464664bf0c2c288be2
* https://github.com/dotty-staging/scalatestplus-testng/compare/ea7aaebfb82098204b2ff3ce5e210c820f95853e...880b829301055bb6176c37ce8199d98d476d6c17#

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@cheeseng could you check if this regression happens on the scalatest main branch using our latest nightly build? We should make sure that this is not something that will affect scalatest before we release 3.3.0.

**Comment by cheeseng** [comment]
@nicolasstucki I'll give it a try and report back here.

**Comment by cheeseng** [comment]
@nicolasstucki I tried to build scalatest's main branch using 3.3.0-RC1-bin-20221205-5cf8a58-NIGHTLY via jdk8, jdk11 and jdk17, seems to work fine.  Did community build failed on jdk16?

**Comment by cheeseng** [comment]
@nicolasstucki I just tested jdk16 and it works fine too, is 3.3.0-RC1-bin-20221205-5cf8a58-NIGHTLY the latest version that I should be testing with?

**Comment by nicolasstucki** [comment]
@cheeseng there are a couple of tests that failed in our build (JDK 8 I believe). I wonder if I pulled the correct scalatest branch into https://github.com/dotty-staging/scalatest/compare/39370e391342eb3d3ecfa847be16734f2fb1f3a2...6be253c707c33e4ba52dfc464664bf0c2c288be2

Otherwise it could be an issue with the patches we have done (https://github.com/scalatest/scalatest/compare/main...dotty-staging:scalatest:patched3). Or it could be an issue with the custom project setting/setup we use for the community build.

**Comment by cheeseng** [comment]
@nicolasstucki I am sorry I missed the notification of your message, I am not sure why branch you pulled, fyi for current stable version 3.2.x we are building it from branch name 3.2.x-new, and the main branch is for our upcoming 3.3.0 release.

I did tried to build the mentioned 2 branches (3.2.x-new and main) with 3.3.0-RC1-bin-20221205-5cf8a58-NIGHTLY, both works.

Do let me know if there's anything I can help in the community build.

**Pull request closed without merging**
