### PR TITLE
Change hk take 2

### PR DESCRIPTION
**Pull request by odersky**
Rebased #731 to master and added some changes to make all tests pass, including the standard collection tests in #787. In retrospect, it would have been good to add this ealier because the fixes
of #779 in #787 were cruder than what is in this PR. In particular, we no longer need to intercept cyclic reference errors.

Review by @DarkDimius or @smarter

### CODE REVIEW

**Comment by odersky** [comment]
Seems the tests are not running?

**Comment by SethTisue** [comment]
I'll look into why Scabot isn't kicking in here.

**Comment by SethTisue** [comment]
it was because the PR includes more than 30 commits, which exceeded the GitHub API's default page size. I fixed Scabot to request a page size of 100 commits (the maximum allowed), and manually started a new Jenkins run: https://scala-ci.typesafe.com/view/dotty/job/dotty-master-validate-main/437/

**Comment by smarter** [comment]
So what happens when we have a PR with 101 commits? :)

**Comment by SethTisue** [comment]
> So what happens when we have a PR with 101 commits

I dare you!

**Comment by DarkDimius** [comment]
Otherwise LGTM, though I do not fully understand all the consequences of this change.
Glad to have `Map.scala` pass.

**Pull request merged**
