### PR TITLE
Try to refine handling of SymDenotations V2

### PR DESCRIPTION
**Pull request by odersky**
It seems we get many cache misses when going from Symbols to their denotations. This is a very common operation: When compiling typer/*.scala, we generate ~80K symbols, ~125K SymDenotations, yet dereference .denot more than 15.8M times. Of these, 11.7M go to the symbol's initial denotation.

After closing #4504, this PR tries something else: Cache the hottests fields of denotations
in symbols, so that we can get at them without a dereference. 

We don't need to introduce forwarders in Symbols to do this (although it might be a good idea for other reasons), and we don't need to have Symbol inherit from SymDenotation (which has proven to be a bad idea).

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Current status: Symbol.denot calls reduced from 15.8M to 6.4M when compiling typers/*.scala

**Comment by smarter** [comment]
> The previous performance test have a 404. What could be the reason for this?

This happens randomly sometimes, I don't know if @liufengyun knows the root cause, but the workaround is to add index.html at the end: http://dotty-bench.epfl.ch/4512/index.html

**Comment by odersky** [comment]
Rebased to master

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by allanrenucci** [comment]
There is probably some rebase breakage

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
The performance failure is fixed, the result is here: http://dotty-bench.epfl.ch/4512

**Comment by odersky** [comment]
So it seems there's a significant speedup for dotty itself (about 3% according to latest benchmark), and no speedups for the other tests. I'll run one more test, and then we can decide what to do with this.

**Comment by odersky** [comment]
test performance please

**Comment by allanrenucci** [comment]
I see a non negligible slow down for scalap and re2.

Isn't the speedup on Dotty legitimate? My guess is that the speedup comes from the changes in the Dotty code base and not from a faster compiler . By adding all the cached SymDenotation facades to `Symbol`, you significantly reduce the number of implicit conversions from `Symbol` to `SymDenotation`.

**Comment by odersky** [comment]
No clear win, except for dotty. Let's cherry-pick any improvements that make sense.

**Pull request closed without merging**
