### PR TITLE
Update version to 0.3.0

### PR DESCRIPTION
**Pull request by DarkDimius**

### CODE REVIEW

**Comment by olafurpg** [comment]
Has this patch been released? I'd like to update the community build.

**Comment by DarkDimius** [comment]
@olafurpg, it's on maven: http://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.2/0.2.0-RC1/

**Comment by DarkDimius** [comment]
@olafurpg, isn't the community build supposed to use the latest nightly?

**Comment by olafurpg** [comment]
@DarkDimius has a new version of sbt-dotty been released? I'm already using 0.2.0-RC1 in https://github.com/scala/compiler-benchmark/pull/31 :)

**Comment by olafurpg** [comment]
The community build uses the `dottyLatestNightlyBuild` method in sbt-dotty to infer the compiler version.

**Comment by smarter** [comment]
>  has a new version of sbt-dotty been released? 

Not yet, will do that today

**Pull request merged**
