### PR TITLE
Prefer focus for missing arg position

### LINKED ISSUE #15630: Invalid caret position for missing given argument error messages
## Compiler version

Welcome to Scala 3.2.1-RC1-bin-SNAPSHOT-git-baf21dd (18.0.1.1, Java OpenJDK 64-Bit Server VM).

## Minimized code

```Scala
scala> def f = summon[Int]
-- Error: --------------------------------------------------------------------------------------------------------------
1 |def f = summon[Int]
  |                   ^
  |                   No given instance of type Int was found for parameter x of method summon in object Predef
1 error found
```

## Output

The caret doesn't seem to be aligned.

## Expectation

The caret should be aligned with the guilty text.

### PR DESCRIPTION
**Pull request by som-snytt**
The focus puts the caret at the bad application, instead of hanging in space where an explicit argument might have gone in an alternate reality.

The two benefits are pointing at an existing thing that is wrong and also shifting the messaging left.

Sample dramatic diff:
```
-- Error: tests/neg/i14025.scala:1:16 ----------------------------------------------------------------------------------
1 |val foo = summon[deriving.Mirror.Product { type MirroredType = [X] =>> [Y] =>> (X, Y) }] // error
  |                                                                                        ^
  |                ^
```

Further future enhancements could include the hypothetical args printed in Scala 2 messages, perhaps under `-explain`:
```
f(x, y, z)
^
The missing context arguments were expected as follows:
f(e1, e2)(x, y, z)
 ^^^^^^^^
```
Fixes #15630

### CODE REVIEW

**Comment by dwijnand** [comment]
I almost feel like start is better than focus?  I rather than the change being:

```diff
 2 |  val x = implicitly[List[Boolean]] // error
-  |                                   ^
+  |                    ^
   |
 8 |  val value3 = M.pure("ola") // error
-  |                            ^
+  |                     ^
```

make it:

```diff
 2 |  val x = implicitly[List[Boolean]] // error
-  |                                   ^
+  |          ^
   |
 8 |  val value3 = M.pure("ola") // error
-  |                            ^
+  |                 ^
```

WDYT?

**Comment by som-snytt** [comment]
When you put it that way, I like my suggestion for future enhancement, just show me the signature with the holes.

**Comment by som-snytt** [comment]
I really feel like I'm not so stupid that it should take more than one or two rounds of tests to see which tests failed. I will endeavour [typelevel spelling] to figure out why it can't just summarize at the end and eliminate the scrolling.

**Comment by som-snytt** [comment]
Excerpt from my journal during this expedition:

Day 37, I moved the caret to the left, then all the tests expecting `// error` on a particular line number fail if the caret shifted to the previous line. Moreover, Pixie the test rig is coy about showing me her diff. I must be going mad.

**Comment by som-snytt** [comment]
@dwijnand I think my previous comment, that "an improved show-me-the-holes message" is ideal, but I maintain that this delta is an improvement. I'm still very bothered by carets pointing at whitespace.

**Pull request closed without merging**
