### PR TITLE
Fix #1907: Improve error message

### LINKED ISSUE #1907: Union type found when inferring `Array.empty`
```scala
import java.io.File

object Test {
  Some(new File("."))
    .map(_.listFiles).getOrElse(Array.empty)
    .map(_.listFiles)
}
```
Error message:

```
value `map` is not a member of Array[java.io.File] | Array[T]
where:    T is a type variable which is an alias of Array[T]
```

### PR DESCRIPTION
**Pull request by odersky**
Two fixes:

 - we avoid the 5-levels of array tag by synthesizing array tags at the same time as other class tags
 - we bail when asked to generate a `ClassTag[Nothing]` or `ClassTag[Null]`.

The second point is likely contentious. It does forbid some programs that would make sense such as

    def f(x: Any) = ???
    f(Array(): _*)

But it also avoids many situations that would lead to surprising results or confusing errors later.

@retronym What is your take on this?

### CODE REVIEW

**Comment by odersky** [comment]
This is based on #1918. Only the last 3 commits are new. The contentious commit about not synthesizing ClassTags of bottom types is 	e34555f.

**Comment by retronym** [comment]
I'll need to page this back in to comment meaningfully, but for now, I'll dump some links to related discussions about soundness issues with arrays and/or class tags of bottom types:

https://issues.scala-lang.org/browse/SI-9754
https://issues.scala-lang.org/browse/SI-5353
https://issues.scala-lang.org/browse/SI-7453

**Comment by odersky** [comment]
@retronym Thanks for the links. They are all treated OK under this commit. I am not sure whether they would have been soundness issues before, since dotc with its union types behaves differently than scalac. So for instance i1907.scala is compiled by scalac but rejected by dotc.

**Comment by smarter** [comment]
This also indirectly solves https://github.com/lampepfl/dotty/issues/1730, I think it's fine to require the user to be explicit when dealing with `Array[Nothing]`/`Array[Null]`, though the error message as is might be confusing so we should not forget to add a detailed `-explained` message for it at some point.

**Comment by odersky** [comment]
@smarter It would solve #1730, but only if we also disallow forming a ClassTag[Nothing] or ClassTag[Null] manually. I think it would be a good idea to do this, though.

**Comment by smarter** [comment]
Yes, you're right, otherwise the soudness hole is still there.

**Pull request merged**
