### PR TITLE
Add formatters for Option, Map, Period, and Atoms

### PR DESCRIPTION
**Pull request by hamzaremmal**
Before: 
- using a `Map` with the i-interpolator  won't compile
- using an `Option` in the i-interpolator will fall back to the `Show[Product]` given which results in a call to `toString`

### CODE REVIEW

**Review by dwijnand — CHANGES_REQUESTED** [review]
I don't think we should be using the i interpolator in writing the show instances.

**Comment by hamzaremmal** [comment]
> I don't think we should be using the i interpolator in writing the show instances.

I actually hesitated at the beginning because it shouldn't really a problem (but I agree on the premise)

**Comment by dwijnand** [comment]
Could  you pull my changes in #19674 (or approve the PR there)?   Then we can merge one or the other PRs and get these changes finally in (I had these changes locally for a long time, but never had a strong reason to work them into a PR).

**Review by dwijnand — APPROVED** [review]
Thank you!

**Pull request merged**
