### PR TITLE
Add endpoints to the community build

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@julienrf thanks for adding this! All of the Dotty community projects reside as forks of the original repos under dotty-staging organization. Could you create such a fork for `endpoints` and point the PR to it?

**Comment by julienrf** [comment]
@anatoliykmetyuk I would love to but I don’t have the rights to fork under the dotty-staging organization.

**Comment by anatoliykmetyuk** [comment]
@julienrf I've sent you an invite to dotty-staging, you should be able to create the fork.

**Comment by julienrf** [comment]
I don’t understand, the error seems to be in scalaz.

**Comment by anatoliykmetyuk** [comment]
See #9058.

**Pull request merged**
