### PR TITLE
Corrected a typo in the online documentation for Programmatic Structural Types

### PR DESCRIPTION
**Pull request by raymondtay**

### CODE REVIEW

**Comment by allanrenucci** [comment]
Hi @raymondtay . Can you rebase on top of master. We updated the CI

**Comment by raymondtay** [comment]
Thanks @allanrenucci !

**Comment by odersky** [comment]
@raymondtay Thanks for the fix. LGTM.

**Comment by odersky** [comment]
@allanrenucci I leave for you to merge as I am not sure whether the .yml is up to date.

**Comment by allanrenucci** [comment]
Superseded by #3086

**Pull request closed without merging**
