### PR TITLE
Do level checking on instantiation

### LINKED ISSUE #8900: Dig deeper on avoidance
#8867 fixed a tricky avoidance problem #8861 by introducing new techniques for preventing closure types from capturing variables they are not supposed to see. 

There are several areas where our understanding of this issue is still incomplete. It would be good to follow this up with test cases, code fixes and possibly formalizations, as the subject matter is extremely slippery and the requirements for type inference are extremely stringent.

I left in the code base of #8867 several comments starting with

    // AVOIDANCE TODO

This should be followed up.

### LINKED ISSUE #15595: Pickler crashes with unresolved local type in closure
## Compiler version
Fails in 3.1.1
Works in 3.1.2
Works In 3.1.3-RC4
Fails in 3.1.3-RC5
Fails in 3.2.0-RC1

## Minimized code

Based on https://scala3.westeurope.cloudapp.azure.com/blue/organizations/jenkins/buildCommunityProject/detail/buildCommunityProject/561/pipeline

```Scala
trait MatchResult[+T]

@main def Test() = {
  def convert[T <: Seq[_], U <: MatchResult[_]](fn: T => U)(implicit x: Seq[_] = Seq.empty): U = ???
  def resultOf[T](v: T): MatchResult[T] = ???

  convert { _ =>
    type R = String
    resultOf[R](???)
    // this would not lead to crash: 
    // val x = resultOf[R](???)
    // x
  }
}

```

## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: type R (line 11) #6547 when pickling /home/wmazur/projects/virtuslab/community-build3/test.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:783)
        at dotty.tools.dotc.transform.Pickler.run$$anonfun$1$$anonfun$1(Pickler.scala:72)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:110)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:110)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:311)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:312)
        at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:115)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:234)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:245)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:253)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:262)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:262)
        at dotty.tools.dotc.Run.compileSources(Run.scala:186)
        at dotty.tools.dotc.Run.compile(Run.scala:170)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:133)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$7(BloopHighLevelCompiler.scala:151)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:71)
        at bloop.tracing.BraveTracer.traceInternal(BraveTracer.scala:65)
        at bloop.tracing.BraveTracer.trace(BraveTracer.scala:39)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:70)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$6(BloopHighLevelCompiler.scala:151)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
        at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
        at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Error: Unexpected error when compiling project_6d5831c594_6d5831c594-15348604ae: 'assertion failed: unresolved symbols: type R (line 11) #6547 when pickling /home/wmazur/projects/virtuslab/community-build3/test.scala'
```
</details>

## Code after typer phase (click arrow to expand)
<details>
Differences in enclosing packages and imports originate from minimalizing issue in the original repo

```scala
package <empty> {
  import util.WithTemporaryCollection.*
  import org.specs2.matcher.MatchResult
  final class ChangeStreamSpec() extends Object() {
    def resultOf[T >: Nothing <: Any](v: T): org.specs2.matcher.MatchResult[T]
       = 
    ???
    trait Coll() extends Object {}
    def convert[T >: Nothing <: Seq[? >: Nothing <: Any], 
      U >: Nothing <: org.specs2.matcher.MatchResult[? >: Nothing <: Any]
    ](fn: T => U)(implicit x: Seq[ChangeStreamSpec.this.Coll]): U = ???
    def convert$default$2[T >: Nothing <: Seq[? >: Nothing <: Any], 
      U >: Nothing <: org.specs2.matcher.MatchResult[? >: Nothing <: Any]
    ](fn: T => U): Seq[ChangeStreamSpec.this.Coll] @uncheckedVariance = 
      Seq.empty[ChangeStreamSpec.this.Coll]
    {
      val fn$1: Seq[?] => org.specs2.matcher.MatchResult[R] = 
        {
          {
            def $anonfun(_$1: Seq[?]): org.specs2.matcher.MatchResult[R] = 
              {
                type R = String
                this.resultOf[R](???):org.specs2.matcher.MatchResult[String]
              }
            closure($anonfun)
          }
        }
      this.convert[Seq[?], org.specs2.matcher.MatchResult[R]](fn$1)(
        this.convert$default$2[Seq[?], org.specs2.matcher.MatchResult[R]](fn$1)
      )
    }
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by odersky**
Level checking was first implemented #14026. The idea was to avoid level-incorrect constraints from the outset,  by cloning type variables and adjusting bounds as needed. This fixed a number of issues, but also caused a number of regressions since the number of added type variables had subtle interactions with other aspects of type checking. 

This PR is more conservative in its change set: It still allows level-incorrect constraints to be formed, but fixes levels when type variables are instantiated. To do this soundy, it uses an "_untrusted bounds_" mode in the type comparer, under which we do not accidentally forget types when forming lubs or glbs with other references that have bad bounds.

One can choose between level checking when forming constraints (i.e. #14026) vs level checking on instantiation (i.e. #15746) by setting the value `Config.checkLevelsOnConstraints`

Fixes #8900 
Fixes #15595

### CODE REVIEW

**Comment by odersky** [comment]
@smarter I have put everything under two config flags, so one can switch between

 - no level checking at all (unsound)
 - level checking on instantiation
 - level checking on constraint formation

That way, we can fix the immediate issues while we take more time to decide what kind of checking is best.

**Comment by odersky** [comment]
@WojciechMazur This commit is fairly high risk for regressions. Can you run the large CB with this branch to see what would break?

**Comment by WojciechMazur** [comment]
Sure, I've started the build and its progress can be found here https://scala3.westeurope.cloudapp.azure.com/blue/organizations/jenkins/runBuild/detail/runBuild/6/pipeline 
I should be able to aggregate the results on Monday. So far I can see some type related problems with the compilation of Akka https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/268/

**Comment by odersky** [comment]
So I conclude we have some breakage. @WojciechMazur from your experience, can you give an estimate how bad it is?

On the other hand, the current situation with unsound and buggy type variable instantiation is untenable. So we will need to make the effort to minimize the regressions and try to fix them individually. I am not sure whether this is better done with a merged PR or before. In any case we should merge this PR at the start of a release cycle.

**Comment by odersky** [comment]
I think we should merge this now, as long as we are in the beginning of a release cycle, and have a chance to catch regressions. Who can give it a review?

**Comment by smarter** [comment]
Shouldn't we check whether this breaks more or less things in the open community build than the previous level-checking before settling on this approach?
I won't be able to do a thorough review of this PR this month but one thing that really needs to be addressed is the use of a var in TypeVar in https://github.com/lampepfl/dotty/pull/15746/files#diff-c59c50b7dcb6f1a4eb6d807a1c6c54a684c01e368d3a293ae8fd055531ac97faR4508. This will lead to very weird bugs whenever the constraint is rolled back, as explained in the commit message of https://github.com/lampepfl/dotty/pull/14026/commits/3ab18a90ac24dba440c498aab6a8f0c763589605 :
> Each fresh variable will be upper-
or lower-bounded by the existing variable it is substituted for
depending on variance (an idea that I got from [1]), in the invariant
case the existing variable will be instantiated to the fresh one (unlike
[2], we can't simply mutate the nestingLevel of the existing variable
after running avoidance on its bounds because the constraint containing
these bounds might later be retracted).

**Comment by odersky** [comment]
> Shouldn't we check whether this breaks more or less things in the open community build than the previous level-checking logic before settling on this approach?

I don't think so, since we can selectively turn either logic on. Level checking on constraint formation clearly does not work as is, and requires major changes to several parts of the type checker to make it work. There's no-one scheduled or volunteering to do these changes, so we cannot count on them to be done. Level checking on instantiation has a chance to work, we have to go through the effort of minimization and see what the reason for the breakages are.

Not doing level checking at all (which is the current state) also clearly does not work, and, if not addressed will just encourage more unsound code. 

> I won't be able to do a thorough review of this PR this month but one thing that really needs to be addressed is the use of a var in TypeVar in https://github.com/lampepfl/dotty/pull/15746/files#diff-c59c50b7dcb6f1a4eb6d807a1c6c54a684c01e368d3a293ae8fd055531ac97faR4508. This will lead to very weird bugs whenever the constraint is rolled back, as explained in the commit message of https://github.com/lampepfl/dotty/commit/3ab18a90ac24dba440c498aab6a8f0c763589605 :

I am actually not so sure about this. The worst that could happen is that a type variable gets a lower level than expected, which is still sound. I find the alternative of instantiating type variables very complicated, and will not have time to do it. So i propose we merge with the option of improving this aspect later.

**Review by smarter — CHANGES_REQUESTED** [review]
> There's no-one scheduled or volunteering to do these changes

It's something I'd like to do, although I can't promise when exactly right now.

> The worst that could happen is that a type variable gets a lower level than expected, which is still sound.

It's probably sound, but it leads to weird "action at a distance" effects. Type inference bugs are already very hard to debug because there's so many interactions to consider, but with this change I fear the situation would get 10x harder to deal with: now some logic in a  retracted TyperState might influence whether your code compiles or not, this will lead to regressions that take enormous effort to understand and that probably cannot be fixed.

**Comment by odersky** [comment]
I think in summary, with the long list of failures associated with the current disabled behavior, it's still better to go ahead and merge this. I am not happy about it, but I don't see a practicable alternative.

**Comment by odersky** [comment]
I opened issue #15884 to keep track of the nestingLevel update problem.

**Comment by odersky** [comment]
> It's something I'd like to do, although I can't promise when exactly right now.

I think that would be good. But we cannot keep the code in the current problematic state until this is resolved. I think this needs to go into 3.2.1. So I propose we get back to it later, without the pressure of time constraints.

**Comment by smarter** [comment]
Ok, but it would still be good if someone else could review this then.

**Comment by odersky** [comment]
@dwijnand Do you think you could give this a go? It's plain constraints as opposed to GADT constraints but since the two are duals it should be close.

**Comment by odersky** [comment]
I found a solution for the problem of hidden state in nestingLevel: Make the state explicit in TyperState where updates to nesting levels are stored.

**Comment by smarter** [comment]
Nice!  I was considering whether the nestingLevel should be stored in the Constraint, because there's multiple places where we rollback constraints without rolling back the full TyperState, e.g:
- https://github.com/lampepfl/dotty/blob/ead0fbc7804026e2c764f88f7576029c2fb7a51f/compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala#L103
- https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1766
- https://github.com/lampepfl/dotty/blob/ead0fbc7804026e2c764f88f7576029c2fb7a51f/compiler/src/dotty/tools/dotc/typer/Applications.scala#L2226
But perhaps these places should use TyperState#{snapshot, resetTo} instead.

**Comment by odersky** [comment]
> But perhaps these places should use TyperState#{snapshot, resetTo} instead.

Yes, that seems right.

**Comment by odersky** [comment]
Actually, I think we need the TyperState shapshot only for harmonize. The operations in ProtoTypes and TypeComparer only affect constraints but do not instantiate type variables.

**Comment by odersky** [comment]
In fact, I am not sure what to do about harmonize. It seems that neither resetting the constraint nor resetting the typerstate is correct here. We need to come back to this.

**Comment by WojciechMazur** [comment]
Regressions found in the open community build: 
Tested 639 projects, 6 regressions found 
| Project | Version |  Build URL |
| ------- | ------- | --------- |
| akka/akka | 2.6.19 | [Open CB #2604](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2604/) |
| fd4s/vulcan | 1.8.3 | [Open CB #2607](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2607/) |
| mvv/sager | 0.2-M1 | [Open CB #2611](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2611/) |
| scala-ts/scala-ts | 0.5.13 | [Open CB #2612](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2612/) |
| sirthias/borer | 1.10.1 | [Open CB #2622](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2622/) |
| zio/zio-query | 0.3.1 | [Open CB #2614](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2614/) |

**Comment by dwijnand** [comment]
Akka failure:

```
[info] compiling 21 Scala sources and 2 Java sources to /home/jenkins/agent/workspace/buildCommunityProject/repo/akka-cluster-typed/target/scala-3.2.1-RC1-bin-f01abfba6840d8e91e1a8936cd7c112007667a23-COMMUNITY-BUILD/classes ...
[error] -- [E007] Type Mismatch Error: /home/jenkins/agent/workspace/buildCommunityProject/repo/akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala:92:46 
[error] 92 |                reply.foreach { cmd.replyTo ! _ }
[error]    |                                              ^
[error]    |Found:    akka.cluster.ddata.typed.javadsl.Replicator.GetResponse[?1.CAP]
[error]    |Required: akka.cluster.ddata.typed.javadsl.Replicator.GetResponse[d]
[error]    |
[error]    |where:    ?1 is an unknown value of type scala.runtime.TypeBox[d, akka.cluster.ddata.ReplicatedData]
[error]    |          d  is a type in an anonymous function in method withState with bounds <: akka.cluster.ddata.ReplicatedData
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
```

**Comment by odersky** [comment]
Is there a way to minimize the Akka failure? So far it does not tell us much. ?.CAP is an unknown instance of some type parameter. It's quite plausible that we first instantiated a type variable to something unsound and then this was the fallback. But it could also be something else.

**Comment by dwijnand** [comment]
I can't reproduce it, but the code looks like something that you could easily fix with an explicit type argument or type annotation.  The fix looks good to me.  I might continue to try to recreate a minimised version of Akka's failure tomorrow.

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
