### PR TITLE
Add/trait parameters

### PR DESCRIPTION
**Pull request by odersky**
Implements #640. @retronym do you want to take a look?

### CODE REVIEW

**Comment by retronym** [comment]
```scala
trait U(a: Any) extends T {
  def d = a // okay
  val v = a // okay
  a // crash
}
```

```
exception while transforming (a: Object) extends Object with T {
  private <accessor> def a(): Object
  def d(): Object = U.this.a()
  <accessor> def v(): Object = U.this.a()
  U.this.a()
} of class class dotty.tools.dotc.ast.Trees$Template # 136
exception while transforming <trait> trait U(a: Object) extends Object with T {
  private <accessor> def a(): Object
  def d(): Object = U.this.a()
  <accessor> def v(): Object = U.this.a()
  U.this.a()
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 137
exception while transforming package <empty> {
  <trait> trait U(a: Object) extends Object with T {
    private <accessor> def a(): Object
    def d(): Object = U.this.a()
    <accessor> def v(): Object = U.this.a()
    U.this.a()
  }
  final lazy module val U: U$ = new U$()
  final module class U$() extends Object() { this: U$ =>}
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 154
exception occurred while compiling sandbox/test.scala
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at dotty.tools.dotc.transform.SymUtils$.loop$1(SymUtils.scala:64)
	at dotty.tools.dotc.transform.SymUtils$.subst$extension(SymUtils.scala:66)
	at dotty.tools.dotc.transform.Constructors$intoConstr$2$.transform(Constructors.scala:100)
	at dotty.tools.dotc.transform.Constructors$intoConstr$2$.transform(Constructors.scala:103)
	at dotty.tools.dotc.transform.Constructors$intoConstr$2$.apply(Constructors.scala:112)
	at dotty.tools.dotc.transform.Constructors.splitStats$1(Constructors.scala:180)
```

**Comment by retronym** [comment]
I think this is a clearer way to express the test cases:

```
object Trace {
  private var results = List[Any]()
  def apply[A](a: A) = {results ::= a; a}
  def fetchAndClear(): Seq[Any] = try results.reverse finally results = Nil
}
trait T(a: Any) {
  val ta = a
  Trace(s"T.<init>($ta)")
  val t_val = Trace("T.val")
}

trait U(a: Any) extends T {
  val ua = a
  Trace(s"U.<init>($ua)")
}

object Test {
  def check(expected: Any) = {
    val actual = Trace.fetchAndClear()
    if (actual != expected)
      sys.error(s"\n$actual\n$expected")
  }
  def main(args: Array[String]): Unit = {
    new T(Trace("ta")) with U(Trace("ua")) {}
    check(List("ta", "T.<init>(ta)", "T.val", "ua", "U.<init>(ua)"))

    new U(Trace("ua")) with T(Trace("ta")) {}
    check(List("ta", "T.<init>(ta)", "T.val", "ua", "U.<init>(ua)"))
  }
}

```

**Comment by odersky** [comment]
@retronym Yes, that was the corner case I meant.

**Comment by odersky** [comment]
Seems we are done with reviews. Merging.

**Comment by odersky** [comment]
rebased to master

**Pull request merged**
