### PR TITLE
remove scala.Enum type alias

### PR DESCRIPTION
**Pull request by bishabosha**
also removed some qualified types where not specifically testing how the compiler behaves for java.lang.Enum

### CODE REVIEW

**Comment by bishabosha** [comment]
@romanowski Hi, I'm not sure how to update the test in `scala3doc-testcases/src/tests/annotations.scala` the EnumAnnotation signature needs to change so it does not clash with 'java.lang.Enum' but I'm not sure if there are any other updates required

**Comment by romanowski** [comment]
@bishabosha those tests are self-defined (we compare source with documentation) so you can rename it freely

**Comment by bishabosha** [comment]
@romanowski I believe I identified the problem is that the tests do not print the fully qualified path of types in signatures, so there requires two imports to unimport `java.lang.Enum`, but the CI should pass now

**Comment by bishabosha** [comment]
@smarter CI has passed

**Review by smarter — APPROVED** [review]

**Pull request merged**
