### PR TITLE
Upgrade to sbt 0.13.14-RC2, switch to build.sbt

### PR DESCRIPTION
**Pull request by smarter**
Let's wait until https://github.com/sbt/sbt/issues/3012 is fixed first.

### CODE REVIEW

**Comment by felixmulder** [comment]
:+1: for removing the unused scalastyle plugin

**Comment by smarter** [comment]
@felixmulder I think this is ready to go in (even though sbt 0.13.14 is not released yet, this way we may be able to get potential issues fixed before the release)

**Comment by felixmulder** [comment]
What about https://github.com/sbt/sbt/issues/3012?

**Comment by felixmulder** [comment]
Otherwise LGTM

**Comment by smarter** [comment]
Using org.scala-sbt:interface is fine even with coursier as long as we add resolvers to all subprojects as explained in https://github.com/coursier/coursier/issues/284#issuecomment-230317311

**Pull request merged**
