### PR TITLE
Update documentation after #3665

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by smarter** [comment]
LGTM. Though I find it weird to call this testCompilation when it also runs tests :).

**Comment by allanrenucci** [comment]
Do you a better alternative? I am happy to change the name. Martin wanted something that starts with "test" so that the command can be discovered using autocompletion in sbt

**Comment by smarter** [comment]
testCompiler ?

**Comment by allanrenucci** [comment]
Merging this since `testCompilation` has been around for some time now.

**Pull request merged**
