### PR TITLE
Fix match type reduction with avoided types

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by mbovel** [comment]
I was initially worried about widening term refs and then realized that your are only doing it for inline proxies, so that is probably fine.

We could add a test to make sure that term refs in scrutinees are not widened in general:

```scala
val x: Int = 42
val y: Int = 43
val z: Int = 44

type IsX[T] =
    T match
        case x.type => true
        case _ => false
def test = summon[IsX[y.type] =:= IsX[z.type]] // error

def test2 = summon[
  (
    y.type match
      case x.type => true
      case _ => false
  ) =:= (
    z.type match
          case x.type => true
          case _ => false
  )
] // error
```

**Comment by mbovel** [comment]
I unfortunately found at least one case where widening skolems is not desirable:

```scala
import scala.util.Random
val x = 42

type IsX[T] =
    T match
        case x.type => true
        case _ => false

def bothXOrNot(a: Int, b: Int)(using IsX[a.type] =:= IsX[b.type]) = ???

def test = bothXOrNot(Random.nextInt(), Random.nextInt())
```

It compiles with your change, while it didn't compile before.

**Review by mbovel — APPROVED** [review]
As far as I am concerned, this looks great!

As discussed: allowing match types to be generally "covariant in their scrutinees" would break algorithmic subtyping transitivity, so we probably want to avoid it for now.

However, this PR only adresses a narrower case: skolems and inline proxies. As these cannot be written by users directly in match types patterns, it seems to me that it should pretty safe. I tried to come up with problematic examples but couldn't.

The bug in `compareAtoms` is also an important one and we should definitely merge its fix as soon as possible.

**Comment by Kordyjan** [comment]
It fails under `Fixes regression introduced before Scala 3.3` -> `Can change types in correct Scala 3 code` path in our backporting procedure. So, I'm marking it as `Backport Rejected` with the possibility of changing the decision based on user requests.

**Pull request merged**
