### PR TITLE
Fix i18629

### PR DESCRIPTION
**Pull request by EnzeXing**
This PR fixes the minimized test of #18629 that could previously crash the global initialization checker because of empty patterns when matching against `List()`.

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM, thank you

**Review by olhotak — APPROVED** [review]
LGTM

**Comment by EnzeXing** [comment]
I think the failed checks are due to server issues just now. How to rerun those checks?

**Comment by olhotak** [comment]
I reran the tests but now they failed on the i18629.scala test that you added.

**Pull request merged**
