### PR TITLE
Add some overview notes on the GADT implementation

### PR DESCRIPTION
**Pull request by dwijnand**
Authored by Aleksander Boruch-Gruszecki.

The intent here is to start to have some more detailed information on
the implementation, even in an initially rough form that can be refined
over time.

### CODE REVIEW

**Comment by bishabosha** [comment]
would you mind submitting this instead to the [Scala 3 contribution guide](https://docs.scala-lang.org/scala3/guides/contribution/arch-intro.html), I would like to remove the internals docs at some point as they were copied and improved upon there.

**Comment by dwijnand** [comment]
I kind of think contributing stuff should be in the repo, not outside.  I can see the value of splitting out more general language documentation, helpful guides, examples, faqs and whatnot.  But for things that are so closely related to internals and implementation I'd rather keep things close.  For instance, if something starts as a piece of scaladoc or in-code comment, it could grow and want to become in markdown, perhaps to add a diagram or some clickable links - I don't think it should have to be exported to another repo.  Similar to the desire to iterating on the capture checking docs or explicit null docs, which are WIP and not part of any release.

**Review by bishabosha — APPROVED** [review]
Thanks for putting the guide together all involved!

**Comment by bishabosha** [comment]
actually, the sidebar still needs updating - https://github.com/lampepfl/dotty/blob/main/docs/sidebar.yml

**Review by bishabosha — DISMISSED** [review]
I believe that the sidebar config file should update as well

**Pull request merged**
