### PR TITLE
Support arbitrary code in top level splices

### PR DESCRIPTION
**Pull request by nicolasstucki**
This addition will allow us to write code such as

```scala
inline def power(x: Double, inline n: Int): Double = ${
  def powerCode(i: Int): Expr[Double] = 
    if (i == 0) '{ 1 } else '{ x * ${powerCode(i - 1)} }
  powerCode(n)
}
```

Will be transformed to

```scala
inline def power(x: Double, inline n: Int): Double = ${ power$impl$1('{x}, n) }
```

```scala
def power$impl$1(x: Expr[Double], n: Int): Expr[Double] = {
  def powerCode(i: Int): Expr[Double] = 
    if (i == 0) '{ 1 } else '{ $x * ${powerCode(i - 1)} }
  powerCode(n)
}
```

Where `power$impl$1` is placed in a top-level object.

### CODE REVIEW

**Comment by LPTK** [comment]
Will this work?

```scala
inline def power(x: Double, inline n: Int): Double = ${
  if (n == 0) '{ 1 } else '{ x * power(x, ${Literal(n - 1)}) }
}
```

**Comment by nicolasstucki** [comment]
Not with the current changes. But it should be possible to adapt it to work. The notation `${Literal(n - 1)}` is the only dubious part. I will leave it for a future PR.

**Comment by LPTK** [comment]
@nicolasstucki How do you create a literals in quoted code?

**Comment by nicolasstucki** [comment]
Literals can be lifted with `n.toExpr`

**Pull request closed without merging**
