### PR TITLE
Fix #15055

### LINKED ISSUE #15055: Nightly Dotty workflow of 2022-04-28 failed
See https://github.com/lampepfl/dotty/actions/runs/2236991940

### PR DESCRIPTION
**Pull request by mbovel**
[test_windows_full]

### CODE REVIEW

**Comment by mbovel** [comment]
@som-snytt, would that make sense to use [`Path.getFileName`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#getFileName()) here?

**Comment by mbovel** [comment]
Answering my own question: no, because using `Path` induces additional validation of the `path` that we do not want here:

```
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <highlighting>
```

I forced-pushed a second attempt that just replaces `/` with `File.separator`.

**Comment by som-snytt** [comment]
I'll take a look (when fully awake), but there's no reason for virtual paths to respect the syntax of some random other file system (such as Windows).

**Comment by som-snytt** [comment]
Also, I've been working under WSL for some time, and just revived my cygwin, so I'll try to test locally under windows. Worst case, actually try using windows tooling, shudder.

**Comment by som-snytt** [comment]
> would that make sense to use [Path.getFileName](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#getFileName()) here?

worth adding that `InteractiveDriver` did that before the recent tweak.

I also considered that `VirtualFile` should require user to supply both path and simple name if they are not the same. Then the strings could be taken as opaque instead of structured.

**Review by som-snytt — COMMENTED** [review]
these classes are still an unfortunate weak spot, or "experimental". Since VirtualDirectory uses / it seems more robust to say, No, virtual means not tied to your local conventions. The alternative PR makes SourceFile convert the slashes.

**Pull request closed without merging**
