### PR TITLE
Make benchmarks depend only on library classpath

### PR DESCRIPTION
**Pull request by Blaisorblade**
Followup to #5020.

Testing that our benchmark program don't need to link against the compiler.
Warning: This might make performance incomparable with earlier (similarly to
other current changes.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
test performance please

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
Don't merge, there are still 4 failures in benchmarks. I'm investigating.

**Comment by Blaisorblade** [comment]
Closing as the idea is now in #5020 and up to @liufengyun.

**Pull request closed without merging**
