### PR TITLE
Fix #6450: Don't drop apply alternatives in overloading resolution

### LINKED ISSUE #6450: Compatibility issue with Scala at runtime
This was initially reported [on the dotty gitter channel](https://gitter.im/lampepfl/dotty?at=5c740b5c5df86a456891486f)  by @Jasper-M but I did not find an open issue for that.
The behaviour is the same with -language:Scala2

Scala
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
defined class Foo

scala> new Foo().foo
res6: Int = 1
```
Dotty
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
// defined class Foo

scala> new Foo().foo
val res0: Double = 0.0
```

### PR DESCRIPTION
**Pull request by odersky**
The overloading resolution algorithm dropped alternatives reachable through applys
when testing for applicability. It did so in three situations

 - when comparing the arities of alternatives
 - when testing via isDirectlyApplicable
 - when testing via isApplicable

The third problem stemmed from confusion between overloaded versions
of `isApplicable` (it's ironical that overzealous use of overloading
broke overloading resolution in the compiler!). The version for TermRefs
would not consider `apply` insertion, but the version for Types would.
This means that the overloading broke the Liskov substitution principle. If
a general type happened to be a TermRef the more specific isApplicable
version would kick in, which however did less than the original.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by anatoliykmetyuk** [comment]
Here's a minimised example of why ScalaCheck is failing:

```scala
trait A {
  def apply(x: Any): Int =  1
}

object B {
  def f(x: Any): Int = 2
  lazy val f = new A {}
  val x = f(null)
}
```

In Scala 2:

```scala
scala> trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): Int = 2; lazy val f = new A {}; val x = f(null) }; B.x
<console>:13: error: ambiguous reference to overloaded definition,
both lazy value f in object B of type => A
and  method f in object B of type (x: Any)Int
match argument types (Null)
       trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): Int = 2; lazy val f = new A {}; val x = f(null) };;
```

In this PR:

```scala
scala> trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): Int = 2; lazy val f = new A {}; val x = f(null) }; B.x
// defined trait A
// defined object B
val res0: Int = 1
```

Another example:

```scala
trait A {
  def apply(x: Any): Int =  1
}

object B {
  def f(x: Any): A = new A {}
  lazy val f: A = f(null)
}
```

In Scala 2:

```scala
scala> trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): A = new A {}; lazy val f: A = f(null) }; B.f
defined trait A
defined object B
res10: A = B$$anon$1@54ddd7e4
```

In this PR:

```scala
scala> trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): A = new A {}; lazy val f: A = f(null) }; B.f
1 |trait A { def apply(x: Any): Int =  1 }; object B { def f(x: Any): A = new A {}; lazy val f: A = f(null) }; B.f
  |                                                                                                 ^^^^^^^
  |                                                             Found:    Int
  |                                                             Required: A
```

The second one is what's going on in ScalaCheck.

I'll see what can be done here.

**Comment by odersky** [comment]
@anatoliykmetyuk Thank you for the minimizations, which did highlight a problem. Unfortunately, even after fixing the problem, ScalaCheck still fails. Can you give it another try?

**Comment by anatoliykmetyuk** [comment]
Ok. This PR:

```scala
scala> trait A {
     |   def apply(x: AnyRef): Int
     | }
     |
     | object B {
     |   def f(e: Any): A = ???
     |   val f: A = f(null)
     | }
     |
7 |  val f: A = f(null)
  |             ^^^^^^^
  |             Found:    Int
  |             Required: A

scala> trait A {
     |   def apply(x: String): Int
     | }
     |
     | object B {
     |   def f(e: CharSequence): A = ???
     |   val f: A = f(null)
     | }
7 |  val f: A = f(null)
  |             ^^^^^^^
  |             Found:    Int
  |             Required: A

scala> trait A {
     |   def apply(x: String): Int
     | }
     |
     | object B {
     |   def f(e: Integer): A = ???
     |   val f: A = f(null)
     | }
7 |  val f: A = f(null)
  |             ^^^^^^^
  |             Found:    Int
  |             Required: A
```

But:

```scala
scala> trait A {
     |   def apply(x: Any): Int
     | }
     |
     | object B {
     |   def f(e: Any): A = ???
     |   val f: A = f(null)
     | }
     |
// defined trait A
// defined object B

scala> trait A {
     |   def apply(x: Any): Int
     | }
     |
     | object B {
     |   def f(e: AnyRef): A = ???
     |   val f: A = f(null)
     | }
     |
// defined trait A
// defined object B

scala> trait A {
     |   def apply(x: CharSequence): Int
     | }
     |
     | object B {
     |   def f(e: String): A = ???
     |   val f: A = f(null)
     | }
// defined trait A
// defined object B
```

Also:

```scala
scala> def f(x: Any) = 10
     | val f: Foo = f(1)   // Should show "Not found: type Foo" instead
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.config.ScalaSettings.YnoDecodeStacktraces(ScalaSettings.scala:164)
	at dotty.tools.dotc.core.handleRecursive$.apply(TypeErrors.scala:90)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:724)
	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:545)
	at dotty.tools.dotc.core.Types$Type.member(Types.scala:530)
	at dotty.tools.dotc.typer.Applications.onMethod(Applications.scala:1210)
	at dotty.tools.dotc.typer.Applications.sizeFits$2(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.sizeFits$1$$anonfun$1(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.onMethod$$anonfun$1(Applications.scala:1210)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.hasAltWith(Denotations.scala:752)
	at dotty.tools.dotc.typer.Applications.onMethod(Applications.scala:1210)
	at dotty.tools.dotc.typer.Applications.sizeFits$2(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.sizeFits$1$$anonfun$1(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.onMethod$$anonfun$1(Applications.scala:1210)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.hasAltWith(Denotations.scala:752)
	at dotty.tools.dotc.typer.Applications.onMethod(Applications.scala:1210)
	at dotty.tools.dotc.typer.Applications.sizeFits$2(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.sizeFits$1$$anonfun$1(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.onMethod$$anonfun$1(Applications.scala:1210)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.hasAltWith(Denotations.scala:752)
	at dotty.tools.dotc.typer.Applications.onMethod(Applications.scala:1210)
	at dotty.tools.dotc.typer.Applications.sizeFits$2(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.sizeFits$1$$anonfun$1(Applications.scala:1580)
	at dotty.tools.dotc.typer.Applications.onMethod$$anonfun$1(Applications.scala:1210)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.hasAltWith(Denotations.scala:752)
	at dotty.tools.dotc.typer.Applications.onMethod(Applications.scala:1210)
...
```

**Comment by odersky** [comment]
Thanks for the trouble shooting @anatoliykmetyuk! That was a huge help to fix this.

**Comment by odersky** [comment]
@anatoliykmetyuk I found a better scheme. Should be much clearer now.

**Comment by anatoliykmetyuk** [comment]
@odersky do you think we should rebase this before merging to keep the history clean?

**Comment by odersky** [comment]
It was rebased at some point already. So should be OK to merge.

**Pull request merged**
