### PR TITLE
Remove uses of inline overriding inline

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
This change was motivated by https://github.com/lampepfl/dotty/pull/8543#discussion_r392697181

**Comment by nicolasstucki** [comment]
The overriding would be disabled with #8564. Overloading sounds like a better pattern for those use cases. It might be simpler to encode that with extension methods. I will create a prototype and add it in another PR.

**Comment by smarter** [comment]
I think the cleaner solution would be to keep `assert` abstract in the base trait and have different concrete implementations, the user then chooses which concrete implementation to mix-in or make his own. But this is likely to require a bigger refactoring of scalatest, so I think that this PR is good enough for now.

**Comment by LPTK** [comment]
@smarter in general, with such a solution, wouldn't it mean that everyone using the base abstract type (instead of the concrete type) would get normal function calls to the abstract `assert` method, without benefitting from any inlining?

This could even happen in Scalatest, even though it which relies on mixins and using `assert` from inside the class. For example, if I have a mixin component like:

```scala
trait MyTestMixin { self: Assertions =>
  ...
  assert(...)  // calls the abstract method; doesn't inline (surprising behavior)
  ...
}
``` 

Would there be a way to get an error there instead?

**Comment by sjrd** [comment]
> Would there be a way to get an error there instead?

This is the behavior of the brand new abstract inline methods. Precisely.

**Comment by LPTK** [comment]
@sjrd ah thanks, perfect. I had missed that one.

**Comment by ohze** [comment]
With the changes in this PR, IDK how to migrate [scalatestplus-junit](https://github.com/giabao/scalatestplus-junit/blob/43db6f0/src/main/scala-3/org/scalatestplus/junit/VersionSpecificAssertionsForJUnit.scala):
```scala
trait AssertionsForJUnit extends Assertions {
  inline override def assert(inline condition: Boolean)
                            (implicit prettifier: Prettifier, pos: source.Position): Assertion =
    ${ AssertionsForJUnitMacro.assert('{condition}, '{prettifier}, '{pos}, '{""}) }
  ...
```
So I think the [overloading way](#pullrequestreview-380646858) by @liufengyun is better?
Can someone pls help me :(

**Comment by nicolasstucki** [comment]
`inline def` are final, as such, you won't be able to override an `inline def` that is not abstract.

There is an alternative using `abstract inline def`
```scala
trait AbstractAssertions {
   inline def assert(...): Assertion
}
```

```scala
trait Assertions extends AbstractAssertions {
   inline def assert(...): Assertion = ...
}
```

```scala
trait AssertionsForJUnit extends AbstractAssertions {
   inline def assert(...): Assertion = ...
}
```

**Comment by ohze** [comment]
using `abstract inline def` that way => all trait that extends a sub trait of `Assertions` will not able to use `AssertionsForJUnit`.
Ex:
```scala
trait SomeSuite extends org.scalatest.Suite ...
```
Note `org.scalatest.Suite` is a sub trait of `Assertions`.
This is true for class, object too.

**Comment by liufengyun** [comment]
Hi @ohze could you please elaborate a little bit what is the problem with the solution proposed by @nicolasstucki ?

**Comment by smarter** [comment]
The main problem I think is that scalatestplus-junit depends on scalatest, so it can't be fixed without changing scalatest itself.

**Comment by neko-kai** [comment]
@liufengyun All scalatest traits extend `Assertion`, not `AbstractAssertion`, this makes it impossible to mixin an `AssertionsForJUnit` after-the-fact. If these traits are forced to extend `AbstractAssertion` than they will have to always be completed by the user when declaring a new test
```scala
class Test extends WordSpec
```
```scala
class Test extends WordSpec with Assertions
```

**Comment by smarter** [comment]
> So I think the overloading way by @liufengyun is better?

Looks like you figured it out: https://github.com/giabao/scalatestplus-junit/commit/ee3e08aadc8a17650d7a62a93c7f3695aa229d73, any issue with that solution ?

**Comment by ohze** [comment]
> > So I think the overloading way by @liufengyun is better?
> 
> Looks like you figured it out: [giabao/scalatestplus-junit@ee3e08a](https://github.com/giabao/scalatestplus-junit/commit/ee3e08aadc8a17650d7a62a93c7f3695aa229d73), any issue with that solution ?

No issue.
And I have created a PR: scalatest/scalatestplus-junit#12

**Pull request closed without merging**
