### PR TITLE
Revert "Highlight all EBNF snippets. Add missing semicolons."

### PR DESCRIPTION
**Pull request by odersky**
This reverts commit a60c4e714243b9361615facd62469c9a440d16ab.

### CODE REVIEW

**Comment by pikinier20** [comment]
Can we not revert the PR and instead replace semicolons with some other less misleading chars? I thought about dots or maybe some other unicode characters?

**Comment by odersky** [comment]
> Can we not revert the PR and instead replace semicolons with some other less misleading chars? I thought about dots or maybe some other unicode characters?

But why? Scala does not require termination characters, so why add one for EBNF? That is super misleading. Besides, the style without termination character has been used for every Scala grammar since the start and is also the style of the official Java grammar. So, let's not mess with this!

**Comment by pikinier20** [comment]
The need of having some termination character is related only to the fact that we use highlight.js as a highlighting tool and the rules of highlighting EBNF are then much easier. We can also revert this and have small styling issues in ebnf snippets which we can solve later in different way.

**Review by pikinier20 — APPROVED** [review]

**Comment by odersky** [comment]
@pikinier20 Yes, let's do this. Never let your tooling dictate your documentation content.

**Comment by pikinier20** [comment]
I'm gonna make a PR from this branch to stable documentation branch to have it updated there. Then we'll have a backport PR that will also change it on main branch.

**Pull request merged**
