### PR TITLE
Make `EmptyTuple` a `case object`

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Strange, the MiMA passes. I expect it to fail because the case object added new methods on `EmptyTuple`.

@dwijnand do you know if these definitions are ignored by MiMa for some reason?

**Comment by dwijnand** [comment]
It looks like we're only checking scala3-library for backwards compatibility.  And in backwards compatibility adding methods is only a problem for extendable classes, not for object.  So we need to change the setting so both directions are checked:

```
sbt:scala3> set LocalProject("scala3-library-bootstrapped")/mimaCheckDirection := "both"
[info] Defining scala3-library-bootstrapped / mimaCheckDirection
[info] The new value will be used by scala3-library-bootstrapped / mimaFindBinaryIssues, scala3-library-bootstrapped / mimaReportBinaryIssues
[info] Reapplying settings...
[info] set current project to scala3 (in build file:/d/scala3/)
sbt:scala3> scala3-library-bootstrapped/mimaReportBinaryIssues
[error] scala3-library-bootstrapped: Failed binary compatibility check against org.scala-lang:scala3-library_3:3.1.2! Found 23 potential problems (filtered 11)
[error]  * the type hierarchy of object scala.Tuple#package#EmptyTuple is different in other version. Missing types {scala.deriving.Mirror$Product,scala.deriving.Mirror$Singleton,scala.deriving.Mirror}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scala.Tuple$package$EmptyTuple$")
...
[error] stack trace is suppressed; run last scala3-library-bootstrapped / mimaReportBinaryIssues for the full output
[error] (scala3-library-bootstrapped / mimaReportBinaryIssues) Failed binary compatibility check against org.scala-lang:scala3-library_3:3.1.2! Found 23 potential problems (filtered 11)
[error] Total time: 0 s, completed 20 Apr 2022, 11:05:16
```

**Comment by nicolasstucki** [comment]
Thank you @dwijnand. 

The check is passing because we updated to `3.2.0-RC1` and the following code chooses `BinaryCompatible` https://github.com/lampepfl/dotty/blob/main/project/Build.scala#L85-L91. In this case, we only check `"backward"` and not `"both"` which is correct behavior.

**Review by bishabosha — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@sjrd do you see any source or binary compatibility issue with this change? We add some new methods and the possibility of getting a mirror for `EmptyTuple`.

**Comment by sjrd** [comment]
It changes the public API, so it's definitely source incompatible (backward and forward).
It's also definitely forward binary incompatible.

It should be backward binary compatible, though.

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
