### PR TITLE
Crash when calling Compiler.newRun() without a docCtx

### PR DESCRIPTION
**Pull request by GavinRay97**
Changes based on suggestion in the issue:
- https://github.com/lampepfl/dotty/issues/12998#issuecomment-873270695

And the implementation currently seen here:
https://github.com/lampepfl/dotty/blob/79fae194b80e136a243e7c7f949268166d169e1e/compiler/src/dotty/tools/dotc/typer/Namer.scala#L449

### CODE REVIEW

**Comment by som-snytt** [comment]
You'll want to squash and force push one clean commit. But the change looks idiomatic.

It would be nice if the `docCtx.get` in TreePickler were idiomatic so grep doesn't notice it; that follows an assert.  There is a `getOrElse throw` in QuotesImpl.

**Comment by smarter** [comment]
It looks like you haven't signed the CLA yet, would you mind doing so at https://www.lightbend.com/contribute/cla/scala ?

**Comment by GavinRay97** [comment]
Apologies for the delay, have signed the CLA.

Somewhat embarrassingly, though I use git every day for years, I'm not well-versed beyond basic checkout/commit/pull/branch/push.

To squash and force-push as a single commit, would be something like this?
```sh
$ git rebase -i HEAD~2 # Interactive rebase last 2 commits on local
# Select "Squash" from prompt
$ git commit
$ git push -f
```
Or
```sh
git reset --soft HEAD~2 && git commit
git push -f
```

**Comment by smarter** [comment]
There's multiple ways to do it, if you squash using `git rebase -i`, it will prompt you for the commit message of the squashed commit and generate it itself, so you don't need to `git commit` afterwards, but you'll indeed need to do `git push -f`.

**Comment by GavinRay97** [comment]
Okay I think I managed to get it sorted out. Let me know if it's still not right and we can give this a go again 😅

**Comment by smarter** [comment]
It looks good but to have the issue be automatically closed when this PR is merged, you need to include "Fixes #12988" somewhere in the body of the commit message (also this is nitpicking but ideally the first line of the commit message would be a bit more descriptive of what is being fixed e.g., "Fix crash when calling Compiler.newRun() without a docCtx")

**Comment by smarter** [comment]
By the way, you can edit just the commit message by doing `git commit --amend` (and then `git push -f` again)

**Comment by GavinRay97** [comment]
> By the way, you can edit just the commit message by doing `git commit --amend` (and then `git push -f` again)

Thank you for this, I didn't know this and this definitely helps a lot. 
Gimme two seconds, commit incoming =)

**Review by smarter — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
