### PR TITLE
Fix #1818: Whitelist Function1 and Function2

### LINKED ISSUE #1818: Whitelisting scala.Function1 fails to compile in partest.
When running partest with `Function1` whitlisted the following error is reported:
```scala
-- Error: /Users/nicolas.stucki/GitHub/dotty/tests/partest-generated/pos/compileStdLib/Function1.scala -----------------
35 |trait Function1[@specialized(scala.Int, scala.Long, scala.Float, scala.Double) -T1, @specialized(scala.Unit, scala.Boolean, scala.Int, scala.Float, scala.Long, scala.Double) +R] extends AnyRef { self =>
   |                ^^^^^^^^^^^^
   |                cyclic reference involving constructor specialized
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by DarkDimius** [comment]
LGTM after the tests pass. Curious to know if the cyclic reference error was fixed(and how), or we just compile files in different order know.

**Comment by nicolasstucki** [comment]
This was a bootstrap issue, we did a lot of improvements since it was blacklisted.

**Comment by DarkDimius** [comment]
@nicolasstucki CI disagrees with you.

**Comment by nicolasstucki** [comment]
@DarkDimius I ran all the CI tests on my machine before sending this PR. I will have to double check :(

**Comment by nicolasstucki** [comment]
@DarkDimius my machine disagrees with CI. Again...

**Comment by DarkDimius** [comment]
@nicolasstucki, different order of files? One of the reasons whitelist existed before is that it also provided a specific order of files.

**Comment by nicolasstucki** [comment]
I will try adding an order to the files. One that does not depend on the filesystem.

**Comment by DarkDimius** [comment]
@nicolasstucki I propose to order not by the file name, but instead by class name.
The reason is due to way people report bugs. They rarely post file names.

**Comment by smarter** [comment]
We already have some code to order by filename, but I guess it's not used everywhere: https://github.com/lampepfl/dotty/pull/2193
I'd like to keep ordering things by filename because I have at least one test which relies on it.

**Comment by nicolasstucki** [comment]
Will close this PR for now. This is not a priority.

**Pull request closed without merging**
