### PR TITLE
Bump sbt version in community projects

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Review by smarter — CHANGES_REQUESTED** [review]
Editing every submodule shouldn't be needed, the sbt version used by the community projects is determined by https://github.com/lampepfl/dotty/blob/2b74f88ec3ca079f1ab9d99f69b29b910d53554a/community-build/src/scala/dotty/communitybuild/projects.scala#L143

**Comment by prolativ** [comment]
The point is I'm trying to build all our currently maintained community projects using our new community build approach, which by design modifies the build definitions as little as possible and it doesn't override sbt version (this could potentially be changed but the initial idea was that if a project builds successfully in the community build and the compiler version used in the build gets published it should be enough to bump the compiler in the original repository and it should still build successfully).
Of course we won't be modifying all submodules every time new sbt gets published but this fix from 1.5.5 https://github.com/sbt/librarymanagement/pull/384 is quite important for the new community build to run correctly

**Comment by prolativ** [comment]
BTW any idea what I might have done wrong that submodules are not fetched properly in the community build tests?

**Comment by smarter** [comment]
> which by design modifies the build definitions as little as possible and it doesn't override sbt version 

I thought the idea was to use the projects from upstream exactly as they are, if you are going to modify these projects anyway then it's much better to pass a flag than to modify them all one-by-one, the latter approach makes it much harder to keep in sync with upstream, so I wouldn't want to adopt it in our current community build.

> BTW any idea what I might have done wrong that submodules are not fetched properly in the community build tests?

I don't know, seems like the commits weren't pushed to the corresponding repositories on dotty-staging

**Comment by prolativ** [comment]
We don't modify any existing files in projects. We only inject a single file containing the implementation of our sbt plugin, which is responsible for building a project and collecting some statistics. The only modifications of the build definition performed by the plugin are adding a resolver for other artifacts produced in the same build run and enforcing the scala version.
I don't expect any further modifications in community projects' forks necessary to make the new community build work for them

**Comment by smarter** [comment]
I still recommend passing -sbt-version over modifying the submodules, this is much easier to maintain.

**Pull request closed without merging**
