### PR TITLE
Fixes&Changes to TASTY inspired by Linker

### PR DESCRIPTION
**Pull request by DarkDimius**
Most of those changes allow new phases to introduce new sections&trees
after `Pickling` as well as read those sections after `FromTasty`.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@VladimirNik please review.

**Comment by DarkDimius** [comment]
@VladimirNik the code I shared with you in https://gist.github.com/DarkDimius/0f9dc769b0dd7a3c7365 should start working after this PR gets merged.

**Comment by VladimirNik** [comment]
LGTM after tests succeed

**Pull request merged**
