### PR TITLE
First steps to support dependent matches

### PR DESCRIPTION
**Pull request by gsps**
This PR is based on our ongoing work to add dependent types via the `TypeOf` encoding and extends #4806.

At the moment this branch only affects the precision of types given to bindings inside of match patterns. For instance, given
```scala
dependent def headOfCons1 =
  Cons(1, Cons(2, Nil)) match {
    case Cons(x, _) => x
  }
```
we can now reason about the extracted `x` in relation to the scrutinee `Cons(1, Cons(2, Nil))`, so that
```scala
headOfCons1: 1
```
can be proven by the type checker.

Note that this PR currently does not do any reduction of matches on the type level, so a match with multiple cases will not behave any differently yet.

### CODE REVIEW

**Comment by odersky** [comment]
@gsps @OlivierBlanvillain Inactive for 3 months with lots of accumulated conflicts. Should we close this now?

**Comment by OlivierBlanvillain** [comment]
We still indent to work on this PR. It's currently work in progress on is builds on top of #4806 and #4671 which where both indented as intermediate reviewable/mergable milestones. I guess we can close #4806 as resolving conflicts on an intermediate state would not be a very good use of time...

**Comment by odersky** [comment]
@OlivierBlanvillain OK, please go ahead and close #4806.

**Comment by b-studios** [comment]
@OlivierBlanvillain do you still intend to merge this / work on this?

**Pull request closed without merging**
