### PR TITLE
Document how to build a snapshot distribution

### PR DESCRIPTION
**Pull request by japgolly**
Yes the instructions are easy but it takes a bit of digging to find these easy instructions.

### CODE REVIEW

**Comment by michelou** [comment]
> Yes the instructions are easy but it takes a bit of digging to find these easy instructions.

@japgolly IMHO assuming the new section `Building a Local Distribution` you proposes gets accepted it should *also mention* the way to build a snapshot distribution using `sbt` even if some test cases fail (e.g. on MS Windows there are currently 3-4 failing tests).
**PS.** Concretely I build snapshot distributions on MS Windows since Dotty 0.7.

**Comment by japgolly** [comment]
@michelou Hmm I had a look around and I'm not quite sure how to do that. If someone in the know can share the instructions I'd be happy to include them in this PR.

**Review by OlivierBlanvillain — APPROVED** [review]
LGTM, thanks!

**Comment by OlivierBlanvillain** [comment]
Actually, I think the root README might be a bit too expose for this, how about moving it to the "Getting Started as Contributor" page?

**Comment by michelou** [comment]
> Actually, I think the root README might be a bit too expose for this, how about moving it to the "Getting Started as Contributor" page?

Perfectly fine for me. For instance I have [`README.md`](https://github.com/michelou/dotty-examples/blob/master/README.md) and [`BUILD.md`](https://github.com/michelou/dotty-examples/blob/master/BUILD.md) in my [`dotty-examples`](https://github.com/michelou/dotty-examples) repo.

**Pull request merged**
