### PR TITLE
Fix #7636: Put new types in refinements under a language flag

### LINKED ISSUE #7636: Put structural type refinements with type members under a language flag.
If we have refinement types such as
```scala
C { type T = U}
{ type T }
```
it should be checked that the type member `T` does refine a type member in the parent type of the refinement (i.e. `C` or `Any` above). If it is a new type that does not refine anything, this should only be allowed under a language import such as
```scala
import language:newTypesInRefinements
```
### Why Put It Under a Flag?

1. Neither `nsc` nor `dotc` are really made for handling it correctly. It's an afterthought in both of them, and a constant source of bugs. This is because normal code usually does not exercise the feature. 

2. It's prone to hide mistakes. For instance, I detected in `dotc`
```scala
lastSymbol.asInstanceOf[Designator{ type ThisName = self.ThisName }]
```
Type `Designator` does not have a member `ThisName`, so the type refinement is just confusing. 

3. It's prone to abuse, an open invitation to obscure type hackery. Often, it would be perfectly possible to put the types as schemas into the parent class of a refinement, and this would help documentation and the type checker. But since it's shorter there's a temptation to just leave it out. 

### Why Keep the Feature?

Basically, because DOT allows it. However, DOT does not talk about decidability, so it's fair to restrict the feature if decidability cannot be guaranteed.

### PR DESCRIPTION
**Pull request by odersky**
From the doc page:

## Type Members in Structural Types

Scala-2 allowed new type members in refinement types where the type members do not
override or refine anything in the parent type. Examples are:

```scala
Seq { type Helper = U}   // `Seq` does not contain a definition of `Helper`
{ type T }
```

These constructs are now available only under language feature `newTypesInRefinements`. As usual the feature can be enabled by an import
```scala
import language.newTypesInRefinements
```
or by a command-line option `-language:newTypesInRefinements`. If the feature is not enabled the compiler will issue a feature warning.

### Why Put The Construct Under a Flag?

Idiomatic Scala allows to refine only existing member types. This leads to code that is better documented and easier to typecheck. The support in the Scala compiler for this feature is less mature than the rest of the type checker.

### Why Not Drop it Entirely?

New type members in refinements are allowed by DOT, the calculus that underpins Scala. However, it should be noted that DOT does not provide a decision algorithm that can be used for type checking. So having only second-class support for the construct is defensible.

### CODE REVIEW

**Comment by milessabin** [comment]
Another construction which is affected by this,

```scala
def foo[T <: { type U }](t: T): T = t
```
Requires the language import after this change.

**Comment by milessabin** [comment]
Another example which I think should be accepted without a warning or a language import,

```scala
trait Foo
trait Bar extends Foo { type T }
trait Baz extends Foo { type T }

def foo[T0](bar: Bar { type T = T0 }, baz: Baz { type T = T0 })(cond: Boolean): Foo { type T = T0 } =
  if (cond) bar else baz
```
The type `Foo { type T = T0 }` is inferred as the type of the conditional, so why can't it be written by the programmer?

**Comment by odersky** [comment]
@milessabin You mentioned that for Shapeless the problem is in the (nested) `Kind` type.
```scala
  type Kind[C <: Mirror, O[_[_]]] = C { type Kind = K11.type ; type MirroredType = O ; type MirroredElemTypes[_[_]] }
```
What do you think of either of the following approaches:

 - Put `type Kind <: Singleton` in `Mirror`. It does not have to be instantiated by the compiler, it's OK to leave the type abstract. 

 - Or, invent a new supertrait
```scala
trait Kinded { type Kind <: Singleton }
```
and define
```scala
  type Kind[C <: Mirror, O[_[_]]] = Kinded & C { type Kind = K11.type ; type MirroredType = O ; type MirroredElemTypes[_[_]] }
```

**Comment by odersky** [comment]
> The type Foo { type T = T0 } is inferred as the type of the conditional, so why can't it be written by the programmer?

Actually, the inferred type is just `Foo`.

**Comment by milessabin** [comment]
> What do you think of either of the following approaches

Either of them would fix shapeless. I did have something similar to `type Kind` in `Mirror` at one point, and that would be my preference if that's what we have to do.

> Actually, the inferred type is just `Foo`.

The inferred type is widened if it's assigned to a val. But with the refinement in the expected type the inferred type is as I said. This works right now in both Scala 2 and Dotty, and I'd be very surprised if there isn't quite a lot of code which relies on it.

**Comment by odersky** [comment]
> The inferred type is widened if it's assigned to a val. But with the refinement in the expected type the inferred type is as I said. This works right now in both Scala 2 and Dotty, and I'd be very surprised if there isn't quite a lot of code which relies on it.

Correct. But then the type is still written out by the user. If the type had simply been inferred there would be a good argument that it should not be subject to a language flag. But since the type is written explicitly that particular argument does not apply.

**Comment by odersky** [comment]
I see insufficient support for this at the moment. Let's close for now and keep the option to revisit depending on how things develop.

**Pull request closed without merging**
