### PR TITLE
Add -nowarn option to silence warnings

### LINKED ISSUE #2351: Implement "-nowarn" flag
It would be beneficial to be able to silence all warnings by adding the `-nowarn` flag.

* Add a `BooleanSetting` for `-nowarn` to [ScalaSettings](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala)
* Edit [Reporter#reportWarning](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/reporting/Reporter.scala#L40-L42) to do nothing if the flag is set e.g: `if (this.settings.nowarn) ()`

### PR DESCRIPTION
**Pull request by markus1189**
This was too low hanging fruit to resist ;)

Fixes #2351

### CODE REVIEW

**Comment by felixmulder** [comment]
Looks great to me!

Would you mind adding a test in a second commit? One way to test this would be to combine `-nowarn -Xfatal-warnings` and add a test to `./tests/pos-special/` that generates a warning.

The behaviour should be such that the warning would be fatal if issued, but since it's canceled out by `-nowarn` the test should compile without errors.

Would you mind adding that? Otherwise I'm fine with merging as is :tada:

Another way to test it would be to add a test to [ErrorMessagesTests.scala](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala) (which should be renamed to `MessageTests`). But maybe that's overkill :)

**Comment by markus1189** [comment]
Sure I'll add it, I'll ping you when I gave a good test ;)

**Comment by nicolasstucki** [comment]
@markus1189 you should name the commit `Fix #2351: Add -nowarn option to silence warnings.`, this way when we merge this PR the issue will be closed with it.

**Comment by markus1189** [comment]
Okay I added it to `CompilationTests` and reused the `-Xfatal-warnings` file to write an additonal tests that with `-nowarn` it does pass instead of fail.  I chose this because it is easier than propagating the settings in a way that is convenient to use in `ErrorMessagesTests`.

**Comment by felixmulder** [comment]
Thanks a bunch @markus1189! :tada:

**Comment by smarter** [comment]
There's an empty file ` tests/pos-special/nowarn.scala` in this PR, I don't think that's intentional.

**Comment by felixmulder** [comment]
Seems to have disappeared magically...

**Pull request merged**
