### PR TITLE
Fix 10156: Put generic number literals under a flag

### PR DESCRIPTION
**Pull request by odersky**
Actually, under a language import

    language.experimental.genericNumberLiterals

### CODE REVIEW

**Comment by soronpo** [comment]
Don't forget to mention this flag is required in https://dotty.epfl.ch/docs/reference/changed-features/numeric-literals.html

**Comment by sjrd** [comment]
We should add a `neg` test that makes sure that the feature is not accidentally enabled if the language import is not present. I suggest the following:
```scala
import scala.util.FromDigits

object Test extends App {

  val x: BigInt = 13232202002020202020202 // error
  val z: BigDecimal = 132322020020.223 // error

  case class Even(n: Int)

  given FromDigits[Even] {
    def fromDigits(digits: String): Even = {
      val intValue = digits.toInt
      if (intValue % 2 == 0) Even(intValue)
      else throw FromDigits.MalformedNumber()
    }
  }

  val e: Even = 1234 // error

  try {
    println(123: Even) // error
  } catch {
    case ex: FromDigits.MalformedNumber => println("malformed")
  }

  x match {
    case 13_232_202_002_020_202_020_202 => () // error
  }
  (x: Any) match {
    case 13232202002020202020202: BigInt => () // error
  }
  x match {
    case 13232202002020202020202 => assert(false) // error
    case -0xaabb12345ACF12345AC => () // error
  }

  (e: Any) match {
    case 1234: Even => // error
    case _: Even => // error
  }
}
```

**Comment by bishabosha** [comment]
should there be a follow up to move the `FromDigits` class to another package/lib or is it generally useful enough to keep in the library

**Comment by odersky** [comment]
> should there be a follow up to move the FromDigits class to another package/lib or is it generally useful enough to keep in the library?

I had a look at it, but then decided that the downsides would be too high.

 - it's used by the compiler itself
 - it's used in the community build (scodec)

So, moving it elsewhere would cause a lot of breakage, for no apparent gain. The functionality to convert a digit string into some given type is useful.

Also it's not like generic number literals have been rejected. They have been deferred since they are non-essential for 3.0. I suspect they'll make a comeback.

**Review by bishabosha — APPROVED** [review]
Looks good to me

**Pull request merged**
