### PR TITLE
Community build: add cats and update cats-effect

### LINKED ISSUE #10478: cats-effect-* is broken in the community build after bump to 3.0.0-RC1
Looks  like a flaw in the build files somewhere, I have not looked further

```
Error:  scala.MatchError: 3.0.0-RC1-bin-SNAPSHOT (of class java.lang.String)
Error:  Use 'last' for the full log.
Error:  Test dotty.communitybuild.CommunityBuildTestB.catsEffect2 failed
```

### PR DESCRIPTION
**Pull request by griggt**
An alternative to #10587.

Updates cats-effect-2 and cats-effect-3 in the community build to latest upstream. Rather than modifying upstream to use `withDottyCompat` as was done in #10587, here we add the dependencies to the community build.

Projects added:

|  Name |  Reason
| ----- |---|
| [cats](https://github.com/typelevel/cats) |
| [discipline](https://github.com/typelevel/discipline) | dependency of cats
| [discipline-munit](https://github.com/typelevel/discipline-munit) | dependency of cats and cats-effect-2
| [discipline-specs2](https://github.com/typelevel/discipline-specs2) | dependency of cats-effect-3
| [simulacrum-scalafix](https://github.com/typelevel/simulacrum-scalafix) | dependency of cats
| [cats-mtl](https://github.com/typelevel/cats-mtl) | transitive dependency of cats-effect-3
| [coop](https://github.com/typelevel/coop) | dependency of cats-effect-3

Fixes #10478

### CODE REVIEW

**Review by smarter — APPROVED** [review]
LGTM, this is super useful, thank you!

**Comment by smarter** [comment]
I find it weird that running JS tests can exhaust the JVM heap, wdyt @sjrd ? Tests should be running using node and not rhino right?

**Comment by griggt** [comment]
The GC thrashing seems to be triggered by:

```
[info] Fast optimizing /src/dotty/community-build/community-projects/cats/free/.js/target/scala-3.0.0-M3/cats-free-test-fastopt
```

**Comment by griggt** [comment]
Disabling full optimization for the Scala.js tests in cats seems to have solved the GC thrashing issue.

On another note, we'll need to fork all the added projects to dotty-staging if we want to merge this.

**Comment by smarter** [comment]
> On another note, we'll need to fork all the added projects to dotty-staging if we want to merge this.

Ah yes, I think you should be able to create the forks since you're a member of the org.

**Comment by smarter** [comment]
> Disabling full optimization for the Scala.js tests in cats seems to have solved the GC thrashing issue.

Until/unless this is merged upstream, we could do this in the community build config itself with `set scalaJSStage in Global := FastOptStage` so we don't have to diverge from upstream in the submodule.

**Comment by griggt** [comment]
> since you're a member of the org.

am I?  I only see collaborator access on dotty-staging/cats-effect, and am not seeing the option to fork to the dotty-staging org.

**Comment by smarter** [comment]
Oops I thought you did, you should have access now.

**Review by smarter — APPROVED** [review]
>  Dotty CI / community_build_b (pull_request) Successful in 71m 

This is now much longer than community_build_a, maybe we should move some other projects to _a to balance things out?

**Pull request merged**
