### PR TITLE
Scaladoc: fix issues with incorrect external links and special characters

### LINKED ISSUE #14505: Broken link for #:: on the Scaladoc website search results
When searching for the `#::` object on the [API documentation website](https://scala-lang.org/api/3.x/), the link doesn’t lead to the correct URL (I get a 404 page when clicking on it).

The URL that I currently get is:
```
https://scala-lang.org/api/3.x/scala/#::$.html
```

In order for the link to work, it should rather lead to:
```
https://scala-lang.org/api/3.x/scala/%23::$.html
```

image

### PR DESCRIPTION
**Pull request by jchyb**
This includes escaping certain characters found in searchbar links (1st commit) and correctly resolving external links (2nd commit).

Fixes #14505 and #14504.

### CODE REVIEW

**Review by pikinier20 — CHANGES_REQUESTED** [review]
The changes look good but something is broken. Searchbar in generated docs doesn't work (no entries after opening) and is throwing errors to console: 
image

**Comment by jchyb** [comment]
Thank you for spotting this as this was not something that happened locally, now I've updated the PR with fixes. I no longer use new URI(_).isAbsolute() as URI parsing seemed to be the issue. Instead, an additional filed for searchData was added describing whether the searchData contains an internal link or one to the external website.

A similar technique with URIs was employed in a previous PR with Inkuire and, as it turns out, the issues would also happen there (just much more rarely), so I updated that in a separate commit. Unfortunately, as I could not add any new fields there the solution ended up being a little "hacky", but I hope it is at least explained elegantly in the comment.

**Review by pikinier20 — APPROVED** [review]
Good job!

**Comment by Nicolapps** [comment]
Thank you for the fixes!

**Pull request merged**
