### PR TITLE
Add ReactiveMongo-BSON to community-build

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by smarter** [comment]
```scala
[error] -- Error: /__w/dotty/dotty/community-build/community-projects/ReactiveMongo-BSON/api/src/main/scala-3/MacroImpl.scala:478:25 
[error] 478 |      val underlying = f(self)
[error]     |                         ^^^^
[error]     |Cannot prove that the value is fully initialized. May only use initialized value as arguments.
```
You should be able to reproduce this failure in your project locally by compiling with `-Ysafe-init` which is enabled by default in the community build, see https://dotty.epfl.ch/docs/reference/other-new-features/safe-initialization.html for more information (in particular it mentions that `@unchecked` can be used to suppress initialization checks if needed).

**Comment by cchantep** [comment]
Now [failure](https://github.com/lampepfl/dotty/runs/4674607611?check_suite_focus=true#step:8:6152) seems unrelated:

    Failed projects:
     - dotty.communitybuild.CommunityBuildTestA.zio

> Also: https://github.com/lampepfl/dotty/issues/14195

**Comment by smarter** [comment]
> [error]    |scala.quoted.runtime.impl.ScopeException: Expression created in a splice was used outside of that splice.

I assume this is because the community build is run with -Xcheck-macros, so this indicate a real problem in the original project

**Comment by cchantep** [comment]
> > [error]    |scala.quoted.runtime.impl.ScopeException: Expression created in a splice was used outside of that splice.
> 
> I assume this is because the community build is run with -Xcheck-macros, so this indicate a real problem in the original project

I disagree, as indicated in another issue, this option is raising false error.

**Comment by nicolasstucki** [comment]
>>> [error] |scala.quoted.runtime.impl.ScopeException: Expression created in a splice was used outside of that splice.

>> I assume this is because the community build is run with -Xcheck-macros, so this indicate a real problem in the original project

> I disagree, as indicated in another issue, this option is raising false error.

With a quick look over [MacroImpl.scala](https://github.com/ReactiveMongo/ReactiveMongo-BSON/blob/f4e89d98eeb92e27b34a0eab45b5dd7c4180ee29/api/src/main/scala-3/MacroImpl.scala) I saw that use usual `QuotesHelper` helper antipattern has used. This is most likely the cause of the failure as it decontextualizes the `Quotes` context by cashing some instances of it. Therefore all scopes are not correctly tracked causing the `-XcheckMacros` to fail and quadratic times when expanding quotes (to fix wrong owners).

The solution is to always pass the `Quotes` context as a context.

**Pull request closed without merging**
