### PR TITLE
Moved literal message into error Message class

### PR DESCRIPTION
**Pull request by insdami**

### CODE REVIEW

**Comment by felixmulder** [comment]
Hey @insdami! You need to configure git to use your github email (that's why your avatar is not on the commit)

This is also so we can check that you've signed the Scala CLA. Thanks for the PR!

**Comment by insdami** [comment]
Ops! Sorry about that @felixmulder, I'm using work's laptop. I guess the easiest thing to do it's create the PR again, right?

**Comment by felixmulder** [comment]
@insdami - np, whichever!

Here's how to do it using a rebase: https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by felixmulder** [comment]
Thanks for the PR @insdami! :tada:

**Pull request merged**
