### PR TITLE
Scala3doc: cook comments

### PR DESCRIPTION
**Pull request by abgruszecki**
Resolve @define-s and expand @inheritdoc-s.

### CODE REVIEW

**Comment by abgruszecki** [comment]
There are still problems with some definitions in the standard library. The issue is that we don't correctly attach the comment to some trees. I'll fix this in a separate PR.

**Comment by abgruszecki** [comment]
See https://scala3doc.virtuslab.com/pr-10506/scala3-stdlib/-scala%203/-a-p-i/scala/collection/immutable/-list$.html vs https://scala3doc.virtuslab.com/pr-master/scala3-stdlib/-scala%203/-a-p-i/scala/collection/immutable/-list$.html .

**Comment by abgruszecki** [comment]
All issues with attaching comments are now fixed, all missing variable warnings when documenting stdlib are genuine.

**Comment by abgruszecki** [comment]
@odersky I needed to modify the scanner to attach docstrings in some cases where it not attach them before. Can you quickly review https://github.com/lampepfl/dotty/pull/10506/commits/60a8b7224d25183fde1cef5a5902449c8f522e40 (and only that commit)?

**Review by romanowski — APPROVED** [review]

**Comment by romanowski** [comment]
I was a bit merge-happy here, sorry. I can revert this merge or apply fixes if changes in parser needs them.
cc @odersky

**Pull request merged**
