### PR TITLE
Don't clone entire scala/scala commit history for submodules

### PR DESCRIPTION
**Pull request by DarkDimius**
Makes cloning a new repo substantially faster

### CODE REVIEW

**Comment by smarter** [comment]
It would be nice if we could do this on the CI too.

**Comment by dwijnand** [comment]
```
git:
  submodules_depth: 100
```

https://github.com/travis-ci/travis-build/pull/251#issuecomment-254786875

**Comment by smarter** [comment]
@dwijnand Thanks for the info, but we use drone and not travis for our main CI.

**Comment by smarter** [comment]
Limiting the depth of the submodules does not seem to work, the commits for the branch we're interested in are not fetched:
```shell
% git submodule update --init --depth=50
Submodule 'collection-strawman' (https://github.com/scala/collection-strawman.git) registered for path 'collection-strawman'
Submodule 'scala-backend' (https://github.com/lampepfl/scala.git) registered for path 'scala-backend'
Submodule 'scala2-library' (https://github.com/lampepfl/scala.git) registered for path 'scala2-library'
Cloning into '/home/smarter/opt/dotty3/collection-strawman'...
Cloning into '/home/smarter/opt/dotty3/scala-backend'...
Cloning into '/home/smarter/opt/dotty3/scala2-library'...
Submodule path 'collection-strawman': checked out 'c7b52041058c8aa4fb36376b5f6e9188acd1f4e9'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: no such remote ref fd40234ba42430682c1c4d3456ea8bc861537734
Fetched in submodule path 'scala-backend', but it did not contain fd40234ba42430682c1c4d3456ea8bc861537734. Direct fetching of that commit failed.
```

So I'm closing this now.

**Pull request closed without merging**
