### PR TITLE
Fix #1214: PolyType return types may need wrapping with ExprType

### LINKED ISSUE #1214: Polymorphic methods without term params don't have MethodType
This issue is related to #1046 and PR #1205. It's expected that all methods have either `MethodicType` or `PolyType(MethodicType)`.

However, this is not true in current dotty. Given following simple program:

```Scala
class Test {
  def foo[T] = 5
}
```

The method `foo` takes a non-method type `[T]Int`. The full type signature for `foo` is as follows:

```
PolyType(
     List(T),
     List(
         TypeBounds(
             TypeRef(ThisType(TypeRef(NoPrefix,scala)),Nothing),
             TypeRef(ThisType(TypeRef(NoPrefix,scala)),Any)
          )
     ),
     TypeRef(ThisType(TypeRef(NoPrefix,scala)),Int)
)
```

Is this an intentional design or a bug?

### PR DESCRIPTION
**Pull request by DarkDimius**
Namer.methodType is used to get type of method given types of arguments,
    type parameters and return type.
    It has a special case if method does not take arguments that wraps return
    type with ExprType.
    Such wrapping needs to be also performed in case method has type
    parameters.

### CODE REVIEW

**Comment by DarkDimius** [comment]
Ping @liufengyun, please check if this fixes Y-check failure
@odersky please review.

**Comment by liufengyun** [comment]
Just checked, this PR fixed the Y-check failure in #1205. Good job @DarkDimius !

**Comment by odersky** [comment]
That's not how types are supposed to be modeled. The function 

    def f[T]: U

should have type `PolyType(<T>, <U>)`, not `PolyType(<T>, `ExprType<U>`)`. That's the assumption everywhere and we should not change it.

**Comment by DarkDimius** [comment]
@odersky, would you mind explaining intension behind this design decision?
It seems natural to me to assume that return type of a `PolyType` is a `MethodicType`.
It would be also great of you could share your mind beind `def f: U` being `ExprType<U>` instand of simpy `<U>`.

**Pull request closed without merging**
