### PR TITLE
Add test for errors involving module classes

### PR DESCRIPTION
**Pull request by odersky**
Ideally, we should make this into a proper test with check files.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Why didn't you add the `tests/neg/module-class-name.check` check file?

**Comment by odersky** [comment]
> Why didn't you add the tests/neg/module-class-name.check check file?

I never can figure out how to generate that check file in the first place. Can you add it?

**Comment by nicolasstucki** [comment]
Done.

To add those, add the check file and run the test with `--update-checkfiles`
```bash
$ touch tests/neg/module-class-name.check
$ sbt 
> testCompilation tests/neg/module-class-name.scala --update-checkfiles
```

`testCompilation --help` could be used to remember the command.


@anatoliykmetyuk could you have a look at how we could make the checkfile creation process simpler?

**Comment by anatoliykmetyuk** [comment]
@nicolasstucki ok, I'll have a look at it.

**Comment by biboudis** [comment]
And document it somewhere as well! 🙈

**Comment by nicolasstucki** [comment]
`testCompilation --help` might be a good place to add extra documentation.

**Comment by anatoliykmetyuk** [comment]
The issue with testCompilation is that sometimes you need testOnly.

**Pull request merged**
