### PR TITLE
Fix #9664: check outer of warm values

### LINKED ISSUE #9664: -Ycheck-init promoting value to fully initialised when passed to array
## Minimized code

```Scala
// compile with -Ycheck-init
object Wrap1 {                                                                              
  class E
  object E {
    final val A = E()
    val $values = Array(A)
  }
}
object Wrap2 {                                                                              
  class E
  object E {
    final val A = E()
    val ref = A
  }
}
```

## Output

```scala
-- Warning: initcheck.scala:5:23 ----------------------------------
5 |    val $values = Array(A)
  |                        ^
  |Promoting the value under initialization to fully-initialized. Calling trace:
  | -> val $values = Array(A)	[ initcheck.scala:5 ]
1 warning found
```

## Expectation

I thought that directly referencing the value should have the same behaviour as passing it to an array constructor

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #9664: check outer of warm values

### CODE REVIEW

**Comment by bishabosha** [comment]
this still makes the warning when A is defined by new anonymous class:
```scala
class Wrap3 {
  class E
  object E {
    final val A = new E {}
    val ref = Array(A)
  }
}
```

**Review by bishabosha — CHANGES_REQUESTED** [review]
this still makes the warning when A is defined by new anonymous class:
```scala
class Wrap3 {
  class E
  object E {
    final val A = new E {}
    val ref = Array(A)
  }
}
```

**Comment by liufengyun** [comment]
Leaking inner class instances could lead to errors:

```Scala
class Wrap3 {
  def qux(e: E) = e.foo

  class E
  object E {
    final val A = new E { def foo = ref }
    val ref = qux(A)
  }
}
```

Generally, checking safe early promotion of inner class instances is expensive (it needs to go through all the code in its body and its parents), thus currently the checker deems such leaking as unsafe. However, improvements are envisioned to check _small inner classes_ to improve usability.

**Comment by bishabosha** [comment]
ah I see that `scala.runtime.EnumValues.register` was previously added in `Checker.ignoredMethods` which would cover the `$new` method for enums, do you think that instead we could add `Array.apply` ?

**Comment by liufengyun** [comment]
> ah I see that `scala.runtime.EnumValues.register` was previously added in `Checker.ignoredMethods` which would cover the `$new` method for enums, do you think that instead we could add `Array.apply` now that `scala.runtime.EnumValues` is no longer used?

Adding `Array.apply` as ignored opens a big door for unsafety. If such code is safe in the case of enums, you can use `A : @unchecked` to silence the checker.

**Comment by bishabosha** [comment]
ah very cool, thanks

**Review by bishabosha — APPROVED** [review]
LGTM

**Pull request merged**
