### PR TITLE
fixo

### PR DESCRIPTION
**Pull request by ferhtaydn**
convert from procedure to function :)

### CODE REVIEW

**Comment by ferhtaydn** [comment]
hey @felixmulder, I don't know why it is asking CLA to me. Some small fixes to the documentation.

**Comment by felixmulder** [comment]
@ferhtaydn - we legally cannot accept your code if you don't sign the CLA here: lightbend.com/contribute/cla/scala

We're working on something to resolve that, but in the meantime please sign :)

**Comment by ferhtaydn** [comment]
@felixmulder I has signed it long time ago but it was for scala repo if I don't remember wrong. Anyway, I signed the CLA. fyi.

**Comment by felixmulder** [comment]
@dotty-bot: recheck CLA please :heart:

**Comment by ferhtaydn** [comment]
:) Thank you @felixmulder 💯

**Pull request merged**
