### PR TITLE
[WIP] Scala with Explicit Nulls

### PR DESCRIPTION
**Pull request by abeln**
This PR sketches how to change the Scala type system so that reference types are no longer implicitly nullable. Instead, nullability can be recovered via union types (e.g. nullable strings have type `String|Null`).

See the accompanying doc for a description of the design: https://gist.github.com/abeln/9f79774bac111d99b3ae2cb9016a33e6

The changes include
  - a new type hierarchy where `Null <: Any` directly, and of no other type
  - a type "translation" layer for Java interop, to expose the true nullability of types in Java fields/methods
  - a simple form of flow-sensitive type inference to make it easier to work with nullable values

Unfortunately, the changes end up touching many components within the compiler (parser, typer, implicits, etc.), since assumptions about Null are baked in in many places. However, the code that
does the actually-interesting stuff is not much; most of the modified files are fixed tests.

There are still a few (very) important TODOs:
  1. fix all the 37 remaining failing tests (listed here https://pastebin.com/k5qbsrGn)
  2. port the Scala standard library to the new type system
  3. bootstrap Dotty with the new type system

However, before embarking on 2. and 3. we wanted to get feedback from the Dotty team and the community on how things are looking.

Any and all feedback is greatly appreciated!

### CODE REVIEW

**Comment by smarter** [comment]
Very cool! Before we get to reviewing this PR, it'd be helpful if it was cleaned up a bit, there's many commits like "fix tests" which are not really meaningful on their own. Ideally, commits in a PR should be atomic: serve a clear purpose detailed in their commit message, and pass all tests (we don't actually enforce that in the dotty repo currently). This PR also needs to be rebased.

Would it be possible to gate the invasive semantic changes of this PR behind a compiler flag ? This way we could merge it even if we're not sure if we'll accept it, and it'll allow more experimentation in the wild.

https://gist.github.com/abeln/9f79774bac111d99b3ae2cb9016a33e6 states that `JavaNull` is non-denotable. Could the documentation be expanded to justify this ? I'm personally very wary of inferring types that the users cannot write down or talk about, it makes it much harder for users to reason about their code.

**Comment by odersky** [comment]
@abeln I am excited about this PR! Its timing was bit unfortunate, since we just merged a large change how positions get computed which affected many lines. So it will take some effort to rebase, I am afraid.

**Comment by smarter** [comment]
It looks like the behavior of this proposal is being discussed at https://contributors.scala-lang.org/t/wip-scala-with-explicit-nulls/2761 which is just as well since it means we can limit the discussion on this PR to discussing the implementation.

**Comment by abeln** [comment]
@smarter I think we should be able to gate the changes behind a flag.

I don't know how to make the changes atomic, since the algorithm for developing the feature so far has been
1. change the type hierarchy
2. a million tests brake
3. add fixes to gradually fix the tests

Some test fixes involve changing just the tests, but others modify the compiler.
Even now there are a ~30 broken tests, one of which is the standard library.  

The one way to have a less atomic change, but one that keeps the tests passing, would be to squash all the commits into a one.

For _reviewing_ the PR, I think the best way is to go file-by-file, and not commit-by-commit. There's really not that much code to review _within_ the compiler.

So on my end, I can

1. gate the feature behind a flag
2. update the PR as per the changes proposed in the Scala contributors thread
3. fix all remaining positive and run tests
4. rebase

How does that sound?

**Comment by abeln** [comment]
Closing this for now while I rebase and fix the rest of the failing tests.

**Comment by AleksanderBG** [comment]
@abeln  - it might be useful for you to be aware of https://github.com/lampepfl/dotty/issues/4004. Current status quo is that `isInstanceOf[Null]` is permitted by Dotty, but should be rejected with an error (as is the case in Scalac). I saw suggestions on Scala contributors to equate `x == null` with `x.isInstanceOf[Null]` so in the case you go in that direction, please remember to update #4004 as well.

**Pull request closed without merging**
