### PR TITLE
fix #2996: remove useless Makefile in distributed archive

### LINKED ISSUE #2996: Purpose of the Makefile in the binary release
What's the purpose of the Makefile in the binary release? `./bin/dotr` worked fine without running `make`. When should you run make?

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #2996: remove useless Makefile in distributed archive

### CODE REVIEW

**Comment by allanrenucci** [comment]
Should we rebuild the Docker image since you upgraded a dependency?

**Comment by liufengyun** [comment]
@allanrenucci if the docker has network access or ivy mapping, then it seems fine.

**Comment by allanrenucci** [comment]
Sure it can download the updated dependency but it will slow down the build. Rebuilding the Docker will put it in the cache. I think. @felixmulder

**Comment by felixmulder** [comment]
Yes, you guys should totes rebuild ze cache :+1:

**Pull request merged**
