### PR TITLE
Make 1L == 1 an error under strict equality

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a PR for half of https://contributors.scala-lang.org/t/equal-protection-under-eq-law/4034 proposal.

### CODE REVIEW

**Comment by odersky** [comment]
I believe a change like this has to be thought through really well before we do it. It would have to be a separate SIP proposal. The way I see things today, I don't see myself championing such a proposal.

**Comment by eed3si9n** [comment]
What should I do beyond opening the Contributor thread and drafting a PR?

**Comment by odersky** [comment]
Hi Eugene, Sorry, I misunderstood the intent of this. I was not aware this was part of a planned SIP. 

Hmm, we should work out a scheme how to handle this. On the one hand, pre SIPs should come with an implementation, and a PR is the best way to make sure that the implementation works, since then it undergoes the CI. 

But on the other hand, we want to merge a SIP proposal only once it is well on the way of being accepted and we do not want to crowd our PR request queue with proposals that are not yet at this stage. 

It would be good to get ideas from others what the best way to proceed.

**Comment by eed3si9n** [comment]
> I was not aware this was part of a planned SIP.

Is there a SIP number or Contributor thread for Multiversal Equality? This is an implementation tweak on the idea, which also hopefully is compatible with Valhalla as well.

**Comment by odersky** [comment]
It does not have a SIP number (none of the Scala 3 additions do). A contributors thread should be opened soon. We basically open threads for 3 topics per month. But there's no long term scheduling of topics so I don't know when exactly equality will be discussed. Given that there is interest from you and maybe others there's a good reason to do it sooner rather than later.

**Pull request closed without merging**
