### PR TITLE
Fix #6909: Cache alias givens in lazy vals

### LINKED ISSUE #6009: Erased terms can't be passed to erased lambda argument
```scala
def foo(f: (erased Int) => Int): Int = {
  erased val ctx = 1
  f(ctx)
}
```
gives compilation error
> value ctx is declared as erased, but is in fact used

dotty version : 0.13-RC1

### LINKED ISSUE #6909: Defining a given referring to a given inside a trait crashes
## minimized code

```Scala
trait Foo[A]
trait Bar[A] { def foo: Foo[A] }

trait Qux[A] given (A: Bar[A]) {
  given as Foo[A] = A.foo
}
```
Giving it an explicit name doesn't help.

<details>
<summary>Stack trace</summary>

```scala
java.lang.AssertionError: assertion failed: method Foo_A_given$_cache while compiling foo.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: method Foo_A_given$_cache
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
        at dotty.tools.dotc.ast.tpd$TreeOps$.$anonfun$2(tpd.scala:969)
        at dotty.tools.dotc.core.Symbols$Symbol.orElse(Symbols.scala:600)
        at dotty.tools.dotc.ast.tpd$TreeOps$.becomes$extension(tpd.scala:971)
        at dotty.tools.dotc.transform.Getters.transformAssign(Getters.scala:88)
        at dotty.tools.dotc.transform.MegaPhase.goAssign(MegaPhase.scala:686)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:325)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:297)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:406)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:286)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:245)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:248)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:356)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:415)
        at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:427)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:316)
        at scala.collection.immutable.List.map(List.scala:286)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:318)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
        at dotty.tools.dotc.Run.compileSources(Run.scala:120)
        at dotty.tools.dotc.Run.compile(Run.scala:104)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:34)
        at dotty.tools.dotc.Driver.process(Driver.scala:172)
        at dotty.tools.dotc.Driver.process(Driver.scala:141)
        at dotty.tools.dotc.Driver.process(Driver.scala:153)
        at dotty.tools.dotc.Driver.main(Driver.scala:180)
        at dotty.tools.dotc.Main.main(Main.scala)

```
</details>

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
@nicolasstucki Can you take a look at this? I get:
```
-- Error: i3912_2.scala:5:21 ---------------------------------------------------
5 |  val a3: Unit = foo3()
  |                 ^^^^^^
  |Exception occurred while executing macro expansion.
  |java.lang.NoSuchMethodError: scala.quoted.Liftable$.Liftable_Int_delegate()Lscala/quoted/Liftable;
  |	at Macros$.impl(i3912_1.scala:10)
  |
  | This location is in code that was inlined at i3912_2.scala:5
one error found
```
But I get the same problem when I run this locally at master. So I am not sure what's to blame for it; maybe nothing in the PR itself.

**Comment by nicolasstucki** [comment]
If you switch to master you probably need to clean `out/bootstrap/dotty-library-bootstrapped`. To make it work again.

That call to `Liftable_Int_delegate` is [generated here](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala#L221). The definition of that delegate [is here](https://github.com/lampepfl/dotty/blob/master/library/src-bootstrapped/scala/quoted/Liftable.scala#L25).

I noticed that the signature in the bytecode changed from 
```java
public final PrimitiveLiftable<Object> Liftable_Int_delegate()
```
to 
```java
public final Liftable<Object> Liftable_Int_delegate()
```
This might be the source of the problem.

**Comment by odersky** [comment]
> I noticed that the signature in the bytecode changed from
```
public final PrimitiveLiftable<Object> Liftable_Int_delegate()
```
> to
```
public final Liftable<Object> Liftable_Int_delegate()
```
> This might be the source of the problem.

Yes, that looks likely. The new type, `Liftable`, is the correct one. If the result type should be `PrimitiveLiftable` the given instance has to be declared as one.

**Comment by nicolasstucki** [comment]
Sorry, I inverted the snippets. Master has `Liftable<Object>` and this branch has `PrimitiveLiftable<Object>`.

**Comment by nicolasstucki** [comment]
Yes, now the signature is wrong.

I forced it to have `Liftable` and it worked.

```scala
given Liftable_Int_delegate as Liftable[Int] = primitiveLiftable

private def primitiveLiftable[T <: Unit | Null | Int | Boolean | Byte | Short | Int | Long | Float | Double | Char | String]: Liftable[T] = new PrimitiveLiftable

private class PrimitiveLiftable[T <: Unit | Null | Int | Boolean | Byte | Short | Int | Long | Float | Double | Char | String] extends Liftable[T] {
  ....
}

**Comment by odersky** [comment]
OK, I am out of my wits here. dotty-library-bootstrappedJS fails with this error:
```
error] Illegal tree in gen of genInterface(): ValDef(OFFSET$_m_0,TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Long)],Apply(Select(Ident(LazyVals),getOffset),List(Literal(Constant(ClassInfo(NoPrefix, module class Liftable$, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object), TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Serializable))))), Literal(Constant(bitmap$0)))))
--
18376 | [error] (dotty-library-bootstrappedJS / Compile / compileIncremental) Compilation failed
```
It seems that it tries to generate a lazy val offset variable in an interface. The lazy val is probably generated from the given cache. But the generated lazy val seems to be exactly the same as a user-written. How can help and find out what the problem is? Maybe someone has a better idea what this could be. Or we need to start triaging to figure out exactly what file fails. It would be good to finally fix #6909 which has already tripped up several people.

**Comment by odersky** [comment]
Here's a more informative error message:
```
Illegal tree in gen of genInterface(): @scala.annotation.static() @scala.annotation.static() val OFFSET$_m_0: Long =
--
18388 | [error] dotty.runtime.LazyVals.getOffset(classOf[Object with Serializable {...}],
18389 | [error] "bitmap$0"
18390 | [error] )
18391 | [error] class = @scala.annotation.internal.SourceFile(
18392 | [error] "/tmp/2/library/src-bootstrapped/scala/quoted/Liftable.scala"
18393 | [error] ) trait Liftable() extends Object {
18394 | [error] @scala.annotation.static() private def <clinit>(): Unit =
18395 | [error] {
18396 | [error] Liftable.this.OFFSET$_m_0 =
18397 | [error] dotty.runtime.LazyVals.getOffset(classOf[Object with Serializable {...}]
18398 | [error] ,
18399 | [error] "bitmap$0")
18400 | [error] ()
18401 | [error] }
18402 | [error] def toExpr(x: Object): Function1
18403 | [error] def toExpr$direct(x: Object, x$0: scala.quoted.QuoteContext):
18404 | [error] scala.quoted.Expr
18405 | [error] @scala.annotation.static() @scala.annotation.static() val OFFSET$_m_0: Long =
18406 | [error] dotty.runtime.LazyVals.getOffset(classOf[Object with Serializable {...}],
18407 | [error] "bitmap$0"
18408 | [error] )
18409 | [error] }
18410 | [error] in /tmp/2/library/src-bootstrapped/scala/quoted/Liftable.scala
18411 | [error] (dotty-library-bootstrappedJS / Compile / compileIncremental) Compilation failed
```
The `OFFSET` field has the `static` annotation (twice!, no idea why) so it should be legal in an interface. 

@sjrd Can you suggest how to fix this?

We have an annoying problem here:

 - We need to fi #6009, urgently.
 - Lazyvals causes the current problem by inserting a static annotation that JS seemingly does not like.
 - Lazyvals will likely be rewritten soon, but we need a fix of #6009 before that happens.
 - The least path of resistance would be to disable Js generation for now, since we do not need it anyway.
 - Anybody has a better alternative?

**Comment by sjrd** [comment]
I will see what I can do today. I believe the easiest is actually to change the lazy val transform so that it generates something simpler for JS. The current scheme and the new proposed scheme are both unsuitable for JS, because they use `Unsafe`, and are completely overkill for a single-threaded environment anyway.

**Comment by odersky** [comment]
> I will see what I can do today. I believe the easiest is actually to change the lazy val transform so that it generates something simpler for JS. The current scheme and the new proposed scheme are both unsuitable for JS, because they use Unsafe, and are completely overkill for a single-threaded environment anyway.

Indeed. Maybe it's simplest to always assume @threadUnsafe for lazy vals under JS?

**Pull request merged**
