### PR TITLE
Update and reenable shapeless in community build

### PR DESCRIPTION
**Pull request by milessabin**
Fix breakage following #7210.

### CODE REVIEW

**Comment by milessabin** [comment]
@nicolasstucki this adapts shapeless to #7210, but I'm not clear if a fix for #7238 will break things.

Feel free to merge this now, or hold off until later.

**Comment by nicolasstucki** [comment]
I would suggest merging it. We can fix it while fixing #7238 or disable it temporarily again if it is a blocker.

@odersky WDYT?

**Comment by odersky** [comment]
@milessabin It would be best to wait until #7245 is in. Otherwise we have to disable it again for that one, or fix it on the fly. But I prefer it if you could do the fixes to adapt to the new style since it would be good to get feedback how the new style works in your case.

**Comment by milessabin** [comment]
@odersky that's fine. Ping me when #7245 is in its final form.

**Comment by milessabin** [comment]
Updated post #7245.

I'll merge when it goes green.

**Comment by milessabin** [comment]
@odersky I _hugely_ prefer the realignment with method syntax for givens :+1:

**Comment by milessabin** [comment]
Green now.

**Comment by odersky** [comment]
> @odersky I hugely prefer the realignment with method syntax for givens 👍

Yes, it does come out much nicer that way! Kudos to @smarter for quietly insisting on the change.

**Pull request merged**
