### PR TITLE
correct spelling mistakes in (some) comments

### PR DESCRIPTION
**Pull request by olhotak**
This PR only corrects spelling mistakes. It does not change the contents of any comments.

### CODE REVIEW

**Comment by DarkDimius** [comment]
I propose to merge this after #331 gets in, as they conflict

**Comment by olhotak** [comment]
OK, let's wait for #331 (or the new improved version of #331 that is coming).

**Comment by odersky** [comment]
LGTM, but needs a rebase first.

**Comment by olhotak** [comment]
I've rebased to current master.

**Pull request merged**
