### PR TITLE
Fix #6972: Parially revert c53f465524597bad481f4930eaeaae8ae953e1a7

### LINKED ISSUE #6972: Nightly CI build is failing `test_sbt`
See https://dotty-ci.epfl.ch/lampepfl/dotty/475/1/6

### PR DESCRIPTION
**Pull request by nicolasstucki**
The issue is that inherited `main` methods such as the one from `App` are not considered main method with this stricter condition. c53f465524597bad481f4930eaeaae8ae953e1a7

This currently breaks the nightly build.

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Was it not the commit that enabled @main methods from SBT?

**Comment by nicolasstucki** [comment]
The part that enables the `@main` is https://github.com/lampepfl/dotty/commit/c53f465524597bad481f4930eaeaae8ae953e1a7#diff-1e6b86ac307cd27014c80b0d1456e17aR233 which was not reverted

**Comment by anatoliykmetyuk** [comment]
That line is still affected: https://github.com/lampepfl/dotty/blob/c53f465524597bad481f4930eaeaae8ae953e1a7/compiler/src/dotty/tools/dotc/config/Platform.scala#L47

We just need to write the tests for SBT compat at some point.

**Comment by nicolasstucki** [comment]
The code in this PR has a condition that is less restricive. It will just accept more method as `main` methods.

**Comment by smarter** [comment]
But that's too imprecise, it will consider a main method in a trait to be a valid entry point even though such a method is not static.

**Comment by nicolasstucki** [comment]
Yes, it is imprecise and intended as a quick fix for the CI to pass.

**Pull request merged**
