### PR TITLE
Improve performance of `Unlifted.unapply`

### PR DESCRIPTION
**Pull request by nicolasstucki**
* Avoid creation of `Option`s and fail fast
* Align signatures

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance with #quotes please

**Comment by nicolasstucki** [comment]
I do not expect a large performance improvement

**Comment by liufengyun** [comment]
@nicolasstucki I stopped the benchmarking service, as we have merge problems.

**Comment by nicolasstucki** [comment]
It is not that important. The signature change seems to be more important.

**Comment by liufengyun** [comment]
There is a big drop 👍

**Review by liufengyun — APPROVED** [review]
LGTM

**Comment by nicolasstucki** [comment]
@liufengyun looking at the benchmark, this improvement does not make sense. We do not even use that extractor in this branch. Maybe the CPU profile got reset again.

**Comment by liufengyun** [comment]
> @liufengyun looking at the benchmark, this improvement does not make sense. We do not even use that extractor in this branch. Maybe the CPU profile got reset again.

We didn't reboot, thus the CPU should be the same as before. It could be that the speedup comes from other untested merges.

**Pull request merged**
