### PR TITLE
Tastydoc update

### PR DESCRIPTION
**Pull request by AleksanderBG**
Update Tastydoc so that it compiles again.

See #7668.

Remaining work: update collections to 2.13, update tasty.reflect usages in places where a bit of thinking is necessary (`NOTE` comments)

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@AleksanderBG now it compiles. I did not try the tests.

**Comment by AleksanderBG** [comment]
I generated the test documentation and there's definitely something wrong with the changes. Many links are broken. Seems some packages are treated as objects, probably we borked something when adjusting the `SymRef` code.

**Comment by bishabosha** [comment]
its still using the old syntax for givens e.g.
```scala
[error] -- [E019] Syntax Error: /Users/jamie/workspace/dotty/tastydoc/src/dotty/tastydoc/TastyExtractor.scala:61:153 
[error] 61 |  def extractClassMembers(reflect: Reflection)(body: List[reflect.Statement], symbol: reflect.ClassDefSymbol, parentRepresentation: Some[Representation]) given (mutablePackagesMap: scala.collection.mutable.HashMap[String, EmulatedPackageRepresentation]) : List[Representation with Modifiers] = {
```

**Comment by AleksanderBG** [comment]
@bishabosha tastydoc compiles on this branch for me, have you pulled all the changes?

**Comment by bishabosha** [comment]
@AleksanderBG Sorry, I should have checked the commits here before commenting ha

**Comment by AleksanderBG** [comment]
Apparently having `tastydoc` not compile breaks `launchIDE`, so I'm merging this PR into master. We'll worry about making Tastydoc work properly later on.

**Pull request merged**
