### PR TITLE
Fix #1207: Add Batch scripts and improve Shell scripts

### LINKED ISSUE #1207: We need windows batch-scripts

### PR DESCRIPTION
**Pull request by floating-cat**

### CODE REVIEW

**Comment by floating-cat** [comment]
retest this please

**Comment by smarter** [comment]
Hi @floating-cat and thanks for the PR! I don't think there's any way to redo the CLA check on the PR, but that's OK, I've manually checked on https://www.lightbend.com/contribute/cla/scala/check/floating-cat that you have signed the CLA.

**Comment by floating-cat** [comment]
Thanks. This pull request is ready for review.
Though I am not sure who would like review this.

**Comment by allanrenucci** [comment]
I think #1207 refers to windows version of `dist/{dotc, dotd, dotr}`.

Also, I think a better solution here is to get rid of the `project/scripts/build/...` scripts and reimplement `project/VersionUtil.scala` using [JGit](https://www.eclipse.org/jgit/). You can look at what scalac does: https://github.com/scala/scala/blob/2.13.x/project/VersionUtil.scala#L55-L86

**Comment by floating-cat** [comment]
You are right, reimplement `VersionUtil` using JGit is better.
So I close this PR. If I have time to redone this, I would open a new PR.

**Pull request closed without merging**
