### PR TITLE
community build: Fix publishing for scala-xml

### PR DESCRIPTION
**Pull request by griggt**
While investigating some community build failures in #15728, I noticed that `publishLocal` for `scala-xml` wasn't doing anything. It turns out that its build is configured to skip publishing for Scala versions > 3.0.x.

### CODE REVIEW

**Comment by SethTisue** [comment]
we merged https://github.com/scala/scala-xml/pull/615 recently — pulling that in might take care of it?

**Comment by SethTisue** [comment]
oh, ha, no. I'll need to send a sequel PR. working on it

**Comment by griggt** [comment]
> we merged [scala/scala-xml#615](https://github.com/scala/scala-xml/pull/615) recently — pulling that in might take care of it?

Hmmm... 
https://github.com/scala/scala-xml/blob/354cd71f55410ecd497c1cefd2eb2048555fab90/build.sbt#L41

**Comment by SethTisue** [comment]
https://github.com/scala/scala-xml/pull/616

**Comment by griggt** [comment]
updated to pull in https://github.com/scala/scala-xml/pull/616

**Review by ckipp01 — APPROVED** [review]

**Pull request merged**
