### PR TITLE
Fix #5495: Disallow lazy enums

### LINKED ISSUE #5495: Allowed modifiers for enums and enum cases
What should be the allowed modifiers for enums and enum cases? What about:
- enums: access modifiers (`private`, `protected`) and annotations
- enum cases: annotations

### PR DESCRIPTION
**Pull request by odersky**
Use the same scheme already used in Parser for avoiding
type/term flags mixups also when desugaring enums.

### CODE REVIEW

**Comment by smarter** [comment]
> Latest installment: Error message ids are an enum. So if a message is no longer needed,
you can drop the enum value, right? Wrong! The error message tests rely on the actual
ordinal number printed, so they fail if that number changes.

It's true that it's a bit cumbersome, but it's very useful: it means that error message ids are stable, so if someone hits error number 4274, they can google "scala error 4274" and find content relevant to that particular error no matter what compiler version was used to produce them.

**Comment by allanrenucci** [comment]
You may want to add the following test from #5525:

```scala
abstract enum Foo1 {} // error: only access modifiers allowed
final    enum Foo2 {} // error: only access modifiers allowed
sealed   enum Foo3 {} // error: only access modifiers allowed
implicit enum Foo4 {} // error: only access modifiers allowed
lazy     enum Foo5 {} // error: only access modifiers allowed
erased   enum Foo6 {} // error: only access modifiers allowed
override enum Foo7 {} // error: only access modifiers allowed
inline   enum Foo8 {} // error: only access modifiers allowed
opaque   enum Foo9 {} // error: only access modifiers allowed

enum Foo10 {
  abstract  case C1()  // error: no modifier allowed
  final     case C2()  // error: no modifier allowed
  sealed    case C3()  // error: no modifier allowed
  implicit  case C4()  // error: no modifier allowed
  lazy      case C5()  // error: no modifier allowed
  erased    case C6()  // error: no modifier allowed
  override  case C7()  // error: no modifier allowed
  private   case C8()  // error: no modifier allowed
  protected case C9()  // error: no modifier allowed
  inline    case C10() // error: no modifier allowed
  opaque    case C11() // error: no modifier allowed
}

enum Foo11 {
  abstract  case C1  // error: no modifier allowed
  final     case C2  // error: no modifier allowed
  sealed    case C3  // error: no modifier allowed
  implicit  case C4  // error: no modifier allowed
  lazy      case C5  // error: no modifier allowed
  erased    case C6  // error: no modifier allowed
  override  case C7  // error: no modifier allowed
  private   case C8  // error: no modifier allowed
  protected case C9  // error: no modifier allowed
  inline    case C10 // error: no modifier allowed
  opaque    case C11 // error: no modifier allowed
}
```

**Comment by odersky** [comment]
> It's true that it's a bit cumbersome, but it's very useful: it means that error message ids are stable, so if someone hits error number 4274, they can google "scala error 4274" and find content relevant to that particular error no matter what compiler version was used to produce them.

I get that. But in that case, ErrorMessageIds should not have been defined as enum values.

**Comment by odersky** [comment]
@allanrenucci I ended up incorporating the key approach of #5525: check that enums only take access flags (btw enum cases also accept accept flags). That makes error reporting more uniform. We still need the defensive addition of flags that issues an error rather than a crashing when term flags and type flags are mixed.

**Pull request merged**
