### PR TITLE
Add pos tests check files and position tests

### PR DESCRIPTION
**Pull request by nicolasstucki**
Now `.check` files in pos tests check the compilation log (warnings and info). Based on this we can test the positions by printing the tree with positions.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Those already exist in `neg` tests `.check` files.

**Comment by nicolasstucki** [comment]
If we want to test all positions, the test will naturally be fragile. Now we have `--update-checkfiles` if we need to update them.

**Comment by liufengyun** [comment]
> Now we have `--update-checkfiles` if we need to update them.

It seems there is a high chance of abusing the feature, which will make the checks useless, given that the check files are not intelligible.

**Comment by nicolasstucki** [comment]
We must try to only small tests that do not have much chance of changing positions. My guess is that we will have some changes at the start and once it stabilizes we will never update them again.

**Comment by liufengyun** [comment]
@nicolasstucki The CI is not happy.

**Pull request closed without merging**
