### PR TITLE
Use transformStats to handle imports

### LINKED ISSUE #11538: summonFrom and summon use different scopes for implicit search
## Compiler version

3.0.0-RC1

## Minimized code

https://scastie.scala-lang.org/KfWryGwAT3SW7xwpv6k6OA

## Output

Compiler error due to the fact that `summonFrom` only seems to do the implicit search within the closest enclosing scope (it compiles if the given is imported in the same scope as the `summonFrom` call).

## Expectation

The calls to `summon` and `summonFrom` should obey the same rules for implicit search.

### PR DESCRIPTION
**Pull request by odersky**
Everything else is a deviation from the way its done in type checking and in the spec.
This is an alternative to #11548 for fixing #11538.

Fixes #11538.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Does this also solve the issue in #11479?

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
Also fixes #11557

**Comment by odersky** [comment]
With https://github.com/lampepfl/dotty/pull/11591/commits/d5fa3f227eb2043b4c2f0eae7591e1b461254da1 we now also fix #11479.

**Comment by deusaquilus** [comment]
I think this also fixes #11563.

**Pull request merged**
