### PR TITLE
Various fixes related to lambda adaptation

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by nicolasstucki** [comment]
Needs rebase

**Comment by smarter** [comment]
> Visit http://dotty-bench.epfl.ch/3203/ to see the changes.

@liufengyun  I'm getting a 404 on this page

**Comment by liufengyun** [comment]
It works on my phone, strange. Are you using Firefox or Chrome?

Le 28 sept. 2017 7:32 PM, "Guillaume Martres" <notifications@github.com> a
écrit :

**Comment by smarter** [comment]
Same issue with both firefox and chrome, however I don't get a 404 when I use curl or wget.

**Comment by smarter** [comment]
Hah, it magically works now!

**Comment by nicolasstucki** [comment]
Needs rebase

**Pull request merged**
