### PR TITLE
Add regression test

### LINKED ISSUE #9685: Confusing suggested import involving inline implicit
## Minimized code

```Scala
import munit.FunSuite

class Example extends FunSuite {
  1.asdf
}
```

## Output

```scala
[error] 4 |  1.asdf
[error]   |  ^^^^^^
[error]   |value asdf is not a member of Int, but could be made available as an extension method.
[error]   |
[error]   |The following import might make progress towards fixing the problem:
[error]   |
[error]   |  import munit.Clue.generate
[error]   |
[error] one error found
```

## Expectation

Expected:

```scala
[error] 2 |  1.asdf
[error]   |  ^^^^^^
[error]   |  value asdf is not a member of Int
```

Dotty 0.27.0-RC1 suggests `munit.Clue.generate` to fix this issue. The `clue` method and `Clue` class are defined as: 
```scala
inline implicit def generate[T](value: T): Clue[T] = ${ clueImpl('value) }

class Clue[+T](
    val source: String,
    val value: T,
    val valueType: String
)
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Closes #9685

### CODE REVIEW

**Review by anatoliykmetyuk — APPROVED** [review]

**Comment by tgodzik** [comment]
Are we sure this one got fixed? There is still an open issue about it https://github.com/scalameta/munit/issues/626 <- is there anything munit needs to change?

**Comment by nicolasstucki** [comment]
The self-contained minimization started working. It is possible that the original example hit the bug differently. I suggest re-minimizing the issue to understand what is failing.

**Comment by tgodzik** [comment]
There is a minimization in the issue, also pasted it into original issue.

**Comment by julienrf** [comment]
It is not clear to me why this test passes. I’ve pushed a very slight variation that fails here: https://github.com/lampepfl/dotty/pull/17924/commits/1e7bf82006f6e05659ed8a2763d80d8c79e1c9d3

**Pull request merged**
