### PR TITLE
add test: incremental compilation for macros

### PR DESCRIPTION
**Pull request by liufengyun**
This test shows that incremental compilation for macros is broken.

### CODE REVIEW

**Comment by smarter** [comment]
Two possible solutons:

-  Macro definitions should be marked as macros when converting the api into sbt's representation, currently we only mark methods with the Macro flag: https://github.com/lampepfl/dotty/blob/0f4d3b28c16377e08564b05fdaf5248674ae67c3/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L589 This way, when sbt detects that a file with a macro in it has been modified, it will recompile all files that called it.

- Alternatively, we can store the full tree of the macro in the representation we pass to sbt, so that it will only recompile files if the macro was actually modified. There's no good way to do this currently, but I'm already doing this for inline defs by simply putting the pretty-printed body of the def in an annotation: https://github.com/lampepfl/dotty/blob/0f4d3b28c16377e08564b05fdaf5248674ae67c3/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L595-L603, we could do the same for macro definitions

**Comment by liufengyun** [comment]
It seems macros are more complex --- we need to track all the transitive closure of macro implementation in order to ensure correctness. If the body of any method directly or indirectly called from macro implementation is changed (no signature change), then all usage of the macros should be re-compiled & re-expanded.

A good news is that, currently we force macros to be defined and compiled in another project. So if we don't do cross-project incremental compilation, then it seems we are good.

**Comment by smarter** [comment]
See also https://infoscience.epfl.ch/record/204855/files/MacrosInSbtProblemSolved.pdf

**Comment by smarter** [comment]
(as far as I know, the work presented in this report was never merged into sbt)

**Comment by liufengyun** [comment]
Close, this is a known issue for zinc:

https://github.com/sbt/zinc/issues/249

Another difficulty with incremental compilation is related to shadowing:

https://github.com/sbt/zinc/issues/226

**Pull request closed without merging**
