### PR TITLE
Improvements & bugs that were discovered while implementing specialization.

### PR DESCRIPTION
**Pull request by DarkDimius**
The big one is the change in mixin.
It reduces the size of dotty.jar by 4%.

### CODE REVIEW

**Comment by smarter** [comment]
https://github.com/dotty-staging/dotty/commit/89386d05cff42f0f16c4e301749a2dc5ed8c329c and https://github.com/dotty-staging/dotty/commit/13792086f90f9f231c3774e5681556a8c41352b3 should have tests.

**Comment by DarkDimius** [comment]
@smarter https://github.com/dotty-staging/dotty/commit/89386d05cff42f0f16c4e301749a2dc5ed8c329c cannot be tested as this is the usage of internal helper-API that previously was supported and now requires using more low-level api.

Speaking about https://github.com/dotty-staging/dotty/commit/13792086f90f9f231c3774e5681556a8c41352b3 - I'm not sure if there can be a test that does not need specialization at the moment. 

I believe that those changes generally improve robustness of compiler and are worth getting in.

**Comment by DarkDimius** [comment]
@odersky please review. 74d5820 in particular needs careful review.

**Comment by odersky** [comment]
Otherwise LGTM

**Comment by odersky** [comment]
@darkdimius Do you want to do the final changes to get this in now?

**Pull request merged**
