### PR TITLE
Fix #10044

### LINKED ISSUE #10044: REPL: chained extension methods can only be called once
## Minimized code

Only in the REPL, it seems like calling a chain of extension methods has a strange side effect that prevents it from happening again

```Scala
scala> IArray(1,2,3).reverse.sorted                                                                                   
val res0: opaques.IArray[Int] = Array(1, 2, 3)

scala> IArray(1,2,3).reverse.sorted                                                                                   
1 |IArray(1,2,3).reverse.sorted
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value sorted is not a member of scala.opaques.IArray[Int].
  |An extension method was tried, but could not be fully constructed:
  |
  |    genericArrayOps[T](
  |      opaques.arrayOps.extension_reverse[Int](
  |        {
  |          Array.apply(
  |            {
  |              1
  |            }
  |          , 
  |            {
  |              [2,3 : Int]:Int*
  |            }:Int*
  |          ).asInstanceOf[opaques.IArray[Int]]:IArray[Int]
  |        }
  |      )
  |    )

scala> 
```

## Expectation

this is ok when they are called one after the other in a source file

### PR DESCRIPTION
**Pull request by griggt**
Fixes #10044

### CODE REVIEW

**Comment by SethTisue** [comment]
curious what investigation path led you to this

**Comment by griggt** [comment]
You mean I can't leave it as an "exercise for the reader"? 😅 

As soon I'm able to turn my notes into something concise and coherent I'll post it here.  All the investigative work I did on this was back in February and when I went to look at it again this weekend it took quite some time to make sense of it.

**Comment by som-snytt** [comment]
I also looked earlier today because I have a "works only once" issue. I think when I looked, it didn't even have a link to the ticket, I had to type it in by hand.

**Review by dwijnand — APPROVED** [review]
You're a beast, nicely done.

**Comment by SethTisue** [comment]
fyi @mpilquist

**Comment by mpilquist** [comment]
Awesome!

**Review by smarter — CHANGES_REQUESTED** [review]
Let's hold off merging this until we understand better what's going on here: https://github.com/lampepfl/dotty/issues/10044#issuecomment-1117156138

**Comment by griggt** [comment]
Closed in favor of #15120, which fixes the problem in the general case.

**Pull request closed without merging**
