### PR TITLE
Eliminate `newNakedSymbol` methods

### PR DESCRIPTION
**Pull request by odersky**
These methods produce a partially initialized symbol, which is dangerous for any code
using them. It turns out that any delays in the symbol initialization we need can be
provided by the symbol's completer.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please: a3b542b, 44cb461, 552fffa, 41c4ae3, 653d8b4

**Comment by odersky** [comment]
@liufengyun Can it be that the performance test does not come back for three days?

**Comment by liufengyun** [comment]
@odersky There is something abnormal, I'm looking into it.

**Comment by liufengyun** [comment]
I restarted the job for this PR yesterday, it's running since then. However, we have a significant slowdown of the benchmarks, ~5h per PR job. It might be related to the changes in the file system or related to the jmh update in #10591.

**Comment by odersky** [comment]
test performance please

**Comment by anatoliykmetyuk** [comment]
@odersky what's the status on this one? Are you planning to continue working on it or can it be closed?

**Comment by odersky** [comment]
The first commit is now in #13641. The other refactorings complicate things and don't seem to improve performance. So that might be a dead end, or a blocker until we have better ideas.

**Pull request closed without merging**
