### PR TITLE
Also reduce term projections

### PR DESCRIPTION
**Pull request by odersky**
We already reduce `R { type A = T } # A` to `T` in most situations when we create types. We now also reduce `R { val x: S } # x` to `S` if `S` is a singleton type.

This will simplify types as we go to more term-dependent typing. As a concrete benefit, it will avoid several test-pickling failures due to pickling differences when using dependent types.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@mbovel Performance tests seem to be inoperational

**Comment by odersky** [comment]
I am afraid this PR needs a performance test to be mergeable.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Looks like it does not affect performance, so I think we should adopt this, since it can make dependent types smaller.

**Review by mbovel — COMMENTED** [review]
Is there any way we could write a test for this?

This works:

```scala
type T
type T1 = { type A = T } # A
def test = summon[T1 =:= T]
```

But I can't do:

```scala
type S <: Singleton
type S1 = { val x: S } # x
def test = summon[S1 =:= S]
```
```
-- [E007] Type Mismatch Error: tests/pos/projection-term-singleton.scala:2:10 --
2 |type S1 = { val x: S } # x
  |          ^^^^^^^^^^^^
  |          Found:    Object{val x: S}
  |          Required: ?{ x: ? }
```

I guess this is because in `R # x`, the typer expects `R` to have a _type_ member named `x`, not a term member?

I also tried:

```scala
import scala.reflect.Selectable.reflectiveSelectable
type S <: Singleton
def test =
  def foo: { val x: S } = ???
  val x: S  = foo.x
```

and

```scala
import scala.reflect.Selectable.reflectiveSelectable
def getX[S, R <: {val x: S}](r: R) = r.x
```

but both already pass before your PR.

**Pull request merged**
