### PR TITLE
Pattern-bound type refs should have Case flag set

### LINKED ISSUE #6157: Inline match issue with separate compilation
The following compiles correctly as a single source file,
```scala
import scala.compiletime._

object Utils {
  type Id[t] = t

  inline def summonAllValues[T] <: T = inline erasedValue[Id[T]] match {
    case _: Unit => ()
    case _: (a, b) => (constValue[a], summonAllValues[b])
  }
}

import Utils._

object Foo {
  type Labels = ("i", ("s", ("b", Unit)))
}

object Test extends App {
  val labels = summonAllValues[Foo.Labels]
}
```
However, if `Utils` is split off to a separate source file and compiled first,
```scala
import scala.compiletime._

object Utils {
  type Id[t] = t

  inline def summonAllValues[T] <: T = inline erasedValue[Id[T]] match {
    case _: Unit => ()
    case _: (a, b) => (constValue[a], summonAllValues[b])
  }
}
```
with the following second,
```scala
import Utils._

object Foo {
  type Labels = ("i", ("s", ("b", Unit)))
}

object Test extends App {
  val labels = summonAllValues[Foo.Labels]
}
```
then the latter fails with,
```
-- Error: tests/pos/inline-match-separate/inline-match-separate_1.scala:6:65 ---
6 |  inline def summonAllValues[T] <: T = inline erasedValue[Id[T]] match {
  |                                       ^
  |cannot reduce inline match with
  | scrutinee:  compiletime.erasedValue[Utils.Id[Foo.Labels]] : Utils.Id[Foo.Labels]
  | patterns :  case _:Unit
  |             case _:Tuple2[a @ _, b @ _]
  | This location is in code that was inlined at inline-match-separate_2.scala:8
7 |    case _: Unit => ()
8 |    case _: (a, b) => (constValue[a], summonAllValues[b])
9 |  }
one error found
```

### PR DESCRIPTION
**Pull request by milessabin**
Fixes #6157.

### CODE REVIEW

**Comment by smarter** [comment]
I don't know what this does but the description of this flag is manifestly incomplete:
https://github.com/lampepfl/dotty/blob/d2499265ab2d13bf70eee17bfad67734804fecd9/compiler/src/dotty/tools/dotc/core/Flags.scala#L293-L294

Could you update it to explain what Case does on a val ?

**Comment by smarter** [comment]
Sounds like these two usages of the flag are completely unrelated, so it'd be clearer to use two flags (we're not running out of bits for them yet).

**Comment by milessabin** [comment]
I agree that it looks like we have two distinct uses of the same flag here.

I _think_ that using `Case` to represent case classes came first. Do you know who repurposed it to mean pattern bound type variable and why?

**Comment by smarter** [comment]
I think it was just done for convenience and there's no deep reason for it, you have my blessing to add a `PatternBound` flag :).

**Comment by odersky** [comment]
We are not that far to running out of flags, so I vote for keeping a single `Case` flag but documenting carefully the different meanings.

**Comment by milessabin** [comment]
@odersky I'll add a comment to this PR.

**Comment by smarter** [comment]
OK, in that case maybe call the flag `PatternBoundOrCase` so it's more obvious that it has a dual meaning, and add convenience methods like `def isCaseClass(implicit ctx: Context) = isClass && is(PatternBoundOrCase)` to `SymDenotation`.

**Comment by milessabin** [comment]
@smarter OK, but I'd rather do that in a followup PR.

**Comment by milessabin** [comment]
Follow on issue [here](https://github.com/lampepfl/dotty/issues/6178), assigned to me.

Any objections if I merge this now?

**Pull request merged**
