### PR TITLE
partest: correct line numbers in run stack traces

### PR DESCRIPTION
**Pull request by smarter**
partest adds a warning in a comment at the beginning of source files
that it copies, but this means that every line number displayed in a
stack trace is offset by 6. We can workaround this by moving the warning
to the end of the file.

### CODE REVIEW

**Comment by DarkDimius** [comment]
The reason why this header is in the beggining of the file is to make it apparent that people should not modify the generated files.

I believe that moving the header to the end of the file defeats the purpose.

**Comment by smarter** [comment]
> The reason why this header is in the beggining of the file is to make it apparent that people should not modify the generated files.

I understand that, but:
- The files are in a directory `partest-generated` which makes it obvious that they're generated
- Most test files are small so you should still be able to see the warning at the end
- If your text editor is not terrible, you should be able to recover an overwritten file
- Having wrong line number information can make you waste a lot of time trying to fix a bug in the incorrect place, I believe that's much worse thing than having your test file overwritten
- If we wanted to really fix this we should fix or rewrite partest so that we don't need to generate files and so that we don't need so many layers of abstractions which lead to hard to debug issues like https://github.com/lampepfl/dotty/issues/1264. This won't happen soon, but I want correct line information now, hence this patch.

**Comment by DarkDimius** [comment]
Proposal from the dotty meeting: change the comment to still be a prepend, but be a single line prepend instead with scary amount of exclamation marks.

**Comment by smarter** [comment]
That looks like a good solution to me since you shouldn't look at generated tests anyway, I'll update my PR

**Comment by DarkDimius** [comment]
Please reopen this PR when you'll update it. Thanks.

**Comment by smarter** [comment]
Looks like I can't reopen a pr after force-pushing a branch, so I'll open a new one

**Pull request closed without merging**
