### PR TITLE
Refactor common scripting test code

### PR DESCRIPTION
**Pull request by philwalk**
This addresses issues described in #12962
It also is relevant to #14073

Refactor test sources:
```
compiler/test/dotty/tools/scripting/BashScriptsTests.scala
compiler/test/dotty/tools/scripting/ClasspathTests.scala
compiler/test/dotty/tools/scripting/ScriptingTests.scala
```

Common code is moved to a new file:

```
compiler/test/dotty/tools/scripting/ScriptTestEnv.scala
```

So called `invalid tests` (where permissions fail when running bash command lines) are now treated by default as test failures, although this behavior can be overridden, if needed, by defining `PASS_INVALID_TESTS`.

### CODE REVIEW

**Review by BarkingBad — APPROVED** [review]
Looks good. Sadly, you didn't add `[test_non_bootstrapped]` and `[test_windows_full]` in body of your PR to enable these checks.

I think we need to add this trick to CI
`types: [ opened, synchronize, reopened, edited ]`
from here https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-do-workflows-trigger-on-pull_request so we could enable the CI without reopening the PR

**Comment by philwalk** [comment]
> add `[test_non_bootstrapped]` and `[test_windows_full]` in body of your PR to enable these checks.

So if I add those strings to the PR text, it will enable the addition tests?

**Comment by BarkingBad** [comment]
Unfortunately, editing text body now will have no effect, because we don't have `edited` action listed in the `ci.yaml` :( We have to open a separate PR with these 2 tags

**Review by michelou — CHANGES_REQUESTED** [review]
@philwalk Here are my suggestions :

File `scripting/BashScriptsTests.scala`
- who does *remove* the temporary file create on line [**21**](https://github.com/lampepfl/dotty/blob/1da66ba74e27ceae3ca8473f6210ba0b8fe7f3f7/compiler/test/dotty/tools/scripting/BashScriptsTests.scala#L21) ?!<br/><ins>Tip</ins> : use annotation `org.junit.AfterClass`.
- improve comment text on line [**59**](https://github.com/lampepfl/dotty/blob/1da66ba74e27ceae3ca8473f6210ba0b8fe7f3f7/compiler/test/dotty/tools/scripting/BashScriptsTests.scala#L59);<br/>e.g. <code>verify `dist/bin/scala` with -J setting and Scala script file</code>.<br/><ins>NB.</ins> The same remark applies to the next 3 test functions (`-J` and `-D`).
- variable `mismatches`in unused on line [**98**](https://github.com/lampepfl/dotty/blob/1da66ba74e27ceae3ca8473f6210ba0b8fe7f3f7/compiler/test/dotty/tools/scripting/BashScriptsTests.scala#L98).

File `scripting/ScriptTestEnv.scala`
- remove 1st (*empty*) line of file.
- add comment text on line [**15**](https://github.com/lampepfl/dotty/blob/c15097213682b91a653cdd91f328fa45fcb72401/compiler/test/dotty/tools/scripting/ScriptTestEnv.scala#L15)
- add a comment on line [**68**](https://github.com/lampepfl/dotty/blob/c15097213682b91a653cdd91f328fa45fcb72401/compiler/test/dotty/tools/scripting/ScriptTestEnv.scala#L68) to explain the values returned by the `bashCommand` function !
- add a comment to explain why we may encounter "`permission denied`" on line [**79**](https://github.com/lampepfl/dotty/blob/c15097213682b91a653cdd91f328fa45fcb72401/compiler/test/dotty/tools/scripting/ScriptTestEnv.scala#L79)

**Comment by philwalk** [comment]
@michelou - thanks for the feedback, all your suggestions are incorporated in #14113

**Comment by BarkingBad** [comment]
No longer valid

**Pull request closed without merging**
