### PR TITLE
Pick right type parameters for opaqueToBounds in TreeUnpickler

### LINKED ISSUE #12927: Incremental compiler crash during pickling
Very simple change in code causes incremental compilation to crash.
No crash from clean compilation.

## Compiler version

v3.0.1-RC2 (also tested on nightly)

## Minimized code
See https://github.com/soronpo/dottybug/tree/inc_comp_crash

**Bar.scala**
```Scala
object Bar:
  type Fuzzy[W <: Int] = Int
  opaque type BlaBla[W <: Int] <: Foo.BlaBla[Fuzzy[W], Int] =
    Foo.BlaBla[Fuzzy[W], Int]
```

**Foo.scala**
```scala
object Foo:
  opaque type BlaBla[+T, D] = Int
  extension [T, D](token: BlaBla[T, D]) def data: D = ???

//To cause the crash, after initial clean compilation
//replace `???` with `value.data` to cause the compiler crash
def foo[W <: Int](value: Bar.BlaBla[W]): Unit = ??? //value.data
```
## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: type W (line -1) #6058 when pickling C:\IdeaProjects\dottybug\src\main\scala\Foo.scala while compiling C:\IdeaProjects\dottybug\src\main\scala\Foo.scala
[error] ## Exception when compiling 2 sources to C:\IdeaProjects\dottybug\target\scala-3.0.1-RC2\classes
[error] java.lang.AssertionError: assertion failed: unresolved symbols: type W (line -1) #6058 when pickling C:\IdeaProjects\dottybug\src\main\scala\Foo.scala
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:788)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$3$$anonfun$2(Pickler.scala:69)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:106)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run(Pickler.scala:106)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error] dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:111)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:231)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error] dotty.tools.dotc.Run.compile(Run.scala:150)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2346)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2303)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2299)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed: unresolved symbols: type W (line -1) #6058 when pickling C:\IdeaProjects\dottybug\src\main\scala\Foo.scala
```
</details>

### LINKED ISSUE #12945: Invariant opaque type refinement loss across external dependency
**Edit:**

I managed to further minimize the example.

--------------------
It seems that type inference behaves differently across test dependency and fails to reduce (possibly any kind of different module dependency is affected).

## Compiler version

v3.0.1-RC2 (also checked on nightly 3.0.2-RC1-bin-20210624-ecbe3d2-NIGHTLY)
## Minimized code
Minimized project at: https://github.com/soronpo/dottybug/tree/invariance_widen_err

**Main.scala**
```Scala
opaque type Lie[W <: Int] = Int
object Lie:
  trait TC[-T]:
    type Out
  object TC:
    given [W <: Int]: TC[Lie[W]] with
      type Out = W

val x  = summon[Lie.TC[Lie[7]]]
val works = summon[x.Out =:= 7]
```

**Test.scala** //must be placed at scala/test
```Scala
object Test:
  val x  = summon[Lie.TC[Lie[7]]]
  val fails = summon[x.Out =:= 7]
```

## Output

```scala
[error] -- Error: C:\IdeaProjects\dottybug\src\test\scala\Test.scala:3:33
[error] 3 |  val fails = summon[x.Out =:= 7]
[error]   |                                 ^
[error]   |                 Cannot prove that Test.x.Out =:= (7 : Int).
[error] one error found
```

## Expectation
No error. Notice the same expression works within the main module and fails within the test module.

## Note
Opaque types seem to be part of the problem, since if we change `Lie` to a trait the error goes away.
The contravariance in `Lie.TC` is also crucial for the error, but it should not cause widening because `Lie` is invariant.

### LINKED ISSUE #12950: Opaque type's type parameter widened causing implicit lookup failure
## Compiler version
3.0.0

## Minimized code

```Scala
package repro
object repro:
    object opq:
        opaque type Lift[T] = Int
        extension(v: Int)
            def lift[T]: Lift[T] = v
        extension[T](l: Lift[T])
            def value: Int = l

    export opq.Lift as Lift
    export opq.lift as lift

    final type Two

    extension[TL](l: Lift[TL])
        def repro[TR](using m: Mul[TL, TR]): Int = l.value + m.value

    abstract class Mul[TL, TR]:
        val value: Int

    transparent inline given mulGivenInt[TL <: Int & Singleton, TR <: Int & Singleton]: Mul[TL, TR] =
        val m: Int = scala.compiletime.constValue[TL] * scala.compiletime.constValue[TR]
        new Mul[TL, TR] { val value: Int = m }

    transparent inline given mulGivenTwo[TR <: Int & Singleton]: Mul[Two, TR] =
        val m: Int = 2 * scala.compiletime.constValue[TR]
        new Mul[Two, TR] { val value: Int = m }

```

## Output

```scala
scala> import repro.repro.{*, given}

// this works, using a type 'Two' that is not an integer literal
scala> val x = 1.lift[Two]
val x: repro.repro.opq.Lift[repro.repro.Two] = 1

scala> x.repro[2]
val res0: Int = 5

// this will fail for some reason
scala> val y = 1.lift[2]                                                                                                                                                             
val y: repro.repro.opq.Lift[2] = 1
scala> y.repro[2]
1 |y.repro[2]
  |          ^
  |no implicit argument of type repro.repro.Mul[Int, (2 : Int)] was found for parameter m of method repro in object repro.
  |I found:
  |
  |    repro.repro.mulGivenInt[(Int & Singleton), (Int & Singleton)]
  |
  |But given instance mulGivenInt in object repro does not match type repro.repro.Mul[Int, (2 : Int)].

```

## Expectation

In the second example `val y = 1.lift[2]` I would expect that the integer literal type parameter not be widened to `Int` in the call to `y.repro[2]` - it should succeed and return `5`, the same as with `x.repro[2]`

Instead the `TL` type parameter is being widened to `Int`: `repro.repro.Mul[Int, (2 : Int)]`

It seems to be specifically related to using `opaque type` - a more simple repro I attempted worked correctly, when the opaque type was not involved.

### LINKED ISSUE #13001: Inconsistent compilation results in mirror-deriving code
## Compiler version
3.0.0

## Minimized code

Not minimized, but the `github4s` project at this specific commit:
https://github.com/47degrees/github4s/tree/bab2cd491d948807d364fa73687138d35f9feb6c

## Output

With the file: https://github.com/47degrees/github4s/blob/gb-scala3/github4s/src/test/scala/github4s/unit/EncoderDecoderSpec.scala#L83

I've observed three different, seemingly-unrelated behaviors so far:

- If I comment out all `test` invocations except the first one, compilation succeeds.
- If I comment out all `test` invocations except the first *two*, compilation fails on *both*, with errors about not finding the `Mirror`:

<details><summary>Compiler output</summary>
<pre>
[error] -- Error: /Users/gavin/Code/github4s/github4s/src/test/scala/github4s/unit/EncoderDecoderSpec.scala:83:19 
[error] 83 |  test[BlobContent]
[error]    |                   ^
[error]    |no implicit argument of type org.scalacheck.Arbitrary[github4s.domain.BlobContent] was found for an implicit parameter of method test in class EncoderDecoderSpec.
[error]    |I found:
[error]    |
[error]    |    github4s.ArbitraryDerivation.auto.deriveArb[A](
[error]    |      github4s.DerivedGen.derived[A](
[error]    |        /* missing */
[error]    |          summon[
[error]    |            deriving.Mirror{
[error]    |              Kind = shapeless3.deriving.K0.type; 
[error]    |                MirroredType <: github4s.domain.BlobContent
[error]    |              ; MirroredElemTypes <: Tuple
[error]    |            }
[error]    |          ]
[error]    |      )
[error]    |    )
[error]    |
[error]    |But no implicit values were found that match type deriving.Mirror{
[error]    |  Kind = shapeless3.deriving.K0.type; 
[error]    |    MirroredType <: github4s.domain.BlobContent
[error]    |  ; MirroredElemTypes <: Tuple
[error]    |}.
[error] -- Error: /Users/gavin/Code/github4s/github4s/src/test/scala/github4s/unit/EncoderDecoderSpec.scala:84:20 
[error] 84 |  test[BranchCommit]
[error]    |                    ^
[error]    |no implicit argument of type org.scalacheck.Arbitrary[github4s.domain.BranchCommit] was found for an implicit parameter of method test in class EncoderDecoderSpec.
[error]    |I found:
[error]    |
[error]    |    github4s.ArbitraryDerivation.auto.deriveArb[A](
[error]    |      github4s.DerivedGen.derived[A](
[error]    |        /* missing */
[error]    |          summon[
[error]    |            deriving.Mirror{
[error]    |              Kind = shapeless3.deriving.K0.type; 
[error]    |                MirroredType <: github4s.domain.BranchCommit
[error]    |              ; MirroredElemTypes <: Tuple
[error]    |            }
[error]    |          ]
[error]    |      )
[error]    |    )
[error]    |
[error]    |But no implicit values were found that match type deriving.Mirror{
[error]    |  Kind = shapeless3.deriving.K0.type; 
[error]    |    MirroredType <: github4s.domain.BranchCommit
[error]    |  ; MirroredElemTypes <: Tuple
[error]    |}.
[error] two errors found
[error] two errors found
[error] (github4s / Test / compileIncremental) Compilation failed
</pre>
</details>

I've also tried with the first 10-20 or so uncommented, and it fails with those same `Mirror` errors on each.

- If I uncomment *all* `test` invocations, and try compiling the file as-is, compilation prints *no* output, the compiler never terminates (I've left it for >20 minutes), and it ignores ctrl-c inputs

## Expectation

If the code is correct, it should compile.
If it's incorrect, it should fail consistent, the compiler shouldn't run forever and be uncancelable.

Code that compiles without error should not start producing errors when an unrelated statement is added to the file.

### LINKED ISSUE #13128: Unexpected opaque type argument widening across dependencies
While it is possiblly related to  #12945 and #12950, in this example there is just an opaque type, without any extension methods and implicit invocation and the example is very small, although still requires separate compilation to trigger.

## Compiler version

3.0.3-RC1-bin-20210716-cc47c56-NIGHTLY

## Minimized code
Minimized project at: https://github.com/soronpo/dottybug/tree/opaque_widen

**main/scala/Main.scala**
```Scala
opaque type Foo[T <: Int] = Int
```

**test/scala/Test.scala**
```Scala
def grabT[T <: Int](arg : Foo[T]) : T = ???
final val t1 = grabT(??? : Foo[8])
val t2 : 8 = t1
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: C:\IdeaProjects\dottybug\src\test\scala\Test.scala:3:13
[error] 3 |val t2 : 8 = t1
[error]   |             ^^
[error]   |             Found:    (t1 : Int)
[error]   |             Required: (8 : Int)
[error] one error found
```

## Expectation
No error.

### LINKED ISSUE #13190: Incremental compilation and opaque types don't play nice together
## Compiler version
3.0.1

## Minimized code

fileA.scala
```Scala
object Opaque {
  opaque type FieldType[K, +V] <: V = V
}
```

fileB.scala
```scala
import Opaque.*

object Test {
  type FindField[R <: scala.Tuple, K] = R match {
    case FieldType[K, f] *: t => f
    case _ *: t => FindField[t, K]
  }

  val f: FieldType["A", Int] = ???
  val f1: Int = f
  //val f2: Int = f

  type R = FieldType["A", Int] *: FieldType["B", Double] *: FieldType["C", String] *: FieldType["D", Boolean] *: EmptyTuple
  summon[FindField[R, "B"] =:= Double]
}
```

### Steps to reproduce
1. Compile both files together in a project. Everything should compile fine.
2. Uncomment `val f2: Int = f`
3. Try to compile again (and not cleaning beforehand). It will error for `f1`, `f2`, and the summon
4. Clean and compile. It works again

## Output

```scala
[error] -- [E007] Type Mismatch Error: D:\DevProjects\Stable\shapeless\core\src\main\scala-3\fileB.scala:10:16
[error] 10 |  val f1: Int = f
[error]    |                ^
[error]    |              Found:    (Test.f : Opaque.FieldType[("A" : String), Int])
[error]    |              Required: Int
[error] -- [E007] Type Mismatch Error: D:\DevProjects\Stable\shapeless\core\src\main\scala-3\fileB.scala:11:16
[error] 11 |  val f2: Int = f
[error]    |                ^
[error]    |              Found:    (Test.f : Opaque.FieldType[("A" : String), Int])
[error]    |              Required: Int
[error] -- Error: D:\DevProjects\Stable\shapeless\core\src\main\scala-3\fileB.scala:14:38
[error] 14 |  summon[FindField[R, "B"] =:= Double]
[error]    |                                      ^
[error]    |Cannot prove that Test.FindField[Test.R, ("B" : String)] =:= Double.
[error]    |
[error]    |One of the following imports might make progress towards fixing the problem:
[error]    |
[error]    |  import shapeless.~?>.idKeyWitness
[error]    |  import shapeless.~?>.idValueWitness
[error]    |  import shapeless.~?>.witness
[error]    |
[error]    |
[error]    |
[error]    |Note: a match type could not be fully reduced:
[error]    |
[error]    |  trying to reduce  Test.FindField[Test.R, ("B" : String)]
[error]    |  failed since selector  Test.R
[error]    |  does not match  case Opaque.FieldType[("B" : String), f] *: t => f
[error]    |  and cannot be shown to be disjoint from it either.
[error]    |  Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |    case _ *: t => Test.FindField[t, ("B" : String)]
```

## Expectation
It should compile in both cases, also when using incremental compilation.

### PR DESCRIPTION
**Pull request by odersky**
We passed the TypeParamRefs instead of the type param symbols when unpickling (but not in Namer).

Fixes #12945
Fixes #13001 
Fixes #13190 

Also:

Fixes #12950
Fixes #13128
Fixes #12927

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
The 3-issue wombo!

**Comment by griggt** [comment]
Seems like this also fixes #12950 and #13128

**Comment by smarter** [comment]
Should this be backported to the release branch given the number of issues it fixes?

**Comment by griggt** [comment]
Also fixes #12927 (I believe this one needs an sbt scripted test)

**Comment by soronpo** [comment]
> Should this be backported to the release branch given the number of issues it fixes?

Silly me opening all those issues 😜 
Well, I had no guarantee that they are related.

**Comment by dwijnand** [comment]
> Seems like this also fixes #12950 and #13128
> Also fixes #12927 (I believe this one needs an sbt scripted test)

@odersky are you in the process of pulling in these test cases, or shall we merge this as is?

**Comment by odersky** [comment]
I am still trying to figure out the failure in onnx-scala. I'll also add tests that work.

**Comment by odersky** [comment]
Also:

Fixes #12950
Fixes #13128

**Comment by odersky** [comment]
I have added tests for everything except #12927. I leave adding a test for that to someone who has more sbt foo than I.

**Comment by odersky** [comment]
onnx-scala was frustrating. I first could not get it to test separately. Once I managed that, I thought that it was a problem in unpickler. Once I fixed that with great effort I found out that all other fixed issues broke again. So I finally figured out that the original version of unpickler was correct and the fault was in onnx-scala.

**Comment by griggt** [comment]
I'll push a test for #12927

**Comment by odersky** [comment]
@griggt Great. Thanks!

**Comment by odersky** [comment]
What is the branch on which one has to rebase the backport?

**Comment by smarter** [comment]
It's release-3.0.2: https://github.com/lampepfl/dotty/tree/release-3.0.2

**Comment by dwijnand** [comment]
Hepta-kill!

**Comment by Daenyth** [comment]
So this should be in the 3.0.3 release?

**Comment by dwijnand** [comment]
The backport is #13219, and it needs work to land.

**Pull request merged**
