### PR TITLE
Add bitwise Int compiletime operations

### PR DESCRIPTION
**Pull request by bishabosha**

### CODE REVIEW

**Comment by bishabosha** [comment]
not really sure why `tests/pos/singleton-ops-test-issue-8280.scala` broke

**Comment by panacekcz** [comment]
(Hope you don't mind me chiming in, I clicked the pr wondering about this.)
It fails because the type `scala.compiletime.ops.int.&` shadows the intersection type `scala.&` in `Int & Singleton`.
Actually, the Syntax section at http://dotty.epfl.ch/docs/reference/new-types/intersection-types-spec.html should be updated, `&` seems to be just a normal identifier, not a soft keyword.

**Comment by bishabosha** [comment]
> `&` seems to be just a normal identifier, not a soft keyword.

Ah yeah, that makes total sense

**Comment by bishabosha** [comment]
what would be a more appropriate name for the `int.&` operation?

**Comment by OlivierBlanvillain** [comment]
`BitwiseAnd` and `BitwiseOr`?

I would also be ok with the lazy solution which would be to just require people to always write `int.&` and `int.|`.

**Pull request merged**
