### PR TITLE
fix #11897: error on given pattern in val def

### LINKED ISSUE #11897: Pattern `given` on the LHS of a `val` definition should enter corresponding scope
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
scala> given Int = 0
lazy val given_Int: Int

scala> def test = {
     |   val (x, given Int) = (1, 1)
     |   summon[Int]
     | }
def test: Int

scala> test                                                                                                             
val res0: Int = 0
```

## Expectation

This is quite surprising/unexpected.

I would expect it to work in the same way as the following:

```Scala
scala> def test = {
     |   given Int = 1
     |   summon[Int]
     | }
def test: Int

scala> test
val res1: Int = 1
```

### LINKED ISSUE #12629: val and single given pattern combination
## Compiler version

3.0.0

## Minimized code

```Scala
case class A(i: Int)
case class B(b: Boolean)

def test =
  val (given A) = A(23)
  val given B = B(false)
```

## Output

compiles ok

## Expectation

`val given B` is treated as a pattern val def, but this is too close to `given B = B(false)` so I would expect a syntax error in favour of the alias given,

alternatively, with #11897 fixed, it could be a way to define a (non-lazy) given?

### PR DESCRIPTION
**Pull request by bishabosha**
fixes #11897
fixes #12629

### CODE REVIEW

**Comment by smarter** [comment]
I'm not familiar with this code, could you describe in the commit message what it did previously and what it does differently now?

**Comment by bishabosha** [comment]
This change will break source compatibility as now given patterns will shadow other givens in scope - so I imagine this should require some language import?

**Comment by bishabosha** [comment]
it seems attempting to detect `val given Int = 1` has the same tree as `given Int = 1`, causing an error unexpectedly, so will need to go back to drawing board on that, or just drop the change.

**Comment by smarter** [comment]
> This change will break source compatibility as now given pattern defs will shadow other givens in scope - so I imagine this should require some language import?

Source-breaking change can be introduced in 3.1, but I would also prefer just not allowing givens in pattern definitions, I don't think we need another way of defining givens.

**Comment by bishabosha** [comment]
This PR has now changed to make it an error to include given patterns in a val definition - this is still source breaking change - so how should it be introduced?

**Comment by smarter** [comment]
Given that it did nothing before and was not advertised as a feature, I'm inclined to get it in without worrying about the hypothetical source compat breakage.

**Comment by bishabosha** [comment]
I have changed the implementation and adjusted the error message

**Review by smarter — APPROVED** [review]

**Pull request merged**
