### PR TITLE
Avoid creating closure for asserts

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance please

**Comment by odersky** [comment]
Did you check the bytecode that this does in fact inline? Just being paranoiac here.

Otherwise LGTM

**Comment by nicolasstucki** [comment]
Yes it does inline, but the generated code is a bit larger.
I would prefer patching the assert I found problematic by hand.

**Comment by nicolasstucki** [comment]
While compiling `dotty.tools.dotc.core` e2f4be6 reduces the time of `FlagSet.|` from 0.911 sec to 0.010 sec.

I would drop the first commit. The standard library already has this `@inline` in the `Predef.assert` but it is ignored by dotty as it is compiled in `scala2` mode. My solution may improve it a bit.

**Comment by odersky** [comment]
I think we can keep the first commit. There are other asserts, where it would be nice to give them a second parameter without fear that a closure will be created.

**Comment by nicolasstucki** [comment]
Removed the second commit

**Pull request merged**
