### PR TITLE
Allow non-hot values in SeqLiterals

### LINKED ISSUE #14460: Inner enum declarations cause initialization-checker error
## Compiler version

3.1.2-RC1

## Minimized code

```Scala
class Outer:
    enum MyEnum {
        case Case
    }
```

## Output

```scala
-- Error: tests/init/pos/inner-enum.scala:3:8 --------------------------------------------------------------------------
3 |        case Case
  |        ^
  |        Cannot prove that the value is fully initialized. May only use initialized value as method arguments.
  |
  |        The unsafe promotion may cause the following problem:
  |        Access non-initialized value $values. Calling trace:
  |         -> case Case	[ inner-enum.scala:3 ]
```

## Expectation

When compiling with the `-Ysafe-init` flag this declaration should pass.

### PR DESCRIPTION
**Pull request by Xavientois**
Closes #14460, #14751

Do not ensure that elements in a SeqLiteral are Hot.

Review by @liufengyun

### CODE REVIEW

**Comment by Xavientois** [comment]
@liufengyun @olhotak I have not yet implemented the parametricity solution we discussed, as this change appears to solve all of the enum cases we were looking at (`Array.apply` and `AnyRef`).

This currently passes all of the enum test cases, but fails three neg tests:
- tests/init/neg/scodec.scala 
- tests/init/neg/early-promote.scala
-  tests/init/neg/leak-warm.scala

Since we want `List.apply` to allow cold arguments, it looks like `leak-warm` should no longer cause an error.

I am less certain about the desired behaviour for the other two tests. Should they still trigger an error?

**Comment by liufengyun** [comment]
Thanks Josh!

> I am less certain about the desired behaviour for the other two tests. Should they still trigger an error?

For `SeqLiterals`, we need to return a `join` of the argument values instead of `Hot`. The current change simply skips the check of argument values, thus it is problematic.

**Comment by liufengyun** [comment]
> > For `SeqLiterals`, we need to return a `join` of the argument values instead of `Hot`. The current change simply skips the check of argument values, thus it is problematic.
> 
> I think I may have originally misunderstood. What do you mean by the `join` of the values? Should I try to promote them?

I mean you can return `Result(ress.map(_.value).join, ress.flatMap(_.errors))`. The logic in `call` will take care of the promotion check.

**Review by liufengyun — APPROVED** [review]
LGTM

**Review by olhotak — APPROVED** [review]
LGTM. There's a merge conflict in a `.check` file that needs to be resolved.

**Pull request merged**
