### PR TITLE
Backport changes to reference docs from 3.2.0

### LINKED ISSUE #16201: Scala 3 reference docs for 3.2.0 do not have updated sources
as of 18 October 2022 https://docs.scala-lang.org/scala3/reference/language-versions/source-compatibility.html looks like:
Screenshot 2022-10-18 at 09 59 56

it should show content as listed in https://github.com/lampepfl/dotty/blob/release-3.2.0/docs/_docs/reference/language-versions/source-compatibility.md

### PR DESCRIPTION
**Pull request by bishabosha**
did a rebase of `release-3.2.0` onto `language-reference-stable` and fixed conflicts

fixes #16201

### CODE REVIEW

**Comment by bishabosha** [comment]
now I added only changes to the reference docs, the sidebar and the layout

**Comment by bishabosha** [comment]
How I fixed it: Take the latest `language-reference-stable` branch, e.g. commit 5b81f19  rebase `release-3.2.0` onto it, fixing any conflicts. Then adjust all `nightlyOf` occurrences in the markdown front matter to `movedTo`. Then unstage all commits by resetting to the reference stable head with `git reset 5b81f19`, then add only the reference docs changes with `git add docs/_docs/reference`

**Comment by julienrf** [comment]
I wonder if a merge would work better than a rebase?

**Comment by bishabosha** [comment]
> I wonder if a merge would work better than a rebase?

I guess in case changes occur independently? in this case it seems the changes don't overwrite anything

**Review by julienrf — APPROVED** [review]

**Review by Kordyjan — APPROVED** [review]

**Pull request merged**
