### PR TITLE
Save TASTY in attribute of classfiles.

### PR DESCRIPTION
**Pull request by DarkDimius**
Currently saves on all classfiles in the same compilation unit. 
@odersky, feel free to take over

### CODE REVIEW

**Comment by xeno-by** [comment]
So if there are multiple classes in the same file, the same attribute will be written multiple times? Also, how is this supposed to be accessible at runtime?

**Comment by DarkDimius** [comment]
> So if there are multiple classes in the same file, the same attribute will be written multiple times?

This should be fixed by either having a single top-level class per compilation unit after pickler, or pickler should prepare a map of what TASTY to save in which file. 

>Also, how is this supposed to be accessible at runtime?

Given this implementation, only using classloader.

This implementation is not thought as a long-term one, but to foster testing of TASTY in Dotty.
I would propose to discuss how should actual implementation look like on next TASTY meeting.

**Comment by odersky** [comment]
@DarkDimius Please review.

**Comment by xeno-by** [comment]
I pulled this PR together with https://github.com/lampepfl/dotty/pull/495 into master, then compiled Dotty, then ran it on a simple file, and it blew up. No idea whether I'm doing something wrong, or it's a genuine bug, but here's the log: 

```
16:48 ~/Projects/dotty/sandbox (flatmap2015)$ cat Test.scala
class C {
  def x = 42
  def y = x
}
16:49 ~/Projects/dotty/sandbox (flatmap2015)$ dotc -Ytest-pickler Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: denotation module class <empty> invalid in run 2. ValidFor: Period(1..4, run = 3)
	at scala.Predef$.assert(Predef.scala:165)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:508)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:544)
	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:370)
	at dotty.tools.dotc.core.SymDenotations$class.stillValid(SymDenotations.scala:49)
	at dotty.tools.dotc.core.Contexts$Context.stillValid(Contexts.scala:51)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1220)
	at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1206)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1194)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:270)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:187)
	at dotty.tools.dotc.ast.tpd$modsDeco.mods(tpd.scala:399)
	at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:393)
	at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
	at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
	at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
```

**Pull request merged**
