### PR TITLE
Typer#escapingRefs: don't let the types of lower bounds escape

### PR DESCRIPTION
**Pull request by smarter**
In 0efa171e8ccca0d49fc6d800fd21e29f7b7336fd I changed the definition of `NamedPartsAccumulator` to exclude lower bounds as this is required for the implicit search, but `NamedPartsAccumulator` is also used by `Typer#escapingRefs` so in the following code:
```scala
class Foo[T]
val z = {
  class C

  ??? : Foo[_ >: C]
}
```
the type of `z` was inferred to be `Foo[_ >: C]` instead of `Foo`.

To avoid this, `NamedPartsAccumulator` will only exclude lower bounds if the parameter `excludeLowerBounds` is explicitely set to `true`.

No test because there is no way to detect that a type has escaped, this might be something that could be added to `TreeChecker`.

<hr>

This PR also removes dead code from `Typer#escapingRefs`.

<hr>

Review by @odersky .

### CODE REVIEW

**Comment by odersky** [comment]
In fact, given the observed failure of implicits, I would revert completely. Implicits should be searched in lower as well as upper bounds. So NamedParts can be reverted to use both bounds.

**Comment by smarter** [comment]
@odersky : That's one way to do it, but I think this is unnecessary, the failures we get for implicits are due to issues in the inference of type parameters: https://github.com/lampepfl/dotty/issues/739

For example, in https://github.com/lampepfl/dotty/issues/553 we have the type `CC? >: ([+HK$0] => scala.collection.immutable.List[HK$0])[HK$0 =+ (T? >: Int)] <: ([HK$0] =>  <: scala.collection.TraversableOnce[HK$0])` and implicit search fail, but if https://github.com/lampepfl/dotty/issues/739 was fixed then `CC` would be instantiated to `List` like it is in Scala2 and the implicit search would succeed.

I have a prototype that fixes the inference of type parameters, but it uncovered some issues with `Typer#ensureNoLocalRefs` which I need to fix first, including the issue fixed by this pull request.

**Comment by smarter** [comment]
@odersky : could you take another look at this? I just rebased it because it turns out I need this for the sbt phase.

**Comment by odersky** [comment]
LGTM

**Pull request merged**
