### PR TITLE
Fixes #3860 REPL pretty-printed output for by-name parameters

### LINKED ISSUE #3860: REPL pretty-printed output for by-name parameters is wrong
```scala 
scala> def calculate(input: => Int) = input * 37
def calculate(input: : Int): Int
```

### PR DESCRIPTION
**Pull request by eklavya**
Fix #3860.

### CODE REVIEW

**Comment by allanrenucci** [comment]
CLA is [signed](https://www.lightbend.com/contribute/cla/scala/check/eklavya)

**Comment by eklavya** [comment]
@allanrenucci is this PR ok? Just pinging to know what's up.

**Comment by Blaisorblade** [comment]
@allanrenucci is away but this PR looks like a strict improvement, with a test. Merging.

**Comment by eklavya** [comment]
Thanks @Blaisorblade :)

**Pull request merged**
