### PR TITLE
Don't lift try-catch statements that are already in local functions

### LINKED ISSUE #13941: `Cannot rewrite recursive call: it is not in tail position` error
## Compiler version

- `3.1.2-RC1-bin-20211102-82172ed-NIGHTLY`
- `3.1.1-RC1`
- `3.1.0`
- `3.0.2`

## Minimized code

```Scala
import scala.annotation.tailrec

class A {
  def b = Option("a").map { x =>
    @tailrec def loop(): Int = {
      try {
        2
      } catch { 
        case _: Throwable =>
          loop()
      }
    }
    x
  }
}
```

## Output

```scala
[error] 10 |          loop()
[error]    |          ^^^^^^
[error]    |          Cannot rewrite recursive call: it is not in tail position
```

### PR DESCRIPTION
**Pull request by KacperFKorban**
closes #13941

The problem in #13941 is that before tail recursion can be expanded the `try` is lifted to a local function, which in turn moves direct recursive calls.

### CODE REVIEW

**Review by odersky — COMMENTED** [review]
The change looks correct to me. Can you find out more what happened for the CB timeout?

**Comment by KacperFKorban** [comment]
I'm pretty sure that the problem is with the implementation of [intercept](https://github.com/scalatest/scalatest/blob/da64062d575c071760d6fe40696e94bbdd04bf3c/dotty/core/src/main/scala/org/scalatest/Assertions.scala#L757) in scalatest, which somehow depends on the try-catch being lifted [here](https://github.com/scalatest/scalatest/blob/da64062d575c071760d6fe40696e94bbdd04bf3c/jvm/scalatest-test/src/test/scala/org/scalatest/SuiteSuite.scala#L325). Though I'm not sure how to fix it yet.

**Comment by odersky** [comment]
> I'm pretty sure that the problem is with the implementation of intercept in scalatest, which somehow depends on the try-catch being lifted here. Though I'm not sure how to fix it yet.

That looks likely, yes. Who worked on that macro? Maybe we can ask them for help? And how big is the damage? Can we disable the tests that fail individually?

**Comment by KacperFKorban** [comment]
Looks like the macro implementation is the same as for Scala 2 and just uses `ClassTag`s and `Position`s. I see some commits from @nicolasstucki in the same file but I'm pretty sure they are not related.

**Comment by odersky** [comment]
Does Scala 2 lift to class level as well, or do they stop at the enclosing method?

Also, it would be good to find out _what_ method fails in ScalaTest. Maybe we overlooked something and certain kinds of DefDefs should not supporess try lifting.

**Comment by KacperFKorban** [comment]
Scala 2 seems to behave the same way here i.e. it doesn't lift in this case. I have an idea about how to fix it. It might be the case that entering a `DefDef` changes the `needLift` value for the entire scope since it is never set back to the previous value. If so, then it's just an implementation error on my side.

**Comment by KacperFKorban** [comment]
The problematic test case is [RefSpecSpec / "should generate NotAllowedException wrapping a non-fatal RuntimeException is thrown inside scope"](https://github.com/scalatest/scalatest/blob/da64062d575c071760d6fe40696e94bbdd04bf3c/jvm/scalatest-test/src/test/scala/org/scalatest/RefSpecSpec.scala#L2479). The problem seems to be that the position is reported as if it was thrown in one scope higher than it's supposed to (lineNo: 2485 != 2488). This is most likely because one less `try` is lifted somewhere in the call sequence.

Decreasing the stack depth for `NotAllowedException` in [RefSpecLike](https://github.com/scalatest/scalatest/blob/da64062d575c071760d6fe40696e94bbdd04bf3c/jvm/refspec/src/main/scala/org/scalatest/refspec/RefSpecLike.scala#L133) seems to fix the tests, but I'm not 100% sure about this fix. Although this would make the stack depth the same as for `2.13`, which sounds correct.

Should I disable this test for now?

**Comment by odersky** [comment]
> Decreasing the stack depth for NotAllowedException in RefSpecLike seems to fix the tests, but I'm not 100% sure about this fix. Although this would make the stack depth the same as for 2.13, which sounds correct.

Then it looks like this was a fix to port scalatest to 3 that should be reverted?

**Comment by KacperFKorban** [comment]
Not really, this default behavior was left since [mid-2016](https://github.com/scalatest/scalatest/commit/a37a951b08c84c42f0c22dddf54ff777a2fd3e79#diff-3acbd6362bb672a0ae01c5bb539e8c31532ba60ec4024c62bce15933db7ef46d) and was intended for Scala 2.11. I think that it just happened to work for dotty.

This means that adding a special case for Scala 3 in [RefSpecLike#ensureScopesAndTestsRegistered](https://github.com/scalatest/scalatest/blob/da64062d575c071760d6fe40696e94bbdd04bf3c/jvm/refspec/src/main/scala/org/scalatest/refspec/RefSpecLike.scala#L133) would be required, but that's still a 2 line change.

**Comment by odersky** [comment]
Yes, let's patch it as you suggest

**Comment by KacperFKorban** [comment]
Fixed scalatest's tests. CB should work properly now.

**Review by odersky — APPROVED** [review]

**Pull request merged**
