### PR TITLE
More type parameters' inference fixes

### PR DESCRIPTION
**Pull request by smarter**
Review by @odersky

### CODE REVIEW

**Comment by odersky** [comment]
Otherwise LGTM

**Comment by odersky** [comment]
@smarter Please do PRs only from staging. Makes it easier to collaborate from them.

**Comment by smarter** [comment]
> @smarter Please do PRs only from staging. Makes it easier to collaborate from them.

Will do.

**Comment by smarter** [comment]
Superseded by #863, closing.

**Pull request closed without merging**
