### PR TITLE
Add/resident compiler

### PR DESCRIPTION
**Pull request by odersky**
This adds a resident compiler command. For usage information, see doc comment in Resident.scala.
We'll later refine this to become a general compile server.

### CODE REVIEW

**Comment by odersky** [comment]
I'd like to get this in before it starts to rot. Any objections?

**Comment by odersky** [comment]
Rebased to current master

**Comment by DarkDimius** [comment]
While being rebased this PR removed most of changes that were made in #691. I'll make a PR to bring them back

**Comment by xeno-by** [comment]
What's the main benefit of having this feature? Is it cutting down the startup time of the compiler or there's more? Also, how does this compare with sbt-server?

**Pull request merged**
