### PR TITLE
[Do not merge] experiment - use a volatile field for completion checking

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
test performance please

(check that ScalaPB is back)

**Comment by smarter** [comment]
Related work by @DarkDimius on parallelizing the typer: https://github.com/lampepfl/dotty/issues/991

**Comment by liufengyun** [comment]
ScalaPB is now back, though your browser cache may disagree :)

**Comment by odersky** [comment]
> ScalaPB is now back, though your browser cache may disagree :)

... and with a nice downwards slope, too! 29% faster since the last datapoint is not bad.

**Pull request closed without merging**
