### PR TITLE
add scala library as a submodule

### LINKED ISSUE #1290: SBT: report a warning if ./scala-scala is absent
Dotty test suite would fail if one didn't clone compatible version of stdlib.

It would be nice to give a warning for people running either `test` or `partests` suggesting the to do:

```
git clone -b dotty-library https://github.com/DarkDimius/scala.git ./scala-scala
```

### PR DESCRIPTION
**Pull request by liufengyun**
To synchronize the submodule:

    git submodule init
    git submodule update

Reference: https://git-scm.com/book/en/v2/Git-Tools-Submodules

Review @DarkDimius .

### CODE REVIEW

**Comment by DarkDimius** [comment]
I'm fine with making it a submodule, butI don't think it fixes #1290, as people still need to *know* that they need to issue additional commands.

**Comment by liufengyun** [comment]
I agree, while adding submodule makes the dependency explicit, an additional warning message is even better.

**Comment by sjrd** [comment]
In my experience, it is easier to download it directly as part of the build. It causes less headache. Of course that's also because in Scala.js we have to download the appropriate version of Scala wrt the version we're building Scala.js for. So actually we end up with one subdirectory for each version of Scala we build against.

In dotty's case, there's only ever one specific version, so it's easier, and the submodule idea can work without any particular hassle.

**Comment by DarkDimius** [comment]
Note, that branch submodules were added in Git 1.8.2, which was realeased in 2013. 
Git version prior to that will silently clone master and fail the test suite later.

**Pull request closed without merging**
