### PR TITLE
Inliner improvements

### PR DESCRIPTION
**Pull request by odersky**
This is some preliminary work to improve the Inliner to allow a larger set of idioms to be used in typeclass derivation. The idioms are tried in typeclass-derivation2{b|c}.scala, which serve as test-beds for now.

### CODE REVIEW

**Comment by odersky** [comment]
[run/typeclass-derivation2c.scala](https://github.com/dotty-staging/dotty/blob/inliner-fixes/tests/run/typeclass-derivation2c.scala) is a worked out strawman that illustrates a feasible code generation strategy for typeclass derivation. It would be good to have the input of everyone involved before potentially proceeding to an implementation of these generation patterns.

**Comment by odersky** [comment]
This needs a technical review whether the bug fixes and improvements in the inliner make sense. For the purpose of this review we can treat the new typeclass-derivation{a|b}.scala files simply as tests. 

We should separately discuss whether this is the scheme that should be implemented by the compiler. I propose we do that second discussion in #6153.

**Comment by milessabin** [comment]
@odersky I'm having trouble figuring out what the bugfixes and/or inliner improvements actually are here. Can you briefly summarise?

**Comment by odersky** [comment]
The compiler changes are in the commit messages of e2e56eb, b939933, b0b2383, f7d2658, 20e54a3.
The other commits elaborate the test cases.

**Comment by smarter** [comment]
Merging this PR broke the CI: http://dotty-ci.epfl.ch/lampepfl/dotty/12073/4
>  tests/neg/i6241.scala failed

**Comment by milessabin** [comment]
Ahh, right ... that became a pos test.

**Pull request merged**
