### PR TITLE
Support custom val symbol in ValDef.let

### PR DESCRIPTION
**Pull request by cchantep**
Related to #13929 

Currently `ValDef.let` doesn't allow to define `Flags` for the `val` definition.

Usage:

```scala
val tpe = TypeRepr.of[String]

val valSym = Symbol.newVal(
  Symbol.spliceOwner,
  "myValName",
  tpe,
  Flags.Lazy,
  Symbol.noSymbol
)

ValDef.let(Symbol.spliceOwner, valSym, Expr("foo")) { v =>
  '{ println(v) }.asTerm
}
```

In this way, it's possible to create an `Ref` to the `val` before its definition (required for recursive/lazy definitions).

```scala
// After `tpe` and `valSym` but before `let` call
val earlyRef = Typed(Ref(valSym), Inferred(tpe))
```

### CODE REVIEW

**Comment by nicolasstucki** [comment]
If you already created the `Symbol` you should use the normal `ValDef.apply` constructor. The `ValDef.let` constructors are the ones that create the symbol for you.

**Comment by nicolasstucki** [comment]
Maybe an example of how to use `ValDef.apply` would be helpful.

**Comment by nicolasstucki** [comment]
Also, if you have the symbol of the `val` you can recover its owner.

**Comment by cchantep** [comment]
> If you already created the `Symbol` you should use the normal `ValDef.apply` constructor. The `ValDef.let` constructors are the ones that create the symbol for you.

Yes you can, but that's quite error prone.

**Comment by nicolasstucki** [comment]
The quotes API will always be more error-prone than the quotes API. By using the symbol constructor we drove into an error-prone territory, the `let` does not help much there. If you want to make your code less error-prone consider using quotes instead. For example, creating a `lazy val` can be done with 

```scala
def lazyVal[T: Type, U: Type](rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
  '{ lazy val x: T = $rhs; ${body('x)} }

def lazyVal[T: Type, U: Type](name: String, rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
  // implement using reflection

// ...
// other variants of val definitions
```


Then your example can be simplified to
```diff
- val tpe = TypeRepr.of[String]

- val valSym = Symbol.newVal(
-  Symbol.spliceOwner,
- "myValName",
-  tpe,
-  Flags.Lazy,
-  Symbol.noSymbol
- )

- ValDef.let(Symbol.spliceOwner, valSym, Expr("foo").asTerm) { v =>
-  '{ println(v) }.asTerm
- }
+  lazyVal("myValName", Expr("foo")) { x => 
+   '{ println(v) }
+ }
```

I have always been against the addition of the `ValDef.let` helpers because they make it look like they are the simple version of how to generate `ValDef` in blocks. But it hides the even simpler version that I showed above. 

The only place where once needs to use the `ValDef` constructor is when creating members or parameters which is a completely different story.

**Comment by cchantep** [comment]
> The quotes API will always be more error-prone than the quotes API. By using the symbol constructor we drove into an error-prone territory, the `let` does not help much there. If you want to make your code less error-prone consider using quotes instead. For example, creating a `lazy val` can be done with
> 
> ```scala
> def lazyVal[T: Type, U: Type](rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
>   '{ lazy val x: T = $rhs; ${body('x)} }
> 
> def lazyVal[T: Type, U: Type](name: String, rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
>   // implement using reflection
> 
> // ...
> // other variants of val definitions
> ```
> 
> Then your example can be simplified to
> 
> ```diff
> - val tpe = TypeRepr.of[String]
> 
> - val valSym = Symbol.newVal(
> -  Symbol.spliceOwner,
> - "myValName",
> -  tpe,
> -  Flags.Lazy,
> -  Symbol.noSymbol
> - )
> 
> - ValDef.let(Symbol.spliceOwner, valSym, Expr("foo").asTerm) { v =>
> -  '{ println(v) }.asTerm
> - }
> +  lazyVal("myValName", Expr("foo")) { x => 
> +   '{ println(v) }
> + }
> ```
> 
> I have always been against the addition of the `ValDef.let` helpers because they make it look like they are the simple version of how to generate `ValDef` in blocks. But it hides the even simpler version that I showed above.
> 
> The only place where once needs to use the `ValDef` constructor is when creating members or parameters which is a completely different story.

The

**Comment by cchantep** [comment]
> > The quotes API will always be more error-prone than the quotes API.

?

> > By using the symbol constructor we drove into an error-prone territory, the `let` does not help much there. If you want to make your code less error-prone consider using quotes instead. For example, creating a `lazy val` can be done with
> > ```scala
> > def lazyVal[T: Type, U: Type](rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
> >   '{ lazy val x: T = $rhs; ${body('x)} }
> > 
> > def lazyVal[T: Type, U: Type](name: String, rhs: Expr[T])(body: Expr[T] => Expr[U])(using Quotes): Expr[U] =
> >   // implement using reflection
> > 
> > // ...
> > // other variants of val definitions
> > ```

Using the quotes syntax requires to have `Type[T]`, the `Expr[T]` "world" rather than the `Term`/`TypeRepr` one.
So for me those are not alternative, neither to the current `ValDef.let`, nor to the one draft there.

**Comment by nicolasstucki** [comment]
If you have a `Term` you can always recover and `Expr[Any]` with `asExpr` and then recover its `Type`. 
The type can be recovered as shown in the [Macro Tutorial](https://docs.scala-lang.org/scala3/guides/macros/faq.html#how-can-i-get-the-precise-type-of-an-expr) with this code

```scala
rhsTerm.asExpr match
  case '{ $rhs: t } => 
    lazyVal[t]("myValName", rhs){ x => '{ println(v) } } // `[t]` can be iferred
```

**Comment by cchantep** [comment]
> If you have a `Term` you can always recover and `Expr[Any]` with `asExpr` and then recover its `Type`. The type can be recovered as shown in the [Macro Tutorial](https://docs.scala-lang.org/scala3/guides/macros/faq.html#how-can-i-get-the-precise-type-of-an-expr) with this code
> 
> ```scala
> rhsTerm.asExpr match
>   case '{ $rhs: t } => 
>     lazyVal[t]("myValName", rhs){ x => '{ println(v) } } // `[t]` can be iferred
> ```

Recovering an `Expr[Any]` is not sufficient to use in a typed quotes `'{ ... }`.

**Comment by nicolasstucki** [comment]
> Recovering an Expr[Any] is not sufficient to use in a typed quotes '{ ... }.

Not sure when it is not sufficient.  Could you provide an example?

We can use `'{ ... }` as in 
```scala
rhsTerm.asExpr match
  case '{ $rhs: t } => '{ lazy val myValName: t = $rhs; println(v) }
```

**Comment by cchantep** [comment]
> > Recovering an Expr[Any] is not sufficient to use in a typed quotes '{ ... }.
> 
> Not sure when it is not sufficient. Could you provide an example?
> 
> We can use `'{ ... }` as in
> 
> ```scala
> rhsTerm.asExpr match
>   case '{ $rhs: t } => '{ lazy val myValName: t = $rhs; println(v) }
> ```

- 1. In the use cases I see, it's not possible to do either `.asExprOf[T]` nor `'{ val v: T = ... }` because the `Type` is not statically known.
- 2. `println` would work with `Expr[Any]`, but as soon as you want to call a field/method specif to the type, as `'{ v.foo }`, the quotes will refuse.

**Comment by nicolasstucki** [comment]
> - 1. In the use cases I see, it's not possible to do either `.asExprOf[T]` nor `'{ val v: T = ... }` because the `Type` is not statically known.
> - 2. `println` would work with `Expr[Any]`, but as soon as you want to call a field/method specif to the type, as `'{ v.foo }`, the quotes will refuse.

Both those cases are possible and covered in the [matching-types](https://docs.scala-lang.org/scala3/guides/macros/quotes.html#matching-types) section of the Macro Tutorial.

To do `.asExprOf[T]` nor `'{ val v: T = ... }` need to make a statically known name for the type wich can be achieved with type variables in quoted patterns. The previous example already did that 

```scala
rhsTerm.asExpr match
  case '{ $rhs: t } =>
    // The type of `rhs` is statically known as `t`
    // A given `Type[t]` is available here
    rhsTerm.asExprOf[t] // ok
    '{ val x: t = $rhs; ... } // `t` statically known to be the given `Type[t]`
```
Alternatively we could do
```scala
rhsTerm.tpe match
  case '[t] =>
    // A given `Type[t]` is available here
    val rhs = rhsTerm.asExprOf[t] // ok
    '{ val x: t = $rhs; ... } // `t` statically known to be the given `Type[t]`
```

Methods and field/method can also be statically known

```scala
trait Foo:
  def foo: Int = 2
```

```scala
rhsTerm.asExpr match
  case '{ expr: Foo } =>
    '{ $expr.foo }
```
or to get the precise type `t`
```scala
rhsTerm.asExpr match
  case '{ type t <: Foo; expr: `t` } =>
    '{ $expr.foo }
```

**Comment by cchantep** [comment]
> > * 1. In the use cases I see, it's not possible to do either `.asExprOf[T]` nor `'{ val v: T = ... }` because the `Type` is not statically known.
> > * 1. `println` would work with `Expr[Any]`, but as soon as you want to call a field/method specif to the type, as `'{ v.foo }`, the quotes will refuse.
> 
> Both those cases are possible and covered in the [matching-types](https://docs.scala-lang.org/scala3/guides/macros/quotes.html#matching-types) section of the Macro Tutorial.
> 
> To do `.asExprOf[T]` nor `'{ val v: T = ... }` need to make a statically known name for the type wich can be achieved with type variables in quoted patterns. The previous example already did that
> 
> ```scala
> rhsTerm.asExpr match
>   case '{ $rhs: t } =>
>     // The type of `rhs` is statically known as `t`
>     // A given `Type[t]` is available here
>     rhsTerm.asExprOf[t] // ok
>     '{ val x: t = $rhs; ... } // `t` statically known to be the given `Type[t]`
> ```

We are not speaking of the same thing.
Having `t` extracted there doesn't help to select & apply functions/fields specific to this type.

```scala
v match {
  case '{ $rhs: t } =>
    '{
    val tv: t = $rhs
    tv.foreach { inner => println("inner=" + inner) }
/*
[error] ^^^^^^^^^
[error] value foreach is not a member of t.
 */
  }
}
```

> 
> Alternatively we could do
> 
> ```scala
> rhsTerm.tpe match
>   case '[t] =>
>     // A given `Type[t]` is available here
>     val rhs = rhsTerm.asExprOf[t] // ok
>     '{ val x: t = $rhs; ... } // `t` statically known to be the given `Type[t]`
> ```

With which version/branch? For me it doesn't compile.

```scala
v.asTerm.tpe match {
  case '[t] =>
    /*
[error] ^^^^
[error] Quote pattern can only match scrutinees of type scala.quoted.Type
     */
    println(s"t = $t")
}

val tpe: TypeRepr = TypeRepr.of[T]

val typ = tpe match {
  case '[t] => t
    /*
[error] ^^^^
[error] Quote pattern can only match scrutinees of type scala.quoted.Type
     */
}
```

> 
> Methods and field/method can also be statically known
> 
> ```scala
> trait Foo:
>   def foo: Int = 2
> ```
> 
> ```scala
> rhsTerm.asExpr match
>   case '{ expr: Foo } =>
>     '{ $expr.foo }
> ```
> 
> or to get the precise type `t`
> 
> ```scala
> rhsTerm.asExpr match
>   case '{ type t <: Foo; expr: `t` } =>
>     '{ $expr.foo }
> ```

If you are able to write such constraints `: Foo` or `type t <: Foo`, you are able to directly write `term.asExprOf[Foo]`.
The issues are not in such case.

**Comment by cchantep** [comment]
Not related to this PR specifically, but I think the documentation could more clearly state, that the quote type matching could be use to extract static type from `TypeRepr`/`Type[_]`.

```scala
  inline def foo[T](v: Any): Unit = ${ fooImpl[T]('v) }

  private def fooImpl[T: Type](v: Expr[Any])(using q: Quotes): Expr[Unit] = {
    import q.reflect.*

    TypeRepr.of[T].asType match {
      case '[t] =>
        val vt = Type.of[t]
        val typedExpr = v.asExprOf[t](using vt)

        '{
          val ve: t = ${typedExpr}

          println(s"ve = $ve")
        }
    }
  }
```

**Pull request closed without merging**
