### PR TITLE
Add names to `using` parameters for cleaner docs

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by odersky** [comment]
I am not sure this is a good idea. These names are just noise. What is the problem with the docs if they are left out? Maybe we need to upgrade the doc tool to handle this gracefully?

**Comment by nicolasstucki** [comment]
There are two issues
* All names appear as x$1
* We cannot refer to names in the @param in the docs

**Comment by arturopala** [comment]
What about adding `@using` annotation to the docs, accepting type name rather than parameter name? This would help to understand better the definition.

**Comment by nicolasstucki** [comment]
I will create an issue for this.

**Pull request closed without merging**
