### PR TITLE
Implement -print

### PR DESCRIPTION
**Pull request by edmundnoble**

### CODE REVIEW

**Comment by DarkDimius** [comment]
CLA [signed](http://www.lightbend.com/contribute/cla/scala/check/edmundnoble).
LGTM after tests pass.
Conflicts with #1345.

**Comment by odersky** [comment]
The options in ScalaSettings have been imported wholesale from scalac. We still need to do the work and remove those options that are not honored by dotty. In the case of -print, I believe we should not 
implement it, as -Xprint is already available. So I would rather change the PR to remove -print from ScalaSettings.

**Comment by odersky** [comment]
LHTM, thanks!

**Comment by nicolasstucki** [comment]
@edmundnoble you should squash those 3 commits (or remove the ones that cancel each other).

**Pull request merged**
