### PR TITLE
Decouple quoted Type interface from encoding V2

### PR DESCRIPTION
**Pull request by nicolasstucki**
Before, `quoted.Type` was defined as

```scala
// old
class Type[X <: AnyKind]:
  type T = X
```

Where `T` is the proper type of the instance of a `Type`. This is the type used for all operations within the compiler.

The only purpose of the type `X` was to be able to write context bounds as `[X: Type]` and staged types `Type[X]` instead of
`Type { type T = X }`.
Unfortunately, the type `X` makes the assumption that `X` is known, which implies that instances of `Type` with unknown types need to be encoded with a whildcard type.
A `val t: Type[?] = ...` is unusable as we cannot heal staged wildcard types, even though we do have a `t.T` which can be handled.

Now, we change the definition of `Type` to only have the type member and rename it to `QuotedType`.
```scala
// new
class QuotedType:
  type T <: AnyKind
```

This solves the aforementioned limitations with unkown staged types.
Now we are also able to remove the wildcard from `QuoteContext.tasty.Type.seal` and the result can be used in quotes.

To keep the context bound syntax and provide more descriptive name for the concept, we defined the `quoted.Type` type alias.

```scala
type Type[X <: AnyKind] = QuotedType { type T = X }
```

Alternative to #9485. This one does not affect the user interface.

### CODE REVIEW

**Comment by smarter** [comment]
> A val t: Type[?] = ... is unusable as we cannot heal staged wildcard types

What's special about types with wildcards that prevents them from being healed compared to types with abstract type members?

**Comment by nicolasstucki** [comment]
We do not have a way to recover the tag in some situations as we cannot do an implicit search on `Type[?]` not recover the tag from the path of the type.

**Comment by smarter** [comment]
> as we cannot do an implicit search on Type[?]

Does that change if you replace `Type{?]` by `QuotedType`? I don't really understand where the difference is.

**Comment by nicolasstucki** [comment]
The issue is that in the first one `$t` might be kept as `t.T` or might be dealiased to `?` (or one of its bounds) which we cannot recover from. In contrast, the second will always be `t.T`, even if we do not know more about the type.

**Comment by smarter** [comment]
> might be dealiased to ? (or one of its bounds) 

Where does that happen? That seems very wrong to me: a wildcard is a form of existential, it cannot be dealiased in any way without breaking soundness

**Comment by nicolasstucki** [comment]
Then it might not be dealiasing

**Pull request closed without merging**
