### PR TITLE
Empty PR to test the benchmarks again

### PR DESCRIPTION
**Pull request by smarter**
I'm suspicious.

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by liufengyun** [comment]
This morning I changed the forks and warmups for some noisy lines (mainly
Vector and exhaustivity check tests), that might explain some of the
changes.

Le 17 sept. 2017 5:47 PM, "Guillaume Martres" <notifications@github.com> a
écrit :

**Comment by smarter** [comment]
I think the bot decided to run the benchmarks again because you quoted the command :).

**Comment by liufengyun** [comment]
Thanks for the catch @smarter . The duplicate job removed and system updated. Now commands have to start from a line, so quoted commands are excluded.

**Comment by smarter** [comment]
Looks like the benchmark changes made a big difference, invalidating the results of https://github.com/lampepfl/dotty/pull/3133 and https://github.com/lampepfl/dotty/pull/3136. @liufengyun I suggest reverting the changes for now. In the future I guess we'll need to rerun the benchmarks for all points when we make changes like this.

**Comment by liufengyun** [comment]
@smarter I've temporarily reverted the changes in https://github.com/liufengyun/bench/commit/19cd60cdf8f7819ea418a0cc0a92eca9443569e5 on the server, which affects 5 lines. Now you can try again.

Note that re-run all benchmarks is both computationally expensive and laborious, thus re-run is only justified when there's a compelling reason.

1. Each point takes about 1 hour
1. The dependencies/structure of the compiler is changing, which requires updating the infrastructure to fit the compiler every time it changes.

**Comment by smarter** [comment]
test performance please

**Comment by smarter** [comment]
This looks more reasonable to me.

**Pull request closed without merging**
