### PR TITLE
Trial: Use `with` instead of `given` for context parameters

### PR DESCRIPTION
**Pull request by odersky**
This is the third experiment to change the current syntax that uses `given` for both instances and parameters. Instead of fiddling with the instance keyword (`witness` or `default`) we change the parameter syntax by going back to `with`, which we had before `given`.

Using `given` for parameters has several potential problems:

 - Many commenters felt that this was an over-use of `given` with too many similarities to the current status where `implicit` is used for everything.
 - Parameters in given instances were particularly burdensome. This was fixed in #7788, but the fix introduces problems on its own. First, it introduces another irregularity. Second, commenters felt the syntax was confusing because it looked too much like function types.
 
To start with browsing:

 https://github.com/dotty-staging/dotty/blob/try-with/docs/docs/reference/contextual/motivation.md

### CODE REVIEW

**Comment by odersky** [comment]
Changes in a nutshell:

 - Definition site context parameters are expressed ` with (x: T)` or `with T`.
 - Use site context arguments are expressed `.with(e)`.
 - Context function types (_aka_ implicit function types) are written `S? => T`.
 - Given instances go back to the `given x as T` syntax instead of `given x: T` before. This
   avoids the subtly different roles labels play for givens as compared to everywhere else. It also
   avoid the problem that a standalone given instance `given x as T` for a concrete class `T` 
   can no longer be confused with an abstract type.

One area where I feel `with T` works much better than `(given T)` are convoluted context parameter lists.  If you have many context parameters it is awkward to format them with `(given ...)` parameters, same as with `(implicit...)`.  As a consequence, may people will use extra long lines since they feel it's too difficult to break them into multi-line definitions. For instance, this beauty from #7859.
```scala
given [Left, Right](given lubLeft: Lub[Right], lubRight: Lub[Right])(given lub2: Lub2[lubLeft.Output, lubRight.Output]): Lub[Left | Right] ...
```
I believe this is much more legible if we change to `with`:
```scala
given [Left, Right](
with (lubLeft: Lub[Right], lubRight: Lub[Right])
with lub2: Lub2[lubLeft.Output, lubRight.Output])
as Lub[Left | Right] ...
```
`with` does have slightly weirder application syntax than `given`. But since these are _implicit_ parameters a definition syntax that flows well is much more important than the application syntax, IMO.

**Comment by soronpo** [comment]
I like than we get less of `given` everywhere. I'm unsure about `with`. Although used for annotations, but I would like to propose to use `@`, which actually means "at condition".

**Comment by bmeesters** [comment]
I quite like it. Pulling the `with` (or `given` or whatever) outside the parenthesis reads much better IMO. Using _with_ might be a bit confusing initially, but I think after a while it is easy to get used to. Also a big :+1: for using two different keywords for providing and expecting.

**Comment by odersky** [comment]
Note that this looks a bit like [C# constraints](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters), only with `with` instead of `where`. This is intentional. A good way to think about many classes of context parameters is as constraints  over the type parameters of a method.

**Comment by morgen-peschke** [comment]
> Note that this looks a bit like [C# constraints](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters), only with `with` instead of `where`.

Has `where` already been considered and rejected? This seems to read quite nicely:
```
def foo(a: Bar)(where b: Baz): Foo = ???

foo(a)
foo(a)(where b)
```

**Comment by odersky** [comment]
In the group meeting yesterdays there were concerns about `with` regarding visual binding precedence. 
In
```scala
      def max(x: T, y: T) with Ord[T] : T = ...
```
one is tempted to read `:` like a symbolic infix operator with higher precedence than `with`. I recognize the problem, so I tried to come up three other alternatives, given below. For each alternative, we study a horizontal layout, and a vertical layout, for the cases where there are many context parameters.

```scala
// infix with

      def max(x: T, y: T) with Ord[T] : T = 
        if x < y then y else x

      def max(x: T, y: T)
          with Ordering[T],
               Numeric[T])
          : T =
        if x < y then y else x

// tag in front of (...). instead of `where`, one can also use `implicit` or `given`, 
// the layout appearance is similar in each case.

      def max(x: T, y: T)(where Ord[T]): T = 
        if x < y then y else x

      def max(x: T, y: T)(
          where
            ord: Ordering[T], 
            n: Numeric[T]
        ): T =
        if x < y then y else x

// Context parameters in `{...}`

      def max(x: T, y: T){ Ord[T] }: T = 
        if x < y then y else x

      def max(x: T, y: T) {
          ord: Ordering[T], 
          n: Numeric[T]
        }: T =
        if x < y then y else x

// Have implicit parameters and normal parameters in one list, separated by `where` (or whatever).

      def max(x: T, y: T where Ord[T]): T = 
        if x < y then y else x

      def max(x: T, y: T
          where
            ord: Ordering[T], 
            n: Numeric[T]
        ): T =
        if x < y then y else x
```
Comparing all of these, I believe `with` still has the edge. I believe one can get used to the fact that `:` has lower precedence than `with` when reading code, in particular since this is already the case when `with` is placed on the other side of `:`. I.e.
```
  e : A with B
```
is parsed `e : (A with B)` and not `(e: A) with B`.

**Comment by liufengyun** [comment]
Previously `given` without parenthesis is a [problem](https://github.com/lampepfl/dotty/issues/7151#issuecomment-526920558) in the following example:

```Scala
  def dyni given QuoteContext  :  PV[Int] => Expr[Int] = dyn[Int]
```

One parsing obstacle in the above is that `given` can also start implicit function types. With `with`, it parses much better if we give put spaces around `:`:

```Scala
  def dyni with QuoteContext  :  PV[Int] => Expr[Int] = dyn[Int]
```

**Comment by liufengyun** [comment]
Or, we may use `return` as an alternative:

```Scala
  def dyni with QuoteContext return PV[Int] => Expr[Int] = dyn[Int]

  def max(x: T, y: T) with Ord[T] return T = ...
```

**Comment by kavedaa** [comment]
What if `as` is allowed as a synonym for `:` everywhere?

```scala
def max(x: T, y: T) with Ord[T] as T = ...
```

```scala
def dyni with QuoteContext as PV[Int] => Expr[Int] = dyn[Int]
```
```scala
def foo(i: Int)
  with Bar
  with Zip
  as String = ...
```
It would have to be allowed in simple constructs as well:

```scala
val x as Int = 1
```
```scala
def f(i as Int) as Int = i * 2
```
But would preferrably only be used where `:` would be visually ambiguous or confusing.

(I don't think the *particular* word `as` is perfect here - it has some connotations of "casting" or "conversion". `of type` might be more precise. But `as` has the advantage of being short. :) )

**Comment by odersky** [comment]
I think in the end using `:` with a space in front works reasonably well. Having a separate alternative syntax has its own downsides.

**Comment by hepin1989** [comment]
```
extension <extension name> on <type> {
  (<member definition>)*
}
```
Cool

**Comment by odersky** [comment]
Superseded by #8017

**Pull request closed without merging**
