### PR TITLE
Use scala/vscode-scala-syntax vscode plugin for syntax

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@smarter any feedback on this PR?

**Comment by smarter** [comment]
Does https://github.com/scala/vscode-scala-syntax matches exactly https://github.com/daltonjorge/vscode-scala now ?

**Comment by smarter** [comment]
Also can we get vscode-scala-syntax published under the name scala first.

**Comment by smarter** [comment]
or scala-lang maybe.

**Comment by nicolasstucki** [comment]
Now the syntax is exactly the same. I just added some code snippets. I will try to release it on some scala name.

**Comment by nicolasstucki** [comment]
@smarter now it is published as `scala-lang`.
https://marketplace.visualstudio.com/items?itemName=scala-lang.scala

**Pull request closed without merging**
