### PR TITLE
[WIP] Add methods to abstract over structure of case classes

### PR DESCRIPTION
**Pull request by felixmulder**
Inspired by #1341, I decided to take a crack at improving case classes. These commits add two members to case classes:

* `def fields: List[String]`
* `def toMap: Map[String, Any]`

I think it is important to have a good way of abstracting over the members of case classes, this provides just that. One drawback to having this signature in the `toMap` method is that we loose type information. Ideally something like an `HMap` could be used here to retain type information.

There's room for improvement in this implementation as well - for instance `def fields` could of course be a `@static val fields` in the companion instead.

These two functions could in turn be used to improve the `toString` capabilities of case classes as well as various forms of pickling. Let me know your thoughts on this - if it feels like a step in the right direction, I wouldn't mind spending some time on this.

### CODE REVIEW

**Comment by odersky** [comment]
I see lots of ideas for improvements to case classes. Instead of trying to do this piece-wise I would prefer to have a very comprehensive SIP detailing how case classes should in the future support generic programming. I'll open an issue for this to serve as a place where discussions can take place.

**Comment by felixmulder** [comment]
Sounds good :)

**Comment by sourcekick** [comment]
@odersky or someone else: Please provide the link to the new issue where this is/was being discussed further.

**Comment by Blaisorblade** [comment]
@sourcekick I can't read Martin's mind, but the next issue, #1347, appears highly relevant.

**Pull request closed without merging**
