### PR TITLE
small English grammar fixes

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Comment by ShapelessCat** [comment]
I think you need to sign this: https://www.lightbend.com/contribute/cla/scala

**Comment by bplommer** [comment]
> I think you need to sign this: [lightbend.com/contribute/cla/scala](https://www.lightbend.com/contribute/cla/scala)

thanks - done 😊

**Comment by nicolasstucki** [comment]
CLA signed: https://www.lightbend.com/contribute/cla/scala/check/bplommer

**Comment by b-studios** [comment]
Hey, @bplommer maybe you can rebase and fix the conflict? This would probably also trigger the CLA check again and then we are ready to go :)

**Comment by nicolasstucki** [comment]
Rebasing should fix the issue.

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
