### PR TITLE
Initialize quote cache on tasty inspector run

### LINKED ISSUE #13919: TastyInspector crashes when creating a TypeRepr of non-primitive type
## Compiler version

3.0.2, 3.1.0 and 3.1.1-RC1

Seems to be ok on 3.0.0

## Minimized code

```Scala
import scala.quoted.Quotes
import scala.tasty.inspector as ins
import scala.tasty.inspector.TastyInspector

class Traverser() extends ins.Inspector {

  def inspect(using q: Quotes)(tastys: List[ins.Tasty[q.type]]): Unit = {
    import q.reflect._

    TypeRepr.of[Int] // ok

    TypeRepr.of[String] // fail
    // java.util.NoSuchElementException: None.get while compiling out/app/jar/dest/out.jar
    // Exception in thread "main" java.util.NoSuchElementException: None.get
    //     at scala.None$.get(Option.scala:627)
    //     at scala.None$.get(Option.scala:626)
    //     at dotty.tools.dotc.quoted.QuotesCache$.getTree(QuotesCache.scala:19)
    //     at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:183)
    //     at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTypeTree(PickledQuotes.scala:66)
    //     at scala.quoted.runtime.impl.QuotesImpl.unpickleType(QuotesImpl.scala:2975)
    //     at Traverser.inspect(main.scala:11)
    //     at scala.tasty.inspector.TastyInspector$TastyInspectorPhase$1.runOn(TastyInspector.scala:73)
    //     at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
    //     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
    //     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
    //     at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
    //     at dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
    //     at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
    //     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    //     at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
    //     at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
    //     at dotty.tools.dotc.Run.compileUnits(Run.scala:228)
    //     at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:12)
    //     at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
    //     at dotty.tools.dotc.Driver.process(Driver.scala:199)
    //     at dotty.tools.dotc.Driver.process(Driver.scala:167)
    //     at dotty.tools.dotc.Driver.process(Driver.scala:179)
    //     at scala.tasty.inspector.TastyInspector$.inspectFiles(TastyInspector.scala:112)
    //     at scala.tasty.inspector.TastyInspector$.inspectAllTastyFiles(TastyInspector.scala:58)
    //     at main$package$.main(main.scala:32)
    //     at main.main(main.scala:25)
  }

}

@main() def main() = {

  val inspector = Traverser()
  scala.tasty.inspector.TastyInspector.inspectAllTastyFiles(
    Nil,
    "out/app/jar/dest/out.jar" :: Nil, // this is the jar of this program. Although we're not actually doing anything, we need to pass in at least one file, otherwise the bug does not manifest itself
    Nil
  )(inspector)

}
```

Mill build config

```
// install mill:
// curl -sS -L "https://github.com/com-lihaoyi/mill/releases/download/0.9.9/0.9.9" > mill && chmod +x mill

import mill._, scalalib._

object app extends ScalaModule {
  def scalaVersion = "3.1.0"
  def ivyDeps = Agg(
    ivy"org.scala-lang::scala3-tasty-inspector:${scalaVersion()}"
  )
}
```

Run mill app.jar && mill app in order to compile and run the program.

You can also get the fully working example here: https://github.com/jodersky/tasty-inspector-typerepr

## Output (click arrow to expand)

The error as shown in the comment in the snippet above

### PR DESCRIPTION
**Pull request by jodersky**
This fixes #13919

### CODE REVIEW

**Comment by jodersky** [comment]
cc @nicolasstucki

**Review by nicolasstucki — APPROVED** [review]

**Comment by jodersky** [comment]
Not sure what exactly broke in the community build. From what I can tell it looks like requests times out on a flaky network connection. Is there a way to retrigger the community-projects build?

**Comment by nicolasstucki** [comment]
That failure is happening in many PRs. We are looking into it. This PR probably did not break any of the projects in the community build.

**Comment by jodersky** [comment]
Is the community build failure a blocker? Could we rerun that check?

**Comment by nicolasstucki** [comment]
I restarted the build. If it still fails I would suggest rebasing.

**Pull request merged**
