### PR TITLE
Fix #5188: See through annotations and typevars when computing argume…

### LINKED ISSUE #5188: Inline avrargs crashes typer
```scala
object Test {
  inline def sum(inline args: Int*): Int = ???
  sum(1, 2, 3)
}
```
crashes with

```
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:426)
	at scala.collection.immutable.Nil$.head(List.scala:423)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:496)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:288)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:597)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:695)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:755)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$7(Applications.scala:780)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2058)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$1(Applications.scala:781)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:725)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:826)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:723)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:83)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1882)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1936)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1967)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1963)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1979)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2026)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2039)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedClassDef$1(Typer.scala:1593)
	...
```

### PR DESCRIPTION
**Pull request by odersky**
See through annotations (and typevars) when computing argument types.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
The commit message has a typo, #5198 is not an issue.

**Comment by nicolasstucki** [comment]
I guess it was supposed to be #5188. Is that correct?

**Comment by odersky** [comment]
Yes, #5188. I changed the commit message.

**Comment by odersky** [comment]
Now I get in -Ycheck:all:

    Exception in thread "main" class dotty.tools.dotc.reporting.diagnostic.messages$Error at i5188.scala:3: right-hand side of inline value args must be a known value

The problem is that the varargs 1, 2, 3 are known values, but their translation SeqLiteral(1, 2, 3) is not. @nicolasstucki can you see what we should do about it? We could just disable the `checkInlineConformant` check in Retypers, but I am not sure that's the right thing to do here.

**Comment by nicolasstucki** [comment]
I will have a look.

**Comment by nicolasstucki** [comment]
The fix in `TypeApplications.scala` looks good to me. @liufengyun Could you review my additional commits. Thanks.

**Pull request merged**
