### PR TITLE
Do the implicit search shadowing check in the correct context

### PR DESCRIPTION
**Pull request by smarter**
This commit fixes a very sneaky bug, the following code:
```scala
lazy val shadowing =
  typed(untpd.Ident(ref.name) withPos pos.toSynthetic, funProto)
       (nestedContext.addMode(Mode.ImplicitShadowing).setExploreTyperState)
```
is parsed by scalac as:
```scala
lazy val shadowing =
  typed(untpd.Ident(ref.name) withPos pos.toSynthetic, funProto);
(nestedContext.addMode(Mode.ImplicitShadowing).setExploreTyperState);
```
So we don't actually use the nested context in `typed`, instead we end
up implicitly using `ctx`!

Review by @odersky

### CODE REVIEW

**Comment by smarter** [comment]
This sort of bug is the reason why GCC 6 added a warning `-Wmisleading-indentation`, I wonder if we could do the same in scala.

**Comment by smarter** [comment]
The tests now fail with `assertion failed: inconsistent: some typevars were added to uncommittable constraint`.

@odersky : What's the harm of adding typevars to an uncommittable constraint set? Could we bypass this check?

**Comment by smarter** [comment]
Changing the assertion check was enough to make all tests pass, so I think this is good to go now.

**Comment by odersky** [comment]
LGTM

**Pull request merged**
