### PR TITLE
Change enum scheme to correspond to new description in issue #1970

### PR DESCRIPTION
**Pull request by odersky**
Always demand that type parameters of cases are given explicitly.

### CODE REVIEW

**Comment by odersky** [comment]
Only first commit needs to be reviewed.

**Comment by propensive** [comment]
Was the motivation that the "parameter-inference" was just too magic, otherwise?

**Comment by odersky** [comment]
Too much magic, and not consistent with design principles elsewhere, yes.

**Comment by sjrd** [comment]
The changes look good. I think it would be good to add tests for things that were previously impossible/very awkward. For example:
```scala
enum E[+T] {
  case A[T, U](t: T, u: U) extends E[T] // is the explicit extends necessary here?
  case B
}
```
and things like that.

**Comment by odersky** [comment]
@sjrd I'll roll in the tests in a future PR. Have to merge now to write the docs.

**Pull request merged**
