### PR TITLE
Fix in syntax.md. CSS adjustments

### LINKED ISSUE #14697: docs: broken highlighting in syntax summary for `"`
https://dotty.epfl.ch/docs/reference/syntax.html

image

### PR DESCRIPTION
**Pull request by pikinier20**
closes #14697 

@MarcinAman

### CODE REVIEW

**Review by KacperFKorban — COMMENTED** [review]
I think that we have to update the `highlight.pack.js` since it doesn't include support for `ebnf` ATM. Though for some reason it includes `OCaml` and `Ruby` for example :thinking:

Overall, I think that the change to styling is a big improvement :smile:

**Comment by KacperFKorban** [comment]
Hmmm, there is some code that looks lik`ebnf` support in hljs repo.
rel: https://github.com/highlightjs/highlight.js/pull/1255

**Comment by pikinier20** [comment]
Tried to bump hljs version and use ebnf syntax highlighting for this snippet but it broke:
image

**Comment by pikinier20** [comment]
Ok, just manually changed the hljs rules and added semicolons at the end of rules and got sth better:
image

Probably there's a way to remove the semicolons but it would require some work on hljs rules

**Comment by pikinier20** [comment]
image
this looks nice

**Review by KacperFKorban — APPROVED** [review]

**Comment by odersky** [comment]
I am afraid the change of semicolons completely butchered the grammar. The grammar is the core piece of specification. Every symbol counts. Please don't do wholesale changes like this without consulting more broadly.

**Comment by odersky** [comment]
I find it very problematic that a PR pretending to be style fix can change a core piece of the specification and all docs without passing proper review. We have to review how we deal with PRs and how we can avoid such blunders in the future.

**Comment by odersky** [comment]
I'll revert the commit for now, and re-open the issue.

**Comment by odersky** [comment]
I see now that all the `;` are meta-symbols for the EBNF, not symbols of the grammar itself. But we never did it that way. Every Java and Scala grammar I know is written without `;` terminators, for good reason: The `;` is too easily confused with a symbol in the grammar. So, please don't do sweeping changes to the docs like this.

**Comment by odersky** [comment]
I think in general if it is a change that affects docs wholesale it has to be discussed in team with the authors of the docs. I find it very frustrating to see docs I spent many hours writing massacred like this.

**Comment by pikinier20** [comment]
> I see now that all the `;` are meta-symbols for the EBNF, not symbols of the grammar itself. But we never did it that way. Every Java and Scala grammar I know is written without `;` terminators, for good reason: The `;` is too easily confused with a symbol in the grammar. So, please don't do sweeping changes to the docs like this.

The highlight.js tool which we use to highlight the syntax, is not very sophisticated and uses basic regexes to consume grammars. The authors of EBNF highlighting added these semicolons in order to simplify rules and not use lookaheads etc. (You need to know when the rule ends to parse next token as a LHS of next rule) 

I'm sorry about this situation. I guess we can just replace the semicolons with some invisible unicode character or any other symbol that won't be misleading.

**Pull request merged**
