### PR TITLE
Remove substDealias

### PR DESCRIPTION
**Pull request by smarter**
Does not seem to be needed anymore.

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by odersky** [comment]
I am not sure. SubstDealias was needed when we modeled parameters as refinements. But inprinciple the same configurations could arise through explicit refinements. How do we know 
this cannot lead to problems? I am worried about scenarios like

    [foo := bar]  P { type T = foo } # T

**Comment by smarter** [comment]
Hmm, but then just dealiasing does not seem to be enough to handle all cases, e.g. what about:
```scala
val x: P { type T = foo }
type S <: x.T
[foo := bar] S
```

**Comment by odersky** [comment]
@smarter Good point. Can we construct a test case out of this, or is there something else that means we don't substitute in situations like this? If we can't construct a test case I agree we should drop substDealias anyway in order to fail faster.

**Pull request merged**
