### PR TITLE
Record anonymous child classes for exhaustivity check

### PR DESCRIPTION
**Pull request by liufengyun**
Record anonymous child classes for exhaustivity check

### CODE REVIEW

**Comment by liufengyun** [comment]
@nicolasstucki could you please give some help with the decompile failure in CI? I run the following on my local machine:

```
sbt > dotc -Ythrough-tasty -Ycheck:all tests/pos/t8324.scala
```

It works without any problem.

**Comment by nicolasstucki** [comment]
I will have a look

**Comment by nicolasstucki** [comment]
@liufengyun the issue was not a fromtasty compilation one. It was about recompiling decompiled code. I remove it from the whitelist. Now it should work.

**Comment by nicolasstucki** [comment]
@liufengyun you still have a pickling test failing (t8611b)

**Comment by liufengyun** [comment]
Thanks a lot @nicolasstucki for the fix.

**Pull request merged**
