### PR TITLE
Teach backend to emit `iinc` instructions

### PR DESCRIPTION
**Pull request by harpocrates**
The backend is now able to turn `x += 42` into an `iinc 42`
instruction. The optimization only applies to `+=` and `-=`, provided
the the net increment fits inside a signed 16-bit value (the ASM library
handles choosing `iinc` or `wide iinc` as is appropriate).

Ported from scala/scala#9713

### CODE REVIEW

**Comment by harpocrates** [comment]
I'm not sure what to do about tests. The initial PR had tests, but they used `scala.tools.partest.BytecodeTest`. I tried grepping inside Dotty test directory for JVM bytecode tests but didn't find any. In fact, I couldn't find anything like [the Scala 2 `test/files/jvm`](https://github.com/scala/scala/tree/2.13.x/test/files/jvm) folder.

**Comment by smarter** [comment]
The equivalent is https://github.com/dotty-staging/dotty/tree/master/compiler/test/dotty/tools/backend/jvm, specifically https://github.com/dotty-staging/dotty/blob/master/compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala

**Comment by harpocrates** [comment]
Thanks @smarter! I completely forgot that there are tests in the `compiler` directory.

**Comment by odersky** [comment]
Is that something worth doing? I guess it won't make code any faster but it gives some small improvement in bytecode size. Is that worth the additional effort of maintaining the code? What does the Scala 2.13 backend do?

**Comment by bishabosha** [comment]
> Is that something worth doing? I guess it won't make code any faster but it gives some small improvement in bytecode size. Is that worth the additional effort of maintaining the code? What does the Scala 2.13 backend do?

This is a port of https://github.com/scala/scala/pull/9713 which was just merged

**Comment by lrytz** [comment]
It's mostly a cosmetic change. It could potentially benefit performance by pushing some methods below the JVM's inlining size limits. I also see it as going with the flow of the platform, javac emits `iinc` too. And we have more complicated code in the backend to maintain 🙂

**Review by lrytz — APPROVED** [review]

**Pull request merged**
