### PR TITLE
Avoid deprecated URL ctor in scaladoc

### PR DESCRIPTION
**Pull request by som-snytt**
Follow-up to https://github.com/lampepfl/dotty/pull/17403 includes scaladoc.

### CODE REVIEW

**Review by romanowski — APPROVED** [review]

**Review by romanowski — APPROVED** [review]

**Review by romanowski — APPROVED** [review]

**Review by romanowski — APPROVED** [review]

**Comment by ckipp01** [comment]
Screenshot 2023-05-08 at 09 13 07

@romanowski _really_ _really_ _really_ approves this 😆

**Review by ckipp01 — APPROVED** [review]
👍🏼 looks good, thanks @som-snytt.

**Comment by romanowski** [comment]
> @romanowski really really really approves this 😆

It is testament to the GitHub UI :) As they say ~~3~~ 4  times the charm :D

**Comment by som-snytt** [comment]
@ckipp01 I'm curious how this PR was merged. Is it without a merge commit, but a rebase and merge? I see the difference because `git branch -d` won't work locally. I haven't had coffee yet this morning.

**Comment by ckipp01** [comment]
> @ckipp01 I'm curious how this PR was merged. Is it without a merge commit, but a rebase and merge? I see the difference because `git branch -d` won't work locally. I haven't had coffee yet this morning.

I used whatever the default was, I think "Squash and merge". Maybe you already fetched upstream and synced? And since you deleted the branch here, it's deleted locally as well? Or do you mean it won't allow you to delete it locally?

**Comment by som-snytt** [comment]
Thanks, my M.O. is to fetch, rebase my local main, then `git branch -d` which will fail if the commit isn't merged "fully", so I don't worry about making a mistake. Otherwise (for nontrivial changes) I verify before `branch -D` to delete unconditionally.

**Pull request merged**
