### PR TITLE
Get more collections whitelisted

### PR DESCRIPTION
**Pull request by DarkDimius**
Adds all classes in `scala.collection.*` and `scala.collection.immutable.*`

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky please review.

**Comment by odersky** [comment]
I propose to rebase this on top of #928, so that we can see what failures remain.

**Comment by DarkDimius** [comment]
@odersky rebased and updated whitelist and issues.
Please review.

**Comment by odersky** [comment]
LGTM

**Pull request merged**
