### PR TITLE
Fix #16405 ctd - wildcards prematurely resolving to Nothing

### LINKED ISSUE #16405: Argument types are erroneously inferred as `Nothing` when a method is explicitly eta-expanded as in `f(_)`
## Compiler version

3.2.1 and 3.2.2-RC1

## Minimized code

Runnable: https://scastie.scala-lang.org/WNexehduQzOT4XJ2XfUB7Q

```Scala
import scala.compiletime.summonInline

case class TypeDesc[T](tpe: String)
object TypeDesc {
  given TypeDesc[Nothing] = TypeDesc("Nothing")
  given TypeDesc[String] = TypeDesc("String")
  given TypeDesc[Int] = TypeDesc("Int")
}

def exampleFn(s: String, i: Int): Unit = ()

inline def argumentTypesOf[R](fun: (?, ?) => R): (TypeDesc[?], TypeDesc[?]) = {
  inline fun match {
    case x: ((a, b) => R) =>
      (summonInline[TypeDesc[a]], summonInline[TypeDesc[b]])
  }
}

inline def argumentTypesOfNoWildCard[A, B, R](fun: (A, B) => R): (TypeDesc[?], TypeDesc[?]) = argumentTypesOf(fun)

inline def argumentTypesOfAllWildCard(fun: (?, ?) => ?): (TypeDesc[?], TypeDesc[?]) = argumentTypesOf(fun)

@main def main: Unit = {
  println(argumentTypesOf(exampleFn)) // good
  println(argumentTypesOf(exampleFn(_, _))) // bad
  println(argumentTypesOfNoWildCard(exampleFn(_, _))) // good
  println(argumentTypesOfAllWildCard(exampleFn)) // bad, even without explicit placeholders
}
```

## Output

```scala
(TypeDesc(String),TypeDesc(Int))
(TypeDesc(Nothing),TypeDesc(Nothing))
(TypeDesc(String),TypeDesc(Int))
(TypeDesc(Nothing),TypeDesc(Nothing))
```

## Expectation

```scala
(TypeDesc(String),TypeDesc(Int))
(TypeDesc(String),TypeDesc(Int))
(TypeDesc(String),TypeDesc(Int))
(TypeDesc(String),TypeDesc(Int))
```

Expected there to be no difference between `exampleFn` and `exampleFn(_, _)` form in type inference in general and when calling `argumentTypesOf`.
Expected all variants of argumentTypesOf* to not infer Nothing regardless of using wildcards anywhere in the parameter type.

This code is a minimized version of real library code in https://github.com/izumi/izumi which we're trying to port to Scala 3

### PR DESCRIPTION
**Pull request by odersky**
Fixes https://github.com/lampepfl/dotty/issues/16405, which was a problem because it could it get in the way of some metaprogramming techniques. The main issue was the fact that when typing functions, the type inference would first look at the types from the source method (in decomposeProtoFunction resolving found type wildcards to Nothing) and only after that, it could look at the target method.

This is a continuation and simplification of #16625

### CODE REVIEW

**Comment by odersky** [comment]
@jchyb It turned out that we don't need to detect wildcards arguments. It's simpler and equally valid to just avoid `Nothing` as an inferred parameter as long as their is an alternative.

**Review by jchyb — APPROVED** [review]
LGTM! It really does simplify things

**Review by jchyb — CHANGES_REQUESTED** [review]
Oh no, I just noticed that It looks like there are some related problems in the community-build after all

**Comment by odersky** [comment]
Yes, there's a problem with ZIO. I'll try to find out more what caused it.

**Comment by odersky** [comment]
@jchyb It turned out that one needs to take wildcards into account to make both zio and #16405 pass. Making type inference do the expected thing in all the edge cases is really a minefield. My latest changes essentially come back to your idea, but instead of keeping track of wildcards in a separate data structure, we simply keep the original wildcard bounds in decomposeProto.

**Review by jchyb — APPROVED** [review]
Looks great! Thank you

**Pull request merged**
