### PR TITLE
Fix #5833: Refine condition what constitutes an IFT in adapt

### LINKED ISSUE #5833: Implicit dependent functions typing behaves incorrectly
```scala 
object Dependent{
  def x: ( (i: Int) |=> Int ) = ???
  def y: ( (i: Int) |=> Int ) = x
}
object Independent{
  def x: ( Int |=> Int ) = ???
  def y: ( Int |=> Int ) = x
}
object NarrowDependent{
  def x: ( Int |=> Int ) = ???
  def y: ( (i: Int) |=> Int ) = x 
}
object WidenDependent{
  def x: ( (i: Int) |=> Int ) = ???
  def y: ( Int |=> Int ) = x 
}
```

Independent, NarrowDependent are compiled with no errors.
Dependent, WidenDependent both fail to compile:
Dependent:
```scala
Found:    => (i: Int) |=> Int(Dependent.x)
Required: Int
```
WidenDependent: 
```scala
Found:    => (i: Int) |=> Int(WidenDependent.x)
Required: Int
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by biboudis** [comment]
Before LGTMing I was wondering if the following is valid code. I took the first one and introduced `Entry`. By refining the return type of the context query based on it (once directly and one via tha parameter) I get the following error:

```scala
trait Entry { type Key; val key: Key }

class NarrowDependentDT[E <: Entry]{
  def x: given (e: E) => e.Key = ???
  def y: given (e: Entry) => e.Key = x
}
```

```scala
22 |  def y: given (e: Entry) => e.Key = x
   |                                      ^
   |                                 no implicit argument of type E was found for parameter of given (e: E) => e.Key
```

**Comment by AleksanderBG** [comment]
@biboudis are you sure the arguments are the right way around? Your example does compile if `x = y` instead.

**Comment by biboudis** [comment]
I also checked the inverse and indeed it worked. I am still confused by this however.

**Comment by odersky** [comment]
The error seems to be legit. `x` needs an `E` as argument, but we only have an `Entry`.

**Pull request merged**
