### PR TITLE
Correctly link to docs from index page

### PR DESCRIPTION
**Pull request by romanowski**

### CODE REVIEW

**Comment by romanowski** [comment]
fixes #10682

**Comment by nicolasstucki** [comment]
I believe you meant #10642

**Comment by romanowski** [comment]
Yes, It fixes #10642

**Review by abgruszecki — APPROVED** [review]
LGTM.

**Review by BarkingBad — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@romanowski these changes broke the Windows tests on master.

**Pull request merged**
