### PR TITLE
Remove reflectedFields macro

### LINKED ISSUE #11076: `community-docs` CI is using the non-bootstrapped library
`community-docs` CI is using the non-bootstrapped library. It must use the bootstrapped version of the library.

This was seen in https://github.com/lampepfl/dotty/pull/11074/checks?check_run_id=1689298098 where one of the methods was implemented `???` only on the `non-bootstrapped`.

### PR DESCRIPTION
**Pull request by nicolasstucki**
This macro is problematic because the community buid can be compiled on the non-bootstrapped library.

Fixes #11076

### CODE REVIEW

**Comment by liufengyun** [comment]
> This macro is problematic because the community build can be compiled on the non-bootstrapped library.

What is the problem with the non-bootstrapped library? Won't macros still work in that context?

**Comment by nicolasstucki** [comment]
Macros may not work properly if we change something from one version to the other. Also, if we change the TASTy version number we might be executing code that expects a different version. I hit one of those issues in #11074 which made it impossible to compile the community-build project.

**Comment by liufengyun** [comment]
> Macros may not work properly if we change something from one version to the other. Also, if we change the TASTy version number we might be executing code that expects a different version. I hit one of those issues in #11074 which made it impossible to compile the community-build project.

Thanks for the detailed explanation. So the rule to follow is: don't use macros in any sub-projects of Dotty, due to bootstrapping problems.

**Comment by nicolasstucki** [comment]
Don't use macros on sub-projects that use the non-bootstrapped compiler. Some projects only compile with the bootstrapped compiler and in those it is fine.

**Review by abgruszecki — APPROVED** [review]

**Review by liufengyun — APPROVED** [review]

**Pull request merged**
