### PR TITLE
Use `inline val` for inlined `final val`s

### PR DESCRIPTION
**Pull request by nicolasstucki**
These `val`s are already inlined and do not generate a field, but they
still generate a getter that is never used. My marking these as `inline`
we can remove the getter and save a few bytes at runtime.

By making these fields `inline` we can also check that the RHS constant
folds to a value at compile time.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Those are only in the compiler. Not in the library.

**Comment by smarter** [comment]
test performance please

**Comment by nicolasstucki** [comment]
Test performance please

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk the benchmarking machine is not responding.

**Comment by anatoliykmetyuk** [comment]
test performance please

**Review by smarter — APPROVED** [review]

**Pull request merged**
