### PR TITLE
Move TupledFunctions to standard directory

### PR DESCRIPTION
**Pull request by liufengyun**
Move TupledFunctions to standard directory

For discussion:

- [ ] Do we really need it? How useful they are in practice.

   For example, stdlib only defines such methods up to arity 5

- [ ] What about other operations? Such as, `curried` and `uncurried`?

- [ ] Rename `TupledFunction` to `FunctionTupling`?

### CODE REVIEW

**Comment by nicolasstucki** [comment]
`TupledFuntions` are there to support generic function application of any arity. I guess we could be added later to the language when someone finds the need for this feature.

**Comment by nicolasstucki** [comment]
The name was chosen to be aligned with `FuntionN.tupled`.

**Comment by nicolasstucki** [comment]
I believe we can encode `curry` and `uncurry` using `TupledFunction` and `*:`.

**Comment by nicolasstucki** [comment]
I created #10411 to discuss this further

**Review by nicolasstucki — APPROVED** [review]

**Comment by liufengyun** [comment]
Superseded by #10416

**Pull request closed without merging**
