### PR TITLE
Fix #8886: use alpha annotation from overriden symbols

### LINKED ISSUE #8886: Need not require @alpha Annotation, when it can be derived without conflict
I suggest not requiring @alpha Annotation, when an existing overridden method already annotated and there are no other conflicts

I design a library and want to globally use '_?' name ending to indicate Option
```Scala
  @alpha("codeOption") def code_? : Option[String]
```
For library design the annotation is not a problem, it is welcome.

But if the annotated methods have to be massively implemented by library users, the promising idea will fail

```Scala
import scala.annotation.alpha

trait Source:
  @alpha("codeOption") def code_? : Option[String]

// Current way
def getCode1: Source = new Source{ @alpha("codeOption") def code_? = Some("ABC") }

// Desired way, currently not possible
def getCode2: Source = new Source{ def code_? = Some("ABC") }
```

### PR DESCRIPTION
**Pull request by TheElectronWill**

### CODE REVIEW

**Comment by sjrd** [comment]
Erm, I don't think we should do that. Or at least, the current behavior is in line with the intention of the SIP, so it's working as intended.

**Comment by TheElectronWill** [comment]
Sorry, I forgot to check the related SIP.
Should we close the #9378 then? (or move it to feature-requests?)

**Comment by sjrd** [comment]
We should at least move it to feature-requests, yes. I'm not familiar with the procedure to do that, though.

**Comment by TheElectronWill** [comment]
There should be a `transfer issue` button on the right of the issue page. I am not allowed to use it with dotty-feature-requests.

**Pull request closed without merging**
