### PR TITLE
Fix scas compiler version

### PR DESCRIPTION
**Pull request by liufengyun**
Fix scas compiler version

### CODE REVIEW

**Comment by liufengyun** [comment]
We already override the compiler globally, it seems to be enough:

https://github.com/lampepfl/dotty/blob/master/community-build/src/scala/dotty/communitybuild/projects.scala#L89

**Comment by nicolasstucki** [comment]
It seems to have failed the tests

**Comment by liufengyun** [comment]
@anatoliykmetyuk Do you know if the following is necessary for mill (all other mill projects do the same), given that there is already a global override?

```diff
-    baseCommand = "scas.application"
+    baseCommand = s"scas.application[$compilerVersion]"
```

**Comment by anatoliykmetyuk** [comment]
What needs to be done is this:

https://github.com/dotty-staging/PPrint/blob/7a668f52cc19addd4f24e41ef11714a8e2b0e405/build.sc#L103-L104

For all mill projects.

**Comment by liufengyun** [comment]
The necessary changes are now in #10632

**Pull request closed without merging**
