### PR TITLE
Increase the maximum heap size on Jenkins

### PR DESCRIPTION
**Pull request by smarter**
Review by @odersky or @DarkDimius

### CODE REVIEW

**Comment by smarter** [comment]
```
[info] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006ded80000, 2463629312, 0) failed; error='Cannot allocate memory' (errno=12)
[info] #
[info] # There is insufficient memory for the Java Runtime Environment to continue.
[info] # Native memory allocation (mmap) failed to map 2463629312 bytes for committing reserved memory.
[info] # An error report file with more information is saved as:
[info] # /home/jenkins/workspace/dotty-master-validate-partest/hs_err_pid24921.log
```
I think this means that we're trying to allocate more memory than available on the VM.

@SethTisue, @adriaanm : How much memory do the VMs have? Is this something that could be increased?

In the meantime, I'll try reducing `-Xmx` a bit and see if I can find a middle ground.

**Comment by DarkDimius** [comment]
@smarter 

Quoting @adriaanm 
> behemoths are c4.2xlarge, the others c4.xlarge

c4.2xlarge = 15 Gb Ram,
c4.xlarge = 7.5 Gb ram

**Comment by smarter** [comment]
/rebuild -- let's see if this is stable now

**Comment by smarter** [comment]
@DarkDimius : can we reduce the parallelism so that we use less memory?

**Comment by smarter** [comment]
OK, I've done four runs with the maximum heap size increased from 1 GB to 1.1 GB for Jenkins and they all succeeded, so I propose we merge this now and worry about a longer-term solution later. I didn't change the memory settings used when running the tests locally because decreasing the heap size there would probably slow down the tests.

**Comment by odersky** [comment]
Can we give it 1.5G? That would give us some margin for more complicated
tests.

 - Martin

On Sat, Jan 16, 2016 at 9:15 PM, Guillaume Martres <notifications@github.com
> wrote:

> OK, I've done four runs with the maximum heap size increased from 1 GB to
> 1.1 GB for Jenkins and they all succeeded, so I propose we merge this now
> and worry about a longer-term solution later. I didn't change the memory
> settings used when running the tests locally because decreasing the heap
> size there would probably slow down the tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/1030#issuecomment-172252345>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
> Can we give it 1.5G? That would give us some margin for more complicated tests.

Unfortunately not, I tried that at first but got the failure described in https://github.com/lampepfl/dotty/pull/1030#issuecomment-172213236 because apparently we're using up all the RAM available on the VM instance, 1.1G is the max I could get away with, even 1.25G is too much. So this is really a short-term fix.

**Comment by smarter** [comment]
Note that if the VM instances had a swap partition then at least we wouldn't get a crash when using too much RAM, it would just be very slow, but an even better fix would be to figure out how we're using the 15GB of RAM of the VMs (I have no idea how many JVMs we run in parallel and what controls this)

**Comment by DarkDimius** [comment]
> I have no idea how many JVMs we run in parallel and what controls this

We run 1 JVM per core. 
Those Amazon EC2 VMs have 1.875 GB per core.

**Comment by smarter** [comment]
> We run 1 JVM per core. 

You mean, `partest` starts 1 JVM per-core? But you also have to take into account the JVM used by sbt itself right?

**Comment by smarter** [comment]
If N=Number of cores, could we try running partest with N-1 JVMs instead of N JVMs?

**Comment by DarkDimius** [comment]
c4.2xlarge:
8 Cores,
15 GB Ram.

Even if we run 9 JVMs, that' 1.6GB per VM.

**Comment by smarter** [comment]
You also have to take into account that some ram is used by the OS itself, and the total memory usage of a JVM is bigger than its heap size, but I don't know how much, so we might be close to the limit.

**Comment by smarter** [comment]
(One thing that might be worth investigating: in the error I showed above the amount of memory that the JVM tried to "commit" was 2463629312 bytes = 2.35 GB, this is much bigger than the maximum heap size of 1.5G I specified, so something weird may be going on here, we might have more details once https://github.com/scala/scala-jenkins-infra/pull/157 is merged and we can take a look at the log file).

**Comment by odersky** [comment]
Wait: Partest runs N threads in one VM. Otherwise we would not have seen
data races. Each thread runs a full compiler, and a full compiler needs a
couple 100 mb to compile a significant chunk of sources. So it seems to me
that if max heap if fixed we could still reduce memory pressure by reducing
N. What is N at the moment?


On Sun, Jan 17, 2016 at 12:11 AM, Guillaume Martres <
notifications@github.com> wrote:

> (One thing that might be worth investigating: in the error I showed above
> the amount of memory that the JVM tried to "commit" was 2463629312 bytes =
> 2.35 GB, this is much bigger than the maximum heap size of 1.5G I
> specified, so something weird may be going on here, we might have more
> details once scala/scala-jenkins-infra#157
> <https://github.com/scala/scala-jenkins-infra/pull/157> is merged and we
> can take a look at the log file).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/1030#issuecomment-172267809>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
> What is N at the moment?

It's the number of cores on the machine, here's an attempt at reducing this: https://github.com/lampepfl/dotty/pull/1032

**Comment by SethTisue** [comment]
> @SethTisue, @adriaanm : How much memory do the VMs have? Is this something that could be increased?

Adriaan has some numbers at https://github.com/scala/scala-jenkins-infra/blob/master/doc/design.md, not entirely sure they're current. If you want to poke around yourself, we should probably get you access to the Jenkins nodes so you can ssh in and investigate on your own, try experiments from the command line, etc.  see https://github.com/scala/scala-jenkins-infra/blob/master/doc/client-setup.md#hosts-and-ssh-config

**Comment by smarter** [comment]
@SethTisue : That could be useful in the future yes, I guess you'll need me to give you an ssh key, if so you can use: http://guillaume.martres.me/id_rsa.pub

**Comment by SethTisue** [comment]
@adriaanm could you help Guillaume with this? I realized this is part of this process I don't know about, the docs just say "Send Adriaan your public key... He will use it to encrypt your credentials"

**Comment by adriaanm** [comment]
Here's the section where you documented how to do this: https://github.com/scala/scala-jenkins-infra/blob/master/doc/client-setup.md#get-your-public-key-added :-)

**Comment by SethTisue** [comment]
You can lead a horse to documentation, but you can't make him drink. Even if you are the horse.

**Comment by SethTisue** [comment]
Hmm, I merged https://github.com/scala/scala-jenkins-infra/pull/159 and ran chef-client on jenkins-master, but I didn't see anything about the change in the resulting output, and I don't see Guillaume's key in `~ec2-user/.ssh/authorized_keys`. Is there something else we need to do to make the change kick in?

**Comment by adriaanm** [comment]
`default['authorized_keys']['jenkins']` is for the `jenkins` user

**Comment by SethTisue** [comment]
hmm. do I need to run chef-client on the workers?

**Comment by adriaanm** [comment]
yes, but they should run that on a schedule

**Comment by SethTisue** [comment]
ok. @smarter, if this isn't already working for you, let us know.

**Pull request merged**
