### PR TITLE
Reorder match based on frequency

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance please

**Comment by odersky** [comment]
Where did you get the frequency data from? I believe the previous scheme was already optimized for dotty bootstrap. With the new scheme dotty bootstrap seems slower. Could be noise, of course.

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
I got the frequencies by compiling dotty bootstrapped with counters I added to the pattern match branches.

**Comment by odersky** [comment]
I see. The numbers I looked at was total numbers of trees generated. It seems there are some small differences there.

**Comment by liufengyun** [comment]
@nicolasstucki You'll go two points ahead to find the previous testing point, as there are two merges after the first test point.

**Comment by smarter** [comment]
@liufengyun Perhaps the testing points could be shown in a different colors (blue) ?

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
I won't put more reorderings in this PR. It is ready for review

**Comment by smarter** [comment]
The benchmarks result appear empty to me, so it's hard to review this :).

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
I've cleaned up the rubber in the data resulted from the exception in `scalapb` and a bug in the script. Now the charts are visisble (need refresh, clear cache?).

**Comment by smarter** [comment]
@nicolasstucki  From the benchmarks result it's unclear if the reordering had any effect, did you see a difference in local testing?

**Comment by odersky** [comment]
It does not seem to matter much, but it can't possibly make things worse. So, LGTM.

**Pull request merged**
