### PR TITLE
Port ClassPath optimisations and bug fixes from scalac

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by smarter** [comment]
- Don't put people nickname with an @ in commit messages, otherwise they'll get an email everytime the commit is rebased/merged somewhere
- when you port a commit, I would keep the following information in the commit message:
 - the original title of the commit
 - the original content of the commit message
 - the original hash of the commit
 - the full name of the author for proper attribution, not the nickname

Examples: https://github.com/lampepfl/dotty/pull/2229/commits

**Comment by smarter** [comment]
I think it's fine to have the PR URL in the commit message too :)

**Comment by smarter** [comment]
test performance please

**Comment by allanrenucci** [comment]
>I think it's fine to have the PR URL in the commit message too :)

Should I include both the commit hash and the PR url?

**Comment by smarter** [comment]
Yeah.

**Comment by smarter** [comment]
Thanks to the latest commit, you should be able to remove this: https://github.com/lampepfl/dotty/blob/master/sbt-dotty/sbt-test/source-dependencies/binary/project/P.scala#L10-L12 and the nightly tests should still pass

**Comment by smarter** [comment]
You can manually check that this test in particular passes by doing:
```scala
> sbt-dotty/scripted source-dependencies/binary
````

**Comment by liufengyun** [comment]
@allanrenucci @smarter : currently the benchmarks only work if the PR is made from the `dotty-staging/dotty` repo. I've to investigate why it doesn't send an error message.

**Comment by smarter** [comment]
@allanrenucci Could you recreate this PR using the dotty-staging repo so we can benchmark it?

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
@allanrenucci @smarter : testing PRs from any github repo is now supported.

**Pull request closed without merging**
