### PR TITLE
Improve support for Unicode supplementary characters in identifiers and string interpolation (as in Scala 2)

### LINKED ISSUE #16271: Improve support for Unicode supplementary characters in identifiers and string interpolation (as in Scala 2)
## Minimized code

```Scala
Welcome to Scala 3.2.0 (19, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val Trying to highlight erroneous position <7..7>. Input size: 6
😈 = 42
-- Error: --------------------------------------------------------------------------------------------------------------
1 |val 😈 = 42
  |    ^
  |    illegal character '\ud83d\ude08'

scala>
```

## Shotput

Gave it a shot.

## Expectation

https://twitter.com/SethTisue/status/1587184657141039110

### PR DESCRIPTION
**Pull request by som-snytt**
Forward port https://github.com/scala/scala/pull/9805

Fixes #16271

### CODE REVIEW

**Comment by som-snytt** [comment]
image

**Review by lrytz — APPROVED** [review]
LGTM

**Comment by SethTisue** [comment]
@som-snytt merge conflict needs resolving

My only concern before hitting "merge" is to ask whether you looked at whether `docs/_docs/internals/syntax.md` and/or `docs/_docs/reference/syntax.md` need to be updated?

**Comment by som-snytt** [comment]
It looks like the fix on Scala 2 had no impact on the spec because it's "Unicode."

**Comment by som-snytt** [comment]
> Could `§` be allowed too? It seems nonsensical to allow emojis but not the paragraph character, which is on our keyboards.

In what context? is it punctuation? Not every character is accepted everywhere.

Arbitrary identifiers:
```
scala> def `§` = 42
def $u00A7: Int
```

Also, not on my keyboard.

**Comment by TheElectronWill** [comment]
> In what context? is it punctuation? Not every character is accepted everywhere.

Yes, the the [section sign](https://www.fileformat.info/info/unicode/char/00a7/index.htm) is in the "punctuation" category. So are `!`, `?` and `/`, which are all allowed without backticks :)

**Comment by raquo** [comment]
> It would make a nice replacement for $ in frontend cases like Laminar.

To clarify Laminar's use case – we tend to prefix variable and method names with `$` as a shorthand for "stream of / signal of". It's an easy way to distinguish between similar but different types at a glance, by name alone, e.g.:

```
val item: Item = ???
val items: List[Item] = ???
val $item: EventStream[Item] = ???
val $items: EventStream[List[Item]] = ???
val $$items: EventStream[EventStream[List[Item]]] = ???
// etc.
```

This convention arose because `$` is the only symbolic character that alphanumeric identifiers can be prefixed with. It's been very useful that way, until we learned that `$` is reserved for compiler internals.

I suggest that it would be useful to allow some "keyboard-typeable" special character to be used as a prefix (or alternatively, as a suffix) to identifiers like variable and method names, and if that's not feasible, to perhaps allow characters like `§`. Emojis are... cool, but they are too visually disruptive to be used for this purpose in my humble opinion.

We only point to `§` because it's visually similar to `$`, I don't know enough about the compiler internals to say what is a good idea for the language, just trying to communicate the problem that the lack of `$` presents us.

**Comment by som-snytt** [comment]
That's an interesting use case. I'd suggest https://github.com/lampepfl/dotty-feature-requests

**Pull request merged**
