### PR TITLE
Initial infrastructure and hello world for the Scala.js back-end.

### PR DESCRIPTION
**Pull request by sjrd**
The Scala.js back-end can be enabled with the `-scalajs` command-line option. Currently, it adds one phase to the pipeline, which emits .sjsir files from trees.

A sandbox project `sjsSandbox`, in `sandbox/scalajs/`, can be used to easily test Scala.js compilation. One can run the `main()` method of the `hello.world` object with

    > sjsSandbox/run

The back-end only contains the bare mimimum to compile the hello world application in the sandbox. Anything else will blow up (for example, primitive method calls). It is a work-in-progress.

### CODE REVIEW

**Comment by sjrd** [comment]
I am not sure whether you would consider this for inclusion in the repo, at this point. But I figured it was in a good enough state to suggest it.

In any case, I would very much like comments on the general aspect. Please tell me if I'm doing anything stupid at this point.

It might be interesting to compare this with the scalac implementation at https://github.com/scala-js/scala-js/tree/master/compiler/src/main/scala/org/scalajs/core/compiler
In particular, the "giant" `JSCodeGen` is mostly parts of [`GenJSCode`](https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala).

I guess all of @odersky @DarkDimius @smarter might be interested in having a look at this, if not all the details.
Also /cc @nicolasstucki and @gzm0.

**Comment by DarkDimius** [comment]
>In any case, I would very much like comments on the general aspect. Please tell me if I'm doing anything stupid at this point.

I followed most of the code. Ideologically it looks good to me. I'd be curious to see how much different would be handling of `Try` and code generated by patmat compared to scalac. Please tell me if you'll need help understanding some details(especially in LabelDefs).

**Comment by sjrd** [comment]
Rebased. I saved the earlier comments at https://github.com/sjrd/dotty/commit/57c1b1c7fdee3129d44be8b5c3e0c4c7d7bdc373
Note that, if you comment on the Files tab *of the PR* (instead of in the commits), the comments survive rebases on GitHub.

**Comment by sjrd** [comment]
@DarkDimius I added a commit moving `JSDefinitions` to a custom `SJSPlatform` as you suggested. This required to have a valid `ctx` with properly initialized `settings` when creating the `ContextBase.platform`, which required to defer its initialization.

I am not sure if the new situation is desirable. But in any case the required changes highlight that, in master, `platform` is a useless concept, since it is not configurable.

**Comment by sjrd** [comment]
Are OOMs in partest CI common? Or are the failures in fact not spurious?

**Comment by smarter** [comment]
I'm getting them too so it's probably not your fault, we're just steadily using more and more memory, you can try increasing https://github.com/lampepfl/dotty/blob/master/project/Build.scala#L11 and see if it helps.

**Comment by sjrd** [comment]
It appears to have helped, indeed.

So, from my side, I'm happy with this PR the way it is. I guess it deserves a real review, now.

**Comment by sjrd** [comment]
@DarkDimius Following our conversation from this afternoon, I have added a commit addressing your concern about the bootstrap'ability of scalajs-ir. Instead of depending on the compiled artifacts, the build now depends on the sources and compiles them as part of dotty. In bootstrap tests, they are therefore part of the compilation of dotty by itself.

**Comment by sjrd** [comment]
As for *testability*, something we could do would be to simply add a CI command `sbt sjsSandbox/run`. This triggers the Dotty+Scala.js compilation, the linking (including verying the IR--similar to how the JVM verifies bytecode), and the execution with Rhino of the generated .js code.

**Comment by DarkDimius** [comment]
@sjrd, for testability, I leave this for you to decide. Please tell me if you wish to add it to CI.
LGTM

**Comment by sjrd** [comment]
Thanks!

> Please tell me if you wish to add it to CI.

I think it would be worth it, yes.

**Comment by smarter** [comment]
How long do the tests take?

**Comment by sjrd** [comment]
> How long do the tests take?

`sjsSandbox/run`? Less than 3 seconds on my machine.

**Comment by smarter** [comment]
OK then, add it :).

**Pull request merged**
