### PR TITLE
Fix #241

### LINKED ISSUE #241: Type overriding does not result in type intersection
The following:
```scala
class A { type T = Int; val x: T = 1 }
class B extends A { override type T = String }

object O {
  val b: B = new B
  val s: String = b.x
}
```
Compiles without any error. 
RefChecks.scala mentions:
```
        // types don't need to have their bounds in an overriding relationship
        // since we automatically form their intersection when selecting.
```
Should b.x have the type "Int | String" ?
CC @odersky @DarkDimius @namin .

### PR DESCRIPTION
**Pull request by odersky**
Finally works now. Note that this needs the previous fixes to go in as well. Only two commits are new here. I tried on master, but this caused many errors which go away when using branch fix-#939.

Review by @smarter or @samuelgruetter (only last two commits).

### CODE REVIEW

**Comment by smarter** [comment]
OK, I'm not exactly sure what the proper fix is but:

1. In `ClassInfo#typeRef`, if `this` is `ClassInfo(Mix___eFoo_I_wBar__f, class I)`, then the owner of the class `I` is `Foo_I_` which is different from `this.prefix`, so `clsDenot` return `cls.denot.copySymDenotation(info = this)`.
2. In `NamedType#computeDenot` we call `prefix.isTightPrefix(d.owner)` to check if we need to recompute the denotation of this type. The prefix of the `TypeRef` computed by the method in step 1 is `Mix___eFoo_I_wBar__f`, but the owner is `Foo_I_`, so we end up recomputing the denot, which leads to subtyping checks, which leads to a loop.

Since we don't allow class overriding in Dotty I think we can just bypass the `isTightPrefix` check when the denotation is a `ClassDenotation` like this: https://github.com/smarter/dotty/commits/fix-%23241

Alternatively, we could change the owner of the denot returned by `clsDenot` in `ClassInfo#typeRef`.

**Comment by odersky** [comment]
In general we can't prevent the recomputation of the denotation without
giving it a fixed sym. That's what symbolicTypeRef does.

On Mon, Dec 14, 2015 at 10:45 PM, Guillaume Martres <
notifications@github.com> wrote:

> OK, I'm not exactly sure what the proper fix is but:
>
>    1. In ClassInfo#typeRef, if this is ClassInfo(Mix___eFoo_I_wBar__f,
>    class I), then the owner of the class I is Foo_I_ which is different
>    from this.prefix, so clsDenot return cls.denot.copySymDenotation(info
>    = this).
>    2. In NamedType#computeDenot we call prefix.isTightPrefix(d.owner) to
>    check if we need to recompute the denotation of this type. The prefix of
>    the TypeRef computed by the method in step 1 is Mix___eFoo_I_wBar__f,
>    but the owner is Foo_I_, so we end up recomputing the denot, which
>    leads to subtyping checks, which leads to a loop.
>
> Since we don't allow class overriding in Dotty I think we can just bypass
> the isTightPrefix check when the denotation is a ClassDenotation like
> this: https://github.com/smarter/dotty/commits/fix-%23241
>
> Alternatively, we could change the owner of the denot returned by clsDenot
> in ClassInfo#typeRef.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/1000#issuecomment-164569584>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
OK, so why can't we always call `symbolicTypeRef` in `typeRef`?

**Comment by odersky** [comment]
Symbolic refs go stale on reload.

On Tue, Dec 15, 2015 at 12:58 AM, Guillaume Martres <
notifications@github.com> wrote:

> OK, so why can't we always call symbolicTypeRef in typeRef?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/1000#issuecomment-164598638>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
LGTM, I think I get it, but:
> In general we can't prevent the recomputation of the denotation without giving it a fixed sym

I think that `ClassInfo#typeRef` always returns a type with a `SymDenotation` valid for the current run, so the only reason for recomputing the denotation is if the prefix is not tight:
```scala
          case d: SymDenotation =>
            if (this.isInstanceOf[WithFixedSym]) d.current
            else if (d.validFor.runId == ctx.runId || ctx.stillValid(d))
              if (d.exists && prefix.isTightPrefix(d.owner) || d.isConstructor) d.current
              else recomputeMember(d) // symbol could have been overridden, recompute membership
            else {
              val newd = loadDenot
              if (newd.exists) newd else d.staleSymbolError
            }
```
So just disabling the `isTightPrefix` for class denotations should work, but maybe there's some cases I'm missing.

**Comment by smarter** [comment]
(I said LGTM but the `frozen_<:<` still need to be added before this is merged).

**Comment by odersky** [comment]
Is it OK with people if we merge the whole PR? At this stage everything before the PR feels very outdated, and I would not want to base anything on it.

**Comment by smarter** [comment]
Fine with me.

**Pull request merged**
