### PR TITLE
Fix typo, reorder words for better clarity

### PR DESCRIPTION
**Pull request by yoohaemin**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Thank you for the fix @yoohaemin! Can you please sign the CLA [here](https://www.lightbend.com/contribute/cla) so that we can merge this?

**Comment by yoohaemin** [comment]
CLA signed!

**Comment by nicolasstucki** [comment]
@yoohaemin are you sure you signed the correct CLA? It still says `false` https://www.lightbend.com/contribute/cla/scala/check/yoohaemin

**Comment by yoohaemin** [comment]
Sorry for the confusion, seems I signed the wrong one. I signed the Scala one this time.

**Comment by nicolasstucki** [comment]
Thanks @yoohaemin

**Pull request merged**
