### PR TITLE
Move s.u.FromString to s.u.CommandLineParser.FromString.

### PR DESCRIPTION
**Pull request by sjrd**
There are many competing ways to parse things. `FromString` is tailored for command-line parsing. As such we should not expose it with a general name like `scala.util.FromString`. Instead, we move it inside `CommandLineParser` to make it clear that it is meant for command-line parsing.

### CODE REVIEW

**Review by odersky — APPROVED** [review]
The expect file of SemanticDB tests needs an update. Otherwise LGTM

**Comment by sjrd** [comment]
Updated with a rebase + executing
```
> scala3-compiler-bootstrapped/test:runMain dotty.tools.dotc.semanticdb.updateExpect
```

**Comment by sjrd** [comment]
Re-running ...

**Comment by sjrd** [comment]
Well this time the Windows bootstrapped build passed, but the community build job refused to even start ...

**Comment by smarter** [comment]
I restarted the CI runner which was stuck, restarting this job too and hopefully it'll work now.

**Pull request merged**
