### PR TITLE
Fix typo in union-types doc

### PR DESCRIPTION
**Pull request by rockjam**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@felixmulder dotty-bot and the CLA check disagree.

@rockjam did you sign the CLA?

**Comment by felixmulder** [comment]
https://www.lightbend.com/contribute/cla/scala/check/rockjam <- no

**Comment by felixmulder** [comment]
There will be some weird interactions with the bot if the commit meta data and account are not synced properly. I'd have to look at the JSON for the commits in this PR to know for sure.

**Comment by rockjam** [comment]
@nicolasstucki where do I sign CLA?

**Comment by smarter** [comment]
@rockjam https://www.lightbend.com/contribute/cla/scala

**Comment by rockjam** [comment]
@smarter Thanks

**Comment by rockjam** [comment]
Actually, typo is fixed already in master.

**Pull request closed without merging**
