### PR TITLE
Navigation displays only flatten package structure

### PR DESCRIPTION
**Pull request by romanowski**
Classes, methods etc are not longer added to navigation

### CODE REVIEW

**Comment by romanowski** [comment]
cc @pikinier20 @BarkingBad

**Comment by abgruszecki** [comment]
OK, I actually think that the hierarchy looks way better in this PR:
https://scala3doc.virtuslab.com/pr-10299/scala3-stdlib/api/index/index.html
than it does on master:
https://scala3doc.virtuslab.com/pr-master/scala3-stdlib/api/index/index.html

Will merge once CI passes.

**Review by abgruszecki — APPROVED** [review]

**Review by abgruszecki — CHANGES_REQUESTED** [review]
Alright, correction: this PR actually seems to break unrolling navigation. Compare:

https://scala3doc.virtuslab.com/pr-master/scala3-stdlib/api/scala/collection/immutable/-lazy-list/index.html?query=@SerialVersionUID(3)%20final%20class%20LazyList[+A]%20extends%20AbstractSeq[A]%20with%20LinearSeq[A]%20with%20LinearSeqOps[A,%20[A]%20=%3E%3E%20LazyList[A],%20LazyList[A]]%20with%20IterableFactoryDefaults[A,%20[A]%20=%3E%3E%20LazyList[A]]%20with%20Serializable

https://scala3doc.virtuslab.com/pr-10299/scala3-stdlib/api/scala/collection/immutable/-lazy-list$/index.html#[58][58]/index.html

I guess that this is because classes are no longer items in navigation.

@romanowski I think we should fix that before merging this PR.

**Comment by romanowski** [comment]
sure. good catch. I will take a look.

**Review by abgruszecki — APPROVED** [review]

**Pull request merged**
