### PR TITLE
Consider aliases of Any as top

### LINKED ISSUE #19610: Excessively loose type inference
## Compiler version

3.3.1
3.4.0-RC4

## Minimized code

```Scala
// Error: Cannot prove that A[U] <:< A[N].
Wrap(new A[N]{})

// Adding the obvious type argument to Wrap makes it compile just fine.
Wrap[N](new A[N]{})

final case class Wrap[T <: U](first: A[T])(using A[T] <:< A[N])

sealed trait A[+T]

type U = Any
type N = Nothing
```

## Compiler output

```scala
Cannot prove that A[U] <:< A[N].
```

## Expectation

No error, similarly to when `U` is inlined, or `N` is not set to `Nothing`.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #19610

### CODE REVIEW

**Comment by odersky** [comment]
This is kind of dangerous. We previously took `[T <: Any]` as an approximation of `[T]` since that's the best we can do. But now, if `type Alias = Any` we also treat `[T <: Alias]` as "having no upper bound", which is patently untrue.

**Comment by dwijnand** [comment]
I feel like we should sway one side or the other, not this in-between, where `[T]` and `[T <: Any]` are the same but, `[T <: Any]` and `[T <: Alias]` aren't.  Maybe upper bound should be `Option[Type]` 😀

**Comment by odersky** [comment]
It does not matter what the precise rules are, as long as we stick to them.

**Comment by dwijnand** [comment]
I think "aliases shouldn't affect typing" is a rule we obey.  I'm not sure if it's a rule for type inference too, but _I_ think it should be.  By "stick to them" do you mean don't touch how inference works or am I interpreting too broadly?

**Pull request closed without merging**
