### PR TITLE
Reduce allocations when loading packages from classpath

### PR DESCRIPTION
**Pull request by liufengyun**
Reduce allocations when loading packages from classpath

This is a port of the following PR in scalac:

https://github.com/scala/scala/pull/8927

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
test performance please

**Review by odersky — APPROVED** [review]
LGTM so far. I pushed another commit that uses the new method for more operations. 

Correction: I tried to do that but it meant that many name operations needed a Context now, where they need none before.
So, that's problematic. Let's first see whether the additional operations termName(String), typeName(String) need to be called very often. Right now, they are, but that's because of other things that are in the queue to be optimized away. Let's see what remains.

**Comment by odersky** [comment]
I now went the other way and moved the "string slice to name" logic into Decorators. That way we can keep Names
clean of Contexts, which is a clearer architecture.

**Pull request merged**
