### PR TITLE
Revert docs to 0.18 state

### PR DESCRIPTION
**Pull request by odersky**
Since reference docs are always online, we should not change them before
the Dotty version implementing the changes is released.

The new version of contextual docs is instead found in contextual-new
and linked from the old docs. Same for metaprogramming/inline.html.

### CODE REVIEW

**Comment by OlivierBlanvillain** [comment]
Would it make sense to stop publishing the website on every merge and instead do it manually when we release? WDYT @anatoliykmetyuk?

**Comment by julienrf** [comment]
Or maybe have two online places where we could browse the docs? One for the last release, and the other continuously rendered from `master`.

**Comment by anatoliykmetyuk** [comment]
Not all changes to the docs reflect the stuff changed by a release. But some changes do. We can push such changes to the corresponding release branch. E.g. 0.19.0-RC1 changes go in PRs against 0.19.x branch. Since there is a step in the release procedure where we merge a release branch into master on release (to make sure master contains all the changes from the release) these changes will end up in master exactly on release.

**Comment by anatoliykmetyuk** [comment]
Or, since there's no 0.19.x right now, we can push to 0.18.x - this will get the changes into master on stable 0.18.0 release.

Alternatively we can create 0.19.x branch right now from master and push the docs there. On 19-RC release, we merge master into 0.19.x instead of creating that branch as previously from master.

**Comment by anatoliykmetyuk** [comment]
I argue for the second option since the 19-RC docs belong with the 19-RC branch.

**Comment by OlivierBlanvillain** [comment]
With short release cycles I think we should keep it as simple as possible, which would be something like publish the master's docs on every release and do something more complicated to backport docs changes.

IIRC the current process with `RCs` and `0.X` branch for each release was setup specifically to be able to backport commits into specific releases in order to make new `0.X.1`/`0.X.2` releases while keeping master linear, but I'm not sure we did that even once, so lets not over-engineer the process for documentation...

**Comment by anatoliykmetyuk** [comment]
I mean, it is already quite overengineered :) changing one step doesn't change the picture.

**Comment by anatoliykmetyuk** [comment]
Also I wouldn't call 6 weeks a short cycle if we are talking about the ability to make modifications to the website.

**Pull request merged**
