### PR TITLE
Closes #1319 Report git-hash used to package the distribution in REPL

### LINKED ISSUE #1319: REPL should report git-hash used to package the disrtibution
Something similar to https://github.com/hmrc/sbt-git-stamp simplify implementing this.

### PR DESCRIPTION
**Pull request by krasinski**
- Adds SBT BuildInfoPlugin to know git-hash in runtime
- Reports git-hash in REPL

### CODE REVIEW

**Comment by felixmulder** [comment]
Hi @krasinski, thanks for the PR. It looks like you're hitting a CI oddity. A rebuild should fix it.

Cheers,
Felix

**Comment by krasinski** [comment]
I will try to do this in another way - by storing the git-hash in manifest file and then reading it back in runtime.

**Comment by krasinski** [comment]
Hi @felixmulder, I pushed the new solution, can you review?

**Comment by felixmulder** [comment]
LGTM, great job @krasinski !

**Pull request merged**
