### PR TITLE
Correct typo in query types

### PR DESCRIPTION
**Pull request by stevenheidel**
Correction 3 of 3 that I found while reading the docs last night. (If this isn't right then I've misunderstood something)

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
Thank you for the fix @stevenheidel! Can you please sign the CLA [here](https://www.lightbend.com/contribute/cla) so that we can merge this?

**Comment by stevenheidel** [comment]
Thanks, it's now signed

**Comment by nicolasstucki** [comment]
CLA verified https://www.lightbend.com/contribute/cla/scala/check/stevenheidel

**Comment by nicolasstucki** [comment]
This typo has already been fixed

**Pull request closed without merging**
