### PR TITLE
Survive TypeErrors in isMatchedBy

### LINKED ISSUE #15673: Bad parameter reference CC[A]#C at typer
This is a reproducer for the community build failure of scala-tessella/ring-seq reported in #15647 

## Compiler version

3.2.0-RC2
Works in 3.1.2
Fails in 3.1.3
Fails in 3.2.0-RC*
Fails in 3.2.1-RC1-bin-20220711-6efd92d-NIGHTLY

## Minimized code

```scala
trait SeqOps[+A, +CC[_], +C]:   // scala.collection.SeqOps
  def reverse: C

extension[A, CC[B] <: SeqOps[B, CC, CC[B]]](ring: CC[A])
  def startAt(i: Int): CC[A] = ???
  def reflectAt(i: Int): CC[A] =
    startAt(i).reverse
```

## Output

```scala
-- Error: ring.scala:7:11 ------------------------------------------------------
7 |    startAt(i).reverse
  |           ^
  |           bad parameter reference CC[A]#C at typer
  |           the parameter is type C in trait SeqOps but the prefix CC[A]
  |           does not define any corresponding arguments.
  |           idx = 2, args = [A]
```

## Workaround

```diff
-    startAt(i).reverse
+    val c = startAt(i)
+    c.reverse
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #15673

### CODE REVIEW

**Comment by odersky** [comment]
How I fixed it: 

At first, I was a bit puzzled why a change to hasKnownMembers would have an effect like the one seen in #15673. The test case was really simple, so that was a plus. I compiled with -Xprompt and looked at the stack trace. That indicated that the error was a TypeError that was raised somewhere else and that was caught and issued in `typedUnadapted`. I grepped for the error message and found the method where it was issued: `TypeRef#argDenot`. I converted the TypeError to AssertionError to see the stack trace where it was issued: `isMatchedBy` in ProtoTypes. That explained why it would appear now as a regression: `hasUnknownMembers` overapproximates less in #14762, so the failing code path after the `hasUnknownMembers` in `isMatchedBy` is now taken where previously it was masked. 

The question was still how to fix it. The problem was as explained in the new comment in `hasmatchingMember`
```
          // We have a type `CC[A]#C` where `CC`'s upper bound is `[X] => Any`, but
          // the current constraint stipulates CC <: SeqOps[...], where `SeqOps` defines
          // the `C` parameter. We try to resolve this using `argDenot` but `argDenot`
          // consults the base type of `CC`, which is not `SeqOps`, so it does not
          // find a corresponding argument. In fact, `argDenot` is not allowed to
          // consult short-lived things like the current constraint, so it has no other
          // choice. The problem will be healed later, when normal selection fails
          // and we try to instantiate type variables to compensate. But we have to make
          // sure we do not issue a type error before we get there.
```
The fix then was simply to catch a `TypeError` in `isMatchedBy` and return `false` instead. That would catch other `TypeErrors` as well (e.g. `CyclicReference). Arguably that's OK. `isMatchedBy` is a low-level operation that should not itself issue errors and should fail in a safe way when it encounters a `TypeError`. 

 some more output to that message to see the current

**Comment by odersky** [comment]
The CB build fails because of this:
```
sbt.librarymanagement.ResolveException: Error downloading tools.jackson:jackson-base:3.0.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/tools.jackson/jackson-base/3.0.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://scala-webapps.epfl.ch/artifactory/sbt-plugin-releases/tools.jackson/jackson-base/3.0.0-SNAPSHOT/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 409 for URL: https://scala-webapps.epfl.ch/artifactory/central/tools/jackson/jackson-base/3.0.0-SNAPSHOT/jackson-base-3.0.0-SNAPSHOT.pom) while downloading https://scala-webapps.epfl.ch/artifactory/central/tools/jackson/jackson-base/3.0.0-SNAPSHOT/jackson-base-3.0.0-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/tools/jackson/jackson-base/3.0.0-SNAPSHOT/jackson-base-3.0.0-SNAPSHOT.pom
```

**Comment by dwijnand** [comment]
Now there's a real puzzler: how does catching a TypeError cause scala-webapps.epfl.ch to start returning 409s?! 😄

**Review by dwijnand — CHANGES_REQUESTED** [review]
This seems like a little extreme.  Is there no way to add a guard somewhere that quietly returns false instead of recovering from a thrown exception?  Or can we at least tighten around what call can't be guarded but we want to recover from it throwing?

**Review by dwijnand — APPROVED** [review]
Ah, I see, 24 matched lines of with "case" and "TypeError".  OK, fair enough.

**Comment by griggt** [comment]
Rebased to fix community build failure.

**Review by griggt — APPROVED** [review]
Thanks for the explanation, I was struggling to make the connection.

**Pull request merged**
