### PR TITLE
Restrict visibility of copy and apply

### PR DESCRIPTION
**Pull request by odersky**
Make the synthesized copy and apply methods of a case class have the
same visibility as its private constructor.

I believe it would make sense to spec it that way.

### CODE REVIEW

**Comment by odersky** [comment]
This was prompted by https://contributors.scala-lang.org/t/removing-copy-operation-from-case-classes-with-private-constructors/2605.

**Comment by allanrenucci** [comment]
I suspect the change to `apply` might break a lot of code. I'll run this patch through the community build

**Comment by odersky** [comment]
> I suspect the change to apply might break a lot of code. I'll run this patch through the community build

That would be good to know, yes.

**Comment by allanrenucci** [comment]
It breaks the 2.13 std lib in one place: https://github.com/scala/scala/blob/b846ae5dd600456dd9f4da089bddea8ea5fbb58b/src/library/scala/collection/immutable/VectorMap.scala#L213

I am not sure what was the intention of the author here. cc/ @odd

**Comment by julienrf** [comment]
I guess `NextOfKin`’s constructor should be `private[Tombstone]` instead.

**Comment by smarter** [comment]
@adriaanm Opinions on whether this change could also make it to 2.13 or 2.14 ?

**Comment by adriaanm** [comment]
We could do something for 2.13.x (x > 0) under -Xsource to experiment with the community build. We're kind of maxed out for the next few weeks, but happy to accept PRs sooner.

**Comment by odersky** [comment]
> I guess NextOfKin’s constructor should be private[Tombstone] instead.

I agree. Exactly the same mistake was found in dotty's `Interactive` object. So I my tentative conclusion is that any errors caused by this change are true errors that should be fixed. 

@julienrf @odd Can one of you fix `VectorMap`, then we can merge this PR.

**Comment by odersky** [comment]
Thanks for the quick fix @julienrf. Can you merge this PR once the 2.13.x fix is in?

**Comment by smarter** [comment]
Hmm, If this doesn't get into 2.13, it's going to make cross-compilation harder, since getting your code to compile with Dotty might require a non-binary-compatible change :/.

**Comment by adriaanm** [comment]
I'll discuss with the team to see what we can do here.

**Comment by odersky** [comment]
A possible option would be to not do this under Scala-2 mode. Let's see what Scala 2.14 does.

**Comment by odd** [comment]
@allanrenucci @julienrf Indeed, the intention was to only allow direct calls to the constructor of `NextOfKin` from inside `Tombstone.apply` so it should have been `private[Tombstone]` all along.

**Comment by odersky** [comment]
> @allanrenucci @julienrf Indeed, the intention was to only allow direct calls to the constructor of NextOfKin from inside Tombstone.apply so it should have been private[Tombstone] all along.

So, arguably, the current behavior is surprising and could be a security risk. One more reason to fix it.

**Comment by adriaanm** [comment]
So, I don't think we can change this in 2.13 (at least not by default), both because of close we are to RC1 and due to the unknown amount of breakage this would cause. 

Cross-compilation should be achievable by explicitly writing the private apply method, right? Since these cases are rare, that doesn't sound like a big burden for added security.

**Comment by SethTisue** [comment]
> I don't think there's a known or recommended pattern to combine a private constructor with a public apply or copy method

My informal impression is that a private constructor usually arises when someone is trying to lock down a case class to prevent invalid instances from being constructed. You make the constructor private, and you write a custom public `apply` method that validates the arguments before calling the private constructor.

Can I assume that combination (private constructor, custom public apply) will remain supported?

**Comment by dwijnand** [comment]
> You make the constructor private, and you write a custom public `apply` method that validates the arguments before calling the private constructor.

What happens if the arguments aren't valid?

The only use-case I can think of for having a public `apply` that doesn't throw exceptions and has the same return type (`Foo`, not `Option[Foo]`) is for memoisation.

Also, it would be nice if a private constructor didn't become public in the bytecode and therefore public to Java users (https://github.com/scala/bug/issues/6882).

**Comment by smarter** [comment]
> Also, it would be nice if a private constructor didn't become public in the bytecode and therefore public to Java users

https://openjdk.java.net/jeps/181 should make this much easier for Java 11+.

**Comment by dwijnand** [comment]
See also https://github.com/scala/bug/issues/7085#issuecomment-292418408, Java has a strategy for this for inner classes already:

> Another tricky aspect of Java's approach to access is constructors. It creates 'access constructors' with an extra dummy parameter. The type of the parameter was used to uniquely distinguish the constructors, and was chosen to be the type of the inner class that needed to access the constructor.

**Comment by smarter** [comment]
I know, but I don't think it's worth changing things now just for Java 8.

**Comment by odd** [comment]
> The only use-case I can think of for having a public `apply` that doesn't throw exceptions and has the same return type (`Foo`, not `Option[Foo]`) is for memoisation.

A public user defined apply method is also useful for normalizing parameters before passing them on to the private constructor (especially so if the class is a case class and you want the normalized value to be used in the auto generated `equals`, `hashCode` etc).

**Comment by propensive** [comment]
In the longer term, can `copy` be implemented as an extension method with Scala 3's metaprogramming facilities? Would that be able to take into account the visibility modifiers on the constructor?

**Pull request merged**
