### PR TITLE
Remove DottyPredef

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Review by smarter — APPROVED** [review]

**Comment by nicolasstucki** [comment]
We are currently getting an error while running `tests/run-staging`. It looks like the library is not found in the classpath. Not sure how removing `DottyPredef` could have triggered this issue. @odersky @smarter do you know why this could be happening?
We use `getClass.getClassLoader` to get the classloader that loaded the application. Could this be linked with loading `DottyPredef`?

<details>

```
Test 'tests/run-staging/i8178.scala' failed with output:                        
Exception in thread "main" java.lang.reflect.InvocationTargetException
  | => sat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
        at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Caused by: dotty.tools.dotc.MissingCoreLibraryException: Could not find package scalaShadowing from compiler core libraries.
Make sure the compiler core libraries are on the classpath.
   
        at dotty.tools.dotc.core.Denotations$.select$1(Denotations.scala:1237)
        at dotty.tools.dotc.core.Denotations$.recurSimple$1(Denotations.scala:1265)
        at dotty.tools.dotc.core.Denotations$.recur$1(Denotations.scala:1267)
        at dotty.tools.dotc.core.Denotations$.staticRef(Denotations.scala:1269)
        at dotty.tools.dotc.core.Symbols$.requiredPackage(Symbols.scala:841)
        at dotty.tools.dotc.core.Definitions.ScalaShadowingPackage(Definitions.scala:257)
        at dotty.tools.dotc.core.Definitions.init(Definitions.scala:1729)
        at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:830)
        at dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:542)
        at dotty.tools.dotc.Run.rootContext(Run.scala:67)
        at dotty.tools.dotc.Run.<init>(Run.scala:85)
        at scala.quoted.staging.QuoteCompiler$ExprRun.<init>(QuoteCompiler.scala:103)
        at scala.quoted.staging.QuoteCompiler.newRun(QuoteCompiler.scala:46)
        at scala.quoted.staging.QuoteDriver.run(QuoteDriver.scala:39)
        at scala.quoted.staging.Toolbox$$anon$1.run(Toolbox.scala:38)
        at scala.quoted.staging.package$.run(staging.scala:19)
        at i8178$package$.Test(i8178.scala:12)
        at Test.main(i8178.scala:8)
        ... 6 more
```
</details>

**Comment by griggt** [comment]
Just a passing thought on the test failure, not sure if relevant here: while investigating an unrelated issue that came up today on gitter, I noticed that calling `getClass` from a toplevel def showed up in the bytecode as 

```
invokevirtual #29   // Method dotty/DottyPredef$.getClass:()Ljava/lang/Class;
```

**Comment by nicolasstucki** [comment]
@griggt could you open an issue and point to the gitter thread?

**Comment by nicolasstucki** [comment]
Thank you @griggt, you just saved me a few hours of frustration.

**Comment by nicolasstucki** [comment]
@smarter I moved `DottyPredef` to `src-non-bootstrapped` and adapted some tests

**Review by smarter — APPROVED** [review]

**Pull request merged**
