### PR TITLE
Back to the future: `rewrite` to `inline`

### PR DESCRIPTION
**Pull request by odersky**
As a first step, rename all occurrences of `rewrite` to `inline`.

`inline` is now a soft keyword, so it can still be used as an annotation.

### CODE REVIEW

**Comment by Glavo** [comment]
image
It seems that repl can't highlight the `inline` keyword now.

**Comment by nicolasstucki** [comment]
Was it doing it before? I thought we never added highlight for it. Now we should.

**Comment by Glavo** [comment]
image

@nicolasstucki The inline keyword will be highlighted in Dotty 0.9.0-RC1.

**Comment by allanrenucci** [comment]
@nicolasstucki This is fixed in #5137. Maybe you should review it

**Pull request merged**
