### PR TITLE
Don't lift the argument of a `synchronized` block in scoverage

### PR DESCRIPTION
**Pull request by KacperFKorban**
possible fix for lampepfl#16940

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
I'm not 100% sure why it was `vals` instead of `defs` in the first place. I also can't think of anything wrong with this, but just to make sure I also tagged @TheElectronWill on this. However it's a LGTM from me. Thanks!

**Comment by TheElectronWill** [comment]
Will every argument be turned into a def, in all circumstances? I'm a bit worried about the performance and size overhead of that.

**Comment by nicolasstucki** [comment]
Isn't this changing the evaluation semantics?

**Comment by nicolasstucki** [comment]
From the test case, it seems that the failure is on a by-name argument. If so changing the binding of that by-name argument to a `def` is the correct fix. But we should use `def`s for by-name arguments.

**Comment by mohe2015** [comment]
Any updates on this?

**Comment by odersky** [comment]
I am not sure whether lifting to defs would break the semantics, i.e. whether we can guarantee used exactly once. Probably we can't. I would feel very nervous with such a change. Also lifting to defs certainly will make the code go much slower in many cases.

**Comment by nicolasstucki** [comment]
> Does lifting to defs actually change the semantics?

It should not. We already do that for by-name arguments of inline definitions.

> Don't we guarantee that every lifted expression will be referenced exactly once?

It is referenced once at the call site, but possibly evaluated many times in the function.

**Comment by odersky** [comment]
As far as I know, cbn arguments are already lifted into defs. It's just cbv arguments that are lifted into vals.

**Comment by KacperFKorban** [comment]
Ok. In that case, I changed this fix to just avoid lifting arguments of `synchronized` blocks.

**Comment by KacperFKorban** [comment]
@nicolasstucki does this look ok now?

**Pull request merged**
