### PR TITLE
Drop old extension method syntax

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@odersky I created #9534 to help unblock this PR

**Comment by odersky** [comment]
I give up. Can somebody else take this over please?

**Comment by nicolasstucki** [comment]
I'll have a look at it

**Comment by odersky** [comment]
@nicolasstucki I think I have switched branches by accident. Trying again.

**Comment by nicolasstucki** [comment]
There was one extension left using the old syntax. Now it should be fine.

**Comment by odersky** [comment]
@nicolasstucki It seems something with the pushing of xml-interpolator went wrong. Did you push the new commits in that submodule.

**Comment by nicolasstucki** [comment]
I pushed the commit and restarted the tests

**Comment by odersky** [comment]
Good to get this over the finish line!

**Pull request merged**
