### PR TITLE
Community build: split into 3 concurrent jobs

### PR DESCRIPTION
**Pull request by griggt**

### CODE REVIEW

**Review by anatoliykmetyuk — APPROVED** [review]
LGTM

**Comment by smarter** [comment]
If you're interested in reviving this PR (was there anything missing that led to it staying unmerged?), now might be a good time as the community build has grown quite a bit.

**Comment by griggt** [comment]
At the time, I didn't think it was a big enough win (~45 vs. 60 minutes at the cost of an extra runner)

I'll have a look at updating it today.

**Comment by griggt** [comment]
Latest community build running times (minutes):

<table>
<tr><td>This PR</td><td> 44 / 46 / 44</td></tr>
<tr><td>Nightly build</td><td>72 / 59</td></tr>
</table>

**Review by smarter — APPROVED** [review]

**Pull request merged**
