### PR TITLE
Erasure#Typer: Document makeBridgeDef

### PR DESCRIPTION
**Pull request by smarter**
Review by @DarkDimius

### CODE REVIEW

**Comment by DarkDimius** [comment]
Am I missing something or changes are: 
  - one less error reporting(that instead will fail in non-obvious place in typeAssinger);
  - renaming of variables(newDefSym -> implDefSym, parentSym -> overridenSym);
  - previous method was able to run before erasure(and be reused by specialization), this one cannot as assumes single parameter list?

**Comment by smarter** [comment]
- The error method was not used, that's why I removed it.
- Yep, I also added comments
- Ah, I didn't know that being able to reuse it for specialization was planned, if you prefer I can drop this part of the changes.

**Comment by DarkDimius** [comment]
> The error method was not used, that's why I removed it.

It [was used](https://github.com/lampepfl/dotty/pull/491/files#diff-7d76351125e3a0376bea4b9db34a05ccL531).

>Yep, I also added comments

Comment looks fine for me.


I'd prefer to maintain previous names, I dont find new ones much better, as otherwise this commit touches most lines without good reason, and making following git history of changes harder. (I frequently use `git annotate` to see why the code is written in some particular way)

**Comment by smarter** [comment]
OK, commit changed to only add documentation to `makeBridgeDef`, I still think the renaming was useful though (you can always call git annotate/blame on an old revision).

**Comment by DarkDimius** [comment]
LGTM

**Pull request merged**
