### PR TITLE
Future migration warning for alphanumeric infix operator

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by dwijnand** [comment]
Do you see this warning on GitHub too?

image

Any idea why it pops up here?

**Comment by nicolasstucki** [comment]
I copy pasted the name form somewhere else when I created the branch. Unfortunately, it was formatted with unicode dashes and I only noticed it after I opened the PR.

**Comment by sjrd** [comment]
Let's make sure they don't make it into the merge commit message. The branch name will disappear but not the commit message.

**Comment by nicolasstucki** [comment]
I will create a new PR from a new branch to make sure everything is clean.

**Comment by nicolasstucki** [comment]
Replaced with #18908

**Pull request closed without merging**
