### PR TITLE
fix #13332: change accessibility in whyNotGenericSum

### LINKED ISSUE #13332: Summoning Mirror for ADT defined in trait
## Compiler version

scala-3.1.0-RC1-bin-20210817-f27c250-NIGHTLY (I tried  to use the most recent I could find as I thought there's a chance that https://github.com/lampepfl/dotty/pull/11686 might have fixed this as it's in a similar area. Not entirely sure if that made it into this nightly or not)

## Minimized code

```Scala
import scala.deriving.Mirror

class Scope extends IListDefn {

  type Of = Mirror { type MirroredType[X] = IList[X]; type MirroredMonoType = IList[Any] ; type MirroredElemTypes[_] <: Tuple }

  val M = summon[Of]
}


trait IListDefn {
  sealed trait IList[A]
  case class INil[A]() extends IList[A]
  case class ICons[A](h: A, t: IList[A]) extends IList[A]
}
```

## Output

```scala
[error] -- Error: /private/tmp/scala/Minimization.scala:7:20 ---------------------------
[error] 7 |  val M = summon[Of]
[error]   |                    ^
[error]   |no implicit argument of type Scope.this.Of was found for parameter x of method summon in object Predef
[error] one error found
```

## Expectation
Compilation should succeed (and does if you move the `IList` definition out of the trait and up to top-level)

### PR DESCRIPTION
**Pull request by bishabosha**
change to use `isAccessibleFrom`

fixes #13332

### CODE REVIEW

**Comment by dwijnand** [comment]
image

🤔

**Comment by bishabosha** [comment]
> image
> 
> 🤔

I'll see what I can do today - but I imagine reviewing would not meet the deadline, so perhaps I should remove again

**Comment by odersky** [comment]
> I'll see what I can do today - but I imagine reviewing would not meet the deadline, so perhaps I should remove again

Even if it could be reviewed it should wait IMO. Big changes in functionality should be tested in nightlies for an extended period of time before being rolled into a release.

**Comment by bishabosha** [comment]
closing this in favor of a new approach

**Pull request closed without merging**
