### PR TITLE
 Fix ensureFreshScopeAfter always cloning scope

### PR DESCRIPTION
**Pull request by smarter**
PR on top of https://github.com/lampepfl/dotty/pull/3216, only the last commit is new.

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by smarter** [comment]
Oops, I should have tested commit N-1 and N to get useful information. @liufengyun is there a way to cancel a running test?

**Comment by liufengyun** [comment]
You can issue another test for `N - 1`: `test performance please: 196c23c` --- the results will accumulate.

**Comment by smarter** [comment]
Yes but they won't be in the correct order which will look confusing :).

**Comment by liufengyun** [comment]
> Yes but they won't be in the correct order which will look confusing

The hash will help disambiguate :)

I manually cancelled the job, you can reissue the command. I'll add a command to cancel running jobs.

**Comment by smarter** [comment]
Thanks!

**Comment by smarter** [comment]
test performance please: 196c23c ea1400f

**Comment by smarter** [comment]
@liufengyun help :smile: ^

**Comment by liufengyun** [comment]
test performance please: 196c23c ea1400f

There's some issue with the lock of jmh when force killing test.

**Comment by smarter** [comment]
ouch, bad parsing :P

**Comment by liufengyun** [comment]
test performance please: 196c23c ea1400f

**Comment by liufengyun** [comment]
There's some regression with the multi-commits test -- I just manually scheduled the test.

**Comment by liufengyun** [comment]
The multi-commit command should work now with the fix (already deployed on server): https://github.com/liufengyun/bench/commit/259f6263fe12c098790fdf754d6ca3d8eb07c8ac

**Comment by smarter** [comment]
@liufengyun Are the tests still running?

**Comment by liufengyun** [comment]
I just checked, there's now some issue with publishing website. I manually published below:

http://dotty-bench.epfl.ch/3222-1/index.html

But it only tests the first commit.

**Comment by liufengyun** [comment]
test performance please

**Comment by smarter** [comment]
Hmm this is going to be misleading because more stuff has been merged between the last test command 4 hours ago and the new test command now.

**Comment by liufengyun** [comment]
After the current test finishes, it's possible to run `retest performance please` to test against the latest master in a new test session.

**Pull request merged**
