### PR TITLE
Correct small typo in macros example

### PR DESCRIPTION
**Pull request by stevenheidel**
Correction 2 of 3 that I found while reading the docs last night.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@stevenheidel you will need to sign the CLA at https://www.lightbend.com/contribute/cla/scala.

Otherwise the changes look good to me.

**Comment by biboudis** [comment]
Change looks good @stevenheidel! Thanks!

I noticed your other PRs. We usually try to contain changes as a unit of work. I think we can merge these now but next time it would be more convenient if you would contain all relevant changes (e.g., Fixes at docs) as one PR. A draft PR is preferable if you have work in progress!

Despite this, a big thanks that you took the time to have a look and make the fixes 🎉

**Comment by stevenheidel** [comment]
Will do in the future, thanks. Also I just signed the CLA 👍

**Comment by nicolasstucki** [comment]
CLA verified https://www.lightbend.com/contribute/cla/scala/check/stevenheidel

**Pull request merged**
