### PR TITLE
Fix/#646 array addition

### PR DESCRIPTION
**Pull request by odersky**
Two fixes to implicits. First, a stratification of classTag methods in DottyPredef according to priority.
Second, and more importantly, we do not check for ambiguous implicits in viewExists. 

Review by @adriaanm @DarkDimius

### CODE REVIEW

**Comment by odersky** [comment]
The first three commits are from #665 and #666

**Comment by odersky** [comment]
Rebased to master

**Comment by DarkDimius** [comment]
otherwise LGTM

**Comment by odersky** [comment]
Rebased to master

**Pull request merged**
