### PR TITLE
Add 'Sciss/Lucre' to Community Build

### PR DESCRIPTION
**Pull request by Sciss**

### CODE REVIEW

**Comment by Sciss** [comment]
Hmmm. I could run `testOnly for scissLucre`, but apparently missed scalatest for some tests of dependencies. When I add `dependencies = List(scalatest)`, I get build error from scalactic:

```
Generated /home/hhrutz/Documents/devel/dotty/community-build/community-projects/scalatest/dotty/scalactic/target/scala-3.0.0-M3/src_managed/main/org/scalactic/ColCompatHelper.scala
Generated /home/hhrutz/Documents/devel/dotty/community-build/community-projects/scalatest/dotty/scalactic/target/scala-3.0.0-M3/src_managed/main/org/scalactic/ArrayHelper.scala
[error] -- [E007] Type Mismatch Error: /home/hhrutz/Documents/devel/dotty/community-build/community-projects/scalatest/dotty/scalactic/src/main/scala/org/scalactic/anyvals/NumericString.scala:1541:4 
[error] 1541 |    value.lines
[error]      |    ^^^^^^^^^^^
[error]      |    Found:    java.util.stream.Stream[String]
[error]      |    Required: Iterator[String]
[error] one error found
[error] (scalacticDotty / Compile / compileIncremental) Compilation failed
```
Don't know what to do.

**Comment by smarter** [comment]
```scala
[error] 1541 |    value.lines
[error]      |    ^^^^^^^^^^^
[error]      |    Found:    java.util.stream.Stream[String]
[error]      |    Required: Iterator[String]
```
This happens when running on a recent JDK which added String#lines that returns a Stream, it needs to be fixed upstream in scalatest but our community build runs on Java 8 and if you run it locally on Java 8 it should work.

**Comment by Sciss** [comment]
> ```scala
> [error] 1541 |    value.lines
> [error]      |    ^^^^^^^^^^^
> [error]      |    Found:    java.util.stream.Stream[String]
> [error]      |    Required: Iterator[String]
> ```
> 
> This happens when running on a recent JDK which added String#lines that returns a Stream, it needs to be fixed upstream in scalatest but our community build runs on Java 8 and if you run it locally on Java 8 it should work.

Ah! Yes, I had switched back to JDK 11 for other project, whereas before I ran successfully on JDK 8. So hopefully this test run succeeds now.

**Comment by smarter** [comment]
Ah, it's fixed upstream already: https://github.com/scalatest/scalatest/commit/543f9acd3cc3c33706ea15b6abd61f53bb3a65e3

**Comment by smarter** [comment]
>  Dotty CI / community_build_b (pull_request) Successful in 87m 

This is a > 20 minutes increased runtime for this job, I assume most of that comes from tests, could you try running less tests (for example, no tests for the intermediate projects and/or less tests for lucre itself) to reduce the running time?

**Comment by Sciss** [comment]
I don't know if this shave off much, the dependencies are very small, the only one that runs substantial tests is Scala STM, which I think would anyway be a project that should be tested in the CB.

When you look at the raw log, beginning at 2020-12-08T01:43:47.6464622Z

- preparing the build of Lucre (dependencies): ca. 4 minutes
- compilation: 1.5 minutes
- test run: 6 minutes (it does a lot of data structure and database-baked testing that uses disk I/O, so it's inherently taking that time)

That's around 11.5 minutes. In comparison, Scala STM, beginning at 2020-12-08T00:54:20.8986504Z

- preparing the build of Scala STM (dependencies): ca. 0.5 minutes
- compilation: 1.5 minutes
- test run: <1 minute

Now we're at 14.5 minutes. Add another 30 seconds for the other eight dependencies, then we sum up to around 20 minutes.

**Comment by Sciss** [comment]
Entire testing runs for 4 1/2 hours

**Comment by Sciss** [comment]
So to summarise, I don't think removing intermediate tests will bring down the time much; maybe two minutes or so. Running less (selected) tests for Lucre is not a good idea; here it would require that the tests be parametrised, for example to build smaller data structures; this could shave off max. three minutes I think.

**Comment by griggt** [comment]
Moving the tests for Lucre and its dependencies from `CommunityBuildTestB` to `CommunityBuildTestA` in `CommunityBuildTest.scala` may shave off another ~3.5 minutes (the build/publish time for scalatest), since scalatest is already built and published in `CommunityBuildA`, but not `CommunityBuildB`.

**Comment by Sciss** [comment]
Ok, should I try that - move to A, disable all tests but stm/lucre?

**Comment by smarter** [comment]
That sounds good to me, I also think we could try splititng the community build into more concurrent jobs now that we can run more jobs at once (https://github.com/lampepfl/dotty/pull/10703) but that can be explored separately.

**Comment by griggt** [comment]
> we could try splititng the community build into more concurrent jobs 

I had the same thought... how many runners do we have now?

**Comment by smarter** [comment]
> I had the same thought... how many runners do we have now?

14 right now, but I'm monitoring how things go and will increase it gradually until the machines are fully used.

**Review by smarter — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
