### PR TITLE
Refine criterion when to widen types

### LINKED ISSUE #15926: 3.2.0 regression around match types
## Compiler version

3.2-RC1, 3.2-RC2, 3.2-RC3, 3.2-RC4

## Minimized code

```Scala
@main def main(): Unit =
  println(summon[Sum[Minus[Succ[Zero]], Minus[Succ[Zero]]] =:= Minus[Succ[Succ[Zero]]]])

sealed trait IntT
sealed trait NatT extends IntT
final case class Zero() extends NatT
final case class Succ[+N <: NatT](n: N) extends NatT
final case class Minus[+N <: Succ[NatT]](n: N) extends IntT

type NatSum[X <: NatT, Y <: NatT] <: NatT = Y match
  case Zero => X
  case Succ[y] => NatSum[Succ[X], y]

type NatDif[X <: NatT, Y <: NatT] <: IntT = Y match
  case Zero => X
  case Succ[y] => X match
    case Zero => Minus[Y]
    case Succ[x] => NatDif[x, y]

type Sum[X <: IntT, Y <: IntT] <: IntT = Y match
  case Zero => X
  case Minus[y] => X match
    case Minus[x] => Minus[NatSum[x, y]]
    case _ => NatDif[X, y]
  case _ => X match
    case Minus[x] => NatDif[Y, x]
    case _ => NatSum[X, Y]
```

## Output

```scala
Cannot prove that Minus[NatSum[Succ[Succ[Zero]], NatT]] =:= Minus[Succ[Succ[Zero]]].

Note: a match type could not be fully reduced:

  trying to reduce  NatSum[Succ[Succ[Zero]], NatT]
  failed since selector  NatT
  does not match  case Zero => Succ[Succ[Zero]]
  and cannot be shown to be disjoint from it either.
  Therefore, reduction cannot advance to the remaining case

    case Succ[y] => NatSum[Succ[Succ[Succ[Zero]]], y]
```

## Expectation
Code should compile, as in Scala 3.1.3.

### LINKED ISSUE #17149: Match type bounded by type with argument(s) cannot be reduced to satisfy `=:=` check
Pointed out by @DmytroMitin in the following post:

https://stackoverflow.com/questions/75837775/in-scala-2-or-3-is-there-a-higher-kind-argument-extractor-without-using-match-t/75842531#75842531

```
  type Ext[S <: Seq[_]] = S match {
    case Seq[t] => t
  }

implicitly[Ext[Seq[Int]] =:= Int] // e.scala: Cannot prove that e.Ext[Seq[Int]] =:= Int
```

If I change the definition of `Ext` as follow, the consequence will differ:

```
  type Ext[S] = S match {
    case Seq[t] => t
  } // success!

  type Ext[S <: Any] = S match {
    case Seq[t] => t
  } // success!

  type Ext[S <: Seq[Any]] = S match {
    case Seq[t] => t
  } // same error
```

### PR DESCRIPTION
**Pull request by odersky**
Refine criterion when to widen types in match type reduction.

We now do not widen if the compared-against type contains variant named type parameters. This is intended to fix the soundness problem in #17149. It also fixes the regression in #15926. @Decel was right in suggesting these two were related.

Fixes #17149
Fixes #15926

Todos:

 - [x] Check & fix neg test failures
 - [x] Add more tests
 - [x] Also consider approximating abstract types to lower bounds. This is completely missing so far. There are neither tests nor an implementation.
 - [x] Update the docs on match types to explain what goes on here.

### CODE REVIEW

**Comment by odersky** [comment]
@Decel, @dwijnand Can one or both of you take this over and address the remaining points? It's a tricky area, I believe quite a bit more work will be needed to arrive at a fully satisfactory solution.

**Comment by dwijnand** [comment]
@odersky Happy to.  @Decel let me know if you want to sync in a call or on the LAMP slack.

Also, what do you think of my approach in #17173?  I don't quite get the mechanics of Ranges in ApproximatingTypeMap's, so I wondered if it can be cleaned up further.  But generally, it solves the problem within matchCases alone.

**Comment by odersky** [comment]
I left a [comment](https://github.com/lampepfl/dotty/pull/17173#issuecomment-1489913866) on #17173.

**Comment by odersky** [comment]
One thing where #17180 falls short is error diagnostics. When we do not widen, we essentially get a "Stuck" error saying scrutinee is not a subtype and is not disjoint either. But before we got a "variable cannot be uniquely instantiated" error, which is much better. After all, scrutinee _is_ a subtype of pattern in this case, for _some_ instantiation of type variables.

We could recover the original error diagnostics by doing the widening in `widenAbstractOKFor` instead of preventing it, but "poisoning" any variant type variables in the other type. Then in `redux` we can flag such type variable instantiations (but in maybe using `Range` is not the best way to do this). Then we can take these flagged variables and issue a `MatchResult.NoInstance` message.

So my proposal would be:

 - change `widenAbstractOKFor` to always return `canWidenAbstract` but poison variant type variables in the other type.
 - in `paramInstance` record poisoned and undetermined type variables instead of wrapping with `Range`.
 - In `redux` produce a `NoInstance` error if bad type variables were recorded.

That could lead to much better error messages. And diagnostics is really important for match types, since the algorithms are so complex.

**Comment by dwijnand** [comment]
I agree.  I marked it draft to convey that even if it's green, it's not to be merged.

**Comment by odersky** [comment]
@Decel @dwijnand What's the status here?

**Comment by dwijnand** [comment]
Let's look at it this this coming week (24th).

**Review by dwijnand — COMMENTED** [review]
LGTM, pending Martin's review

**Comment by dwijnand** [comment]
@odersky I can't request your review of your PR, but could you have a look and say if you're happy with this landing?  Thank you.

**Pull request merged**
