### PR TITLE
Fix trait constructors

### PR DESCRIPTION
**Pull request by odersky**
Trait constructors added a this to the constructor of a trait, which is useless
because the constructor's type is unit. By contrast, it's good to rename the DefDef
to the new name.

Discovered while trying to isolate #685. This causes a -Ycheck:traitConstructor error for all traits.
Review by @DarkDimius

### CODE REVIEW

**Comment by smarter** [comment]
> This causes a -Ycheck:traitConstructor error for all traits.

Can we add `traitConstructors` to `defaultOptions` in `tests.scala` or would that break something ?

**Comment by odersky** [comment]
Note: The error we are seeing here is the same I have been chasing for a while and one that did not show up in the tests for several releases (including commits to main) before.But they did show up in local runs.  It is fixed in #697. 

So the right order should be to get #697 in and then try again.

**Comment by odersky** [comment]
Rebased on top of pending #697

**Comment by odersky** [comment]
> Can we add traitConstructors to defaultOptions in tests.scala or would that break something ?

@smarter Even without traitConstructors, we get "bad owners" in several tests. Not sure why. Would be good to investigate.

**Pull request merged**
