### PR TITLE
Add experimental TupledFunction 

### PR DESCRIPTION
**Pull request by nicolasstucki**
This reverts commit f4e1ca4f565c74fbe1aa56ea88ce6f59409ccdf0.

Originally added in https://github.com/lampepfl/dotty/pull/6568.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
We should also revisit #14138 once this is merged.

**Comment by milessabin** [comment]
Does this generalize to polymorphic functions?

Ie. given `[a, b] => (a, b) => C` we should be able to get to `[a, b] => ((a, b)) => C`.

**Comment by milessabin** [comment]
@nicolasstucki yes, I do ... various higher-kinded transformations.

But also, more generally, it'd be good to keep parity between monomorphic and polymorphic functions wherever possible.

**Comment by nicolasstucki** [comment]
> @nicolasstucki yes, I do ... various higher-kinded transformations.

Could you share a couple of representative examples to include in tests?

**Comment by nicolasstucki** [comment]
We should probably start with the non-polymorphic version and extend it later. I do not have time right now to implement the extension. If we have the current version as experimental library authors could start experimenting with it and provide feedback.

**Review by smarter — APPROVED** [review]
Are dependent functions supported? e.g. `(x, y) => List[x.type]`

**Comment by nicolasstucki** [comment]
> Are dependent functions supported? e.g. (x: Int, y: Int) => List[x.type]

Not sure. I would have to double-check and possibly improve later. 

That would mean the tupled version of the function is `(args: (Int, Int)) => List[args._1.type]`. This might not scale to functions larger than 22 as we do not have the `_N` stable paths.

**Pull request merged**
