### PR TITLE
Increase tests timeout

### PR DESCRIPTION
**Pull request by nicolasstucki**
tests/run/module-serialization-proxy-class-unload.scala timed out again http://dotty-ci.epfl.ch/lampepfl/dotty/12502/4

### CODE REVIEW

**Comment by allanrenucci** [comment]
I think a better solution would be to extract the test into its own unit test and maintain a reasonable timeout. It is probably this slow only because it is ran in parallel with all the other run tests

**Comment by smarter** [comment]
What's weird is that we've had this test for a while and it didn't use to timeout, it seems like things started to go wrong after https://github.com/lampepfl/dotty/pull/5923 but I don't understand why.

**Comment by nicolasstucki** [comment]
I am trying to see if it just takes a long time or if it gets completely blocked for some reason

**Comment by nicolasstucki** [comment]
Replaced by #6433

**Pull request closed without merging**
