### PR TITLE
Make Hole a proper Tree in Trees

### PR DESCRIPTION
**Pull request by nicolasstucki**
This is the first step into making the Hole trees Ycheckable.
To YCheck them we need an untyped version of the tree.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Adds some first cleanup staps needed for #12540

**Comment by smarter** [comment]
Can you explain the context for this PR? This just moves a class to a different location right?

**Comment by nicolasstucki** [comment]
This is the first step to make `Hole` Ycheckable. Right now we generate the holes and immediately pickle them. The idea is that I will add the holes one phase earlier and this way the three can be checked. This will require re-typechecking which means we will need an untyped version of `Hole`.

This just moves the definition to form some lost corner of pickling into `Trees`. The next steps will be added afterward in #12540 or by themselfs.

**Review by smarter — APPROVED** [review]
Sounds good, please put that information in the commit message :).

**Pull request merged**
