### PR TITLE
Fix #580: use isContainedIn to support cases where the enclosing class is also the top-level class

### LINKED ISSUE #580: Regression: Lifted inner method tries to use this
This is exactly the same issue than #545, it was fixed in https://github.com/lampepfl/dotty/commit/b0856feefb90d1c0647bb3725ed9797fc76e0603 but in the same pull request https://github.com/lampepfl/dotty/commit/32a70042fc8a0338e093dba0424c98d25fb3a754 caused a regression.
In the example from #545, the enclosing class is the module class `Test$` and the top class is also the module class `Test$`, so the test `encClass.isProperlyContainedIn(topClass)` fails.

Assigned to @DarkDimius .

### PR DESCRIPTION
**Pull request by smarter**
Review by @DarkDimius .

### CODE REVIEW

**Comment by odersky** [comment]
What can we do to get the builds back again?

**Comment by DarkDimius** [comment]
@odersky they need to be rebased over current master.

**Comment by DarkDimius** [comment]
LGTM

**Pull request merged**
