### PR TITLE
Added specs2-core to the community build

### PR DESCRIPTION
**Pull request by etorreborre**
I will expand it with the rest of the specs2 modules if this one goes well

### CODE REVIEW

**Comment by etorreborre** [comment]
@nicolasstucki do you know what's wrong with the build? I can't see any obvious failure

**Comment by nicolasstucki** [comment]
I restarted the CI tests

**Review by anatoliykmetyuk — APPROVED** [review]

**Comment by symbiont-eric-torreborre** [comment]
@nicolasstucki @anatoliykmetyuk I updated the PR to avoid some specs2 tests

**Comment by etorreborre** [comment]
@nicolasstucki @anatoliykmetyuk I tried a different approach for passing sbt arguments. Can you please start the workflow again?

**Comment by etorreborre** [comment]
@nicolasstucki @anatoliykmetyuk I am trying something else in order to attempt pass to pass arguments to sbt when running the specs2 tests. I hope this one will work. If it doesn't I will need some guidance on how to best do this :-).
Thanks!

I also tried to run the `CommunityBuildC` locally but I had other failures. I don't know what the easy to try to fix the problem locally without bothering you each time.

**Comment by anatoliykmetyuk** [comment]
@etorreborre thanks for all the work adding the project! Could you please point the submodule to this repo instead? https://github.com/dotty-staging/specs2 – I also added you as a maintainer to it. All of the community projects reside under `dotty-staging` organisation to allow for easy fixes of breakages.

**Comment by etorreborre** [comment]
@anatoliykmetyuk I did the change you suggested. Can you please tell me now how I can fix the broken community c job? This is not clear to me. Also, can you start the workflow again because maybe my latest change of the sbt test command worked?

**Comment by etorreborre** [comment]
I'm glad to see that eventually everything worked out ok. Thanks!

**Pull request merged**
