### PR TITLE
Infer missing implicit args in using clause

### PR DESCRIPTION
**Pull request by odersky**
If there are some missing arguments in a using argument clause, infer them
with implicit search.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@nicolasstucki Can you do another boostrap compiler with this PR once it is merged? I want to do a test to move all phase info out of contexts into a separate variable. I hope this can speed up the compiler since then (1) we use fewer contexts (about have as many with some additional tweaks) and (2) we are faster in the hot😂 paths where we need to get the current phase id.

I am now at a position where it's mostly a global search and replace. `(using Context)` becomes `(using Context, Period)`. But we also have 425 occurrences of using argument clauses. With this PR merged we need to update very few of them.

**Comment by nicolasstucki** [comment]
I'll rebootstrap tomorrow

**Comment by nicolasstucki** [comment]
Included in #9356

**Pull request merged**
