### PR TITLE
Memoize: Support creating valid trait setters

### PR DESCRIPTION
**Pull request by DarkDimius**
used to create trait setters that were assigning to non-existing fields.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky please review.

**Comment by odersky** [comment]
Otherwise LGTM

**Comment by DarkDimius** [comment]
>You could shorten these two lines to
`name.drop(start).fieldName`

This would create one more intermediate name. I would prefer to keep it in current state as it is being called from `typedAssign`

**Comment by odersky** [comment]
@DarkDimius OK, it's not a big issue anyway.

**Pull request merged**
