### PR TITLE
New lazy vals implementation

### LINKED ISSUE #15149: @transient lazy val does not get marked as ACC_TRANSIENT
## Compiler version

3.1.0 and 3.1.1

## Minimized code

```Scala
class Test() {
        @transient lazy val lazyVal = "lazy"
        @transient val ordinaryVal = "ordinary"
        }
```

## Output

javap generates:-

```
  public static final long OFFSET$0;
    descriptor: J
    flags: (0x0019) ACC_PUBLIC, ACC_STATIC, ACC_FINAL

  public long 0bitmap$1;
    descriptor: J
    flags: (0x0001) ACC_PUBLIC

  public java.lang.String lazyVal$lzy1;
    descriptor: Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC

  private final transient java.lang.String ordinaryVal;
    descriptor: Ljava/lang/String;
    flags: (0x0092) ACC_PRIVATE, ACC_FINAL, ACC_TRANSIENT
```

## Expectation

0bitmap$1 and lazyVal$lzy1 should both have flag ACC_TRANSIENT.

I am also confused when reading SIP-20 (version 6) as to what OFFSET$0 does - it does not appear in https://dotty.epfl.ch/docs/reference/changed-features/lazy-vals-init.html equivalent code (how could it, an ACC_STATIC can not be directly be directly created in Scala).  But it does appear in the code produced by 3.1.0 and 3.1.1.  Being ACC_STATIC it can not also be ACC_TRANSIENT, but I am unsure whether the code as currently implemented would survive serialisation or any equivalent code following the same rules for what get processed.

### PR DESCRIPTION
**Pull request by szymon-rd**
Cleaned up version of https://github.com/lampepfl/dotty/pull/14545

Implementing the new lazy vals scheme mentioned in https://github.com/lampepfl/dotty/pull/6979, fixing https://github.com/lampepfl/dotty/issues/7140

New PR to avoid force pushing to main branch of the previous author.

Fixes #15149 as well

### CODE REVIEW

**Comment by szymon-rd** [comment]
Ported #14780

**Comment by szymon-rd** [comment]
Fixed #15149

**Comment by szymon-rd** [comment]
Wouldn't it be a better idea to use MethodHandles instead of Unsafe?

**Comment by szymon-rd** [comment]
TODO: Add test for non transient lazy val.

**Comment by sjrd** [comment]
`MethodHandle`s are only available on JDK 9+. We have to support 8+.

**Comment by bishabosha** [comment]
> `MethodHandle`s are only available on JDK 9+. We have to support 8+.

for clarity I assume you both mean `VarHandle`, as method handles were added in JDK 7

**Comment by szymon-rd** [comment]
@bishabosha I actually meant getter/setter method handles. As far as I know they provide direct access to the field and do not actually rely on getter/setters. It would be nice to perform some benchmarks for sure.

**Comment by bishabosha** [comment]
> @bishabosha I actually meant getter/setter method handles. As far as I know they provide direct access to the field and do not actually rely on getter/setters. It would be nice to perform some benchmarks for sure.

AFAIK these do not support atomic operations like CAS, but varhandle is a direct replacement for methods in Unsafe

**Comment by szymon-rd** [comment]
@odersky Could you take a look at this, please?

**Comment by odersky** [comment]
Can you re-push that to staging? That way we can collaborate on it.

**Comment by szymon-rd** [comment]
Created a new PR to change the source branch: https://github.com/lampepfl/dotty/pull/15296

**Pull request closed without merging**
