### PR TITLE
Bump scala baseVersion to 3.0.3-RC1

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Comment by smarter** [comment]
Sorry, I don't have time to do review this month.

**Comment by prolativ** [comment]
@smarter unfortunately it turns out that an RC which is not a nightly cannot compile experimental code as it was hoped in https://github.com/lampepfl/dotty/pull/12913. What should we do about it then?

**Comment by smarter** [comment]
3.0.0 was not a nightly either and we were able to use it as a reference compiler, so something must have changed since then

**Comment by prolativ** [comment]
Yes, the restriction about experimental features was introduced after 3.0.0

**Comment by prolativ** [comment]
@anatoliykmetyuk any idea for a fix or at least a workaround?

**Comment by nicolasstucki** [comment]
Workaround: Don't upgrade the reference compiler

**Comment by nicolasstucki** [comment]
We can use a nightly build for the reference compiler.

**Comment by prolativ** [comment]
OK for now, but we'll need to solve the problem later anyway

**Comment by nicolasstucki** [comment]
We can use 3.0.0 to compile all 3.0.x releases. We need to figure out how to handle this before we have a 3.1.0 release.

**Review by BarkingBad — APPROVED** [review]

**Pull request merged**
