### PR TITLE
Update protoquill

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@deusaquilus I noticed that protoquill master is failing in our master. Is this the failure from #12179?

**Comment by deusaquilus** [comment]
Correct. I just commented all of that out though. Master build and tests are now all passing now.

**Comment by nicolasstucki** [comment]
@deusaquilus it seems the latest master of protoquill is timing out. Could you take this over and try to make protoquill/master work with the latest dotty nightly?

**Comment by deusaquilus** [comment]
Sure, I'll have a look. The issue probably is because it is depending on a SNAPSHOT version of quill-core-portable/quill-sql-portable that no-longer exists. I will publish regular versions of these things ASAP and try to fix this up by tomorrow. Thanks for the info!

**Comment by deusaquilus** [comment]
Updated Proto-Quill master. Removed scalatest dependency. It should be working now.

**Comment by nicolasstucki** [comment]
Updated to the latest master of protoquill

**Comment by deusaquilus** [comment]
Thanks!

**Comment by deusaquilus** [comment]
@nicolasstucki The stuff you did with Extractors.scala is absolutely amazing! I love it!
I need to ask though, is this approach with `def stuff(using Quotes)(quotes.reflect.Term/TypeRepr/etc...)` guaranteed to be possible in future versions of Scala? It would really be sad if in 3.1.0 all of this broken and I had to go back to the old way of doing things because I'd already become reliant on nicer way.

@odersky Any chance you can vouch for this `transparent inline def quotes(using inline q: Quotes): q.type = q` making this stuff possible in future versions of Scala?

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
