### PR TITLE
Ycheck that methods defined in ClassInfo exist in tree.

### PR DESCRIPTION
**Pull request by DarkDimius**
based on #693.
Known to fail: `trait TreeInfo tree does not define methods: Set(method initial$MatchingArgs)`

### CODE REVIEW

**Comment by odersky** [comment]
We now see a non-abstract method error for a lazy val in PatMat.

**Comment by DarkDimius** [comment]
With fixes from this branch, dotty can print greeting without dying. 
Trying to compile something fails with
```
java.lang.AbstractMethodError: Method dotty/tools/dotc/core/Names$TypeName.scala$collection$IndexedSeqOptimized$$super$endsWith(Lscala/collection/GenSeq;)Z is abstract
	at dotty.tools.dotc.core.Names$TypeName.scala$collection$IndexedSeqOptimized$$super$endsWith(Names.scala)
	at scala.collection.IndexedSeqOptimized$class.endsWith(IndexedSeqOptimized.scala:278)
	at dotty.tools.dotc.core.Names$Name.endsWith(Names.scala:38)
	at dotty.tools.dotc.core.NameOps$NameDecorator$.isAvoidClashName$extension(NameOps.scala:75)
	at dotty.tools.dotc.core.NameOps$NameDecorator$.stripAvoidClashSuffix$extension(NameOps.scala:145)
	at dotty.tools.dotc.core.NameOps$NameDecorator$.adjustIfModuleClass$extension(NameOps.scala:149)
	at dotty.tools.dotc.core.Symbols.newModuleSymbol(Symbols.scala:154)
	at dotty.tools.dotc.core.Symbols.newPackageSymbol(Symbols.scala:206)
	at dotty.tools.dotc.core.Definitions.RootClass(Definitions.scala:98)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$2(Denotations.scala:968)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:984)
	at dotty.tools.dotc.core.Symbols.requiredPackage(Symbols.scala:347)
	at dotty.tools.dotc.core.Definitions.ScalaPackageVal(Definitions.scala:110)
	at dotty.tools.dotc.core.Definitions.ScalaPackageClass(Definitions.scala:112)
	at dotty.tools.dotc.core.Definitions.AnyClass(Definitions.scala:141)
	at dotty.tools.dotc.core.Definitions.syntheticCoreClasses(Definitions.scala:625)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:647)
	at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:98)
	at dotty.tools.dotc.Compiler.newRun(Compiler.scala:125)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:20)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by odersky** [comment]
What's the partest failure? Should we try to merge this or work on the branch separately

**Comment by DarkDimius** [comment]
The failure is due to incorrect check file added in this commit(extra line break). It should be fixed now.

**Comment by DarkDimius** [comment]
@odersky tests passed, please review

**Comment by odersky** [comment]
LGTM for everything.

**Pull request merged**
