### PR TITLE
add back the forgotten test file for patmat exhuastivity check

### PR DESCRIPTION
**Pull request by liufengyun**
By adding back the `ClassicReporter`, I'm not nostalgic, but to avoid rewriting all the check files :)

Review @felixmulder .

### CODE REVIEW

**Comment by felixmulder** [comment]
I'd prefer not to have duplicate reporters (we actually already have a third one in the sbt bridge :scream:) - would it be alright with you @liufengyun if I took the time to amend the check files in this PR? (I'll push to staging)

**Comment by liufengyun** [comment]
@felixmulder I'm afraid that each refactoring of the reporter (even a minor change capitalisation) would require update the check files, which will be very tedious and become a burden of maintenance.

**Comment by felixmulder** [comment]
@liufengyun - true, let me sleep on it and we'll talk again tomorrow :)

**Comment by DarkDimius** [comment]
@felixmulder @liufengyun, I'd remind you my suggestion for testing. Have a specific reporter that is only used in tests in order to provide minimal information used for tests.

Eg: waring 

```
./tests/patmat/i947.scala:10: warning: unreachable code
       case ys: List[d18383] => false
```

would be reported as

```
UnreachabeCode(line, pos)
```

**Comment by felixmulder** [comment]
@DarkDimius - yes, we agreed upon this scheme this morning. Just haven't gotten around to it yet :)

**Comment by liufengyun** [comment]
According my experience with testing, we often have the need to switch back and forth between check files and source code. Messages like `UnreachabeCode(line, pos)` is not friendly enough for test and development.

**Comment by DarkDimius** [comment]
This is why I propose to have this message defined inline inside the test 
file itself

**Comment by liufengyun** [comment]
@felixmulder what's your opinion on this? Any changes in mind?

**Comment by felixmulder** [comment]
I have a solution in mind for neg tests, and I will build upon this PR.
Will probably have something to show for this in a couple of hours :)

**Comment by felixmulder** [comment]
Latest commit adds a very simplified version of the `ClassicReporter` that is not likely to change. It basically reports in this fashion:

```
2: Pattern Match Exhaustivity: List(_, _, _)
```

WDYT @liufengyun?

**Comment by liufengyun** [comment]
@felixmulder thanks for working on this. I'm fine for changes. Good job 👍

**Pull request merged**
