### PR TITLE
WIP #4721 try improving errors

### PR DESCRIPTION
**Pull request by Blaisorblade**
When a type argument violates its bounds, we give the same errors whether the argument is specified by the user or inferred by the compiler. This PR is an (incomplete) attempt to detect and fix that. However, I failed to distinguish reliably inferred and synthesized type arguments, even following https://github.com/lampepfl/dotty/pull/4946#issuecomment-413785742

This PR builds on #4946 to try improving the resulting error output. Sadly, the position of inferred arguments fails both `isSynthetic` and `isZeroExtent` (`arg.pos [53..54], false`).

```
sbt:dotty> dotc -d out tests/neg/i4721a.scala
[info] Compiling 1 Scala source to /Users/pgiarrusso/git/dotty/compiler/target/scala-2.12/classes ...
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging /Users/pgiarrusso/git/dotty/compiler/target/scala-2.12/dotty-compiler_2.12-0.10.0-bin-SNAPSHOT-nonbootstrapped.jar ...
[info] Done packaging.
[info] Running (fork) dotty.tools.dotc.Main -classpath /Users/pgiarrusso/git/dotty/library/../out/bootstrap/dotty-library-bootstrapped/scala-0.10/dotty-library_0.10-0.10.0-bin-SNAPSHOT.jar -d out tests/neg/i4721a.scala
-- Warning: tests/neg/i4721a.scala:2:39 ----------------------------------------
2 |  def main(args: Array[String]):Unit = m("1") // error
  |                                       ^
  |       Unsatisfiable type parameter constraints in polymorphic application
arg.pos [53..54], false
-- [E057] Type Mismatch Error: tests/neg/i4721a.scala:2:39 ---------------------
2 |  def main(args: Array[String]):Unit = m("1") // error
  |                                       ^
  |                 Type argument Int does not conform to upper bound String
one warning found
one error found
```

### CODE REVIEW

**Comment by odersky** [comment]
@Blaisorblade Inactive for almost 5 months. Can you either finish the PR or close it and re-assign the issue to someone else? Thanks

**Comment by Blaisorblade** [comment]
After discussion, assigned to @AleksanderBG as he's working in the area.

**Comment by b-studios** [comment]
@abgruszecki what is the status on this PR? Should we close it?

**Comment by abgruszecki** [comment]
I think it can be safely closed.

**Pull request closed without merging**
