### PR TITLE
Fix double execution in JSR223 Implementation

### PR DESCRIPTION
**Pull request by rjolly**
The reason for this change is that currently, statements in the
JSR223 script engine are evaluated twice. Once when the "run" method
is called, and once when the value of the result is extracted.
The first one needs not be, it exists solely due to displayDefinitions
being called. If we put it behind a flag, the problem is solved.

### CODE REVIEW

**Comment by smarter** [comment]
I'm confused, what's the method that gets called twice exactly, and by whom ? Why is there a difference between scripting and non-scripting ?

**Comment by rjolly** [comment]
See in https://github.com/rjolly/dotty/blob/master/compiler/src/dotty/tools/repl/ScriptEngine.scala . In the eval method, first the method "run" is called, which at the end calls DisplayDefinitions which causes the method invoke a first time. Then, still in eval, I do a second method invoke (and this is specific to the script engine) to extract the value, which is returned by the eval method.

**Comment by rjolly** [comment]
How to reproduce:
```
user@debian:~/dotty-0.17.0-RC1/lib$ jrunscript -J-Dscala.usejavacp=true -J-Djava.class.path=dotty-compiler_0.17-0.17.0-RC1.jar:dotty-doc_0.17-0.17.0-RC1.jar:dotty-interfaces-0.17.0-RC1.jar:dotty-library_0.17-0.17.0-RC1.jar:scala-library-2.12.8.jar:scala-asm-6.0.0-scala-1.jar:scala-library-2.12.8.jar:scala-asm-6.0.0-scala-1.jar -l scala
scala> def fn = println("hello world")
def fn: Unit

scala> fn
hello world

hello world
()
scala>
```

**Comment by rjolly** [comment]
I there something I can do to help the PR going forward ?

**Comment by rjolly** [comment]
@smarter Is there something I can do to help this PR going forward ?

**Comment by smarter** [comment]
Very sorry about the delay, I'll try to review this properly this week!

**Comment by rjolly** [comment]
@smarter Is it alright to add a command line argument "repl-disable-display" ? The alternative is a constructor argument to ReplDriver, which is not perfect either.

**Comment by rjolly** [comment]
Thanks ! Yes, override would be fine, but indeed it requires some refactoring. I'll think about it.

**Pull request merged**
