### PR TITLE
WORK IN PROGRESS: Implement -Ycheck-subtype: sanity check the result  of isSubType

### PR DESCRIPTION
**Pull request by smarter**
By default, subtyping tests are done using `optimizedIsSubtype`, if `-Ycheck-subtype` is specified, they are also done using `SimpleIsSubType` and the compiler aborts if they disagree. Note that `SimpleIsSubType` only implement a subset of the subtyping tests currently, see `SimpleIsSubType#isDefinedAt`.

---

@namin, @odersky: Feedback welcome, only a few subtyping tests are implemented currently but this should be enough to comment on the design. `partialIsSubType` implements the big pattern match, if it fails `SimpleIsSubType#apply` will try other tests by looking at the widened/underlying/... version of each type.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
There are two reasons why `isSubtype` is complex:

1.    it has to run fast
2.    it has to work during a phase where many kinds of implicit information are being inferred (instantiation of type parameters, resolution of overloaded methods, ...)

`SimpleIsSubType` should get rid of both (1) and (2). With your current architecture, where `SimpleIsSubType` runs directly after each `optimizedIsSubType` call, getting rid of (2) can only be achieved by discarding many interesting cases. I think it would be better to run `SimpleIsSubType` as a part of `-Ycheck` instead (see `dotty.tools.dotc.transform.TreeChecker`).

**Comment by smarter** [comment]
@samuelgruetter : I'll take a look at `TreeChecker`, are you sure that it does not have to do type parameter instantiation?

**Comment by samuelgruetter** [comment]
@smarter I'm quite sure ;-) If you run this simple example

```scala
object p {
  def id[T](x: T): T = x
  println(id("hi"))
}
```

with `-Ylog:all -Ycheck:resolveSuper` and enable the `typr` and `subtyping` printer in `Printers`, you can see quite well what's going on: First, the normal typechecking is done, which also runs `adapt`, where the type parameters are instantiated:

```
[error] [log frontend]     ==> typing println(id("hi"))?
...
[error] [log frontend]       ==> adapting "hi" of type String("hi") to (T?)?
...
[error] [log frontend]       <== adapting "hi" of type String("hi") to (T? >: String("hi")) = "hi"
...
[info] interpolate covariant (T? >: String("hi")) in (T? >: String("hi"))
[info] approx T, from below = true, bound = String("hi"), inst = String("hi")
[info] instantiating (T? >: String("hi")) with String
...
[error] [log frontend]     <== typing println(p.id("hi")) = println(p.id[String']("hi"))
```

Then, during `-Ycheck`, the call `p.id` already has the type parameter given explicitly, and `adapt` does nothing:

```
[info] checking examples/poly.scala after phase TreeTransform:{elimByName, seqLiterals, intercepted, literalize, getters, resolveSuper}
...
[error] [log frontend -> erasure]     ==> typing println(p.id[String']("hi"))?
...
[error] [log frontend -> erasure]     <== typing println(p.id[String']("hi")) = println(p.id[String']("hi"))
```

because the [adapt method of TreeChecker](https://github.com/lampepfl/dotty/blob/b25325233cbc88707f8757de5e4c028b1cf314b3/src/dotty/tools/dotc/transform/TreeChecker.scala#L220) does nothing (except asserting that the actual type is a subtype of the expected type).

**Comment by odersky** [comment]
Is this still wip? In that case we should close. Or else make it a real PR.

**Comment by smarter** [comment]
Closing for now.

**Pull request closed without merging**
