### PR TITLE
Don't add explanation twice

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes https://github.com/lampepfl/dotty/issues/18774

The improvement was https://github.com/lampepfl/dotty/pull/14357

### CODE REVIEW

**Comment by som-snytt** [comment]
I expected a test failure.

**Comment by dwijnand** [comment]
Some of your puns are too hard for me to parse, but I've come so used to seeing them I was surprised you didn't go for something along the lines of: explain to me once, shame on me, explain to me twice, shame on you... :-P

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
I am wondering if we can test this in `sbt-test/`.

**Comment by nicolasstucki** [comment]
> I am wondering if we can test this in sbt-test/. It seems that sbt-test/compilerReporter/i14576/build.sbt does has the base logic we need.

I tried it and that does not work as the extra `-explain` does not go through the test reporter. I guess it is good enough like this.

**Pull request merged**
