### PR TITLE
Switch to Java 17 in the CI

### PR DESCRIPTION
**Pull request by hamzaremmal**
This will unblock #19080.

Support for Java 21 will be provided by #19701 later

### CODE REVIEW

**Review by smarter — CHANGES_REQUESTED** [review]
In the CI logs there is:
> [info] welcome to sbt 1.9.7 (Private Build Java 1.8.0_282)

So this is actually running on Java 8, because Java 17 isn't installed in the docker image and so /usr/lib/jvm/java-17èopenjdk-amd64/bin doesn't exist and the java executable defaults to a java 8 installation on the PATH.

**Comment by hamzaremmal** [comment]
> In the CI logs there is:
> 
> > [info] welcome to sbt 1.9.7 (Private Build Java 1.8.0_282)
> 
> So this is actually running on Java 8, because Java 17 isn't installed in the docker image and so /usr/lib/jvm/java-17/openjdk-amd64/bin doesn't exist and the java executable defaults to a java 8 installation on the PATH.

Java 17 should be installed too 🤔 (along side Java 8 and Java 21) : https://github.com/lampepfl/dotty-ci/blob/1df1746e8cf5077b7e2b87906ee3dda3b908fb20/dotty-docker/Dockerfile#L13

**Comment by hamzaremmal** [comment]
Wrong image name (Should be `lampepfl/dotty:2023-11-07`) 😞

**Comment by hamzaremmal** [comment]
Note that test_windows_fast still uses Java 8 (as it was previously)
> [info] welcome to sbt 1.9.7 (AdoptOpenJDK Java 1.8.0_265)

**Review by smarter — APPROVED** [review]
Thanks!

**Pull request merged**
