### PR TITLE
Syntax highlighting for REPL using ammonite as base instead of JLine

### PR DESCRIPTION
**Pull request by felixmulder**
One was implemented by hand and the other by using dotty's scanner. The one
built by hand is ~short, and behaves correctly.

The scanner one is unfortunately not ready for testing - there are too
many things that are workarounds for it to be a good solution as of now

The code added from Ammonite is licensed under MIT, not sure where to
put the license - but will add it once I know.

### CODE REVIEW

**Comment by felixmulder** [comment]
Once #1238 is merged I believe this will compile under dotty.

**Comment by odersky** [comment]
@felixmulder You can rebase and try again. #1238 is merged.

**Comment by felixmulder** [comment]
@odersky: there was a test that compiled dotty with `-Ycheck-reentrant`. This failed because some immutable structures (with internal mutable state) where not marked `@sharable`. So now everything seems to be working fine and this is ready for review.

**Comment by DarkDimius** [comment]
@odersky, it would be nice to get this in before ScalaDays.

**Comment by odersky** [comment]
LGTM, thanks!

**Pull request merged**
