### PR TITLE
Update TASTy Reflect to summon and given

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@milessabin this PR contains a small change in the Shapeless macros.

**Comment by milessabin** [comment]
@nicolasstucki thanks for the heads up!

**Comment by nicolasstucki** [comment]
I removed the changes from Shapeless.

**Comment by milessabin** [comment]
> I removed the changes from Shapeless.

Slightly confused ... have you left the old API for backwards compatibility?

**Comment by nicolasstucki** [comment]
I left the old API for the TASTy reflect part for now. I only updated the quoted expressions API

**Comment by milessabin** [comment]
Ahh ... right.

**Pull request merged**
