### PR TITLE
update quick links for new ui

### PR DESCRIPTION
**Pull request by bishabosha**
fixes https://github.com/lampepfl/dotty/issues/15896

Screenshot 2022-08-25 at 18 30 11

### CODE REVIEW

**Comment by bishabosha** [comment]
ok I need to update wherever the quick links are generated for this test

**Comment by bishabosha** [comment]
CI should pass now

**Comment by BarkingBad** [comment]
I think Jamie's commit can fix the issue, otherwise I will take a deeper look later

**Comment by bishabosha** [comment]
my commit isn't needed I think - so if https://github.com/lampepfl/dotty/pull/15912/commits/387f7bb6fdc1786370b14af37ab30f8c8eae6555 passes Ill drop it

**Comment by julienrf** [comment]
My change made the CI pass, so it seems my second issue was showing up locally only…

**Review by julienrf — APPROVED** [review]

**Pull request merged**
