### PR TITLE
Update AUTHORS.md

### PR DESCRIPTION
**Pull request by felixmulder**

### CODE REVIEW

**Comment by felixmulder** [comment]
Playing with the bot.

**Comment by smarter** [comment]
> Could you guys please sign the CLA? :pray:

Don't use "guys", it's sexist :).

**Comment by DarkDimius** [comment]
@felixmulder, I propose to add additional item to @dotty-bot response:
- If you are fixing an issue, Start commit message with "Fix #<issue-id>: "

I propose to put it as the second item.

**Comment by felixmulder** [comment]
> Don't use "guys", it's sexist :).

I've never connected a gender to the plural form of that word, honestly. But after your proclamation, I did some digging. The internet seems divided on the issue, better not to offend anyone I guess :)

**Pull request closed without merging**
