### PR TITLE
Change to new given syntax

### PR DESCRIPTION
**Pull request by odersky**
This PR implements the `given` syntax changes described in 
https://github.com/lampepfl/dotty/tree/master/docs/docs/reference/contextual-new

### CODE REVIEW

**Comment by sake92** [comment]
Sorry if I misunderstand something, but comparing  
`implicit class Indexer[T](collection: Seq[T])` to  
`given extension Indexer[T](collection: Seq[T])`,  
they look kinda same right?  

Why not have just `extension` keyword: `extension Indexer[T](collection: Seq[T])`?  
And also anonymous `extension[T](collection: Seq[T])`, although it reads kinda weird... xD

**Comment by odersky** [comment]
The third variation of the theme drops the extension identifier again. In the end, `extension` is unnecessary and risks being more confusing than enlightening. 

1. Adding `extension` makes it look like this is the standard way to specify extension methods. But that's not true. You can perfectly well implement a class and implement its extension methods or add new ones. I.e. the following defines extension methods:

    given X: { ... }

**Comment by nicolasstucki** [comment]
Some outdated docs
- [ ] [Toolbox.scala#L6](https://github.com/lampepfl/dotty/blob/master/staging/src/scala/quoted/staging/Toolbox.scala#L6)
- [ ] [Toolbox.scala#L18](https://github.com/lampepfl/dotty/blob/master/staging/src/scala/quoted/staging/Toolbox.scala#L18)
- [ ] [staging.md#L69](https://github.com/lampepfl/dotty/blame/master/docs/docs/reference/metaprogramming/staging.md#L69)
- [ ] [staging.md#L71](https://github.com/lampepfl/dotty/blame/master/docs/docs/reference/metaprogramming/staging.md#L71)
- [ ] [staging.md#L97](https://github.com/lampepfl/dotty/blame/master/docs/docs/reference/metaprogramming/staging.md#L97)

**Comment by odersky** [comment]
This PR is maximally lenient, allowing all kinds of syntaxes:

 - the final given syntax
 - the previous given syntax with infix given and `as`
 - the delegate syntax

The reason is that bootstrap code currently uses a both of the superseded styles. The idea is to merge this PR into the next bootstrap compiler. Then restrict everything to the new syntax and fix all code and remaining tests to conform to it.

**Comment by Mocuto** [comment]
Where can I see the discussion for why the infix `given` notation was dropped? I very much preferred it over the change introduced in this PR and was surprised to see the latest Dotty release candidate drop it.

**Comment by soronpo** [comment]
@odersky Could you comment why use `given` and not `extension` here for extension methods? I'm not referring to `given extension` which is indeed redundant, but I don't understand why do we need `given` at all here.

**Pull request merged**
