### PR TITLE
Remove library/src-2.x

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@smarter,  moving `library/src-3.x` into `library/src` caused the following error

```scala
[error] -- [E046] Cyclic Error: /tmp/1/library/src/scala/IArray.scala:30:2 -------------
[error] 30 |  def empty[T: ClassTag]: IArray[T] = new Array[T](0)
[error]    |  ^
[error]    |  Cyclic reference involving object IArray
```

did you encountered similar issues when creating those source directories?

**Comment by smarter** [comment]
No, I don't know what the issue is.

**Comment by smarter** [comment]
It's probably just that moving the files around changes the order in which they end up being compiled, and this exposes a bug which is specific to some ordering of the input files.

**Comment by nicolasstucki** [comment]
@smarter I left part of moving `src-3.x` into `src` for another PR as it will take some time debugging.

**Pull request merged**
