### PR TITLE
Extract parser into its own phase

### PR DESCRIPTION
**Pull request by allanrenucci**
Motivations:
- Reuse phase infrastructure (e.g. `-Ystop-after:parsing`)
- Make it easier to replace the parser (useful in the REPL for example)

### CODE REVIEW

**Comment by biboudis** [comment]
I say that this is a work in progress that shouldn't be lost, so no closing. But @allanrenucci if you have free time to write some guidelines for someone to take over that would be amazing! Merci!

**Comment by allanrenucci** [comment]
To move this forward, one would need to investigate the test failures. The dottydoc test failures should be relatively easy to fix. The cyclic and pickling errors on the other hand will require more expertise.

As a first step, one could try to extract the changes in dc61723 into a separate PR.

**Comment by biboudis** [comment]
I will try to take over @allanrenucci

**Comment by b-studios** [comment]
@biboudis we are again at shrinking the PR queue :) Any suggestions on how to proceed with this PR?

**Comment by biboudis** [comment]
I guess rebasing and trying to make the tests work from the start. I started from pickling errors back then, but I think this needs a new round of debugging.

**Comment by OlivierBlanvillain** [comment]
I suggest closing and reopening if someone want to work on it. The last commits are from 2018 so I'm not sure rebasing would even be a sensible option here...

**Pull request closed without merging**
