### PR TITLE
Make members of the empty package invisible from inside other packages

### LINKED ISSUE #7891: Empty package visibility underspecified or just confusing
## minimized code

```Scala
// ok in one compilation unit
def f = "hello, world"

package p {
  @main def m = println(f)
}
```

```Scala
// fonly.scala
def f = "hello, world"

// ponly.scala
package p {
  @main def m = println(f)
}
```
Compiled together or separately:
```
➜  dotc ponly.scala fonly.scala
-- [E006] Unbound Identifier Error: ponly.scala:5:24 ---------------------------
5 |  @main def m = println(f)
  |                        ^
  |                        Not found: f

longer explanation available when compiling with `-explain`
1 error found
```

## expectation

Binding of `f` shouldn't depend on compilation unit, but moreover, members of the empty package should be visible only to members of the empty package; or specify that they are visible in the current compilation unit.

Other restrictions may apply. Cf https://github.com/lampepfl/dotty/issues/7650

Related confusion in Scala 2: https://github.com/scala/bug/issues/10927

### LINKED ISSUE #13114: Empty package is available across files to named packages
## Compiler version

Scala compiler version 3.0.3-RC1-bin-SNAPSHOT-git-7899462 -- Copyright 2002-2021, LAMP/EPFL

## Minimized code
A file with definitions in empty package:
```Scala
def f = 42

class C
```
Another file with definitions in named package:
```Scala
class D2 extends C

package p {
  class D extends C

  @main def test = println((new D, new D2))
}
```
but it doesn't compile without the D2
```Scala
package p {
  class D extends C

  @main def test = println(new D)
}

```
## Output

without the "enabling" D2 to "open" the empty package
```scala
➜  ~/projects/dotty/bin/scalac -d /tmp -Vprint:typer  mt2.scala mt.scala
-- [E006] Not Found Error: mt.scala:5:18 --------------------------------------------------------------------------------
5 |  class D extends C
  |                  ^
  |                  Not found: type C
```

## Expectation

File visibility of empty package defs in named package, per https://github.com/lampepfl/dotty/issues/7891

Not magically visible empty package across compilation units, such as C visible when D2 is defined.

Empty package defs available to empty package anywhere and anything in same file.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #13114
Fixes #7891

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
LGTM!

**Comment by odersky** [comment]
@dwijnand Good point about #7891. With a bit of refinement this is handled now as well.

**Comment by dwijnand** [comment]
OK, so classes in the empty package in difference files can still see each other?  For some reason I thought that every file kind of got it's own "fresh" empty package scope.  I don't know what problem I'm solving with that enforcement, so LGTM!

**Comment by odersky** [comment]
Yes classes in the empty package can see each other, whether they are compiled separately or not. That's how it's specced in Java as well.

**Pull request merged**
