### PR TITLE
More consistent results for union types in pickling

### PR DESCRIPTION
**Pull request by noti0na1**
This PR tries to fix some of the pickling errors in #14946.

#15105 was an attempt to solve the errors of different union types in unpickler, by simplifying the type of match and try nodes.
We thought Typer performs a simplification step after type assigning a tree, so we should do the same step in unpickler. But this is not correct, because the tree before Pickler phase is posttyper, which does not perform a simplification. 
The reason why #15105 fixes some of the errors because **`lub` does not return a consistant result**. But this also introduces more errors in the test.

Let's consider a case: `lub(List(String | Null, String, Null))`.  Inside `lub` we have:

```scala
val t1 = mergeIfSuper(tp1, tp2, canConstrain)
if t1.exists then return t1

val t2 = mergeIfSuper(tp2, tp1, canConstrain)
if t2.exists then return t2
``` 

So, depends on the order of arguments, we may get `String` or `String | Null`.

This PR adds a TreeTransformer to the Pickling, so it can overwrite the types of If, Match, and Try nodes before and after pickling with the simplified version. Hopefully, we can always get consistent types during comparison.

### CODE REVIEW

**Comment by noti0na1** [comment]
test performance please

**Comment by olhotak** [comment]
For the statement:
"So, depends on the order of arguments, we may get String or String | Null."
do you mean **without** `-Yexplicit-nulls`?

I'm confused because with `-Yexplicit-nulls`, the lub cannot be `String`, but without `-Yexplicit-nulls`, we don't have the pickling errors in #14946.

I agree that `lub(t1,t2) == lub(t2,t1)` is a desirable property, that it's difficult to ensure with equivalent but unequal types such as `A|B` and `B|A`, and that simplifying the result of `lub` might be one way to get closer to it, but I don't know whether: 1) it is even possible to achieve `lub(t1,t2) == lub(t2,t1)` in the general case or 2) simplifying the result of `lub` is the best way to get there.

**Comment by olhotak** [comment]
Oh, I see, it's with `-Yexplicit-nulls` but with unsafeNulls. Then the lub can be String.

A desirable property (though it might not be achievable) would be for unsafeNulls to not affect computed lubs. More generally, for unsafeNulls to not affect inferred types, but only to relax certain subtyping checks.

**Review by odersky — COMMENTED** [review]
I don't think lub should call simplified. That's really not supported by the architecture.

**Comment by olhotak** [comment]
Could the printer ignore `|Null` always, even without the unsafeNulls language import?

**Comment by olhotak** [comment]
Could we canonicalize the types in the trees before printing them to strings in the unpickler testing code? This would require a tree transformation that creates a new tree with transformed types.

**Comment by noti0na1** [comment]
> Could we canonicalize the types in the trees before printing them to strings in the unpickler testing code? This would require a tree transformation that creates a new tree with transformed types.

We can call `simplify` on the types of original tree and hope the types from both trees are simplified in the same way, but this is an expensive step, and I'm not sure this can handle all the issues caused by `lub`.

**Comment by noti0na1** [comment]
I don't think adding a TreeMap and running it on the whole tree twice is a good idea. So I delete it and add type simplify to PostTyper, which should achieve the same result.

**Comment by olhotak** [comment]
Good catch.

I thought the TreeMap just for the pickling tests was fine, but if simplifying in PostTyper can fix all the failures, I agree that's less clunky.

So this is another example in the line of issues caused by language imports not being considered everywhere. I don't know enough about the deferred unpickling to suggest how to fix this. Is the cyclic reference specific for unsafeNulls (after you already know that the import is unsafeNulls) or does it happen when trying to resolve the symbol in the import? More generally, I wonder whether language imports should be pickled as something more specific than just general imports.

**Comment by ckipp01** [comment]
Hey @noti0na1, it's been a while here. Do you plan on returning, or are you waiting for a review from someone? How can I help you move this forward?

**Comment by noti0na1** [comment]
Close this PR for now. Plan to revisite this bug soon.

**Pull request closed without merging**
