### PR TITLE
Make sure that trace is shown correctly in the presence of invalid line numbers

### PR DESCRIPTION
**Pull request by liufengyun**
Make sure that trace is shown correctly in the presence of invalid line numbers (-1) in TASTy.

Before:

```Scala
Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)
```

After:

```Scala
Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace:
├── object Parent {                    // error	[ t9312.scala:11 ]
│      ^
├── final val children = Set(Child1, Child2)	[ t9312.scala:21 ]
│                        ^^^^^^^^^^^^^^^^^^^
├── scala.collection.IterableFactory.apply
├── IterableFactory.this.from[A](elems)
├── scala.collection.immutable.Set.from
├── scala.collection.immutable.Set.newBuilder[E].addAll(it)
├── scala.collection.immutable.SetBuilderImpl.addAll
├── super.addAll(xs)
├── scala.collection.mutable.Growable.addAll
├── Growable.this.addOne(it.next())
├── scala.collection.immutable.SetBuilderImpl.addOne
├── SetBuilderImpl.this.hashSetBuilder.addOne(elem)
├── scala.collection.immutable.HashSetBuilder.addOne
├── HashSetBuilder.this.update(HashSetBuilder.this.rootNode, elem, h, im, 0)
├── scala.collection.immutable.HashSetBuilder.update
├── bm.getHash(index)
├── scala.collection.immutable.BitmapIndexedSetNode.getHash
└── BitmapIndexedSetNode.this.originalHashes.apply(index)
```

 Ref: https://github.com/lampepfl/dotty/issues/18882

### CODE REVIEW

**Comment by liufengyun** [comment]
This PR does not fix https://github.com/lampepfl/dotty/issues/18882. The fix will coming next.

**Review by olhotak — CHANGES_REQUESTED** [review]
It looks like the position markers (`^^^`) are now misaligned due to the changes in indentation.

**Comment by liufengyun** [comment]
> It looks like the position markers (`^^^`) are now misaligned due to the changes in indentation.

Good catch, now I fixed the misalignment.

**Review by olhotak — APPROVED** [review]
LGTM

**Pull request merged**
