### PR TITLE
Fix #5962: Add regression test

### LINKED ISSUE #5962: Phase consistency involving higher-kinded types
When a higher-kinded type `S` is used in quote/splice, do we need  an evidence of `Type[S]` or `Type[S[X]]`? Neither type checks.

```Scala
import scala.quoted._
import scala.tasty._

class MatchFactory1[T, S[_]]

object MatcherFactory1 {
  def impl[T: Type, S[_]](self: Expr[MatchFactory1[T, S]])(implicit refl: Reflection, tpS: Type[S[T]]) =
    '{ ~self }
}
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by liufengyun** [comment]
@nicolasstucki The syntax has to be updated.

**Comment by nicolasstucki** [comment]
Syntax updated

**Comment by liufengyun** [comment]
@nicolasstucki LGTM

It's nice to add the test involving inner class too:
https://github.com/lampepfl/dotty/issues/5962#issuecomment-466052699

**Comment by nicolasstucki** [comment]
The example in the has an illegal path. Though with #5988 we will not need to try to encode types this way anymore, I would consider this a non-issue.

**Pull request merged**
