### PR TITLE
Fix compatibility of Java with value classes

### PR DESCRIPTION
**Pull request by smarter**
Review by @odersky.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@smarter can you add a testcase?
I know that we do not have run tests tested yet, but this should not stop us from creating them.

**Comment by DarkDimius** [comment]
Otherwise LGTM

**Comment by smarter** [comment]
Test added.

**Comment by retronym** [comment]
Probably worth a look at https://github.com/scala/scala/commit/44b9cf0ca9606f531218deefe7792b4476552291 which introduced nuanced erasure to Scala based on whether the symbol was Java/Scala, or constructor/non-constructor.

**Comment by DarkDimius** [comment]
@retronym we already have different erasure for java-defined symbol, with different glb.
Why do you need to erase constructors differently?

**Comment by retronym** [comment]
I was echoing a comment in that commit. Looking back a bit further, I think it refers to the special case that the result type of a value class constructor should not erase to the underlying: https://github.com/scala/scala/commit/e171d6d969fe7ce0dd2fd7a7679d6edb08c7579c

I guess you have that covered already.

**Comment by retronym** [comment]
```scala
scala> case class C(val i: Int) extends AnyVal
defined class C

scala> :power

scala> val constructor = symbolOf[C].primaryConstructor
constructor: $r.intp.global.Symbol = constructor C

scala> erasure.specialErasure(constructor)(constructor.info)
res5: $r.intp.global.erasure.global.Type = (i: Int)C

scala> erasure.specialErasure(NoSymbol)(constructor.info)
res6: $r.intp.global.erasure.global.Type = (i: Int)ErasedValueType(class C, Int)
```

**Pull request merged**
