### PR TITLE
Update asm to 9.4

### PR DESCRIPTION
**Pull request by Philippus**
There's first some work to be done in https://github.com/scala/scala-asm.

scala 2.12.x PR: https://github.com/scala/scala/pull/10185
scala 2.13.x PR: https://github.com/scala/scala/pull/10184

### CODE REVIEW

**Comment by SethTisue** [comment]
This seems like a candidate for backporting to 3.2.x.

I will do the work in the scala-asm repo, but not right away (vacation/travel). Unless @lrytz beats me to it :-)

**Comment by SethTisue** [comment]
marking as draft for now (perhaps over-cautiously) until the corresponding Scala 2 PRs have passed CI and been merged

**Comment by SethTisue** [comment]
Okay, the Scala 2 PRs are merged.

**Review by smarter — APPROVED** [review]

**Comment by SethTisue** [comment]
@Kordyjan could this make 3.2.2? (or 3.2.3?)

**Comment by Kordyjan** [comment]
It can make 3.2.2-RC2 (which we will need), so no need to worry.
And as a note, we have decided that there will be no 3.2.3 and we are going for 3.3. Hopefully, we will be able to announce later (probably around 3.3.1 or 3.3.2) that 3.3 is an LTS version.

**Comment by smarter** [comment]
In theory we should only backport things which fix regression, does this fix any regression?

**Comment by SethTisue** [comment]
No, no regression per se, unless you want to get slippery and say that “no longer works on latest JDK” regressed (because the “latest JDK” pointer moved). I’d of course accept a ruling on that grounds, but I’m not sure it’s necessary to be so strict.

One’s feelings might depend on whether one’s crystal ball predicts that 3.3 is really coming soon or whether there’s a chance of it slipping for as long as 3.2 did.

**Comment by smarter** [comment]
>  “supports latest JDK” regressed

But we don't need to upgrade asm to support using the latest JDK, it's only needed for the -target/-release/... flags to emit bytecode that won't be loaded by previous JDK releases, so I don't think it's a big deal. Especially in this case where we're adding support for JDK 20 which won't be released until March 2023.

**Comment by lrytz** [comment]
Right. Scala 2 uses ASM to read classfiles (optimizer, build pipelining), but that's not the case here.

**Pull request merged**
