### PR TITLE
Backport add default scaladoc settings to scaladoc artifact publishing

### PR DESCRIPTION
**Pull request by szymon-rd**

### CODE REVIEW

**Review by KacperFKorban — APPROVED** [review]

**Comment by Kordyjan** [comment]
Should this be merged?

**Comment by KacperFKorban** [comment]
This is actually a PR to [lampepfl:language-reference-stable](https://github.com/lampepfl/dotty/tree/language-reference-stable), so sort of like a backport for scaladoc.

@Kordyjan When it comes backporting it, there should be no harm in that. Though this commit only introduces changes to publishing scaladoc artefacts. So it depends on whether we use this branch for publishing any scaladoc artefacts.

**Comment by ckipp01** [comment]
> This is actually a PR to [lampepfl:language-reference-stable](https://github.com/lampepfl/dotty/tree/language-reference-stable), so sort of like a backport for scaladoc.

Ahh, my mistake. Huh, I probably did the same thing on another pr then, but what is the intended flow for this type of stuff then? For example I often see other prs opened on `language-reference-stable` and then a bot open up another pr for `mai` like https://github.com/lampepfl/dotty/pull/17419. So should these sorts of things always be done in reference stable first?

**Comment by szymon-rd** [comment]
We first merge the commits to the language-reference-stable, as we generate the documentation from this branch. Then, the branch is synced with main. 

A gh action makes the PRs from language-reference-stable to main after PR is merged to language-reference-stable. However, it's only possible to merge PRs to `language-reference-stable` for @Kordyjan and couple of other people (recent branch protection).

**Pull request merged**
