### PR TITLE
Enable many javalib/util/* tests other than Sets for Scala.js

### PR DESCRIPTION
**Pull request by squid314**

### CODE REVIEW

**Comment by squid314** [comment]
Working on simple stuff (I think) for #7113 as I am still new to working on compilers.

**Comment by sjrd** [comment]
@smarter Any opinion on the new format with one exclusion by line?

**Comment by smarter** [comment]
It's not that many so it's fine.

**Comment by squid314** [comment]
My reasoning was that it was easier to comment out one-by-one and it would be more obvious what changed even if you were adding several tests at a time.   :)

**Pull request merged**
