### PR TITLE
simple integration with jline

### LINKED ISSUE #1084: Add jline support to REPL
We should integrate the REPL with jline to allow line editing.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #1084. Please review @odersky .

In this PR, I only added the basic functionality. Are there any specific features that are needed?

### CODE REVIEW

**Comment by odersky** [comment]
LGTM. For future commits, can you push to staging and make the pull request from there? We try to follow that schema to make it easier for several people to collaborate on a PR. Thanks!

**Comment by odersky** [comment]
Oen suggestion: Can we make it accept more than one version of jline? AFAIK 2.12 works fine, so do we need to demand that people upgrade?

**Comment by liufengyun** [comment]
OK, I'll ask @DarkDimius to add me to the staging repo.

Regarding the version, I'm not sure if `ivy` will bind to `2.12` when `2.14` is available. The syntax `[2.12,)` seems to achieve what you want, but it's a bit weird in the Java world.

I agree let's restore it to be `2.12` for the moment.

**Comment by liufengyun** [comment]
Thanks @odersky .

**Comment by som-snytt** [comment]
I have a repl branch which incorporates scala repl bits at https://github.com/som-snytt/dotty/blob/topic/dopler/src/dotty/tools/dotc/repl/jline/Reader.scala

A goal is to have well-defined extension points in the repl package, and a supplied repl with fewer bells and whistles. That was for purpose of adding features, but I'll also check for jline-neutrality.

The day job is doing its annual release so I haven't had the time I'd like, but I'll try to contribute it soon.

Should that be a normal PR against dotty repo?

**Comment by smarter** [comment]
> Should that be a normal PR against dotty repo?

Sure, why not?

**Pull request merged**
