### PR TITLE
Fix emission of annotations

### LINKED ISSUE #1741: JUnit doesn't work with dotty-bridge
I have a Dotty project uses JUnit:

```Scala
libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
testOptions += Tests.Argument(TestFrameworks.JUnit, "-q", "-v")
```

With the test file:

```Scala
import org.junit.Test
import org.junit.Assert._

class MacrosTest {
  @Test def hello = {
    assertTrue(true)
  }
}
```

When run `sbt test`, nothing happens.  When compile with scalac, everything works normally as confirmed by @smarter .

### PR DESCRIPTION
**Pull request by smarter**
Review by @DarkDimius

### CODE REVIEW

**Comment by smarter** [comment]
Looks like this unmasked an issue with the inline body annotations, investigating...

**Comment by DarkDimius** [comment]
Backend-wise LGTM

**Comment by smarter** [comment]
This still isn't enough to fix #1741, turns out [sbt uses the incremental compilation analysis to know which methods have special annotations and need to be run with a test interface](https://github.com/sbt/sbt/blob/0.13/main/actions/src/main/scala/sbt/Tests.scala#L288), but I never implemented support for annotations in incremental compilation: https://github.com/lampepfl/dotty/blob/b9350f40990ce07ba7614a0448a98abd7075abe8/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L501, so I know what I need to do next!

**Comment by smarter** [comment]
Alright, #1741 is fixed by the latest commit, and I added a test to test that the tests are testing something :)

**Comment by liufengyun** [comment]
Well done @smarter 👍  !

**Comment by smarter** [comment]
Ping @DarkDimius , would you mind review the remaining commits?

**Comment by DarkDimius** [comment]
LGTM

**Pull request merged**
