### PR TITLE
sbt-dotty: various fixes, bump to 0.1.0

### PR DESCRIPTION
**Pull request by smarter**
Thanks to @sjrd for writing code that I could steal to delete .tasty files ;).

### CODE REVIEW

**Comment by felixmulder** [comment]
MTGL

**Comment by sjrd** [comment]
My pleasure :)

**Comment by smarter** [comment]
@felixmulder Plz release sbt-dotty 0.1.0, kthxbye.

**Comment by felixmulder** [comment]
:shipit: done!

**Pull request merged**
