### PR TITLE
Add TypeRefiners

### PR DESCRIPTION
**Pull request by odersky**
The aim of this PR is to be able to do a second type checking pass after the first one that is idempotent unless some of the rules change. The idea is to use this as a basis for more complex tasks that need to redo some type inference steps in a more specialized setting.

### CODE REVIEW

**Comment by sjrd** [comment]
> unless some of the rules change

What does that mean? What rules? Why would they change?

**Comment by odersky** [comment]
@sjrd What rules change is left open. For instance, it could be a plugin that reinterprets certain annotated types and changes subtyping rules for them. Retype checking with a type assigner as is usually done could be too limiting then since we might have to redo some type inference steps taking the new rules into account.

**Comment by sjrd** [comment]
I guess you must have at least one use case in mind? Otherwise, why even bother with such wild hypotheticals?

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
I am closing this now because we probably won't need it. But it would be good to not delete the branch since there is a lot of knowledge in there that could be useful for related efforts.

**Pull request closed without merging**
