### PR TITLE
Add Libretto to community build.

### PR DESCRIPTION
**Pull request by TomasMikula**
I would like to add [Libretto](https://github.com/TomasMikula/libretto) to the community build.

### CODE REVIEW

**Comment by TomasMikula** [comment]
Is there a way to re-run the build so that it checks out the HEAD of Libretto's master branch? I have tried to trigger a new build twice with a force push, but an old commit was checked out both times.

**Comment by smarter** [comment]
a git submodule points to a commit, not to a branch, to update it one needs to go into the submodule, checkout the correct commit, cd back outside, git add the submodule directory, then commit.

**Comment by TomasMikula** [comment]
Thanks, updated, new build started.

**Comment by anatoliykmetyuk** [comment]
Thanks for contributing this @TomasMikula! Could you please point the submodule to https://github.com/dotty-staging/libretto ? I've also added you to that repo.

**Comment by TomasMikula** [comment]
@anatoliykmetyuk Done.

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
