### PR TITLE
Fix #2066: Don't qualify private members in SelectionProto's...

### LINKED ISSUE #2066: methods available via implicit conversions should not include private methods
```scala
class Foo

object Test {
  implicit class One(x: Foo) {
    def meth: Unit = {}
  }

  implicit class Two(x: Foo) {
    private def meth: Unit = {}
  }

  def test(foo: Foo): Unit = {
    foo.meth
  }
}
```
```scala
-- [E007] Type Mismatch Error: try/privimpl.scala ------------------------------
13 |    foo.meth
   |    ^^^
   |found:    Foo(foo)
   |required: ?{ meth: ? }
   |
   |
   |Note that implicit conversions cannot be applied because they are ambiguous;
   | both method Two in object Test and method One in object Test convert from Foo(foo) to ?{ meth: Unit }
```

### PR DESCRIPTION
**Pull request by odersky**
... unless they would be accessible in the given context.

### CODE REVIEW

**Comment by liufengyun** [comment]
The fix fails the following case if we change `private` to `protected`:

```Scala
class Foo

object Test {
  implicit class One(x: Foo) {
    def meth: Unit = {}
  }

  implicit class Two(x: Foo) {
    protected def meth: Unit = {}    //  <==== change private to protected
  }

  def test(foo: Foo): Unit = {
    foo.meth
  }
}
```

**Comment by odersky** [comment]
> The fix fails the following case if we change private to protected:

That's expected. `private` behaves differently from the other modifiers. For private/non-private we have different ways to search. For the other modifiers we search first, and then check that the result is accessible. But that check plays no role in (say) overloading resolution or implicit search. This has been always like this, in Java as well as in Scala, and it would be really hard to change.

**Comment by smarter** [comment]
Is this as expected? This doesn't compile:
```scala
class Foo

object Test {
  implicit def two(x: Foo): Two = new Two(x)

  class Two(x: Foo) {
    private def meth: Unit = {}

    def test2(foo: Foo): Unit = {
      foo.meth
    }
  }
}
```
But this does:
```scala
class Foo

object Test {

  class Two(x: Foo) {
    implicit def two(x: Foo): Two = new Two(x)

    private def meth: Unit = {}

    def test2(foo: Foo): Unit = {
      foo.meth
    }
  }
}
```

(Both fail with scalac)

**Comment by odersky** [comment]
> Is this as expected? This doesn't compile:

No, this is weird. It looks like we can't do a good job distinguishing here without losing a lot of implicit cachability. So I'll change it to scalac's behavior to only look for non-private members.

**Comment by smarter** [comment]
Okay, this will require a spec change I think since the spec only mentions accessibility: http://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html#views

**Comment by odersky** [comment]
So, does that means scalac also is in disagreement with the spec here?

**Comment by smarter** [comment]
I think so yes, but I haven't looked closely.

**Pull request merged**
