### PR TITLE
Fix windows CI

### PR DESCRIPTION
**Pull request by BarkingBad**
[test_windows_full]

### CODE REVIEW

**Comment by philwalk** [comment]
This change to `relpath` in `ClasspathTests.scala` is not quite right, because it produces a path with backslashes, which cannot be passed as-is to bash:

```scala
   val relpath = some(testscript.topath.relpath.norm).map {
      case s if cygwin => s"$$(cygpath -aw $s)"
      case s => s
    }.get
```

The backslash is avoided by passing `-am` to cygwin instead:
```scala
   val relpath = some(testscript.topath.relpath.norm).map {
      case s if cygwin => s"$$(cygpath -am $s)"
      case s => s
    }.get
```

If the test is run in a cygwin environment, it fails like this:
```bash
$ bash -c compiler/target/scala-3.1.1-RC1/test-classes/scripting/classpathReport.sc
env: unknown option -- S
Try '/usr/bin/env --help' for more information.
```

It passes in my `msys64` shell (after switching from `cygpath -aw` to `cygpath -am`).

Which problem is this code change aimed at?

**Comment by BarkingBad** [comment]
Are you sure? I don't have access to windows computer, so I experimented with CI checks and I observed that the problem is with path construction. Apparently, we were going up in the file system tree unnecessarily while using the `relativize` method. Hopefully, `.normalize` to the path should fix the issue.

**Comment by philwalk** [comment]
> the problem is with path construction. Apparently, we were going up in the file system tree unnecessarily while using the `relativize` method.

What is an example of the *path construction* problem?  In this case, where the path is consumed by `cygwin bash`, the only example I can't think of where `cygpath` adjustments to the path would be useful is if the path has backslashes, or if it has embedded spaces.   For example:
```bash
cygpath -dm "C:\Program Files"
```
converts to an equivalent path without spaces:
```sh
C:/PROGRA~1
```

**Comment by BarkingBad** [comment]
Sorry, I deleted my comment as I realized I was wrong, however, `normalization` at least helped, now it is failing indeed with the unrecognized `-S` option, not with `file not found` error

**Comment by BarkingBad** [comment]
So I see that the current problem is that we should fix somehow passing arguments.
The question is, whether your proposition will work?
```
    -cp*|-classpath*) # partial fix for #10761
      # hashbang can combine args, e.g. "-classpath 'lib/*'"
      CLASS_PATH="${1#* *}${PSEP}"
      let class_path_count+=1
      shift
      ;;
```
If I am correct we will get arguments as solid string, so I feel like we should try to split the string into multiple args by white spaces rather than to add this additional case, because we will never enter that

**Comment by philwalk** [comment]
> If I am correct we will get arguments as solid string

This strips `-classpath ` from an argument  `-classpath 'lib/*'`, resulting in `CLASS_PATH='lib/*'`.

**Comment by philwalk** [comment]
Ok, this should work (I will start testing it to verify):
```bash
    -cp*|-classpath*) # partial fix for #10761
      # separate hashbang-combined args "-classpath 'lib/*'"
      addScala "-classpath"
      addScala "${1#* *}${PSEP}"
      shift
      ;;
```

**Comment by BarkingBad** [comment]
It works partially, but for script like this:
```
#!bin/scala -classpath 'dist/target/pack/lib/*' -Dkey=value

def main(args: Array[String]): Unit =
  println("Hello " + util.Properties.propOrNull("key"))
```

It won't process the `-Dkey=value` part because it will never hit it. We have to somehow split all the args by white space from $@ and then we will have general solution for as many arguments as we want

**Comment by philwalk** [comment]
> split all the args by white space

That would prevent scala from passing arguments (e.g., filenames) with embedded whitespace.
For now, we can address only the case where an argument contains `-classpath` plus whitespace. 
The reason for the importance of that use-case is because otherwise, it's impossible to create scala scripts with non-standard imports.

**Comment by BarkingBad** [comment]
People cheat this with wrapper workaround, in our case it would be:
```
#!/bin/bash
exec bin/scala -classpath 'dist/target/pack/lib/*' -Dkey=value path/to/script
```

**Comment by philwalk** [comment]
> People cheat this with wrapper workaround, in our case it would be:
> 
> ```
> #!/bin/bash
> exec bin/scala -classpath 'dist/target/pack/lib/*' -Dkey=value path/to/script
> ```

**Comment by philwalk** [comment]
wow, sorry, I accidentally hit [CLOSE WITH COMMENT] and there's no chance to cancel !

**Comment by philwalk** [comment]
> It won't process the `-Dkey=value` part because it will never hit it. We have to somehow split all the args by white space from $@ and then we will have general solution for as many arguments as we want

Here's a proposal:  in `dist/bin/scala`, if an argument contains whitespace, and in addition, at least one of the sub-arguments (when splitting it on whitespace) begins with a hyphen, then we replace the argument with the split sub-arguments in "$@".

**Comment by BarkingBad** [comment]
> > It won't process the `-Dkey=value` part because it will never hit it. We have to somehow split all the args by white space from $@ and then we will have general solution for as many arguments as we want
> 
> Here's a proposal: in `dist/bin/scala`, if an argument contains whitespace, and in addition, at least one of the sub-arguments (when splitting it on whitespace) begins with a hyphen, then we replace the argument with the split sub-arguments in "$@".

This what I was thinking about too. The only question is whether `$#` will be replaced too. Currently I am experimenting with your proposal and observed two interesting things:
- $# is still set to `count = 1` so we don't process further arguemtns after splitting
- the `*` is being unglobbed. When I echo args I pass in bash script I get raw `dist/target/pack/lib/*` but in `MainGenericRunner when I print out args I get list of all matching jars.

**Comment by BarkingBad** [comment]
I think it will be very hard problem in general to allow passing the args in shebang with whitespace. Naively, this works:
```
ARR=( $@ )
set -- ${ARR[@]}
```
but this split also on whitespace in quotes, e. g. `... "my text" ...` which is undesirable. I think we should stick to wrappers, because writing all these logic for preprocessing parameters is very hard and unmaintainable for me

**Comment by philwalk** [comment]
This version handles `-Dkey=value` and all other args, as long as it begins with `-classpath`:

```bash
    -classpath*)
      if [ "$1" != "${1##* }" ]; then
        # hashbang-combined args "-classpath 'lib/*'"
        A=$1 ; shift # consume $1 before adding its substrings back
        set -- $A "$@" # split $1 on whitespace and put it back
      else
        addScala "$1"
        shift
      fi
      ;;
```

However, I'm now grappling with another issue (although it might be unrelated).
With these changes (including changes the shebang line (`#!bin/scala -classpath ...`), we end up with the following java command line being generated by `dist/bin/scala`:

```
java [...] -classpath $jvm_cp_args \
dotty.tools.MainGenericRunner  \
-classpath $jvm_cp_args \
-classpath dist/target/pack/lib/* \
 compiler/target/scala-3.1.1-RC1/test-classes/scripting/classpathReport.sc
```

The problem is that the script only sees `$jvm_cp_args`, so the test fails:
```scala
[info] Test run finished: 1 failed, 0 ignored, 2 total, 5.332s
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error]         dotty.tools.scripting.ClasspathTests
[error] (scala3-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Dec 14, 2021, 8:25:29 AM
sbt:scala3>
```

**Comment by BarkingBad** [comment]
Since `test` and `test_windows_full` passed I think we should merge it, even though it is a workaround, and fix it in some future PR. The second problem, with `test_non_bootstrapped` should be fixed by your @philwalk second PR with refactoring. I still think that after merging this PR we should close your PR and open a new one with:
```
[test_windows_full]
[test_non_bootstrapped]
```
to make sure that everything will work OK. Make sure to include the change to `cwd` property with `normalize` function I made in this PR (I see that you refactored these things) since it is required for Windows platforms (and is more concise with the logic of paths). Is that OK?

**Comment by philwalk** [comment]
> Since `test` and `test_windows_full` passed I think we should merge it, even though it is a workaround, and fix it in some future PR. The second problem, with `test_non_bootstrapped` should be fixed by your @philwalk second PR with refactoring. I still think that after merging this PR we should close your PR and open a new one with:
> 
> ```
> [test_windows_full]
> [test_non_bootstrapped]
> ```
> 
> to make sure that everything will work OK. Make sure to include the change to `cwd` property with `normalize` function I made in this PR (I see that you refactored these things) since it is required for Windows platforms (and is more concise with the logic of paths). Is that OK?

I'm investigating.  It sounds good, although this problem with ClasspathTests is not yet fixed, so should I temporarily disable that test so we can check the other fixes in?

**Comment by BarkingBad** [comment]
To disable tests one should remove `dist/pack` from the CI, both `test_windows_full` and `test` check. Then all tests will silently fail as they were doing for a long time

**Comment by philwalk** [comment]
> To disable tests one cpuld remove `dist/pack` from the CI, both `test_windows_full` and `test` check. Then all tests will silently 
fail as they were doing for a long time, but you can add `@Ignore` annotation as well

Ok, but I think I need to push these fixes to my current open PR #14108, otherwise, I won't be able to get to it soon.
What do I need to do so the additional tests are performed?  Do I edit ci.yaml?
And which tests should be included?

[test_windows_full]
[test_non_bootstrapped]

**Comment by BarkingBad** [comment]
Ok, I'm closing this one then

**Pull request closed without merging**
