### PR TITLE
Change readme

### PR DESCRIPTION
**Pull request by odersky**
Review by @smarter @DarkDimius 

Also: The builds status currently points at Travis but it should be the new jenkins build. Can one of you fix that?

Thanks

 - Martin

### CODE REVIEW

**Comment by smarter** [comment]
LGTM, I can't help with Jenkins but I suggest adding a link to the gitter room: https://gitter.im/lampepfl/dotty

**Comment by DarkDimius** [comment]
>Also: The builds status currently points at Travis but it should be the new jenkins build. Can one of you fix that?

This needs a module to be installed in Jekins. I'll contact @adriaanm and see if we could do something here.

**Comment by adriaanm** [comment]
We have https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin installed -- could that work? I think @retronym knows more about it.

**Comment by smarter** [comment]
Another suggestion: adding links to the talks on Dotty:
- Compilers are Databases: https://www.youtube.com/watch?v=WxyyJyB_Ssc
- Hands-on Dotty: https://www.youtube.com/watch?v=aftdOFuVU1o

**Comment by DarkDimius** [comment]
@adriaanm, the current jobs setup does not track what the current master is. It only tracks pull-requests against master. Using last build status of https://scala-ci.typesafe.com/view/dotty/job/dotty-master-validate-main/ does not cut it.

**Comment by odersky** [comment]
Good point. We should make a page for that.

On Fri, Oct 23, 2015 at 4:59 PM, Guillaume Martres <notifications@github.com
> wrote:

> Another suggestion: adding links to the talks on Dotty:
>
>    - Compilers are Databases: https://www.youtube.com/watch?v=WxyyJyB_Ssc
>    - Hands-on Dotty: https://www.youtube.com/watch?v=aftdOFuVU1o
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/857#issuecomment-150598767>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
> Good point. We should make a page for that.

For now, I've added them to the bottom of https://github.com/lampepfl/dotty/wiki/Getting-Started which is linked from the README.

**Pull request merged**
