### PR TITLE
Remove differences in diagnostic printing in the REPL

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Who's the closest to being the REPL maintainer?

**Comment by SethTisue** [comment]
can you explain the `build.sbt` changes a little?

**Review by SethTisue — APPROVED** [review]
The user-facing changes look very good to me. This is a nice improvement in usability.

And, Dale walked me through the implementation and I see nothing to object to. A few more comments might help future maintainers.

@bjornregnell any thoughts?

**Comment by som-snytt** [comment]
Footnote that Scala 2 REPL enables `-deprecation -feature` unless those flags are explicitly set. (Actually in MainGenericRunner, the test is now that Wconf and Xlint are not set.) You only see extended warning once:
```
scala
Welcome to Scala 2.13.6 (OpenJDK 64-Bit Server VM, Java 17-ea).
Type in expressions for evaluation. Or try :help.

scala> implicit def f(s: String) = s.toDouble
                    ^
       warning: implicit conversion method f should be enabled
       by making the implicit value scala.language.implicitConversions visible.
       This can be achieved by adding the import clause 'import scala.language.implicitConversions'
       or by setting the compiler option -language:implicitConversions.
       See the Scaladoc for value scala.language.implicitConversions for a discussion
       why the feature should be explicitly enabled.
def f(s: String): Double

scala> implicit def f(s: String) = s.toDouble
                    ^
       warning: implicit conversion method f should be enabled
       by making the implicit value scala.language.implicitConversions visible.
def f(s: String): Double

scala>
```

**Comment by SethTisue** [comment]
@som-snytt True, but regardless, the sbt task should have the same defaults as what user get. I would be in favor of a separate PR that added `-deprecation` `-feature` in both contexts.

**Comment by nicolasstucki** [comment]
@dwijnand the CI failed on the merge commit if this PR. It then failed on nightly.

**Comment by dwijnand** [comment]
Does GitHub Actions run on the branch then, rather than a merge commit?  I'll fix up master asap.

**Pull request merged**
