### PR TITLE
Add tests checking whether the links haven't changed

### PR DESCRIPTION
**Pull request by pikinier20**
This test is a response for the links problem that we had some time ago. Also, it might be useful for the language reference documentation that we want to deploy on docs.scala-lang.org since we can detect changed links after applying changes to documentation.

### CODE REVIEW

**Comment by pikinier20** [comment]
@anatoliykmetyuk do you have any idea why the community build here is failing? I don't think I changed anything related to it.

**Comment by bishabosha** [comment]
seems like the community build failure was not deterministic?

**Review by romanowski — COMMENTED** [review]
I wonder if maybe we can use `regenerateExectedLinks` also in `doscLinksSatbility`? So we use only one mechanism to get the list of links?

**Comment by pikinier20** [comment]
> I wonder if maybe we can use `regenerateExectedLinks` also in `doscLinksSatbility`? So we use only one mechanism to get the list of links?

The idea is to keep the reference links list and compare it to generated one. I don't get how we can use `regenerateExpectedLinks` in `docsLinksStability`. I mean, how could we get the expected list of links in other way than having this saved in repo?

**Review by Kordyjan — APPROVED** [review]

**Pull request merged**
