### PR TITLE
Do not harmonize constant args if their type doesn't affect resType

### PR DESCRIPTION
**Pull request by dos65**
Fixes the following sample from #9939:
```scala
scala> f"${3.14}%.2f rounds to ${3}%d"
1 |f"${3.14}%.2f rounds to ${3}%d"
  |                          ^
  |                          type mismatch;
  |                           found   : Double
  |                           required: Int
  | This location contains code that was inlined from rs$line$2:1
```

At the moment when StringInterpolation transformation was performed instead
of receiving `List(Constant(3.0), Constant(3))` arguments they
were: `List(Constant(3.0), Constant(3.0))` (the second one was converted to double because of harmonization).
That caused the reported type mismatch.

In Scala2 harmonization doesn't happen if the resulting type is fully defined.
For f-interp it shouldn't happen too as it's resulting type is a `String`:
```scala
  def f[A >: Any](args: A*): String = macro ???
```

### CODE REVIEW

**Comment by som-snytt** [comment]
Thanks, I happen to have just resurrected my PR for updating the interpolator, but that test from Scala 2 is still commented out. I see on Scala 2, that was for the fix to add the type parameter; there is no harmonics.

**Comment by som-snytt** [comment]
A different idea is to not harmonize because of the lower bound `>: Any`. That is syntax for fixing or defining the `A`, and I guess that was part of the trick in 2014, according to the discussion on the old ticket. I linked the new ticket.

> I think I still have my "I'm a lubber not a typer" t-shirt from back then.

I didn't get enough mileage from that slogan.

```
scala> def f[A](xs: A*) = xs.mkString
def f[A](xs: A*): String

scala> f(3, 3.14)
val res1: String = 3.03.14
```

**Comment by dos65** [comment]
@som-snytt Thanks! I remember that I've checked if it works without `>: A` but it seems that I misinterpret the result. Will change the PR.

btw. Do you have any idea where this logic might be found in scala2 codebase?

**Review by odersky — APPROVED** [review]

**Comment by dos65** [comment]
@odersky @som-snytt noticed that this fix isn't fully compatible with scala2 implementation. Is it ok to leave it as it is?

**Comment by odersky** [comment]
I think we can leave it as it is.

**Pull request merged**
