### PR TITLE
Fix/datarace flags

### PR DESCRIPTION
**Pull request by odersky**
Made FlagTranslation threadsafe, Review by @DarkDimius or @retronym or @vsalvis

### CODE REVIEW

**Comment by odersky** [comment]
The test says "output differs" on one of the run tests. How do get at the log file in jenkins?

**Comment by DarkDimius** [comment]
@odersky, it's quite involved, you'll need help from either @lrytz  or @adriaanm.

**Comment by odersky** [comment]
Note: I cannot run the tests locally. sbt partest gives:

[error] Test dotc.tests.new_all failed: scala.reflect.io.FileOperationException: File 'arrays.flags' already exists., took 0.008 sec
[error]     at scala.reflect.io.Path$.fail(Path.scala:78)
[error]     at scala.reflect.io.Path.createFile(Path.scala:235)
[error]     at test.CompilerTest.copyFiles(CompilerTest.scala:238)
[error]     at test.CompilerTest.computeDestAndCopyFiles(CompilerTest.scala:220)

**Comment by DarkDimius** [comment]
ping @vsalvis, see stacktrace in previous comment.

**Comment by vsalvis** [comment]
Running locally, I get the test failure as well for:
`[info] !! 376 - run/t7291.scala                           [output differs]`
The diff is that it prints only "conjure", whereas the check file is 
```
conjure
traversable
```

I also see spurious failures of pos/tools and pos/io on my machine.

@odersky, can you try manually deleting the /Users/vera/git/dotty/tests/partest-generated/ directory? Do you have uncommitted tests in dotty/tests/new? What does the /Users/vera/git/dotty/tests/partest-generated/gen.log file say in the end (output might be out of order because of parallel JUnit tests)?

**Comment by adriaanm** [comment]
@DarkDimius, this is a side-effect of how you run partest. You can make it output the diff with `--show-diff` (https://github.com/scala/scala-partest/blob/3e608c08a80dd8aaece52b2638518b7281fc6c15/src/main/scala/scala/tools/partest/nest/ConsoleRunnerSpec.scala#L38). You can also archive the log files if you prefer as build artifacts (with a variation on: https://github.com/scala/scala-jenkins-infra/blob/master/templates/default/jobs/scala/validate/test.xml.erb#L20).

**Comment by retronym** [comment]
Here's the corresponding fix for Scalac: https://github.com/scala/scala/pull/2842

**Comment by DarkDimius** [comment]
@adriaanm, for some reason, `--show-diff` does not work on Dotty. #609

**Comment by DarkDimius** [comment]
LGTM, though need to make tests pass, or disable failing tests.

**Comment by vsalvis** [comment]
Sorry this slipped through, we talked about displaying as much debugging
output as possible because of the difficulties of accessing logs. It
probably makes sense to run partest on Jenkins with "--verbose" to get more
information about failures at the end. --verbose will also display diffs if
there are any, as well as compilation logs if compilation failed.

**Comment by DarkDimius** [comment]
@vsalvis, lets take partest discussion to #609

**Comment by odersky** [comment]
@vsalvis Thanks for the tip. It was indeed an uncommitted .java file in tests/new. Now I can run partest locally, and get the same test failure you are seeing on run/t7291, both on current master and this branch. Which makes me wonder how master could have succeeded? Do we have flakey run test diagnosis in jenkins, or is it some other problem?

**Comment by odersky** [comment]
@smarter I did a reorg of disabled after all. It was easier to do it sooner rather than later.

**Pull request merged**
