### PR TITLE
Fix #12267: Constraints should not cross phases 

### LINKED ISSUE #12267: Performance issues with match type reduction
https://github.com/lampepfl/dotty/pull/12153 introduce a performance regression for the stdlib test. I tracked it down to attempts to do match type reductions that seem very slow. 

I saw that overall there were 566 attempts at match type reductions, presumably when compiling the Tuple.scala (and maybe also Tuples.scala) files. Without the change to translucentSuperType there were none. But the change is necessary and 566 does not seem an excessive number. Nevertheless these reduction attempts (which all fail in the end) seem responsible for the significant slowdown of stdlib compilation as a whole.

We should get to the bottom of this. As a first step, we should try to get a flamegraph or other profile just for compiling Tuple.scala and Tuples.scala. Once we know where the slowdown happens we should see what we can do to optimize.

### PR DESCRIPTION
**Pull request by odersky**
Use these changes to compile the stdlib. You need to comment out AnyVal.scala and then
use the following command on community-projects/stdLib213:

    scalac -Ydetailed-stats *.scala */*.scala */*/*.scala */*/*/*.scala

What I see is:

Calls to `translucentSuperType` 53152:

    try norm KO -> 53086
    try norm OK -> 66

The only computationally relevant part of this are calls to tryMatchAlias

    try match alias -> 528

Those calls suceed in 66 cases

    try norm OK -> 66

The successful normalizations all return types like this:

    try norm OK F[T1] *: scala.Tuple.Map[(T2, T3, T4, T5, T6, T7, T8), F] -> 3

Now it could be that trying the normalizations is costly, or that the normalized types
cause exhaustivity checking to explode. Tht remains to be found out.

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Comment by liufengyun** [comment]
test performance with #stdlib please

**Comment by liufengyun** [comment]
test performance with #stdlib please

**Comment by liufengyun** [comment]
test performance with #stdlib please: d3331ee a50963e

**Comment by liufengyun** [comment]
retest performance with #stdlib please

**Comment by odersky** [comment]
We might need something like that in the end, but it also hides errors. Before doing this, I wonder whether we could find sources of overflowing constraints and treat them in a more fine-grained manner that does not wait until the end of a phase to remove constraint entries.

**Comment by liufengyun** [comment]
> We might need something like that in the end, but it also hides errors. Before doing this, I wonder whether we could find sources of overflowing constraints and treat them in a more fine-grained manner that does not wait until the end of a phase to remove constraint entries.

Maybe change `ctx.constraint.gc()` to an assertion instead?

With the following code,

https://github.com/lampepfl/dotty/blob/144069973feb219caf66cb7741f50a75e88cc5e6/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala#L88-L99

We get constraints like the following in compiling `tests/pos/t2619b.scala`:

```
adding constraint B :> AbstractModule to
Constraint(
 uninstantiated variables: B
 constrained types: [B >: ModuleBF.type](prefix: List[B]): List[B]
 bounds:
     B >: ModuleBF.type | ModuleBE.type <: AbstractModule
 ordering:
)
added constraint B :> AbstractModule to
Constraint(
 uninstantiated variables:
 constrained types: [B >: ModuleBF.type](prefix: List[B]): List[B]
 bounds:
     B := AbstractModule
 ordering:
) = true
```

This will leave the tvar that binds to `B` uninitialized, thus depends on the constraint for pickling to work correctly.

**Comment by odersky** [comment]
I think we should do a gc() in the toplevel constraint and should assert that after that the constraint is empty. Right now that's not the case, it seems for several different reasons. I tracked one down to a shortcoming in mergeConstraints but that's not all it seems.

**Comment by odersky** [comment]
This is now superseded by #12333

**Pull request closed without merging**
