### PR TITLE
Change/simplify tasty

### PR DESCRIPTION
**Pull request by odersky**
Drops SkolemTypes and ABSOVERRIDE. Based on #599. Review by @vladimirnik, @DarkDimius

### CODE REVIEW

**Comment by odersky** [comment]
@xeno-by. No SkolemTypes are too limited to encode existential. A SkolemType(T) represents the type
`x.type forSome { val x: T }`. General existential types need to be encoded by creating skolem values.
I..e for a type `T forSome { type X <: B }` create a TypeDef with a synthetic name like `$X` that represents the existential variable and use the type [X := $X]T instead.

**Comment by odersky** [comment]
Merging, to get things to move again.

**Comment by odersky** [comment]
Rebased to master; three commits remaining. @vladimirnik can you review, please?

**Comment by VladimirNik** [comment]
LGTM

**Pull request merged**
