### PR TITLE
Cleanup tests

### PR DESCRIPTION
**Pull request by allanrenucci**
- Remove std lib blacklist
- Factor out some code

### CODE REVIEW

**Comment by allanrenucci** [comment]
Blocked on #5433

**Comment by odersky** [comment]
Why not wait for 2.13 collections instead? I mean the situation with 2.12 is both acceptable and temporary, so why bother changing it now? I agree that #5433 needs to be addressed.

**Comment by allanrenucci** [comment]
> Why not wait for 2.13 collections instead? I mean the situation with 2.12 is both acceptable and temporary, so why bother changing it now? I agree that #5433 needs to be addressed.

I am not sure to understand your comment. This PR is unrelated to #5433. It is a little refactoring in the test infrastructure. It just happen to change the compilation order in some tests which now fail

**Comment by allanrenucci** [comment]
> Nice simplification! While you're at it, could you try moving the sources in a different package than package scala ?

Can this be done in a separate PR. I probably won't have time to do that in the near feature and I don't think it should block this PR

**Pull request merged**
