### PR TITLE
Disambiguate quoted and tasty Type

### PR DESCRIPTION
**Pull request by nicolasstucki**
This ambiguity can be seen in the following
```scala
import scala.quoted._
def f[T: Type](given qctx: QuoteContext) = {
  import qctx.tasty._
  ...
  summon[Type[T]] // qctx.tasty.Type instead of scala.quoted.Type
  ...
}
```

To avoid the ambiguity we simply rename `scala.quoted.Type` to `TypeTag`.
From the 2 this is the one that conforms the least to the common expectation of
what is a `Type`. We chose `TypeTag` because it encapsulates the same kind
of information that `scala.reflect.TypeTag` did.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
This is a drastic but necessary change. The sooner we make the change, the simpler it will be for users.

**Comment by nicolasstucki** [comment]
@milessabin this also added a minor change to shapeless

**Comment by milessabin** [comment]
@nicolasstucki thanks for the heads up!

**Comment by nicolasstucki** [comment]
@milessabin we actually reverted this one for now

**Pull request merged**
