### PR TITLE
Dotty deviation: cannot compile GenTraversableFactory

### PR DESCRIPTION
**Pull request by DarkDimius**
```
[info] Test dotc.tests.pos_GenTraversableFactory started
./tests/pos/GenTraversableFactory.scala:57: error: genericBuilder is not a member of GenTraversableFactory.this.Coll
    def apply(from: Coll) = from.genericBuilder[A]
                                 ^
./tests/pos/GenTraversableFactory.scala:222: error: < is not a member of T(step)
    while (if (step < zero) end < i else i < end) {
               ^
./tests/pos/GenTraversableFactory.scala:222: error: < is not a member of T(end)
    while (if (step < zero) end < i else i < end) {
                            ^
./tests/pos/GenTraversableFactory.scala:222: error: < is not a member of T
    while (if (step < zero) end < i else i < end) {
                                         ^
5 errors found
```

We also seem to have a minor bug somewhere: only 4 errors where reported, but total is 5 errors.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky could you please have a look?

**Comment by odersky** [comment]
When I run this on #805 I get the first error like this:

GenTraversableFactory.scala:52: error: illegal wildcard type argument; does not correspond to type parameter of a class
  class GenericCanBuildFrom[A] extends CanBuildFrom[CC[_], A, CC[A]] {
                                                       ^

That explains it. We cannot do existentials over hk types. The code will have to be rewritten to compile under dotty.

**Comment by DarkDimius** [comment]
@odersky, could you try compiling the file from this branch, not the file in standard library.
This file was modified to compile with dotty

**Comment by odersky** [comment]
GenTraversableFactory is not legal code because it uses a hk type as the type of a parameter. This is now flagged by #821.

**Pull request closed without merging**
