### PR TITLE
Fix #7700: Export forwarders of inline methods are themselves inline

### LINKED ISSUE #7700: Bad interaction between overloading, export, and inline (possibly misleading error message)
I'm getting an unexpected error message when trying to export an inline definition:

```
[error] 12 |  export Macros.show
[error]    |         ^^^^^^
[error]    |         method show is declared as erased, but is in fact used
```

## minimized code
```Scala
package test

trait Show[-A]
  def show(a: A): String

object Macros
  inline def (sc: StringContext) show(args: =>Any*): String = ???

object Show
  def[A] (a: A) show(given S: Show[A]): String = S.show(a)

  export Macros.show
```

In this case, the `inline` doesn't make much sense, in the larger version it's a macro which has been moved to a separate file so it can be used within `Show.scala`.

## expectation

I'd like to be able to present the full API in a central location, with minimal import tax. It's reasonable to expect the users to import `Show.show` or `Show.given`, but not really reasonable to expect them to import `Show.show` and `macros.Show.show`, if it's at all avoidable.

If this is something that is not supported, I'd expect a more relevant error message, as `erased` isn't part of the (visible) definitions.

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by biboudis** [comment]
LGTM. 

@odersky I have a small question: despite that `inline` methods are not overridden by definition, some users may write code like the one below. Does it make sense to emit a warning for cases like these? 

```
package test

class Macros
  inline def meth(): String = ???

object Meth
  private val macros = new Macros() { override def meth(): String = ??? }
  export macros.meth
```

**Comment by odersky** [comment]
You mean, generally warn when an inline method is overridden, or just for exports?

**Comment by biboudis** [comment]
> You mean, generally warn when an inline method is overridden, or just for exports?

I was thinking about both occasions, yes.

**Comment by morgen-peschke** [comment]
Thanks @odersky :)

**Pull request merged**
