### PR TITLE
Two additions to batch files

### PR DESCRIPTION
**Pull request by michelou**
These additions are follow-ups of the two *merged* pull requests  : 
- [`dist/bin/scalac.bat`](https://github.com/lampepfl/dotty/blob/master/dist/bin/scalac.bat), see [PR#13759](https://github.com/lampepfl/dotty/pull/13759).
- [`dist/bin/scaladoc.bat`](https://github.com/lampepfl/dotty/blob/master/dist/bin/scaladoc.bat), see [PR#13577](https://github.com/lampepfl/dotty/pull/13577).

The changes are Windows-specific and have no impact on the CI build.

### CODE REVIEW

**Comment by michelou** [comment]
@smarter Backport candidate to 3.1.1-RC2.

**Comment by smarter** [comment]
Does this fix a regression from a previous scala 3 release? Otherwise it's unlikely to be backported.

**Comment by michelou** [comment]
@smarter My reasoning is as follows :
- PR [#13577](https://github.com/lampepfl/dotty/pull/13577) is both *part of* [3.1.0 final](https://github.com/lampepfl/dotty/releases/tag/3.1.0) (and [3.1.1-RC1](https://github.com/lampepfl/dotty/releases/tag/3.1.1-RC1) too).
- PR [#13790](https://github.com/lampepfl/dotty/pull/13790) and [#13806](https://github.com/lampepfl/dotty/pull/13806) include small fixes to PR [#13577](https://github.com/lampepfl/dotty/pull/13577).

In resume, the feature "batch files support installation path containing spaces"
(Reminder: *Windows specific* and no impact on the CI build)
- was introduced in [3.1.0](https://github.com/lampepfl/dotty/releases/tag/3.1.0) (see "Other bug fixes" in announcement)
- would work as expected in upcoming 3.1.1.

The final decision is yours.

**Comment by smarter** [comment]
I'm not familiar with this code so I shouldn't decide really :). You can submit a backport and have @anatoliykmetyuk decide since he reviewed this PR already.

**Pull request merged**
