### PR TITLE
Add blogpost for 3.0.1 and 3.0.2-RC1

### PR DESCRIPTION
**Pull request by prolativ**
[skip ci]

### CODE REVIEW

**Comment by julienrf** [comment]
Hi @prolativ! The content of the dotty website has recently been moved to docs.scala-lang.org. We are now in the process of archiving dotty.epfl.ch. Do you mind posting the announce on the scala-lang.org website instead?

**Review by julienrf — CHANGES_REQUESTED** [review]
Hi @prolativ! The content of the dotty website has recently been moved to docs.scala-lang.org. We are now in the process of archiving dotty.epfl.ch. Do you mind posting the announcement on the scala-lang.org website instead?

**Comment by prolativ** [comment]
Out of all the blogposts about Scala 3 only the one about 3.0.0 seems to be there. Are you going to migrate the rest as well? If so, maybe it would be better to publish this blogpost to dotty website as this has been done until now and then migrate them all at once? My concern is that during this release many things that seemed to be trivial and normally didn't cause any issues already turned out not to work as expected.
@anatoliykmetyuk WDYT?

**Comment by julienrf** [comment]
I didn’t intend to migrate the existing blog posts about the Dotty releases to the scala-lang.org blog. My reasoning is that these posts were about the development of the Dotty project, so they should stay on dotty.epfl.ch, but now that Dotty has become Scala 3 it makes sense to publish the new stable releases on the scala-lang.org blog. I’m happy to revisit my opinion.

**Comment by prolativ** [comment]
Taking this approach it would make sense to me to migrate at least the blogposts for the releases following 3.0.0, which are 3.0.1-RC1 and 3.0.1-RC2

**Comment by michelou** [comment]
@prolativ IMO [PR#13006](https://github.com/lampepfl/dotty/pull/13006) (namely the addition of batch commands for Windows users)  should be added to the section "Other notable improvements" for release 3.0.2-XXX.

**Review by romanowski — APPROVED** [review]

**Comment by prolativ** [comment]
@michelou you're right, sorry for missing that

**Comment by prolativ** [comment]
Moving the blogpost directly to scala-lang webpage then.
PR replaced by https://github.com/scala/scala-lang/pull/1259

**Pull request closed without merging**
