### PR TITLE
community build: add scala-parallel-collections

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
this is failing for two reasons:

first, `sbt.librarymanagement.ResolveException: Error downloading org.scalacheck:scalacheck_3.0.0-M2:1.15.0` — no idea what I'm expected to do here? I already included `dependencies     = List(scalacheck)`

second, the scala-parallel-collections build requires sbt 1.4.1+ (to get the new built-in-support for `src/main/scala-2` and `src/main/scala-3` directories), but it appears to me that the community build forces the version to 1.3.8. is there a way to get a newer sbt version?

**Comment by griggt** [comment]
> `Error downloading org.scalacheck:scalacheck_3.0.0-M2:1.15.0`

This is because the current version of scalacheck in the community build is `1.14.1-SNAPSHOT`.

I'm the wrong person to be giving advice here, but will note that the other projects in the community build live in forks at https://github.com/dotty-staging/ and may contain adaptations to allow/keep them building inside the community build.

On a positive note, I was able to get this to work in a locally built community build by tweaking the scalacheck version and unmanagedSourceDependencies in build.sbt.

**Comment by smarter** [comment]
> first, sbt.librarymanagement.ResolveException: Error downloading org.scalacheck:scalacheck_3.0.0-M2:1.15.0 — no idea what I'm expected to do here?

As mentioned by @griggt, we'll need to update the scalacheck submodule to 1.15, because we try to keep all our community-build projects on https://github.com/dotty-staging/this means creating (or non-destructively) updating a new branch on https://github.com/dotty-staging/scalacheck/ (same thing for scala-parallel-collections itself: we should fork it to dotty-staging and add that fork as our submodule) I've given you access to dotty-staging if you're up for doing that, otherwise we'll take care of it.

> second, the scala-parallel-collections build requires sbt 1.4.1+ (to get the new built-in-support for src/main/scala-2 and src/main/scala-3 directories), but it appears to me that the community build forces the version to 1.3.8. is there a way to get a newer sbt version?

You can change the forced version to 1.4.1 (I would avoid 1.4.2 due to https://github.com/sbt/sbt/issues/6055) and see if everything works, I think that might require updating some other projects in the community build. Or you can add an extra commit in the fork of scala-parallel-collections in dotty-staging to make it not require sbt 1.4

**Comment by SethTisue** [comment]
thanks for the advice — I'll return to this before too much longer. marking as draft for now.

**Comment by smarter** [comment]
PR to upgrade scalacheck: https://github.com/lampepfl/dotty/pull/10194

**Comment by SethTisue** [comment]
I tried downgrading scala-parallel-collections to ScalaCheck 1.14 but there were source incompatibilities. Rather than wrestle with it, I'm just going to close this for now, but I've subscribed to https://github.com/lampepfl/dotty/pull/10194 so I can reopen this one once that one lands.

Meanwhile, I'll attempt the same upgrade in the Scala 2 community build and see how it goes: https://github.com/scala/community-build/pull/1285

**Review by anatoliykmetyuk — APPROVED** [review]

**Pull request merged**
