### PR TITLE
Fix #2812: incorrect width of blog entry author photo

### LINKED ISSUE #2812: Dotty blog - incorrect width of photos
There is problem with styles on dotty blog site. Authors photos (at the bottom of page) have incorrect width.
For example here http://dotty.epfl.ch/blog/2017/05/31/first-dotty-milestone-release.html

### PR DESCRIPTION
**Pull request by AnEmortalKid**
Fixes #2812

### CODE REVIEW

**Comment by smarter** [comment]
Hi, thanks for your contribution which looks good to me! Before we can merge it you'll need to accept the Scala CLA at https://www.lightbend.com/contribute/cla/scala

**Comment by AnEmortalKid** [comment]
@smarter I think the cla bot lied to me!
```
Hello, and thank you for opening this PR! :tada:

All contributors have signed the CLA, thank you! :heart:

Have an awesome day! :sunny:
```

Let me get on that. I could try to fix the bot to have the link to the scala CLA (not sure what checks its missing since it still posted even though the check failed)

**Comment by AnEmortalKid** [comment]
>Thank you for signing the Scala CLA.

> If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

> We are looking forward to your contributions!

I have signed the CLA

**Comment by smarter** [comment]
Yeah the bot is being weird, it's supposed to check for the CLA but gets it wrong for some reason, we haven't had time to figure out why yet. Anyway, thanks for signing the CLA!

**Comment by smarter** [comment]
Oh actually, there's one change you could do to make this even better: in one of your commit message start with "Fix #2812", this way github will automatically close the issue when this PR is merged.

**Comment by smarter** [comment]
Note that just changing the PR title does not work for github auto-closing feature: you need to actually change the commit message of one of your commit (you can edit the last commit message with `git commit --amend` and then push the result with `git push --force`).

**Comment by AnEmortalKid** [comment]
Ah I did not read the "one of your commit messages bit", my bad. Done

**Comment by smarter** [comment]
Thanks! I'll merge once the CI confirms the tests pass.

**Pull request merged**
