### PR TITLE
Fix #939. Allows IntMap and LongMap to compile

### LINKED ISSUE #939: Failure to type patterns in IntMap
dotc ./scala-scala/src/library/scala/collection/immutable/IntMap.scala

```
./scala-scala/src/library/scala/collection/immutable/IntMap.scala:118: error: Pattern type ((T1?), (T2?), (T3?), (T4?)) is neither a subtype nor a supertype of selector type (key: scala.collection.immutable.IntMapUtils.Int)Option[V]
      case IntMap.Bin(_,_, t@IntMap.Tip(_, _), right) => {
```

### PR DESCRIPTION
**Pull request by DarkDimius**
See also https://github.com/DarkDimius/scala/commit/69cf4238649c5faa91d29f5969f9d5abda30c783 for a small change in stdlib.

### CODE REVIEW

**Comment by odersky** [comment]
LGTM if tests pass

**Comment by odersky** [comment]
@darkdimius Needs to be rebased to master.

**Comment by odersky** [comment]
@darkdimius ping

**Comment by DarkDimius** [comment]
@odersky, thanks for reminding.

**Pull request merged**
