### PR TITLE
Fix/#569 new ref array

### PR DESCRIPTION
**Pull request by odersky**
Review by @DarkDimius

### CODE REVIEW

**Comment by DarkDimius** [comment]
Why is this fix better? AFAIK, this is the first time we break refference equality on symbols.

**Comment by DarkDimius** [comment]
Ohh. I get it now. It's to make sure that nobody actually will do anything with symbol that originates from source. 

Wouldn't this create problems for various `withFixedSym`?

**Comment by odersky** [comment]
I don't think so. `newRefArray` is a dummy. References to the original symbol should kept as they are because the backend will have to interprete them specially, and eliminate the reference ot `newRefArray`. I tried to simply drop the definition of `newRefArray` in erasure altogether, but that broke bridge generation. I think the current version is the least invasive fix.

**Pull request merged**
