### PR TITLE
Incremental compilation: handle constructor proxies

### PR DESCRIPTION
**Pull request by smarter**
I noticed that repeatedly runnning `sbt compile` in dotty lead to the
same files being compiled over and over even though nothing changed,
running `sbt "debug; compile"` revealed messages like this:

[debug] Invalidating '${BASE}/compiler/target/scala-3.0.0-RC1/classes/dotty/tools/dotc/typer/Namer.class' because could not find class dotty.tools.dotc.typer.Namer$ on the classpath.

Indeed, Namer does not have a companion object so there's no
`Namer$.class` file, but sbt was looking for one because we registered
such a companion with `ctx.sbtCallback.binaryDependency`, this happened
because we created a fake companion object for the purpose of holding
constructor proxies (fake apply methods that forward to a constructor).
The fix is to special-case such references, just like we already
special-cased references to the fake companion of Java classes.

### CODE REVIEW

**Review by michelou — COMMENTED** [review]
@smarter Two suggestions :
- Write `If we create constructor proxies` instead of `If we decide to create constructor proxies`.
- Mention in comment the phase/method names where constructor proxies are created.

**Comment by bishabosha** [comment]
on this branch, whenever I open a new sbt session and run `repl` for example, I still have to recompile 62 files, is there another explanation for this?

**Comment by smarter** [comment]
Yep, that happens because the reference compiler is still broken, if you try `sbt scala3-compiler-bootstrapped/compile` it should only recompile the non-bootstrapped compiler.

**Comment by bishabosha** [comment]
> Yep, that happens because the reference compiler is still broken, if you try `sbt scala3-compiler-bootstrapped/compile` it should only recompile the non-bootstrapped compiler.

Thanks for the info, well I can can confirm that the bootstrapped sources keep compiling on `master`, but not this branch so I approve this  change

**Review by bishabosha — APPROVED** [review]

**Pull request merged**
