### PR TITLE
dotc: always use the current version of scala

### PR DESCRIPTION
**Pull request by smarter**
Tested on Linux, it'd be nice if someone could test this on OS X to make sure it works there too.

### CODE REVIEW

**Comment by DarkDimius** [comment]
Having both `build.sbt` and `Build.scala` is sometimes conceived as bad practice, and we actually have both.
At some point `build.sbt` could be removed, and the info will get moved to https://github.com/lampepfl/dotty/blob/master/project/Build.scala

**Comment by smarter** [comment]
@DarkDimius : If we remove `build.sbt`, we'll update this script anyway.

**Comment by odersky** [comment]
@DarkDimius I leave to you to merge or close.

**Comment by DarkDimius** [comment]
Closed as alternative was merged in #535

**Pull request closed without merging**
