### PR TITLE
Add type refinement for abstract type bindings

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by smarter** [comment]
If I can write any type on the rhs of `Refined`, isn't this completely unsound?

**Comment by nicolasstucki** [comment]
There are still some constraints that must be added.

**Comment by Blaisorblade** [comment]
But do we have a way to add constraints that makes this sound? I thought the plan was to warn the user that they use an escape hatch, just like `asInstanceOf`. Maybe call the member `UnsafeRefined` to make this more visible?

**Comment by nicolasstucki** [comment]
@Blaisorblade the current implementation in this PR is a partial implementation of the new scheme.

**Comment by nicolasstucki** [comment]
The unboxed result of `RefinedScrutinee` has the expected performance. Here is a small experiment https://gist.github.com/nicolasstucki/96347efecaa5f6fb71d7146635c079c3

**Comment by Blaisorblade** [comment]
FWIW: last I tried to write value class decorators with a single member, I ran into #4583, which seems hard to avoid.

**Comment by nicolasstucki** [comment]
Will reopen it when I'll have time to work on it

**Pull request closed without merging**
