### PR TITLE
Fix the non-miniphase tree traverser

### LINKED ISSUE #16678: `-Wunused:all` and named function arguments
I tried adding the new unused flag (from https://github.com/lampepfl/dotty/pull/16157) to my work codebase and was surprised that it warned when a *named arguments function defined inline* gives unused warnings. This is even if it uses underscore.

## Compiler version
With nightly: `3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY`

## Minimized code
```scala
//> using scala "3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY"
//> using option "-Wunused:all"

def foo(func: Int => String, value: Int): String = func(value)

println(foo(number => number.toString, value = 5)) //No warn
println(foo(func = number => number.toString, value = 5)) ///Warns twice
println(foo(func = _.toString, value = 5)) //Warns once
```

## Output

```scala
[warn] ./unused-function-param.sc:7:20: unused explicit parameter
[warn] println(foo(func = number => number.toString, value = 5)) //Warns twice
[warn]                    ^^^^^^
[warn] ./unused-function-param.sc:7:27: unused local definition
[warn] println(foo(func = number => number.toString, value = 5)) //Warns twice
[warn]                           ^
[warn] ./unused-function-param.sc:8:20: unused local definition
[warn] println(foo(func = _.toString, value = 5)) //Warns once
[warn]  
```

## Expectation
There is nothing unused here as far as I can tell, so it should not give a warning.

### PR DESCRIPTION
**Pull request by PaulCoral**
Fixes #16678. The issue is related to the second tree traverser (needed as miniphase traverser do not cover every cases). 

Symbols are added to a set during the traversal of their own definition to avoid recording recursive. In the second tree traverser this symbol is never removed, so the following usage are never cached, resulting in false positive.

@szymon-rd

### CODE REVIEW

**Review by szymon-rd — APPROVED** [review]

**Comment by szymon-rd** [comment]
Could you fix the conflicts? @PaulCoral

**Comment by smarter** [comment]
I'm concerned that this phase uses both the miniphase traversing logic and a TreeTraverser, aren't you traversing the same trees multiple times?

**Comment by szymon-rd** [comment]
@smarter Paul responded to this concern in his initial PR:
https://github.com/lampepfl/dotty/pull/16157#issuecomment-1355844388

**Comment by PaulCoral** [comment]
> Could you fix the conflicts? @PaulCoral

Yes, this seems OK to me.

(also I resolve conflict with `main` and it passes the test locally)

**Comment by smarter** [comment]
> Paul responded to this concern in his initial PR:

I'm still somewhat confused:
- you can pattern match on the tree in prepareOthers if you need to do different things on different trees, this doesn't require doing a traversal
- if you really need to do a full traversal, then maybe the phase should not be a mini phase and instead just do the traversal

**Comment by szymon-rd** [comment]
I agree that this is a bit confusing. But IMO it should land in another issue and PR.

**Comment by PaulCoral** [comment]
> > Paul responded to this concern in his initial PR:
> 
> I'm still somewhat confused:
> 
> * you can pattern match on the tree in prepareOthers if you need to do different things on different trees, this doesn't require doing a traversal
> * if you really need to do a full traversal, then maybe the phase should not be a mini phase and instead just do the traversal

The current design of the traversal may appear to be quite confusing and has been a subject of some debate. Here, the full traversal is needed as the `miniphase` does not traverse many type-related parts of the tree, and thus, the symbols are not registered, resulting in many false positives (e.g. an import used only as a type argument). The first design in #16157 was **using only** a `Traversers`. It was also decided that it could be useful to convert to `miniphase`, as in the future, some linter options could be added through other `miniphases`, resulting in a single tree traversal. Using a `TreeTraverser` avoids duplicating the code of the `foldOver` method in `Trees.scala`, and the traversals are usually very short (often only type parameter clauses).

> I agree that this is a bit confusing. But IMO it should land in another issue and PR.

I agree that it may not be optimal, a should maybe be discussed.

**Comment by smarter** [comment]
Thanks for the explanation. I think it would be helpful to add a pattern match on `tree` in `prepareForOther` to be explicit about the trees that end up here (similar to https://github.com/lampepfl/dotty/blob/b824375daa21f96b12ddbfa8ea98672adc3d2a1a/compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala#L165-L172).
Even if we end up doing the same thing for all trees, it would be helpful to understand what the code does exactly. But this doesn't have to be done in this PR of course.

**Comment by szymon-rd** [comment]
Merging it now.

**Pull request merged**
