### PR TITLE
Collective extensions is sensitive to EOF

### LINKED ISSUE #9374: Support multiline collective extensions in REPL
```scala
scala> extension (x: Int) def f =
     | 0
def extension_f(x: Int): Int

scala> extension (x: Int)
1 |extension (x: Int)
  |                  ^
  |                  Extension without extension methods

scala> extension (x: Int):                                                           
1 |extension (x: Int):
  |                   ^
  |                   Extension without extension methods

scala> extension (x: Int) {
1 |extension (x: Int) {
  |                    ^
  |                    `def` expected

scala> extension (x: Int) { def f = 0 }
def extension_f(x: Int): Int
```

### PR DESCRIPTION
**Pull request by som-snytt**
This allows REPL to input extensions.

Fixes #9374

### CODE REVIEW

**Comment by som-snytt** [comment]
Supersedes https://github.com/lampepfl/dotty/pull/13375

This just inlines the call to `extMethod` and checks EOF.

Review by @dos65

**Review by dos65 — APPROVED** [review]
LGTM!

**Comment by som-snytt** [comment]
Also verified that empty extension at EOF errors correctly.
```
5 |
  |^
  |Extension without extension methods
1 error found
```
I haven't written a line counting program since I was a teenager, though I did fix some line bugs in Scala 2's Position, but I see the error is reported on a line after the last line in the file. That is with a terminal EOL, so really the "last line" is merely empty and does not itself end in EOL.

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
Any reason for closing this, @som-snytt?

**Pull request closed without merging**
