### PR TITLE
Memoize: duplicate scala2 behaviour: don't create fields for final vals.

### PR DESCRIPTION
**Pull request by DarkDimius**
This affect initialisation order and we rely on artifacts of initialisation order in Dotty.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky your proposed code will perform transformation when `stats` are not idempotent. Is this intended?

**Comment by DarkDimius** [comment]
It is not yet ready for review. It fails the supposed test.

**Comment by odersky** [comment]
@darkdimius: No, notice the isPureExpr guard. That will do the right test.

**Comment by odersky** [comment]
Rebased to master and added fixes to make this work.

**Comment by odersky** [comment]
Also, applied my own earlier suggested patches.

**Pull request merged**
