### PR TITLE
Use `implicit` instead of `implied` for instance definitions

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
@nicolasstucki The timing of changing tasty libs to the new version was unfortunate. It was just before I had to change `implied` to `implicit`, after lengthy discussions and by popular request. Now the bootstrap breaks since `implied` is no longer supported. Can you please revert the changes in Tastylib for now? Once we have a new bootstrap compiler that supports instance definitions with `implicit` instead of `implied` we can re-apply the changes using the new syntax.

**Comment by odersky** [comment]
@nicolasstucki @smarter For the moment, we support `implicit` as well as `implied` for instance definitions, since otherwise the build would break. We have to move over all definitions in `src-3.x` to drop `implied` in favor of the new syntax. Since it's the first time we are doing this, it's worthwhile to work out a schema in detail. 

I guess each time we do an incompatible change that affects our own files we have to follow these steps:

 1. change the compiler to support new as well as old syntax. That's what this PR does.
 2. wait until the PR gets merged and becomes the new bootstrap compiler.
 3. change all files in library/src-3.x and compiler/src to use the new syntax.
 4. drop support for the old syntax from the compiler.

@smarter Can you confirm that src-3.x should indeed be compiled both by the bootstrapped compiler and the following stage compilers? That's what I am observing.

**Comment by smarter** [comment]
>  Can you confirm that src-3.x should indeed be compiled both by the bootstrapped compiler and the following stage compilers?

Yes, but we still have `src-non-bootstrapped` and `src-bootstrapped` to distinguish between the two, so the following procedure should work:

1. Change the compiler to replace the old syntax by the new syntax
2. Move all files in `src-3.x` that used the old syntax to `src-non-bootstrapped`
3. Copy these same files to `src-bootstrapped` with the new syntax
4. When we update the bootstrapped compiler, the files in `src-non-bootstrapped` can be deleted and the files in `src-bootstrapped` should be moved to `src-3.x`

**Comment by odersky** [comment]
@smarter That's much better. I'll give that a try.

**Comment by odersky** [comment]
@smarter It worked!

**Comment by odersky** [comment]
@nicolasstucki It depends whether you foresee changes in the next 4-6 weeks before the bootstrap compiler supports the new syntax. If yes, I agree it's better to revert to the old syntax. But on the other hand, this is a good test case to see whether our scheme to bootstrap with changes works.

**Comment by nicolasstucki** [comment]
Yes, I will modify the Matcher in the next couple of weeks. I may also have some changes for quoted.Type.

**Comment by odersky** [comment]
> Yes, I will modify the Matcher in the next couple of weeks. I may also have some changes for quoted.Type.

So we can leave `Liftable` and `IArray`?

**Comment by nicolasstucki** [comment]
Yes, those are fine

**Comment by odersky** [comment]
OK. Can you integrate these changes into this PR?

**Comment by nicolasstucki** [comment]
Will do

**Comment by odersky** [comment]
@nicolasstucki Your commits LGTM. I assume #6496 can be dropped now?

**Pull request closed without merging**
