### PR TITLE
.drone.yml: no need to publish the bridge anymore

### PR DESCRIPTION
**Pull request by smarter**
This is no longer necessary since de5d34ac365064f223290ee37aaa9dab81fc77e5

### CODE REVIEW

**Comment by smarter** [comment]
> If you haven't already, please request a review from one of our
collaborators (have no fear, we don't bite)!

I'm not sure if that's a great thing to ask newcomers, they have no idea who to ping for a review.

**Comment by felixmulder** [comment]
@smarter - AFAICT GitHub makes suggestions. But sure, how do we improve this?

**Comment by smarter** [comment]
@felixmulder You can only set the reviewer on a PR in Github if you're a member of the organization, so you won't see suggestions otherwise. I suggest not asking people to do anything, it's our job to decide who reviews what.

**Comment by felixmulder** [comment]
That sounds grrrr 8

PR welcomed.

**Pull request merged**
