### PR TITLE
Avoid NPE in simplify

### LINKED ISSUE #15272: Matchtype recursion crashes
## Compiler version

3.1.3-RC2

## Minimized code

```Scala
    sealed trait EdgeN[+NT]
    object EdgeN:
      case class Head[+NT, +From <: NT, +To <: NT]    (from: From, to: To ) extends EdgeN[NT]
      case class Cons[+NT, +From <: NT, +ToE <: EdgeN[NT]](from: From, to: ToE) extends EdgeN[NT]
      final type InNodesTupleOf[NT, E <: EdgeN[NT]] <: Tuple = E match
        case Cons[nt,from,toE] => from *: InNodesTupleOf[nt,toE]
        case Head[nt,from ,to] => from *: EmptyTuple
      def inNodesTuple[NT,E <: EdgeN[NT]](edge: E): InNodesTupleOf[NT,E] = edge match
        case e: Cons[nt,from,toE] => e.from *: inNodesTuple[nt,toE](e.to)
        case e: Head[nt,from,to] => e.from *: EmptyTuple
    end EdgeN
```

It's basically a non-empty-tuple ADT with an upper type bound for the elements (`NT`). 

## Output (click arrow to expand)

dotty crashes:

```scala
|| [error] java.lang.NullPointerException
|| [error] dotty.tools.dotc.core.TypeOps$.simplify(TypeOps.scala:148)
|| [error] dotty.tools.dotc.core.Types$Type.simplified(Types.scala:1890)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer$$anon$4.apply(TypeComparer.scala:2881)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer$$anon$4.apply(TypeComparer.scala:2879)
|| [error] dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy23$1(Types.scala:6013)
|| [error] dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$3(Types.scala:6013)
|| [error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6017)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer$$anon$4.apply(TypeComparer.scala:2884)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer$$anon$4.apply(TypeComparer.scala:2879)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer.matchCase$1(TypeComparer.scala:2918)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer.recur$2(TypeComparer.scala:2934)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer.op$proxy73$1(TypeComparer.scala:2964)
|| [error] dotty.tools.dotc.core.TrackingTypeComparer.matchCases(TypeComparer.scala:2965)
|| [error] dotty.tools.dotc.core.Types$MatchType.matchCases$1(Types.scala:4865)
|| [error] dotty.tools.dotc.core.Types$MatchType.reduced$$anonfun$1(Types.scala:4874)
|| [error] dotty.tools.dotc.core.TypeComparer.inSubComparer(TypeComparer.scala:2671)
|| [error] dotty.tools.dotc.core.TypeComparer.tracked(TypeComparer.scala:2681)
|| [error] dotty.tools.dotc.core.TypeComparer$.tracked(TypeComparer.scala:2837)
|| [error] dotty.tools.dotc.core.Types$MatchType.reduced(Types.scala:4874)
|| [error] dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:684)
|| [error] dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:390)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:378)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:189)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubApproxHi$1(TypeComparer.scala:1298)
|| [error] dotty.tools.dotc.core.TypeComparer.fallback$2$$anonfun$2(TypeComparer.scala:1160)
|| [error] scala.Function0.apply$mcZ$sp(Function0.scala:39)
|| [error] dotty.tools.dotc.core.TypeComparer.necessaryEither(TypeComparer.scala:1748)
|| [error] dotty.tools.dotc.core.TypeComparer.either(TypeComparer.scala:1604)
|| [error] dotty.tools.dotc.core.TypeComparer.fallback$2(TypeComparer.scala:1160)
|| [error] dotty.tools.dotc.core.TypeComparer.compareLower$1(TypeComparer.scala:1176)
|| [error] dotty.tools.dotc.core.TypeComparer.compareAppliedType2$1(TypeComparer.scala:1200)
|| [error] dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:559)
|| [error] dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:390)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:378)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:189)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:199)
|| [error] dotty.tools.dotc.core.TypeComparer.isSub(TypeComparer.scala:201)
|| [error] dotty.tools.dotc.core.ConstraintHandling.op$proxy2$1(ConstraintHandling.scala:405)
|| [error] dotty.tools.dotc.core.ConstraintHandling.isSubTypeWhenFrozen(ConstraintHandling.scala:405)
|| [error] dotty.tools.dotc.core.ConstraintHandling.isSubTypeWhenFrozen$(ConstraintHandling.scala:27)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubTypeWhenFrozen(TypeComparer.scala:30)
|| [error] dotty.tools.dotc.core.TypeComparer.compareTypeParamRef$1(TypeComparer.scala:406)
|| [error] dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:411)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:378)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:428)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:378)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:321)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:189)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:199)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubArg$1(TypeComparer.scala:1544)
|| [error] dotty.tools.dotc.core.TypeComparer.recurArgs$1(TypeComparer.scala:1546)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubArgs(TypeComparer.scala:1549)
|| [error] dotty.tools.dotc.core.TypeComparer.loop$1(TypeComparer.scala:1110)
|| [error] dotty.tools.dotc.core.TypeComparer.isMatchingApply$1(TypeComparer.scala:1125)
|| [error] dotty.tools.dotc.core.TypeComparer.compareAppliedType2$1(TypeComparer.scala:1195)
|| [error] dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:559)
|| [error] dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:492)
|| [error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:378)
|| [error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1323)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:189)
|| [error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:199)
|| [error] dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:126)
|| [error] dotty.tools.dotc.core.TypeComparer.necessarySubType(TypeComparer.scala:137)
|| [error] dotty.tools.dotc.core.TypeComparer$.necessarySubType(TypeComparer.scala:2737)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.necessarilyCompatible(ProtoTypes.scala:46)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.necessarilyCompatible$(ProtoTypes.scala:25)
|| [error] dotty.tools.dotc.typer.ProtoTypes$NoViewsAllowed$.necessarilyCompatible(ProtoTypes.scala:119)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult(ProtoTypes.scala:96)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult$(ProtoTypes.scala:25)
|| [error] dotty.tools.dotc.typer.ProtoTypes$NoViewsAllowed$.constrainResult(ProtoTypes.scala:119)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult(ProtoTypes.scala:113)
|| [error] dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult$(ProtoTypes.scala:25)
|| [error] dotty.tools.dotc.typer.ProtoTypes$NoViewsAllowed$.constrainResult(ProtoTypes.scala:119)
|| [error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:453)
|| [error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
|| [error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
|| [error] dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1065)
|| [error] dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
|| [error] dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:117)
|| [error] dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:911)
|| [error] dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:991)
|| [error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3104)
|| [error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1002)
|| [error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1040)
|| [error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
|| [error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
|| [error] dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2717)
|| [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2871)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
|| [error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1073)
|| [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2840)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
|| [error] dotty.tools.dotc.typer.Typer.caseRest$1(Typer.scala:1702)
|| [error] dotty.tools.dotc.typer.Typer.typedCase(Typer.scala:1718)
|| [error] dotty.tools.dotc.typer.Typer.$anonfun$24(Typer.scala:1630)
|| [error] scala.collection.immutable.List.map(List.scala:246)
|| [error] dotty.tools.dotc.typer.Typer.typedDependentMatchFinish(Typer.scala:1633)
|| [error] dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1594)
|| [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2846)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
|| [error] dotty.tools.dotc.typer.Typer.$anonfun$47(Typer.scala:2278)
|| [error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
|| [error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2278)
|| [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2808)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
|| [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
|| [error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2476)
|| [error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2820)
|| [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2824)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
|| [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
|| [error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1067)
|| [error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1071)
|| [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2840)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
|| [error] dotty.tools.dotc.typer.Typer.$anonfun$47(Typer.scala:2278)
|| [error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
|| [error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2278)
|| [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2808)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
|| [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
|| [error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2476)
|| [error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2820)
|| [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2824)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
|| [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
|| [error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2603)
|| [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2865)
|| [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
|| [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
|| [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
|| [error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:43)
|| [error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:50)
|| [error] scala.Function0.apply$mcV$sp(Function0.scala:39)
|| [error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:414)
|| [error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:50)
|| [error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:84)
|| [error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
|| [error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
|| [error] scala.collection.immutable.List.foreach(List.scala:333)
|| [error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:84)
|| [error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:225)
|| [error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
|| [error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
|| [error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
|| [error] dotty.tools.dotc.Run.runPhases$1(Run.scala:236)
|| [error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:244)
|| [error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:253)
|| [error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
|| [error] dotty.tools.dotc.Run.compileUnits(Run.scala:253)
|| [error] dotty.tools.dotc.Run.compileSources(Run.scala:186)
|| [error] dotty.tools.dotc.Run.compile(Run.scala:170)
|| [error] dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
|| [error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
|| [error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
|| [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
|| [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
|| [error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
|| [error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
|| [error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
|| [error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
|| [error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
|| [error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
|| [error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
|| [error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
|| [error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
|| [error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
|| [error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
|| [error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
|| [error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
|| [error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
|| [error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2346)
|| [error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2303)
|| [error] sbt.internal.io.Retry$.apply(Retry.scala:46)
|| [error] sbt.internal.io.Retry$.apply(Retry.scala:28)
|| [error] sbt.internal.io.Retry$.apply(Retry.scala:23)
|| [error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
|| [error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2299)
|| [error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
|| [error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
|| [error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
|| [error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
|| [error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
|| [error] sbt.Execute.work(Execute.scala:291)
|| [error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
|| [error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
|| [error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
|| [error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
|| [error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
|| [error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
|| [error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
|| [error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

```
</details>

### PR DESCRIPTION
**Pull request by odersky**
Fixes #15272

There's no crash anymore, but #15272 still does not compile.

### CODE REVIEW

**Comment by odersky** [comment]
It's a bit troubling that this NPE occurred even with explicit null checking. I believe the root of the matter is that `entries` in `OrderingConstraing` is an `Array[Type]`, but the array is only partially filled. The uninitialized elements are `null`. Is there a good way to check for this hole?

**Comment by noti0na1** [comment]
It seems the correct type for `ArrayValuedMap[T]` is `SimpleIdentityMap[TypeLambda, Array[T | Null]]`.

I think the correct to create Array is:
* only create nullable array (`Array[T | Null]`) if there is no initial value
* generate non-nullable array (`Array[T]`) if the initial values or default value generator (`Int => T`) is provided
* provide a transform function from `Array[T | Null]` to `Array[T]` by checking every element not equal to null
* and a unchecked version of transform function using `.asInstanceOf[Array[T]]` directly

But it's hard to do these without changing the standard library

**Comment by olhotak** [comment]
The solution we had in mind way back when @abeln was working on explicit nulls was the following. I was sure we wrote it down somewhere but now I cannot find it:

1. Use `Array[T|Null]` for arrays that can contain some uninitialized elements, and `Array[T]` (where `T` non-nullable) only in cases where we know that all elements of the array are initialized (with non-null values).
2. Add an `Array.ofNulls[T](n: Int): Array[T|Null]` method that constructs an array of null values of a given size.
3. `Array.apply` and `Array.fill` can still return non-nullable arrays because all the elements are provided at creation time, so don't have to be left null.
4. Deprecate `new Array(n: Int)` in favour of point 2. above.

In this case, line 274 of OrderingConstraint.scala does:
```scala
    val entries1 = new Array[Type](nparams * 2)
```
This uses the to-be-deprecated point 4.

We can't do the deprecation without changing the standard library, but perhaps we could already implement 2. in Dotty itself, and modify existing code to avoid the to-be-deprecated point 4., to see how the resulting code looks. Specifically in this case, `entries` would have type `Array[Type|Null]` rather than just `Array[Type]`.

**Comment by olhotak** [comment]
Looking at this again, it's not clear to me whether the `entries` array is **intended** to contain null elements or whether the fact that it contains a null element is itself a bug in the logic.

If the former, its type should be `Array[Type|Null]`. If the latter, its type `Array[Type]` is correct, but then we need to determine how that `null` got in there.

**Comment by odersky** [comment]
The `entries` array can contain nulls in the second half where TypeVars are stored (or not).

**Comment by olhotak** [comment]
OK. In that case, if we wanted to be safe here, we could make an opaque type for the ParamBounds arrays that returns non-nulls from the first half and nullable typeVars from the second half. But I looked into doing that and I don't think it's worth the complexity: in particular, it would mess up the `ConstraintLens` code that expects an array.

So I think we should just merge this as is.

**Review by olhotak — APPROVED** [review]

**Pull request merged**
