### PR TITLE
Non-parametric derived instances now lazy vals

### PR DESCRIPTION
**Pull request by milessabin**
Currently all derived instances would be compiled as given defs, which have caching logic added, where possible, in `CacheAliasImplicits`. These caches are unsynchronized, which is a reasonable default in circumstances where the programmer has the option to manually insert a lazy val or some other form of synchronization.

That option isn't available for derived instances, however, because these givens aren't written explicitly. In this case the more appropriate default is to compile non-parametric derived instances as given lazy vals.

This PR makes that change. Unfortunately the tests aren't all that convincing because an identity test isn't sufficient to distinguish between a lazy val and a def with unsynchronized caching logic. Suggestions for a better approach to the test would be very welcome.

### CODE REVIEW

**Comment by milessabin** [comment]
@odersky this is ready for review now.

**Comment by odersky** [comment]
Is there an urgency to merge this now? We might decide to use lazy vals everywhere (see thread in #6909) in which case this change would be redundant. 

If it's not urgent, then maybe we can discuss #6909 next Monday and then decide what to do.

**Comment by milessabin** [comment]
@odersky I can definitely wait until we've had a chance to discuss #6909.

**Comment by odersky** [comment]
If #7006 gets in, this PR will no longer be necessary.

**Comment by milessabin** [comment]
Happy to close this one :-)

**Pull request closed without merging**
