### PR TITLE
Run CI-partest with bootstrapped compiler

### PR DESCRIPTION
**Pull request by DarkDimius**
I'm doing dirty classpath tricks to make partest prefer dotty-compiled-dotty over scalac-compiled-dotty.

### CODE REVIEW

**Comment by odersky** [comment]
I see a compilation failed on "pos/HelloWorld_v1.scala".

**Comment by DarkDimius** [comment]
> I see a compilation failed on "pos/HelloWorld_v1.scala".


https://scala-ci.typesafe.com/job/dotty-master-validate-partest/509/consoleFull

> [info] ok   6 - pos/HelloWorld_v1.scala                 

Do you have a  local failure?

**Comment by DarkDimius** [comment]
failures are 
>[error] creating stub for StringBuffer, owner = module class lang#1403, file = null

>[error] creating stub for Throwable, owner = module class lang#18930, file = null

**Comment by DarkDimius** [comment]
@odersky please review.

**Pull request merged**
