### PR TITLE
Topic/syntax spec docs

### PR DESCRIPTION
**Pull request by b-studios**
This PR ports the syntax spec from this [tex document](https://github.com/lampepfl/dotty/blob/master/docs/syntax-summary.txt) to Markdown and fixes a couple of typos and minor bugs.

@smarter What do you think?

### CODE REVIEW

**Comment by b-studios** [comment]
I purposfully reengineered the history to make it possible to review the changes. Of course I will squash the commits later to eventually merge.

**Comment by b-studios** [comment]
The two changes that might require reviewing are bac774d and cdc4442.

**Comment by smarter** [comment]
Awesome! You should also add a link to it from https://github.com/lampepfl/dotty/blob/master/docs/docs/index.md, also the tex version should be deleted to avoid duplication.

**Comment by smarter** [comment]
> The two changes that might require reviewing are bac774d and cdc4442.

@odersky, could you have a look please?

**Comment by b-studios** [comment]
Ah, one thing I was not sure about: I deleted the tree annotations that can be found in the tex version, like
```diff
-|  Refinement                                             RefinedTypeTree(EmptyTree, refinement)
+|  Refinement
```

Not sure, whether you want to keep them.

**Comment by odersky** [comment]
Looks great. Definitely better to have this in markdown. 

I would leave the tree annotations in this version of the document, though. The reason is that they give us a good overview what parsed constructs map into. When we export the document to a language spec, they would be removed, of course.

**Comment by odersky** [comment]
LGTM, Thanks!

**Pull request merged**
