### PR TITLE
Normalize slashes in paths in TASTy binaries

### PR DESCRIPTION
**Pull request by abgruszecki**
[test_windows_full]

### CODE REVIEW

**Comment by abgruszecki** [comment]
@liufengyun Asking since you were involved with similar PRs, also involving Windows. It seems like `cmdTests` are not run on Windows. This PR ensures that we always use `/` to separate path elements in TASTy binary files, can you think of any way of testing that on Windows?

**Comment by abgruszecki** [comment]
@bishabosha since you worked around TASTy reader, are there any tests for it that get ran on Windows?

**Comment by bishabosha** [comment]
@abgruszecki One way i normalised paths was in ExtractSemanticDB where the path is converted to javas URI

**Comment by abgruszecki** [comment]
@nicolasstucki Should we mention somewhere that the paths in tasty binaries always use forward slashes?

**Comment by nicolasstucki** [comment]
Documentation for this is a good idea. 
* Can we add it to the `TastyFromat`?
* We should also add it in thee reflection API
* It would be good to repeat it in the method that normalizes the path to make sure the next person that modifies it knows about this.

**Comment by liufengyun** [comment]
> @liufengyun Asking since you were involved with similar PRs, also involving Windows. It seems like `cmdTests` are not run on Windows. This PR ensures that we always use `/` to separate path elements in TASTy binary files, can you think of any way of testing that on Windows?

Yes, `cmdTests` only run on Linux machines. Currently, we don't have scripts that run on Windows. A possibility would be to create a macro test, and print the relative path of a symbol.

**Comment by abgruszecki** [comment]
@nicolasstucki where should we modify `TastyFormat`?

**Comment by abgruszecki** [comment]
And yes, I'll also modify the Quotes API.

**Review by nicolasstucki — APPROVED** [review]

**Pull request merged**
