### PR TITLE
Fix #5441: Primitive operations on Long with Float argument have different semantics from Java

### LINKED ISSUE #5441: Primitive operations on Long with Float argument have different semantics from Java
Scala 2's primitive binary operations on Long that take Float (e.g. `(x: Long) % (y: Float)`) as an argument erroneously perform an operation in double precision, instead of float precision. This is inconsistent wrt Java semantics. Given that dotty reuses Scala 2's backend I expect it to have the same issue. 

More details on reproduction here: https://github.com/scala/bug/issues/11253

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Comment by smarter** [comment]
It looks like the corresponding patch in scalac is slightly different: https://github.com/scala/scala/pull/7435/files, any reason to do things differently? If not it'd be good to do the same thing they do to keep the diff between the two backent as small as possible.

**Comment by prolativ** [comment]
@smarter there were a few comments to the original PR that were not taken into account because the PR got merged too early by accident so I introduced the requested changes here

**Comment by smarter** [comment]
I see, but if the code is equivalent I would prefer going with the scalac version, just so that when we diff the two we don't get confused about why there's a difference here (alternatively we could update both the dotty and scalac and backend at the same time, but it doesn't seem worth it if the code is equivalent anyway).

**Comment by prolativ** [comment]
OK, using the implementation from scala repo

**Review by smarter — APPROVED** [review]
Thanks!

**Pull request merged**
