### PR TITLE
Upgrade ASM to 6.0, fix bug with very large methods

### PR DESCRIPTION
**Pull request by smarter**
Adapted from https://github.com/scala/scala/pull/6180 by Lukas Rytz, the
test case demonstrates that https://github.com/scala/bug/issues/10594 is fixed.

### CODE REVIEW

**Comment by smarter** [comment]
@allanrenucci Could you take care of upgrade the CI cache please?

**Comment by smarter** [comment]
CI failed because of a timeout, maybe because it was overloaded (http://tresormon.epfl.ch/munin/epfl.ch/lampsrv9.epfl.ch/cpu.html), I'll rerun it.

**Comment by smarter** [comment]
Hah, I see. The issue is that dotty simplifier tries really hard to optimize the added testcase :).

**Comment by NALLELUNA** [comment]
> Adapted from [scala/scala#6180](https://github.com/scala/scala/pull/6180) by Lukas Rytz, the test case demonstrates that [scala/bug#10594](https://github.com/scala/bug/issues/10594) is fixed.

**Pull request merged**
