### PR TITLE
Remove indirection of IArray operations

### PR DESCRIPTION
**Pull request by nicolasstucki**
Part of #11298

### CODE REVIEW

**Comment by odersky** [comment]
It would be good to do some micro-benchmarks about performance of array operations vs IArray operations. Ideally the performance should be the same after warmup. We should test direct access with `apply` as well as common collection operations such as `map`, `flatMap`, `filter`, `foldLeft`. And we should test with elements of both primitive and reference types.

**Comment by nicolasstucki** [comment]
This change will not really help with performance. It only makes the module initialization a bit sorter. 

Both #11319 and #11329 take advantage of this change on a semantic level as it prioritizes these extension methods over implicit conversion.

**Comment by nicolasstucki** [comment]
This also removes the indirection on the docs

**Comment by nicolasstucki** [comment]
This is mos

**Pull request closed without merging**
