### PR TITLE
Faster base class sets

### PR DESCRIPTION
**Pull request by odersky**
Speed up construction and testing of base class sets.
Use a linear search with automatic bubbling up of
hits.

### CODE REVIEW

**Comment by odersky** [comment]
@DarkDimius, since you suggested the scheme, do you want to review it?

**Comment by DarkDimius** [comment]
Yes, gladly. Did you already do any measurements?

**Comment by odersky** [comment]
I did not do any measurements yet. Jason did a similar change for scalac (minus the bubbling up part) and it gained them some speed there.

**Comment by DarkDimius** [comment]
@biboudis @olafurpg , are the nightly benchmarks up? This PR is a good opportunity to test their sensitivity

**Comment by retronym** [comment]
My hypothesis in scalac was that (part?) of the speedup was due to forcing fewer basetypeseqs, which we had to do to compute their length, part of the ordering criteria in the binary search. Here are some numbers measured before and after: https://github.com/scala/scala/pull/5829

https://github.com/scala/scala/pull/5829

**Comment by olafurpg** [comment]
@DarkDimius I am helping @biboudis setup/manage the benchmark infrastructure. The benchmarks currently run an old 0.1-bin version, fix pending in https://github.com/lampepfl/dotty/pull/2690

**Pull request merged**
