### PR TITLE
Set reference version to 3.1.3-RC2

### PR DESCRIPTION
**Pull request by Kordyjan**

### CODE REVIEW

**Comment by Kordyjan** [comment]
We have an incident: https://github.com/lampepfl/dotty/issues/14938

**Comment by sjrd** [comment]
Does that mean we need to re-re-revert https://github.com/lampepfl/dotty/pull/14929 ?

**Comment by Kordyjan** [comment]
> Does that mean we need to re-re-revert #14929 ?

Nah. It's good. The `baseVersion` is already 3.2.0-RC1.

On the other hand, this reminded me that I need to re-revert https://github.com/lampepfl/dotty/pull/14067.

**Review by romanowski — APPROVED** [review]

**Comment by dwijnand** [comment]
> On the other hand, this reminded me that I need to re-revert #14067.

https://github.com/lampepfl/dotty/issues/14737

**Pull request merged**
