### PR TITLE
Add regression test for #19087

### PR DESCRIPTION
**Pull request by mbovel**

### CODE REVIEW

**Comment by sjrd** [comment]
If it actually passes as a `pos` test, we have another bug :sweat_smile:. This should be a `neg` test with an appropriate check file.

**Comment by mbovel** [comment]
> If it actually passes as a `pos` test, we have another bug 😅. This should be a `neg` test with an appropriate check file.

Oops, fixed 😅

**Comment by mbovel** [comment]
`community_build_a` failed for something unrelated: `Error: Process completed with exit code 137.`; re-running it.

**Comment by lrytz** [comment]
Many recent PRs failed with this message

**Comment by hamzaremmal** [comment]
I've actually checked this with Fabien on Friday. On the runner's log, it looks like the OS killed the process because of an "Out-of-Memory" error.

**Review by sjrd — APPROVED** [review]

**Pull request merged**
