### PR TITLE
Use indentation to control newline insertion before parentheses

### LINKED ISSUE #7559: Drop Local Blocks
Scala allows local blocks as in

```scala
def foo(x: Int) = {
  val y = x

  { val z = y * y
    println(x)
  }
  y -1 
}
```
This is dangerous, as it only works if there is an empty line in front of the local block. Dropping the empty line can give obscure type errors or even change the meaning of the program since then the block is treated as an argument to a function on the preceding line.

Scala already has `locally` in `Predef`. The example above is better written like this:
```scala
def foo(x: Int) = {
  val y = x
  locally { 
    val z = y * y
    println(x)
  }
  y -1 
}
```
I believe Scala 3 should mandate `locally` and not allow naked local blocks. Changing this would entail:

 - Make local blocks a deprecation warning under -language:Scala2Compat and an error otherwise (using the `errorOrMigrationWarning` in `dotc`).
 - Add a rewrite rule to insert the `locally`.
 - Fix tests and community build to always use `locally`
 - Add a page in the reference section of the Dotty docs that the feature has been dropped.

It would be good to get this in by feature freeze at the end of this release cycle. If there's a volunteer I am happy to review.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #7559

Scala currently uses an ad-hoc set of rules to determine whether a line
starting with an opening `(`, `[`, or `{` is an argument to the previous
line or starts a new statement. Specifically, a new line is always
inserted but is then skipped at some places (which include applications)
if the next token is a `{`. On the other hand, lines starting with `[` and `(` 
always start a new statement. This leads to the gotchas that
```
val x= foo
{ ... }
```
treats the braces as an argument to `foo`. A blank line is required to avoid this.
On the other hand,
```
foo(arg1)
  (arg2)
  (arg3)
```
does not work; the following lines are interpreted as separate statements.

In this PR, indentation is used instead to determine whether a following line starting
with `(`, `[`, or `{` is an argument or a separate statement. In the first example, it
is a separate statement, since it is not indented. In the second example, it is treated
as an argument, since it is indented.

If we are past a blank line, we always assume the newline. For instance, this
example from Pouring.scala works:
```scala
  val moves =
    val glasses = 0 until capacity.length

       (for g <- glasses yield Move.Empty(g))
    ++ (for g <- glasses yield Move.Fill(g))
    ++ (for g1 <- glasses; g2 <- glasses if g1 != g2 yield Move.Pour(g1, g2))
```
Without the blank line, the `(for g <- ...` expression would be treated as an additional
argument to `capacity.length`.

### CODE REVIEW

**Comment by sjrd** [comment]
The whole point of allowing, and *parsing*, new lines at these positions is to allow the following style, inherited from Java:
```scala
class Foo
{
  val x: Int = 5
}

def bar(): Int =
{
  val x = ...
  x
}

xs.foreach
{ x =>
  println(x)
}
```
If indentation is to decide that the above braces create a new statement, then we might as well *always* create a new statement for `{`, and *never* for `(`.

But that's going to break every single codebase written in that style.

**Comment by odersky** [comment]
The first two of these continue to work:
```scala
class Foo
{
  val x: Int = 5
}
```
works since we skip the inserted newline when a template can follow.
```scala
def bar(): Int =
{
  val x = ...
  x
}
```
works since `=` cannot terminate a statement, so we do not insert a newline.

The last example does not work anymore. 
```scala
xs.foreach
{ x =>
  println(x)
}
```
is parsed as two statements, not one. But I have never seen this in practice. On the other hand, I have seen many cases where somebody was bitten by code like this:
```scala
val x = 1
{ println(x); x * x }
```

**Comment by smarter** [comment]
> is parsed as two statements, not one. 

Can we warn about this in Scala 2 mode ?

**Comment by odersky** [comment]
> Can we warn about this in Scala 2 mode ?

I think we could.

**Comment by AleksanderBG** [comment]
@martin do I understand correctly that merging this will resolve #7559? Asking for book-keeping reasons.

**Comment by sjrd** [comment]
What about
```Scala
val x =
  someTest &&
  {
    val xyz = ...
    xyz.whatever
  }
```
I often use this style for complex boolean expressions.

**Comment by odersky** [comment]
@AleksanderBG yes, I added a fix comment.
@sjrd That's not a problem since newlines after trailing infix operators are skipped. I added your example as a test to make this clear.

**Comment by odersky** [comment]
Should we merge this now?

**Comment by anatoliykmetyuk** [comment]
@smarter what's the status of this one? Is it mandatory for the release? Who's reviewing it?

**Pull request merged**
