### PR TITLE
Remove irrefutable match pattern

### LINKED ISSUE #10614: Usage of `@unchecked` annotation with `val` is inconsistent between Scala 2 and 3
in Scala 2, one annotates the scrutinee:

```scala
scala 2.13.4> val Some(x) = Option(3)
                                  ^
              warning: match may not be exhaustive.
              It would fail on the following input: None
val x: Int = 3

scala 2.13.4> val Some(x) = Option(3): @unchecked
val x: Int = 3
```

whereas in Scala 3.0.0-M2 under `-source:3.1` one must annotate the pattern, while annotating the scrutinee is ignored:

```scala
scala> val Some(x) = Option(3)
1 |val Some(x) = Option(3)
  |    ^^^^^^^
  |pattern's type Some[Int] is more specialized than the right hand side expression's type Option[Int]
  |
  |If the narrowing is intentional, this can be communicated by writing `: @unchecked` after the full pattern.

scala> val Some(x) = Option(3): @unchecked                                                                              
1 |val Some(x) = Option(3): @unchecked
  |    ^^^^^^^
  |pattern's type Some[Int] is more specialized than the right hand side expression's type Option[Int] @unchecked
  |
  |If the narrowing is intentional, this can be communicated by writing `: @unchecked` after the full pattern.

scala> val Some(x): @unchecked = Option(3)
val x: Int = 3
```

Scala 3's behavior is as documented at https://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html :

> Sometimes one wants to decompose data anyway, even though the pattern is refutable. For instance, if at some point one knows that a list `elems` is non-empty one might want to decompose it like this:
> 
> ```scala
> val first :: rest = elems   // error
> ```
> 
> This works in Scala 2. In fact it is a typical use case for Scala 2's rules. But in Scala 3.1 it will give a type error. One can avoid the error by marking the pattern with an @unchecked annotation:
> 
> ```scala
> val first :: rest : @unchecked = elems   // OK
> ```
> 
> This will make the compiler accept the pattern binding. It might give an error at runtime instead, if the underlying assumption that `elems` can never be empty is wrong.

but I suggest that Scala 3 should adopt the Scala 2 convention, because:

* it is more consistent with `match`; one also annotates the scrutinee with `match`, like `(foo: @unchecked) match ...`
* we want to support cross-building between 2 and 3, and 2's style is the established precedent

(this came up at https://github.com/scala/bug/issues/12245)

This became more important with the release of Scala 2.13.4, where improved exhaustivity checking has sent many users scurrying to add `@unchecked` to their matches.

### PR DESCRIPTION
**Pull request by changvvb**
Fixes #10614
Remove irrefutable match pattern, so that scala3 has the same behavior as scala2.

### CODE REVIEW

**Review by liufengyun — COMMENTED** [review]
Thanks @changvvb 👍 

Instead of removing the tests, can we adapt them?

**Comment by b-studios** [comment]
Great, thanks @changvvb ! Could you maybe also adjust the [docs](http://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html) ([Sources](https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/changed-features/pattern-bindings.md)) accordingly.

**Comment by changvvb** [comment]
> Thanks @changvvb 👍
> 
> Instead of removing the tests, can we adapt them?

I thought they are meaningless because almost all of these tests commented by `// error` are compiled successfully. 
Deleting these tests is really too rough. I try to inspect them.

**Comment by liufengyun** [comment]
> > Thanks @changvvb 👍
> > Instead of removing the tests, can we adapt them?
> 
> I thought they are meaningless because almost all of these tests commented by `// error` are compiled successfully.
> Deleting these tests is really too rough. I try to inspect them.

Fair enough. I thought Scala 2.13.4 issues a warning for the code below and we need to do the same as well:

``` scala
scala > val Some(x) = Option(3)
```

But it does not.

**Comment by changvvb** [comment]
> Fair enough. I thought Scala 2.13.4 issues a warning for the code below and we need to do the same as well:
> 
> ```scala
> scala > val Some(x) = Option(3)
> ```
> 
> But it does not.

I tried to compile `val Some(x) = Option(3)` both on scala 2.13.4 and scala 3, but no warning appeared.
On the other hand, they both show warning with `Option(3) match { case Some(x) => x }`

**Comment by liufengyun** [comment]
> > Fair enough. I thought Scala 2.13.4 issues a warning for the code below and we need to do the same as well:
> > ```scala
> > scala > val Some(x) = Option(3)
> > ```
> > 
> > 
> > But it does not.
> 
> I tried to compile `val Some(x) = Option(3)` both on scala 2.13.4 and scala 3, but no warning appeared.
> On the other hand, they both show warning with `Option(3) match { case Some(x) => x }`

Yes, I got the same result. Then it's fine to remove them. Could you please rebase and update the docs, as suggested by @b-studios ?

**Comment by changvvb** [comment]
@b-studios @liufengyun 
http://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html introduce `case` for `for` expressions
> This code gives a compile-time error in Scala 3.1 whereas in Scala 2 the list elems is filtered to retain only the elements of tuple type that match the pattern (x, y). The filtering functionality can be obtained in Scala 3 by prefixing the pattern with case:
> `  for (case (x, y) <- elems) yield (y, x)  // returns List((2, 1), (4, 3))`

and
 
> `Generator      ::=  [‘case’] Pattern1 ‘<-’ Expr`

Now, is it necessary to retain it?

**Comment by liufengyun** [comment]
> @b-studios @liufengyun
> http://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html introduce `case` for `for` expressions
> 
> > This code gives a compile-time error in Scala 3.1 whereas in Scala 2 the list elems is filtered to retain only the elements of tuple type that match the pattern (x, y). The filtering functionality can be obtained in Scala 3 by prefixing the pattern with case:
> > `  for (case (x, y) <- elems) yield (y, x)  // returns List((2, 1), (4, 3))`
> 
> and
> 
> > `Generator      ::=  [‘case’] Pattern1 ‘<-’ Expr`
> 
> Now, is it necessary to retain it?

I think it's worthwhile to keep it and make sure it works.

**Comment by liufengyun** [comment]
@changvvb Thanks for your PR. We need to meet a deadline tomorrow, therefore I made a new PR #10793 .

**Comment by changvvb** [comment]
> @changvvb Thanks for your PR. We need to meet a deadline tomorrow, therefore I made a new PR #10793 .

OK, I will close this PR.
I see they are different implements while #10793 drop `Pattern2 [‘:’ Type | Ascription] ‘=’ Expr` syntax but keep irrefutable match pattern in Scala 3.

**Pull request closed without merging**
