### PR TITLE
Implement most of the Scala.js IR code generator.

### PR DESCRIPTION
**Pull request by sjrd**
Notable things that are missing at this point:

* Pattern matching
* Try
* Scala.js-defined JS classes
* JavaScript exports

Otherwise, the code generator is pretty complete. It is able to correctly compile and link a modified version of the Reversi demo (modified not to use any pattern matching).

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @DarkDimius

**Comment by sjrd** [comment]
Addressed @smarter's comments from https://github.com/sjrd/dotty/commit/d5a637deabc24f41c610fafc5c592acf9404f5a9

**Comment by DarkDimius** [comment]
>  1,297 additions, 66 deletions not shown because the diff is too large. Please use a local Git client to view these changes. 

@sjrd I'd be glad to review. But would you please break the  94bc01a commit apart to make GitHub show the diff?

**Comment by sjrd** [comment]
@DarkDimius Done. I separated the JS interop stuff in a separate commit. Now each commit shows a correct diff. If you want I can even remove the JS interop commit from this PR, and bring it back in a follow up PR. As you prefer.

**Comment by DarkDimius** [comment]
Otherwise LGTM

**Comment by sjrd** [comment]
@DarkDimius Updated. I declared caches for the phases, and I added more documentation explaining what you commented on.

**Pull request merged**
