### PR TITLE
Fix support for project with no sources

### PR DESCRIPTION
**Pull request by romanowski**
[test_sbt]

### CODE REVIEW

**Review by smarter — APPROVED** [review]
You can also bump sbt-dotty to 0.5.1 in https://github.com/lampepfl/dotty/blob/75365ead70a2ca3a39b0b351c0e80889c5e48ab3/project/Build.scala#L59, then I can do a release by pushing a tag.

**Comment by abgruszecki** [comment]
Do I understand correctly that the `doc` task which is supposed to have no sources is `test:doc`, and `doc` is just a sanity check? If yes, this LGTM.

**Comment by romanowski** [comment]
> Do I understand correctly that the doc task which is supposed to have no sources is test:doc, and doc is just a sanity check? If yes, this LGTM.

The problem is that we need to adda fake scala file to workaround check in sbt that does not run doc if there is no scala file in `sources`. However when we add a fake file to sources where there is no provided then we just trigger `doc` just to fail on no tasty files provided (we filter out the fake file before). 

Community build does not catch this problem since either projects has no publish set for docs or no sourcse in `Test/doc` and metals tries to publish empty test scope as a part of its CI

**Comment by romanowski** [comment]
@smarter version is bumped

**Comment by abgruszecki** [comment]
Ok, my bad, let me be more precise, I'm asking what exactly is testing that the issue will not reoccur. The newly-added test project has a single source in `src` and runs `doc` and `test:doc`. The fact that `doc` runs is just a sanity check, and the part that actually tests that `doc` doesn't fail with no sources is `test:doc`, is that correct?

**Comment by abgruszecki** [comment]
Also, it seems that `Dotty CI / test` is stuck on "Checkout cleanup script", which is a bit strange.

**Comment by romanowski** [comment]
> The fact that doc runs is just a sanity check, and the part that actually tests that doc doesn't fail with no sources is test:doc, is that correct?

Yes. You try youself that before the fix `test:doc` would fail.

**Pull request merged**
