### PR TITLE
restore position offset in DelegatingReporter

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by felixmulder** [comment]
IIRC this was intentionally removed so that the output to sbt would be identical to that of dotc. Could you provide some verification of this?

**Comment by odersky** [comment]
What's the status here?

**Comment by MasseGuillaume** [comment]
@felixmulder 

```
 bin/dotc sbt-bridge/sbt-test/compilerReporter/simple/Source.scala 
-- [E006] Unbound Identifier Error: sbt-bridge/sbt-test/compilerReporter/simple/Source.scala 
9 |  val a = er1
  |          ^^^
  |          not found: er1

longer explanation available when compiling with `-explain`

one error found
```

```
[E006] Unbound Identifier Error: /tmp/sbt_e825e0d4/simple/Source.scala ------
[info] 9 |  val a = er1
[info]   |          ^^^
[info]   |          not found: er1)
```

The output look the same.

**Comment by felixmulder** [comment]
I'll take your word for it @MasseGuillaume! (=

**Pull request merged**
