### PR TITLE
use File.pathSeparator for classpath in genDocs

### PR DESCRIPTION
**Pull request by robstoll**
- uses File.pathSeparator instead of hard-coded path separator `:`
  in genDocs => this way Windows user can run the command as well

### CODE REVIEW

**Comment by smarter** [comment]
There are other use of ":" in Build.scala, would you mind fixing them too?

**Comment by robstoll** [comment]
@smarter Might be that the following should be fixed as well but could be done in a separate pull request if needed:
https://github.com/lampepfl/dotty/blob/e9b5a976a6931b13f2fd330a9e724dea764ae7bb/compiler/src/dotty/tools/dotc/fromtasty/Debug.scala#L68

https://github.com/lampepfl/dotty/blob/e9b5a976a6931b13f2fd330a9e724dea764ae7bb/doc-tool/test/GenDocs.scala#L26

**Comment by robstoll** [comment]
An improvement would be to reduce code duplication between genDocs and dottydoc, lines 366-370 and 388-391 are the same. This is my first encounter with sbt and I don't know how to move code into an own function without encountering the error that I cannot access `value` outside of a task macro definition.
Would be great if someone could do that (surely an easy task) so that I know how to do it next time :)

**Comment by allanrenucci** [comment]
> Would be great if someone could do that (surely an easy task) so that I know how to do it next time :)

Probably something like this:
```patch
diff --git a/project/Build.scala b/project/Build.scala
index 4d7f1ad1d..05731a00b 100644
--- a/project/Build.scala
+++ b/project/Build.scala
@@ -345,6 +345,8 @@ object Build {
       javacOptions in (Compile, doc) --= Seq("-Xlint:unchecked", "-Xlint:deprecation")
     )
 
+  lazy val dottydocClasspath = taskKey[String]("Dottydoc classpath")
+
   // Settings shared between dotty-doc and dotty-doc-bootstrapped
   lazy val dottyDocSettings = Seq(
     baseDirectory in (Compile, run) := baseDirectory.value / "..",
@@ -358,15 +360,19 @@ object Build {
     fork in Test := true,
     parallelExecution in Test := false,
 
+    dottydocClasspath := {
+      val dottyLib = (packageAll in `dotty-compiler`).value("dotty-library")
+      val dottyInterfaces = (packageAll in `dotty-compiler`).value("dotty-interfaces")
+      val otherDeps = (dependencyClasspath in Compile).value.map(_.data).mkString(File.pathSeparator)
+      dottyLib + File.pathSeparator + dottyInterfaces + File.pathSeparator + otherDeps
+    },
+
     genDocs := Def.taskDyn {
       // Make majorVersion available at dotty.epfl.ch/versions/latest-nightly-base
       // Used by sbt-dotty to resolve the latest nightly
       val majorVersion = baseVersion.take(baseVersion.lastIndexOf('.'))
       IO.write(file("./docs/_site/versions/latest-nightly-base"), majorVersion)
 
-      val dottyLib = (packageAll in `dotty-compiler`).value("dotty-library")
-      val dottyInterfaces = (packageAll in `dotty-compiler`).value("dotty-interfaces")
-      val otherDeps = (dependencyClasspath in Compile).value.map(_.data).mkString(":")
       val sources =
         (unmanagedSources in (Compile, compile)).value ++
           (unmanagedSources in (`dotty-compiler`, Compile)).value
@@ -375,7 +381,7 @@ object Build {
         "-project", "Dotty",
         "-project-version", dottyVersion,
         "-project-url", dottyGithubUrl,
-        "-classpath", s"$dottyLib:$dottyInterfaces:$otherDeps"
+        "-classpath", dottydocClasspath.value
       )
       (runMain in Compile).toTask(
         s""" dotty.tools.dottydoc.Main ${args.mkString(" ")} ${sources.mkString(" ")}"""
@@ -384,10 +390,7 @@ object Build {
 
     dottydoc := Def.inputTaskDyn {
       val args: Seq[String] = spaceDelimited("<arg>").parsed
-      val dottyLib = (packageAll in `dotty-compiler`).value("dotty-library")
-      val dottyInterfaces = (packageAll in `dotty-compiler`).value("dotty-interfaces")
-      val otherDeps = (dependencyClasspath in Compile).value.map(_.data).mkString(":")
-      val cp: Seq[String] = Seq("-classpath", s"$dottyLib:$dottyInterfaces:$otherDeps")
+      val cp: Seq[String] = Seq("-classpath", dottydocClasspath.value)
         (runMain in Compile).toTask(s""" dotty.tools.dottydoc.Main ${cp.mkString(" ")} """ + args.mkString(" "))
```

**Comment by robstoll** [comment]
I have rebased the branch and made the improvement accordingly

**Pull request merged**
