### PR TITLE
Change handling of tvars in implicits

### LINKED ISSUE #739: Type parameters should be instantiated before doing an implicit search
This is a separate issue from #738 but I think that they will need to be fixed together to get something that makes sense.
Consider the following code:
```scala
class Foo

object Test {
  def foo[T](x: T)(implicit ev: T): T = ???

  def test: Unit = {
    implicit val evidence: Foo = new Foo
    foo(new Foo)
  }
}
```

It currently fails with:
```scala
try/constrimpl.scala:9: error: ambiguous implicits: both getter StringCanBuildFrom in object Predef$ and getter NothingClassTag in object DottyPredef$ match type (T? >: Foo) of parameter ev of method foo in object Test$
    foo(new Foo)
                ^
try/constrimpl.scala:10: error: ambiguous implicits: both getter StringCanBuildFrom in object Predef$ and getter NothingClassTag in object DottyPredef$ match type (T? >: Foo) of parameter ev of method foo in object Test$
  }
   ^
two errors found
```

When we do the implicit search, `T` is not instantiated yet, the only thing we know is that its lower bound is `Foo` as the error message says: `... match type (T? >: Foo) of parameter ev of method foo ...`. I don't know how `scalac` deals with this exactly but it seems like it simply instantiate the type parameter before doing the implicit search, we should consider doing the same thing.

Note that this is also needed to properly fix #553, if we don't instantiate `CC` to `List`, then `CC` is only lower-bounded by `List`, and [lower bounds of abstract types are not part of the implicit scope](https://github.com/lampepfl/dotty/commit/0efa171e8ccca0d49fc6d800fd21e29f7b7336fd), this means that the implicit `List.canBuildFrom` will not be in the scope.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #739 by adding the following rule:

Before typing an implicit parameter list of a method m, instantiate all type parameters of m that occur in the type of some preceding value parameter of m.

Review by @smarter, @retronym

### CODE REVIEW

**Comment by odersky** [comment]
Only the last commit is new. Everything else is merged by now.

**Comment by smarter** [comment]
This new scheme seems OK to me but it does not address the issues we have regarding when a type parameter should be minimized or maximized, specifically https://github.com/lampepfl/dotty/issues/738 and https://github.com/lampepfl/dotty/issues/718. It'd be great to see at least https://github.com/lampepfl/dotty/issues/738 addressed to get a better idea of the semantics we're trying to achieve. (Note that both of these issues should be fixed in my prototype)

**Comment by smarter** [comment]
I'm still confused by the rules regarding type parameter maximization, for example:
```scala
import scala.reflect._

class Contra[-T]

object Test {
  def getParam[T](c: Contra[T])(implicit ct: ClassTag[T]): Unit = {
    println(ct)
  }

  def main(args: Array[String]): Unit = {
    getParam(new Contra[Int])
  }
}
```
This will print  `Int` when compiled with scalac, but it will print `Nothing` when compiled with dotty, is that what we want?

**Comment by odersky** [comment]
On Mon, Aug 10, 2015 at 4:44 PM, Guillaume Martres <notifications@github.com
> wrote:

> I'm still confused by the rules regarding type parameter maximization, for
> example:
>
> import scala.reflect._
> class Contra[-T]
> object Test {
>   def getParam[T](c: Contra[T])(implicit ct: ClassTag[T]): Unit = {
>     println(ct)
>   }
>
>   def main(args: Array[String]): Unit = {
>     getParam(new Contra[Int])
>   }
> }
>
> This will print Int when compiled with scalac, but it will print Nothing
> when compiled with dotty, is that what we want?
>

Yes, I think so. Processing the first parameter clause gives T <: Int. Then
when we instantiate T we do so to the lower bound. By what reasoning would
we infer Int?




—
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/752#issuecomment-129648005>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
> Yes, I think so. Processing the first parameter clause gives T <: Int. Then
when we instantiate T we do so to the lower bound. By what reasoning would
we infer Int?

Because in the trees that the user will write (like `getParam(new Contra[Int])`), `T` only appears contravariantly, so we only add constraints to its upper boud, and it seems intuitive to instantiate `T` to the bound where we added constraints.

If we don't do type parameter maximization here, could you provide an example where we do type parameter maximization and it's useful (the program would not compile otherwise or would produce a different result) ?

**Comment by retronym** [comment]
The reasoning in scalac:

```
scala> :paste -raw
// Entering paste mode (ctrl-D to finish)

import scala.reflect._

class Contra[-T]

object Test {
  def getParam[T](c: Contra[T])(implicit ct: ClassTag[T]): Unit = {
    println(ct)
  }
  def getParam1[T](c: Contra[T]) = ()
}


scala> val getParam1 = typeOf[Test.type].member(TermName("getParam1"))
getParam1: $r.intp.global.Symbol = method getParam1

scala> val tparams = getParam1.info.typeParams
tparams: List[$r.intp.global.Symbol] = List(type T)

scala> val tvars = tparams map (sym => TypeVar(sym))
tvars: List[$r.intp.global.TypeVar] = List(?T)

scala> val withTVars = getParam1.info.resultType.instantiateTypeParams(tparams, tvars)
withTVars: $r.intp.global.Type = (c: Contra[?T])Unit

scala> typeOf[Contra[Int]] <:< withTVars.params.head.info
res19: Boolean = true

scala> val formal1 = getParam1.info.params.head.info
formal1: $r.intp.global.Type = Contra[T]

scala> tvars.head.constr
res20: $r.intp.global.TypeConstraint =  <: Int

scala> varianceInType(getParam1.info.params.head.info)(tparams.head)
res27: scala.reflect.internal.Variance = contravariant

scala> varianceInType(formal1)(tparams.head)
res38: scala.reflect.internal.Variance = contravariant

scala> formal1.typeConstructor.typeParams.head.variance
res39: scala.reflect.internal.Variance = contravariant

scala> varianceInType(formal1.typeArgs.head)(tparams.head).flip
res40: scala.reflect.internal.Variance = contravariant

scala> solve(tvars, tparams, varianceInType(formal1)(tparams.head) :: Nil, upper = false, reflect.internal.Depth.AnyDepth)
res46: Boolean = true

scala> tvars.head.inst
res47: $r.intp.global.Type = Int
```

**Comment by odersky** [comment]
Thanks for the analysis, Jason. It seems to point to a fundamental
difference between scalac's and dotty's type inference. I have to mull this
over.

 - Martin

On Mon, Aug 10, 2015 at 6:16 PM, Jason Zaugg <notifications@github.com>
wrote:

> The reasoning in scalac:
>
> scala> :paste -raw
> // Entering paste mode (ctrl-D to finish)
>
> import scala.reflect._
>
> class Contra[-T]
>
> object Test {
>   def getParam[T](c: Contra[T])(implicit ct: ClassTag[T]): Unit = {
>     println(ct)
>   }
>   def getParam1[T](c: Contra[T]) = ()
> }
>
>
> scala> val getParam1 = typeOf[Test.type].member(TermName("getParam1"))
> getParam1: $r.intp.global.Symbol = method getParam1
>
> scala> val tparams = getParam1.info.typeParams
> tparams: List[$r.intp.global.Symbol] = List(type T)
>
> scala> val tvars = tparams map (sym => TypeVar(sym))
> tvars: List[$r.intp.global.TypeVar] = List(?T)
>
> scala> val withTVars = getParam1.info.resultType.instantiateTypeParams(tparams, tvars)
> withTVars: $r.intp.global.Type = (c: Contra[?T])Unit
>
> scala> typeOf[Contra[Int]] <:< withTVars.params.head.info
> res19: Boolean = true
>
> scala> val formal1 = getParam1.info.params.head.info
> formal1: $r.intp.global.Type = Contra[T]
>
> scala> tvars.head.constr
> res20: $r.intp.global.TypeConstraint =  <: Int
>
> scala> varianceInType(getParam1.info.params.head.info)(tparams.head)
> res27: scala.reflect.internal.Variance = contravariant
>
> scala> varianceInType(formal1)(tparams.head)
> res38: scala.reflect.internal.Variance = contravariant
>
> scala> formal1.typeConstructor.typeParams.head.variance
> res39: scala.reflect.internal.Variance = contravariant
>
> scala> varianceInType(formal1.typeArgs.head)(tparams.head).flip
> res40: scala.reflect.internal.Variance = contravariant
>
> scala> solve(tvars, tparams, varianceInType(formal1)(tparams.head) :: Nil, upper = false, reflect.internal.Depth.AnyDepth)
> res46: Boolean = true
>
> scala> tvars.head.inst
> res47: $r.intp.global.Type = Int
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/752#issuecomment-129662448>.
>



-- 
Martin Odersky
EPFL

**Comment by odersky** [comment]
Part of this is now in #799. I'll revive the rest in a separate PR.

**Pull request closed without merging**
