### PR TITLE
[Vulpix] Abort compilation after `maxCompileTime`

### PR DESCRIPTION
**Pull request by felixmulder**

### CODE REVIEW

**Comment by DarkDimius** [comment]
I think this is a very misleading change. 
It doesn't stop the compilation, it stops waiting for it and starts a new one, so that multiple will be performed concurrently.

**Comment by DarkDimius** [comment]
Additionally, it blocks the compilation thread and instead uses global future threadpool, ie the number of compilation threads is not controlled using previous means anymore

**Comment by felixmulder** [comment]
Non-constructive feedback. Please rephrase.

**Comment by DarkDimius** [comment]
While I agree that I could have phrased it differently, I find a sneaky way of putting such changes without documenting them very misleading, hence my reaction. 

Constructive version of it was in the original https://github.com/lampepfl/dotty/pull/2125 PR.
The better way to do it would to have compilation slaves as separate VMs so that we are able to kill them.

**Comment by felixmulder** [comment]
Fair enough :smiley: let's do this properly then!

**Pull request closed without merging**
