### PR TITLE
Remove the collection strawmans from the compiler sources

### PR DESCRIPTION
**Pull request by smarter**
The development of the strawman has now moved to
https://github.com/scala/collection-strawman .

### CODE REVIEW

**Comment by odersky** [comment]
The strawman is used in some of the tests, and it would be good to keep these for monitoring possible regression. We could move it into the test directory, however.

**Comment by smarter** [comment]
Indeed, I thought all the tests contained a copy of the strawmans, but not CollectionTests.scala, I'll move what's need to the test directory.

**Comment by nicolasstucki** [comment]
We should probably have a git submodule with the current collection strawman. We can the use this one for our tests. While trying this out  for the callgraph I found #2188.

**Comment by felixmulder** [comment]
Superseded by #2427

**Pull request closed without merging**
