### PR TITLE
Don't let caseLambda bindings accumulate in constraint

### LINKED ISSUE #9107: Match type subtyping wrongly instantiates types in patterns
There is something off with match type subtyping:

```scala
trait Inv[T]
object Test {
  def ev[X] = implicitly[
    (X match { case Inv[t] => Int }) =:=
    (X match { case Inv[t] => t })
  ]
}
```

```
==> isSubType internal.MatchCase[Inv[t], Int] <:< internal.MatchCase[Inv[t], t] ?
  ==> isSubType Inv[t] <:< Inv[t] ?
  <== isSubType Inv[t] <:< Inv[t]  = true   
  ==> isSubType Inv[t] <:< Inv[t] ?
  <== isSubType Inv[t] <:< Inv[t]  = true   
  ==> isSubType Int <:< t ?                 
    ==> isSubType Int <:< t ?           
      ==> isSubType Int <:< Nothing ?
      <== isSubType Int <:< Nothing  = false  
    <== isSubType Int <:< t  = false        
    ==> lub(Nothing, Int, canConstrain=false)?
    <== lub(Nothing, Int, canConstrain=false) = Int
    ==> isSubType Int <:< Any ?             
    <== isSubType Int <:< Any  = true
  <== isSubType Int <:< t  = true
<== isSubType internal.MatchCase[Inv[t], Int] <:< internal.MatchCase[Inv[t], t] = true
```

The issue seams to be really match type related, as the following minimization attempt is correctly rejected:

```scala
trait M[F[_]]
trait Inv[T]
object Test {
  def ev[X] = implicitly[
    M[[t] =>> internal.MatchCase[Inv[t], t]] =:=
    M[[t] =>> internal.MatchCase[Inv[t], Int]]
  ] // error
}
```

```
==> isSubType internal.MatchCase[Inv[t], Int] <:< internal.MatchCase[Inv[t], t] ?
  ==> isSubType internal.type <:< internal.type ?
  <== isSubType internal.type <:< internal.type  = true
  ==> isSubType Inv[t] <:< Inv[t] ?
  <== isSubType Inv[t] <:< Inv[t]  = true
  ==> isSubType Inv[t] <:< Inv[t] ?
  <== isSubType Inv[t] <:< Inv[t]  = true
  ==> isSubType Int <:< t ?
    ==> isSubType Int <:< t ?
      ==> isSubType Int <:< Nothing ?
      <== isSubType Int <:< Nothing  = false
    <== isSubType Int <:< t  = false
  <== isSubType Int <:< t  = false
<== isSubType internal.MatchCase[Inv[t], Int] <:< internal.MatchCase[Inv[t], t] = false
```

### PR DESCRIPTION
**Pull request by odersky**
Remove them when a `matchCases` has finished.

Fixes #9107

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@OlivierBlanvillain Test 6697 started failing. But arguably the error is correct. So it was wrong before. Do you agree?

**Review by OlivierBlanvillain — APPROVED** [review]
Yes I agree. I think this PR is a duplicate of #9108, I've just pushed the extra test cases to this branch to see if they also pass here.

**Comment by odersky** [comment]
Yes, I see now this is a duplicate of #9108. I notice that 9890.scala fails in both PRs, so that test should be removed.

**Pull request merged**
