### PR TITLE
Make hash codes on type more predictable.

### PR DESCRIPTION
**Pull request by DarkDimius**
May help finding the partest issue.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@odersky please review.

**Comment by odersky** [comment]
I think that will just give us worse hashcode without changing much of the underlying problem. To get reproducible builds we need to make every map that is traversed a linked map. That's a better way to get there.

**Comment by DarkDimius** [comment]
> I think that will just give us worse hashcode

Why would they be worse?

**Pull request merged**
