### PR TITLE
Link directly to a JAR

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by smarter** [comment]
What's the motivation here?

**Comment by nicolasstucki** [comment]
The motivation is to create a tool that given the classpath and an entry point, will link all classes that have a tasty. Later on optimizing them with the linker. The output is a jar to avoid overriding class files that may be in the output directory, making sure that the use of the tool is idempotent.

**Comment by smarter** [comment]
Why not use `-d foo.jar` to write classfileloader directly to a jar instead of an output directory? I think scalac has this feature

**Comment by nicolasstucki** [comment]
That was the intended effects thought I took a complicated solution. I will adapt it to the `-d foo.jar` scheme.

**Comment by nicolasstucki** [comment]
I factored a part that handles JARs in #3382.

**Pull request closed without merging**
